package com.facebook.iabeventlogging.model;

import android.os.Parcel;
import com.facebook.privacy.zone.api.ZonedValue;
import com.facebook.privacy.zone.policy.ZonePolicy;
import java.util.ArrayList;
import p000X.C25940wr;
import p000X.C25960wt;
import p000X.C67W;
import p000X.C91514uR;
import p000X.C91534uT;
/* loaded from: classes3.dex */
public class IABWebviewEndEvent extends IABEvent {
    public String A00;
    public final int A01;
    public final int A02;
    public final int A03;
    public final int A04;
    public final long A05;
    public final long A06;
    public final long A07;
    public final long A08;
    public final long A09;
    public final long A0A;
    public final long A0B;
    public final long A0C;
    public final long A0D;
    public final long A0E;
    public final long A0F;
    public final long A0G;
    public final ZonedValue A0H;
    public final String A0I;
    public final String A0J;
    public final String A0K;
    public final String A0L;
    public final String A0M;
    public final String A0N;
    public final ArrayList A0O;
    public final boolean A0P;
    public final boolean A0Q;
    public final boolean A0R;
    public final boolean A0S;
    public final boolean A0T;
    public final boolean A0U;
    public final boolean A0V;

    public final String toString() {
        StringBuilder A0m = C25940wr.A0m("IABWebviewEndEvent{");
        A0m.append("browserUserAgent=");
        A0m.append(this.A0I);
        A0m.append("userClickTs=");
        A0m.append(this.A0E);
        A0m.append(", webRequestStartedTs=");
        A0m.append(this.A0F);
        A0m.append(", browserOpenTs=");
        A0m.append(this.A06);
        A0m.append(", scrollReadyTs=");
        A0m.append(this.A0D);
        A0m.append(", landingPageDomContentLoadedTs=");
        A0m.append(this.A09);
        A0m.append(", landingPageLoadedTs=");
        A0m.append(this.A0B);
        A0m.append(", landingPageViewEndedTs=");
        A0m.append(this.A0C);
        A0m.append(", browserCloseTs=");
        A0m.append(this.A05);
        A0m.append(", backgroundTimePairs=");
        A0m.append(this.A0O);
        A0m.append(", initialLandUrl='");
        char A00 = C91534uT.A00(this.A0N, A0m);
        A0m.append(", clickSource='");
        A0m.append(this.A0J);
        A0m.append(A00);
        A0m.append(", dismissMethod=");
        A0m.append(this.A01);
        A0m.append(", landingPageStatusCode=");
        A0m.append(this.A03);
        A0m.append(", sslErrorCode=");
        A0m.append(this.A04);
        A0m.append(", interactionCount=");
        A0m.append(this.A02);
        C91514uR.A1N(this, A0m, A00);
        A0m.append(super.A00);
        A0m.append(", isInitialUrlIsOpenApp=");
        A0m.append(this.A0U);
        A0m.append(", deepLinkUrl=");
        A0m.append(this.A0K);
        A0m.append(", shouldUseLEDesign=");
        A0m.append(this.A0V);
        A0m.append(", webviewEndFlags=");
        A0m.append(this.A0G);
        A0m.append(", isCrashed=");
        A0m.append(this.A0S);
        A0m.append(", errorMessage=");
        A0m.append(this.A0L);
        A0m.append(", errorStackTrace=");
        A0m.append(this.A0M);
        A0m.append(", landingPageEstimatedProgressFinishedTs=");
        A0m.append(this.A0A);
        A0m.append(", landingPageContentSizeChangedTs=");
        A0m.append(this.A08);
        A0m.append(", googleOAuth2Encountered=");
        A0m.append(this.A0Q);
        A0m.append(", googleOAuth2ErrorEncountered=");
        A0m.append(this.A0R);
        A0m.append(", isGoogleOAuth2RedirectUrlSchemaStoragerelay=");
        A0m.append(this.A0T);
        A0m.append(", e2eeBlackHoleEnforcementUnsafeBrowsingEncountered=");
        A0m.append(this.A0P);
        A0m.append(", initialCookieInjectCompleteTs=");
        A0m.append(this.A07);
        A0m.append(", trackingNode=");
        A0m.append(this.A00);
        return C25960wt.A0l(A0m);
    }

    @Override // com.facebook.iabeventlogging.model.IABEvent, android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        super.writeToParcel(parcel, i);
        parcel.writeString(this.A0I);
        parcel.writeLong(this.A0E);
        parcel.writeLong(this.A0F);
        parcel.writeLong(this.A06);
        parcel.writeLong(this.A0D);
        parcel.writeLong(this.A09);
        parcel.writeLong(this.A0B);
        parcel.writeLong(this.A0C);
        parcel.writeList(this.A0O);
        parcel.writeParcelable(this.A0H, i);
        parcel.writeString(this.A0N);
        parcel.writeString(this.A0J);
        parcel.writeInt(this.A01);
        parcel.writeInt(this.A03);
        parcel.writeInt(this.A04);
        parcel.writeInt(this.A02);
        parcel.writeByte(this.A0U ? (byte) 1 : (byte) 0);
        parcel.writeString(this.A0K);
        parcel.writeByte(this.A0V ? (byte) 1 : (byte) 0);
        parcel.writeLong(this.A0G);
        parcel.writeByte(this.A0S ? (byte) 1 : (byte) 0);
        parcel.writeString(this.A0L);
        parcel.writeString(this.A0M);
        parcel.writeLong(this.A0A);
        parcel.writeLong(this.A08);
        parcel.writeByte(this.A0Q ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0R ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0T ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0P ? (byte) 1 : (byte) 0);
        parcel.writeLong(this.A07);
        parcel.writeString(this.A00);
    }

    public IABWebviewEndEvent(ZonedValue zonedValue, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, ArrayList arrayList, int i, int i2, int i3, int i4, long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7) {
        super(C67W.IAB_WEBVIEW_END, str, j, j2);
        this.A0I = str2;
        this.A0E = j3;
        this.A0F = j4;
        this.A06 = j5;
        this.A0D = j6;
        this.A09 = j7;
        this.A0B = j8;
        this.A0C = j9;
        this.A05 = j;
        this.A0O = arrayList;
        this.A0H = zonedValue == null ? new ZonedValue(ZonePolicy.A02, "") : zonedValue;
        this.A0N = str3;
        this.A0J = str4;
        this.A01 = i;
        this.A03 = i2;
        this.A04 = i3;
        this.A02 = i4;
        this.A0U = z;
        this.A0K = str5;
        this.A0V = z2;
        this.A0G = j10;
        this.A0S = z3;
        this.A0L = str6;
        this.A0M = str7;
        this.A0A = j11;
        this.A08 = j12;
        this.A0Q = z4;
        this.A0R = z5;
        this.A0T = z6;
        this.A0P = z7;
        this.A07 = j13;
        this.A00 = str8;
    }
}
