.class public final LX/BBl;
.super Ljava/lang/Object;
.source ""

# interfaces
.implements LX/BnL;


# instance fields
.field public final A00:LX/AMh;

.field public final A01:LX/H0Z;

.field public final A02:LX/FVg;

.field public final A03:Lcom/instagram/service/session/UserSession;


# direct methods
.method public constructor <init>(LX/AMh;)V
    .locals 3

    .line 0
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 1
    .line 2
    .line 3
    iput-object p1, p0, LX/BBl;->A00:LX/AMh;

    .line 4
    .line 5
    iget-object v2, p1, LX/AMh;->A05:Lcom/instagram/service/session/UserSession;

    .line 6
    .line 7
    iput-object v2, p0, LX/BBl;->A03:Lcom/instagram/service/session/UserSession;

    .line 8
    .line 9
    iget-object v1, p1, LX/AMh;->A01:LX/4u2;

    .line 10
    .line 11
    new-instance v0, LX/H0Z;

    .line 12
    .line 13
    invoke-direct {v0, v1, v2}, LX/H0Z;-><init>(LX/4u2;Lcom/instagram/service/session/UserSession;)V

    .line 14
    .line 15
    .line 16
    iput-object v0, p0, LX/BBl;->A01:LX/H0Z;

    .line 17
    .line 18
    new-instance v0, LX/FVg;

    .line 19
    .line 20
    invoke-direct {v0, v1, v2}, LX/FVg;-><init>(LX/4u2;Lcom/instagram/service/session/UserSession;)V

    .line 21
    .line 22
    .line 23
    iput-object v0, p0, LX/BBl;->A02:LX/FVg;

    .line 24
    .line 25
    return-void
    .line 26
    .line 27
.end method


# virtual methods
.method public final A8d(LX/GVQ;LX/GVQ;LX/B7B;LX/Alp;)V
    .locals 0

    return-void
.end method

.method public final A8f(LX/GVQ;LX/GVQ;LX/B7B;LX/Alp;)V
    .locals 0

    return-void
.end method

.method public final A8i(Landroid/view/View;LX/GVQ;LX/GVQ;LX/B7B;LX/Alp;)V
    .locals 5

    .line 0
    invoke-static {p1, p4}, LX/0wp;->A1Q(Ljava/lang/Object;Ljava/lang/Object;)V

    .line 1
    .line 2
    .line 3
    const/4 v0, 0x3

    .line 4
    invoke-static {p2, v0}, LX/0OR;->A0B(Ljava/lang/Object;I)V

    .line 5
    .line 6
    .line 7
    iget-object v0, p0, LX/BBl;->A00:LX/AMh;

    .line 8
    .line 9
    iget-object v0, v0, LX/AMh;->A01:LX/4u2;

    .line 10
    .line 11
    invoke-static {p4, v0}, LX/Am9;->A0S(LX/Bnj;LX/4u2;)Z

    .line 12
    .line 13
    .line 14
    move-result v0

    .line 15
    if-eqz v0, :cond_3

    .line 16
    .line 17
    iget-object v3, p0, LX/BBl;->A03:Lcom/instagram/service/session/UserSession;

    .line 18
    .line 19
    sget-object v2, LX/0TD;->A05:LX/0TD;

    .line 20
    .line 21
    const-wide v0, 0x8100d0000001bdL

    .line 22
    .line 23
    .line 24
    .line 25
    .line 26
    invoke-static {v2, v3, v0, v1}, LX/3jC;->A0E(LX/0TD;LX/0if;J)Z

    .line 27
    .line 28
    .line 29
    move-result v0

    .line 30
    if-eqz v0, :cond_2

    .line 31
    .line 32
    iget-object v4, p0, LX/BBl;->A01:LX/H0Z;

    .line 33
    .line 34
    iget-object v1, p4, LX/B7B;->A0T:Ljava/lang/Integer;

    .line 35
    .line 36
    sget-object v0, LX/006;->A01:Ljava/lang/Integer;

    .line 37
    .line 38
    if-ne v1, v0, :cond_0

    .line 39
    .line 40
    invoke-static {p4}, LX/B7B;->A01(LX/B7B;)LX/B7P;

    .line 41
    .line 42
    .line 43
    move-result-object v0

    .line 44
    iget-object v0, v0, LX/B7P;->A0f:LX/B7I;

    .line 45
    .line 46
    iget-object v1, v0, LX/B7I;->A1T:Lcom/instagram/model/reels/sponsored/AutoGeneratedCardType;

    .line 47
    .line 48
    if-eqz v1, :cond_4

    .line 49
    .line 50
    sget-object v0, Lcom/instagram/model/reels/sponsored/AutoGeneratedCardType;->A08:Lcom/instagram/model/reels/sponsored/AutoGeneratedCardType;

    .line 51
    .line 52
    invoke-virtual {v0, v1}, Ljava/lang/Object;->equals(Ljava/lang/Object;)Z

    .line 53
    .line 54
    .line 55
    move-result v0

    .line 56
    if-eqz v0, :cond_4

    .line 57
    .line 58
    :cond_0
    :goto_0
    iget-object v0, v4, LX/H0Z;->A04:Ljava/util/Map;

    .line 59
    .line 60
    invoke-interface {v0, p4, p1}, Ljava/util/Map;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 61
    .line 62
    .line 63
    :cond_1
    invoke-virtual {p2, v4}, LX/GVQ;->A01(LX/HkE;)LX/GVQ;

    .line 64
    .line 65
    .line 66
    :cond_2
    const-wide v0, 0x81079700021297L

    .line 67
    .line 68
    .line 69
    .line 70
    .line 71
    invoke-static {v2, v3, v0, v1}, LX/3jC;->A0E(LX/0TD;LX/0if;J)Z

    .line 72
    .line 73
    .line 74
    move-result v0

    .line 75
    if-eqz v0, :cond_3

    .line 76
    .line 77
    iget-object v1, p0, LX/BBl;->A02:LX/FVg;

    .line 78
    .line 79
    iget-object v0, v1, LX/H0a;->A00:Ljava/util/Map;

    .line 80
    .line 81
    invoke-interface {v0, p4, p1}, Ljava/util/Map;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 82
    .line 83
    .line 84
    invoke-virtual {p2, v1}, LX/GVQ;->A01(LX/HkE;)LX/GVQ;

    .line 85
    .line 86
    .line 87
    :cond_3
    return-void

    .line 88
    :cond_4
    iget-object v0, p4, LX/B7B;->mBrandResearchSurvey:LX/8xl;

    .line 89
    .line 90
    if-eqz v0, :cond_1

    .line 91
    .line 92
    goto :goto_0
    .line 93
    .line 94
    .line 95
    .line 96
    .line 97
    .line 98
    .line 99
    .line 100
    .line 101
.end method

.method public final A8j(LX/GVQ;LX/GVQ;LX/B7B;LX/Alp;)V
    .locals 0

    return-void
.end method
