package p000X;

import android.content.Context;
import android.net.Uri;
import android.text.TextUtils;
import android.view.View;
import ch.boye.httpclientandroidlib.client.utils.Rfc3492Idn;
import ch.boye.httpclientandroidlib.util.LangUtils;
import com.facebook.catalyst.modules.cameraroll.CameraRollManager;
import com.facebook.react.uimanager.BaseViewManager;
import com.google.common.collect.ImmutableList;
import com.instagram.common.typedurl.ImageUrl;
import com.instagram.feed.media.ReelCTA;
import com.instagram.model.effect.AttributedAREffect;
import com.instagram.model.reels.sponsored.AutoGeneratedCardType;
import com.instagram.pendingmedia.model.BrandedContentTag;
import com.instagram.pendingmedia.model.PendingMedia;
import com.instagram.react.modules.base.IgReactQEModule;
import com.instagram.reels.prompt.model.PromptStickerModel;
import com.instagram.service.session.UserSession;
import com.instagram.user.model.User;
import java.io.File;
import java.util.AbstractCollection;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.concurrent.TimeUnit;
/* renamed from: X.B7B */
/* loaded from: classes4.dex */
public final class B7B implements InterfaceC21924Bnj, InterfaceC22116Bqv, InterfaceC34537HpI {
    public int A00;
    public int A01;
    public int A02;
    public AttributedAREffect A03;
    public C20518B6w A04;
    public B76 A05;
    public C18451ACn A06;
    public B74 A07;
    public C20521B6z A08;
    public C158328x1 A09;
    public B70 A0A;
    public ASV A0B;
    public Boolean A0C;
    public Long A0D;
    public List A0E;
    public List A0F;
    public boolean A0G;
    public boolean A0H;
    public boolean A0I;
    public boolean A0J;
    public boolean A0K;
    public String A0L;
    public final B7P A0M;
    public final C98y A0N;
    public final B77 A0O;
    public final C20520B6y A0P;
    public final B7O A0Q;
    public final B7A A0R;
    public final User A0S;
    public final Integer A0T;
    public final String A0U;
    public final String A0V;
    public final List A0W;
    public final List A0X;
    public final List A0Y;
    public final List A0Z;
    public final Set A0a;
    public final Set A0b;
    public C158758xl mBrandResearchSurvey;
    public final B73 mBrandSurveyImpression;

    public static int A00(B7B b7b) {
        return b7b.A0T.intValue();
    }

    public static B7P A01(B7B b7b) {
        B7P b7p = b7b.A0M;
        b7p.getClass();
        return b7p;
    }

    public static PendingMedia A02(B7B b7b) {
        B77 b77 = b7b.A0O;
        b77.getClass();
        return b77.A00;
    }

    public static C19348AfK A03(B7B b7b, C9GK c9gk) {
        return (C19348AfK) c9gk.A0H.get(b7b.BM5());
    }

    public final long A09() {
        B7P b7p = this.A0M;
        if (b7p != null) {
            long A1u = b7p.A1u();
            if (A1u > 0 && A1u < Long.MAX_VALUE) {
                return b7p.A1u();
            }
        }
        C98y c98y = this.A0N;
        if (c98y == null) {
            return Long.MAX_VALUE;
        }
        long j = c98y.A03;
        if (j <= 0 || j >= Long.MAX_VALUE) {
            return Long.MAX_VALUE;
        }
        return TimeUnit.SECONDS.toMillis(j);
    }

    public final InterfaceC21924Bnj A0E() {
        Integer num = this.A0T;
        switch (num.intValue()) {
            case 0:
                B77 b77 = this.A0O;
                b77.getClass();
                return b77;
            case 1:
                C20520B6y c20520B6y = this.A0P;
                if (c20520B6y == null) {
                    return this.A0M;
                }
                return c20520B6y;
            case 2:
            case 19:
            case 20:
            default:
                throw C91544uU.A0v(C073900b.A0L("This item does not represent an ImpressionItem. Item type: ", C178689vh.A00(num)));
            case 3:
            case 4:
            case 5:
                C98y c98y = this.A0N;
                if (c98y != null) {
                    B72 b72 = c98y.A0t;
                    if (b72.A00 == null) {
                        b72.A00 = c98y.A0Y;
                    }
                    return b72;
                }
                return null;
            case 6:
            case 7:
            case 11:
            case 15:
                return this.A0R;
            case 8:
                return this.A08;
            case 9:
                return this.A09;
            case 10:
                return this.A0M;
            case IgReactQEModule.CONFIG_KEY_OFFSET /* 12 */:
            case 13:
            case 21:
                return this.A0A;
            case 14:
                return null;
            case 16:
                return this.A07;
            case LangUtils.HASH_SEED /* 17 */:
                return this.A04;
            case 18:
                return this.A05;
            case 22:
            case 23:
            case 24:
            case 25:
            case Rfc3492Idn.tmax /* 26 */:
            case 27:
            case 28:
                return new C20519B6x(this);
            case CameraRollManager.IMAGES_MEDIA_LATITUDE_LONGITUDE_DEPRECATED_API_LEVEL /* 29 */:
                return this.mBrandSurveyImpression;
        }
    }

    public final C5LY A0G() {
        if (this.A0T == AnonymousClass006.A01) {
            return A01(this).A0f.A1E;
        }
        return null;
    }

    public final C159078yH A0J() {
        if (this.A0T == AnonymousClass006.A01) {
            return A01(this).A0f.A1X;
        }
        return null;
    }

    public final AN5 A0L() {
        if (this.A0T == AnonymousClass006.A01) {
            return A01(this).A2R();
        }
        return null;
    }

    public final User A0M() {
        B7P b7p = this.A0M;
        if (b7p == null || this.A0T != AnonymousClass006.A01) {
            return null;
        }
        return b7p.A2b();
    }

    public final String A0P() {
        List A1E;
        B7P b7p = this.A0M;
        if (b7p != null && (A1E = B7P.A1E(b7p)) != null && !A1E.isEmpty()) {
            BCH A0C = ((BAZ) C25990ww.A0d(A1E)).A0C();
            A0C.getClass();
            String str = A0C.A00.A0E;
            if (str == null) {
                return "";
            }
            return str;
        }
        return null;
    }

    public final String A0T(UserSession userSession) {
        if (this.A0T == AnonymousClass006.A01) {
            return C19763AmC.A03(A01(this), userSession);
        }
        return null;
    }

    public final String A0U(UserSession userSession) {
        if (this.A0T == AnonymousClass006.A01) {
            return C19763AmC.A07(A01(this), userSession);
        }
        return null;
    }

    public final String A0V(UserSession userSession) {
        if (this.A0T == AnonymousClass006.A01) {
            return C19763AmC.A0B(A01(this), userSession);
        }
        return null;
    }

    public final List A0W() {
        if (this.A0T == AnonymousClass006.A01) {
            B7I b7i = A01(this).A0f;
            List list = b7i.A6b;
            if (list == null) {
                list = C25920wp.A0w();
                b7i.A6b = list;
            }
            list.getClass();
            return list;
        }
        return C25920wp.A0w();
    }

    public final List A0X() {
        List list;
        if (this.A0T == AnonymousClass006.A01 && (list = A01(this).A0f.A5O) != null) {
            return ImmutableList.copyOf((Collection) list);
        }
        return null;
    }

    public final boolean A0b() {
        Boolean AVr;
        B7P b7p = this.A0M;
        if (b7p != null && (AVr = b7p.AvD().AVr()) != null && AVr.booleanValue()) {
            return true;
        }
        return false;
    }

    public final boolean A0d() {
        B7P b7p = this.A0M;
        if (b7p != null && b7p.A4l()) {
            return true;
        }
        return false;
    }

    public final boolean A0f() {
        B7P b7p = this.A0M;
        if (b7p != null) {
            return b7p.A4g();
        }
        C98y c98y = this.A0N;
        if (c98y == null) {
            return false;
        }
        Boolean bool = c98y.A0K;
        if (bool != null && bool.booleanValue()) {
            return false;
        }
        return true;
    }

    public final boolean A0h() {
        B7I b7i;
        List list;
        if (this.A0T == AnonymousClass006.A01 && (list = (b7i = A01(this).A0f).A5d) != null && !list.isEmpty() && ((InterfaceC22038BpZ) b7i.A5d.get(0)).Am0() != null && ((InterfaceC22038BpZ) b7i.A5d.get(0)).Am0().booleanValue()) {
            return true;
        }
        return false;
    }

    public final boolean A0i() {
        if (!A1H(EnumC171099gG.A0h) && !A1H(EnumC171099gG.A0m) && !A1H(EnumC171099gG.A0o) && !A1H(EnumC171099gG.A0t)) {
            return false;
        }
        return true;
    }

    public final boolean A0l() {
        if (this.A0T == AnonymousClass006.A01 && A01(this).A2V() != null) {
            return true;
        }
        return false;
    }

    public final boolean A0m() {
        if (this.A0T == AnonymousClass006.A01 && A01(this).A2T() != null) {
            return true;
        }
        return false;
    }

    public final boolean A0n() {
        if (this.A0T == AnonymousClass006.A01 && A01(this).A2W() != null) {
            return true;
        }
        return false;
    }

    public final boolean A0o() {
        if (this.A0T == AnonymousClass006.A01 && A01(this).A2U() != null) {
            return true;
        }
        return false;
    }

    public final boolean A0p() {
        if (this.A0T == AnonymousClass006.A01 && A01(this).A45()) {
            return true;
        }
        return false;
    }

    public final boolean A0q() {
        Boolean AmZ;
        if (this.A0T == AnonymousClass006.A01 && (AmZ = A01(this).AvD().AmZ()) != null && AmZ.booleanValue()) {
            return true;
        }
        return false;
    }

    public final boolean A0r() {
        if (this.A0T == AnonymousClass006.A02 && this.A03 != null) {
            return true;
        }
        return false;
    }

    public final boolean A0s() {
        AutoGeneratedCardType autoGeneratedCardType;
        if (this.A0T == AnonymousClass006.A01 && (autoGeneratedCardType = A01(this).A0f.A1T) != null && AutoGeneratedCardType.CAPTION.equals(autoGeneratedCardType)) {
            return true;
        }
        return false;
    }

    public final boolean A0u() {
        if (this.A0T == AnonymousClass006.A01 && A01(this).A4E()) {
            return true;
        }
        return false;
    }

    public final boolean A0v() {
        if (this.A0T == AnonymousClass006.A01 && A01(this).A1u() < System.currentTimeMillis()) {
            return true;
        }
        return false;
    }

    public final boolean A0w() {
        B7P b7p = this.A0M;
        if (b7p != null && b7p.A4H()) {
            return true;
        }
        return false;
    }

    public final boolean A0y() {
        AutoGeneratedCardType autoGeneratedCardType;
        if (this.A0T == AnonymousClass006.A01 && (autoGeneratedCardType = A01(this).A0f.A1T) != null && AutoGeneratedCardType.GENERIC_CARD.equals(autoGeneratedCardType)) {
            return true;
        }
        return false;
    }

    public final boolean A0z() {
        if (!this.A0H) {
            B7P b7p = this.A0M;
            if (b7p != null && b7p.A0f.A3v == null) {
                return true;
            }
            return false;
        }
        return true;
    }

    public final boolean A10() {
        if (this.A0T == AnonymousClass006.A01 && C25960wt.A1V(A01(this).AvD().BVU())) {
            return true;
        }
        return false;
    }

    public final boolean A11() {
        AutoGeneratedCardType autoGeneratedCardType;
        if (this.A0T == AnonymousClass006.A01 && (autoGeneratedCardType = A01(this).A0f.A1T) != null && AutoGeneratedCardType.LEADGEN.equals(autoGeneratedCardType)) {
            return true;
        }
        return false;
    }

    public final boolean A12() {
        C158628xW c158628xW;
        Boolean BW4;
        if (this.A0T == AnonymousClass006.A01 && (c158628xW = A01(this).A0f.A1G) != null && (BW4 = c158628xW.BW4()) != null && BW4.booleanValue()) {
            return true;
        }
        return false;
    }

    public final boolean A13() {
        Integer num = this.A0T;
        if (num != AnonymousClass006.A15 && num != AnonymousClass006.A1C && num != AnonymousClass006.A0u && num != AnonymousClass006.A03 && num != AnonymousClass006.A07 && num != AnonymousClass006.A04 && num != AnonymousClass006.A05 && num != AnonymousClass006.A1L && num != AnonymousClass006.A09 && num != AnonymousClass006.A0A && num != AnonymousClass006.A06 && num != AnonymousClass006.A08 && num != AnonymousClass006.A0B && num != AnonymousClass006.A0E) {
            return false;
        }
        return true;
    }

    public final boolean A14() {
        Integer num = this.A0T;
        if (num != AnonymousClass006.A15 && this.A0P == null && !C25930wq.A1Z(num, AnonymousClass006.A1C) && !C25930wq.A1Z(num, AnonymousClass006.A1L) && !A15() && num != AnonymousClass006.A06 && num != AnonymousClass006.A08 && !C25930wq.A1Z(num, AnonymousClass006.A09) && num != AnonymousClass006.A0A) {
            return false;
        }
        return true;
    }

    public final boolean A15() {
        Integer num = this.A0T;
        if (num != AnonymousClass006.A05 && num != AnonymousClass006.A04) {
            return false;
        }
        return true;
    }

    public final boolean A16() {
        if (this.A0T == AnonymousClass006.A00 && this.A0O != null) {
            return true;
        }
        return false;
    }

    public final boolean A19() {
        Boolean bool;
        B7P b7p = this.A0M;
        if (b7p != null && (bool = b7p.A0f.A2f) != null && bool.booleanValue()) {
            return true;
        }
        return false;
    }

    public final boolean A1A() {
        if (this.A0T == AnonymousClass006.A01 && A01(this).A4m()) {
            return true;
        }
        return false;
    }

    public final boolean A1C() {
        B7P b7p = this.A0M;
        if (b7p != null && !b7p.BYz() && ((b7p.A42() || b7p.A3a(EnumC171099gG.A0e) != null || b7p.A2S() != null) && !b7p.A3V().isEmpty())) {
            return true;
        }
        return false;
    }

    public final boolean A1D() {
        List A3a;
        PromptStickerModel A0F;
        B7P b7p = this.A0M;
        if (b7p != null && (A3a = b7p.A3a(EnumC171099gG.A0l)) != null && !A3a.isEmpty() && (A0F = C150688fG.A0M(A3a).A0F()) != null && A0F.A09()) {
            return true;
        }
        return false;
    }

    public final boolean A1E() {
        Integer num = this.A0T;
        if (num != AnonymousClass006.A0F && num != AnonymousClass006.A0G && num != AnonymousClass006.A0H && num != AnonymousClass006.A0I && num != AnonymousClass006.A0J && num != AnonymousClass006.A0K && num != AnonymousClass006.A0L) {
            return false;
        }
        return true;
    }

    public final boolean A1I(UserSession userSession) {
        if (this.A0T == AnonymousClass006.A0M && C70763jC.A05(C0TD.A05, userSession, 36324973668934479L).booleanValue()) {
            return true;
        }
        return false;
    }

    public final boolean A1J(UserSession userSession) {
        if (this.A0T == AnonymousClass006.A0M && C70763jC.A05(C0TD.A05, userSession, 36324973668934479L).booleanValue()) {
            return true;
        }
        return false;
    }

    public final boolean A1K(UserSession userSession) {
        Integer num = this.A0T;
        if (num != AnonymousClass006.A15 && this.A0P == null && !C25930wq.A1Z(num, AnonymousClass006.A1C) && num != AnonymousClass006.A0u && num != AnonymousClass006.A03 && !C25930wq.A1Z(num, AnonymousClass006.A1L) && !A15() && num != AnonymousClass006.A06 && num != AnonymousClass006.A0A && num != AnonymousClass006.A07) {
            if (num == AnonymousClass006.A08) {
                B74 b74 = this.A07;
                b74.getClass();
                if (b74.A01.A09) {
                    return true;
                }
            }
            if (C25930wq.A1Z(num, AnonymousClass006.A09) && C70763jC.A0E(C0TD.A05, userSession, 36327374555457530L)) {
                return true;
            }
            return false;
        }
        return true;
    }

    @Override // p000X.InterfaceC34537HpI
    public final int AYO() {
        return this.A01;
    }

    @Override // p000X.InterfaceC22116Bqv, p000X.InterfaceC22115Bqu
    public final B7P Au7() {
        return this.A0M;
    }

    @Override // p000X.InterfaceC34537HpI
    public final int B8e() {
        return this.A02;
    }

    @Override // p000X.InterfaceC22116Bqv
    public final User BKI() {
        return this.A0S;
    }

    @Override // p000X.InterfaceC22116Bqv
    public final String BM5() {
        String str = this.A0L;
        if (str == null) {
            String A0g = C25930wq.A0g("%s_%s", new Object[]{this.A0U, this.A0V});
            this.A0L = A0g;
            return A0g;
        }
        return str;
    }

    @Override // p000X.InterfaceC22116Bqv
    public final boolean BW9() {
        if (this.A0T == AnonymousClass006.A01 && this.A0M != null) {
            return true;
        }
        return false;
    }

    @Override // p000X.InterfaceC21924Bnj
    public final boolean BWz() {
        if (this.A0T != AnonymousClass006.A0D && A0E() != null && A0E().BWz()) {
            return true;
        }
        return false;
    }

    public final boolean equals(Object obj) {
        if ((obj instanceof B7B) && C40702Gy.A00(((B7B) obj).A0U, this.A0U)) {
            return true;
        }
        return false;
    }

    @Override // p000X.InterfaceC21924Bnj
    public final String getId() {
        return this.A0U;
    }

    public final int hashCode() {
        return C91534uT.A0D(this.A0U);
    }

    public static void A04(View view, View view2, B7B b7b, BAZ baz, int i) {
        C25673Dbr.A07(view2, baz, b7b.A06(), i, view.getHeight(), true);
    }

    public static void A05(AbstractCollection abstractCollection, Iterator it) {
        B7P b7p = ((B7B) it.next()).A0M;
        if (b7p != null) {
            abstractCollection.add(b7p);
        }
    }

    public final float A06() {
        switch (A00(this)) {
            case 0:
                return A02(this).A02;
            case 1:
            case 10:
                return A01(this).A1f();
            default:
                return BaseViewManager.CAMERA_DISTANCE_NORMALIZATION_MULTIPLIER;
        }
    }

    public final int A07() {
        if (A0I() != null) {
            return A0I().A00;
        }
        return -1;
    }

    public final int A08() {
        C98y c98y;
        int A00 = A00(this);
        if (A00 != 1) {
            if (A00 != 4 || (c98y = this.A0N) == null) {
                return 0;
            }
            return c98y.A01;
        }
        return C25970wu.A05(A01(this).A0f.A3i);
    }

    public final long A0A() {
        int A00 = A00(this);
        if (A00 != 0) {
            if (A00 != 1) {
                if (A00 != 20) {
                    switch (A00) {
                        case 3:
                        case 4:
                        case 5:
                            C98y c98y = this.A0N;
                            if (c98y != null) {
                                return c98y.A04;
                            }
                            break;
                    }
                } else {
                    Long l = this.A0D;
                    if (l != null) {
                        return l.longValue();
                    }
                }
            } else {
                B7P b7p = this.A0M;
                if (b7p != null) {
                    return b7p.A1v();
                }
            }
            return 0L;
        }
        long j = A02(this).A0a;
        if (j == 0) {
            return C25980wv.A08();
        }
        return j;
    }

    public final ImageUrl A0B() {
        switch (A00(this)) {
            case 0:
                String str = A02(this).A2X;
                str.getClass();
                return C3XZ.A01(new File(str), -1, -1);
            case 1:
            case 6:
            case 7:
            case 10:
            case 11:
                return A01(this).A24();
            case 2:
            case 3:
            case 4:
            case 5:
            case 8:
            case 9:
            default:
                return null;
        }
    }

    public final ImageUrl A0C(int i) {
        String str;
        switch (A00(this)) {
            case 0:
                PendingMedia A02 = A02(this);
                if (!A02.A15() && (str = A02.A2X) != null) {
                    return C3XZ.A01(new File(str), -1, -1);
                }
                break;
            case 1:
            case 10:
                B7P A01 = A01(this);
                if (A01.A3z()) {
                    Uri uri = A01.A05;
                    uri.getClass();
                    return C3XZ.A00(uri);
                }
                return A01.A25(i);
            case 3:
            case 4:
            case 5:
                C98y c98y = this.A0N;
                if (c98y != null) {
                    return c98y.A03();
                }
                break;
        }
        return null;
    }

    public final ImageUrl A0D(Context context) {
        String str;
        switch (A00(this)) {
            case 0:
                PendingMedia A02 = A02(this);
                if (!A02.A15() && (str = A02.A2X) != null) {
                    return C3XZ.A01(new File(str), -1, -1);
                }
                break;
            case 1:
            case 7:
            case 10:
                B7P A01 = A01(this);
                if (A01.A3z()) {
                    Uri uri = A01.A05;
                    uri.getClass();
                    return C3XZ.A00(uri);
                }
                return A01.A2M(context);
            case 3:
            case 4:
            case 5:
                C98y c98y = this.A0N;
                if (c98y != null) {
                    return c98y.A03();
                }
                break;
        }
        return null;
    }

    public final ReelCTA A0F() {
        switch (A00(this)) {
            case 0:
                List<ReelCTA> list = A02(this).A3p;
                if (list == null) {
                    list = Collections.emptyList();
                }
                if (C0hB.A00(list)) {
                    return null;
                }
                for (ReelCTA reelCTA : list) {
                    if (C19637Ak8.A03(reelCTA) != null) {
                        return reelCTA;
                    }
                }
                return null;
            case 1:
            case 10:
                return A01(this).A2K();
            default:
                return null;
        }
    }

    public final EnumC23743Cil A0H() {
        int A00 = A00(this);
        if (A00 != 0) {
            if (A00 != 1) {
                return EnumC23743Cil.DEFAULT;
            }
            return A01(this).ARq();
        }
        return A02(this).ARq();
    }

    public final EnumC23771CjE A0I() {
        if (A1E()) {
            return EnumC23771CjE.VIDEO;
        }
        switch (A00(this)) {
            case 0:
                return A02(this).A15;
            case 1:
            case 10:
                return A01(this).Av2();
            case 2:
            case 6:
            case 7:
            case 8:
            case 9:
            default:
                return null;
            case 3:
            case 5:
                return EnumC23771CjE.LIVE;
            case 4:
                return EnumC23771CjE.LIVE_REPLAY;
        }
    }

    public final AN5 A0K() {
        if (A00(this) != 1) {
            return null;
        }
        B7P A01 = A01(this);
        if (A01.A0C == null && A01.A29() != null) {
            AN5 an5 = new AN5();
            A01.A0C = an5;
            an5.A07 = A01.A29().A0h;
            A01.A0C.A03 = A01.A29().A0U;
            A01.A0C.A04 = A01.A29().A0V;
            A01.A0C.A09 = A01.A29().A0j;
            A01.A0C.A08 = A01.A29().A0i;
            A01.A0C.A02 = A01.A29().A0S;
            A01.A0C.A00 = A01.A29().A0H;
            A01.A0C.A05 = A01.A29().A0Z;
            A01.A0C.A01 = A01.A29().A0I;
        }
        return A01.A0C;
    }

    /* JADX WARN: Can't fix incorrect switch cases order, some code will duplicate */
    public final C37073JRt A0N(UserSession userSession) {
        switch (A00(this)) {
            case 1:
            case 7:
            case 10:
                return A01(this).A2d();
            case 3:
            case 4:
            case 5:
                C98y c98y = this.A0N;
                if (c98y != null) {
                    return c98y.A04(userSession);
                }
                break;
        }
        return null;
    }

    public final Long A0O(UserSession userSession) {
        Object obj;
        B7P A05;
        int A00 = A00(this);
        if (A00 != 0) {
            if (A00 != 1) {
                return null;
            }
            return A01(this).A0f.A3p;
        }
        int A002 = A00(this);
        if (A002 != 0) {
            if (A002 != 1) {
                return null;
            }
            obj = A01(this).A0f.A3p;
        } else {
            obj = A02(this).A22;
        }
        if (obj == null || (A05 = C19618Ajo.A01(userSession).A05(A02(this).A22)) == null) {
            return null;
        }
        return Long.valueOf(A05.A1v());
    }

    public final String A0Q() {
        if (A1E()) {
            ASV asv = this.A0B;
            asv.getClass();
            return C25990ww.A0l(asv.A02, C37479Jei.A02);
        }
        switch (A00(this)) {
            case 0:
                return A02(this).A2u;
            case 1:
            case 10:
                return A01(this).A0K;
            default:
                return null;
        }
    }

    public final String A0R() {
        int A00 = A00(this);
        if (A00 != 1 && A00 != 10) {
            return null;
        }
        return A01(this).A0f.A4q;
    }

    /* JADX WARN: Can't fix incorrect switch cases order, some code will duplicate */
    public final String A0S() {
        switch (A00(this)) {
            case 1:
                return A01(this).A0f.A4l;
            case 3:
            case 4:
            case 5:
                C98y c98y = this.A0N;
                if (c98y != null) {
                    return c98y.A0b;
                }
                break;
        }
        return null;
    }

    public final List A0Y() {
        int A00 = A00(this);
        if (A00 != 0) {
            if (A00 != 1 && A00 != 7) {
                return null;
            }
            return A01(this).A3V();
        }
        return A02(this).A0V();
    }

    public final List A0Z() {
        List list;
        C98y c98y;
        int A00 = A00(this);
        if (A00 != 1) {
            if (A00 == 4 && (c98y = this.A0N) != null) {
                return c98y.A0h;
            }
            return C25920wp.A0w();
        }
        B7P A01 = A01(this);
        synchronized (A01) {
            B7I b7i = A01.A0f;
            list = b7i.A6l;
            if (list == null) {
                list = C25920wp.A0w();
                b7i.A6l = list;
            }
        }
        list.getClass();
        return list;
    }

    public final List A0a() {
        ArrayList A0w = C25920wp.A0w();
        B7P b7p = this.A0M;
        if (b7p != null && b7p.A3Y() != null) {
            for (C1BS c1bs : b7p.A3Y()) {
                User user = c1bs.A00;
                boolean z = false;
                boolean A1V = C25960wt.A1V(c1bs.A02);
                Boolean bool = c1bs.A01;
                if (bool != null) {
                    z = bool.booleanValue();
                }
                A0w.add(new BrandedContentTag(user, A1V, z));
            }
        }
        return A0w;
    }

    public final boolean A0c() {
        Boolean bool;
        if (BW9() && (bool = A01(this).A0f.A1p) != null && bool.booleanValue()) {
            return true;
        }
        return false;
    }

    public final boolean A0e() {
        String str;
        ReelCTA A0F = A0F();
        if (A0F != null) {
            str = C19637Ak8.A03(A0F);
        } else {
            str = null;
        }
        if (!TextUtils.isEmpty(str) && !A0r()) {
            return true;
        }
        return false;
    }

    public final boolean A0g() {
        String str;
        int A00 = A00(this);
        if (A00 != 0) {
            if (A00 != 1) {
                return false;
            }
            str = A01(this).A2y();
        } else {
            List list = A02(this).A3p;
            if (list == null) {
                list = Collections.emptyList();
            }
            if (!C0hB.A00(list)) {
                str = C19637Ak8.A01((ReelCTA) list.get(0));
            } else {
                str = null;
            }
        }
        return !TextUtils.isEmpty(str);
    }

    public final boolean A0j() {
        List list;
        int A00 = A00(this);
        if (A00 != 0) {
            if (A00 != 1) {
                return false;
            }
            B7P A01 = A01(this);
            if (!C0hB.A00(A01.A3W()) || A01.A3y()) {
                return true;
            }
            return false;
        }
        List list2 = A02(this).A3p;
        if (list2 == null) {
            list2 = Collections.emptyList();
        }
        if (!C0hB.A00(list2)) {
            list = ((ReelCTA) list2.get(0)).A0D;
        } else {
            list = null;
        }
        return !C0hB.A00(list);
    }

    public final boolean A0k() {
        if (!A1E()) {
            switch (A00(this)) {
                case 0:
                    return true;
                case 1:
                case 10:
                    return A01(this).A40();
                default:
                    return false;
            }
        }
        return true;
    }

    public final boolean A0t() {
        if (A16()) {
            PendingMedia A02 = A02(this);
            if (!A02.A15() && !A02.A16()) {
                if ((C25930wq.A1Z(A02.A15, EnumC23771CjE.VIDEO) && A02.A2u == null) || A02.A2X == null) {
                    return true;
                }
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A0x() {
        return C25930wq.A1Y(A0G());
    }

    public final boolean A17() {
        C98y c98y;
        int A00 = A00(this);
        boolean A1G = A1G();
        switch (A00) {
            case 3:
            case 4:
                if (A1G && (c98y = this.A0N) != null && c98y.A08.A02()) {
                    return true;
                }
                return false;
            case 5:
                if (A1G && this.A0N != null) {
                    return true;
                }
                return false;
            default:
                return A1G;
        }
    }

    public final boolean A18() {
        if (!A1G() && this.A0T == AnonymousClass006.A01) {
            return true;
        }
        return false;
    }

    public final boolean A1B() {
        if (A0G() != null) {
            if (A0G().A00 != null && !A0G().A00.booleanValue()) {
                return true;
            }
            return false;
        }
        return true;
    }

    public final boolean A1F() {
        if (A1E()) {
            ASV asv = this.A0B;
            asv.getClass();
            if (C25990ww.A0l(asv.A02, C37479Jei.A02) == null) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1G() {
        if (A1E()) {
            return true;
        }
        switch (A00(this)) {
            case 0:
                return C25930wq.A1Z(A02(this).A15, EnumC23771CjE.VIDEO);
            case 1:
            case 10:
                return A01(this).Ba2();
            case 2:
            case 6:
            case 7:
            case 8:
            case 9:
            default:
                return false;
            case 3:
            case 4:
            case 5:
                return true;
        }
    }

    public final boolean A1H(EnumC171099gG enumC171099gG) {
        List B6a = B6a(enumC171099gG);
        if (B6a != null && !B6a.isEmpty()) {
            return true;
        }
        return false;
    }

    @Override // p000X.InterfaceC22116Bqv
    public final float ARQ(UserSession userSession) {
        return A06();
    }

    @Override // p000X.InterfaceC22116Bqv
    public final List B6a(EnumC171099gG enumC171099gG) {
        int A00 = A00(this);
        if (A00 != 0) {
            if (A00 == 1) {
                return A01(this).A3a(enumC171099gG);
            }
            return null;
        }
        List A0V = A02(this).A0V();
        if (A0V != null) {
            ArrayList A0w = C25920wp.A0w();
            Iterator it = A0V.iterator();
            while (it.hasNext()) {
                BAZ A0S = C150658fD.A0S(it);
                if (A0S.A0k == enumC171099gG) {
                    A0w.add(A0S);
                }
            }
            return A0w;
        }
        return null;
    }

    @Override // p000X.InterfaceC21924Bnj
    public final String BDU(UserSession userSession) {
        return C19763AmC.A0G(this, userSession);
    }

    @Override // p000X.InterfaceC21924Bnj
    public final boolean BV8() {
        if (A0E() != null && A0E().BV8()) {
            return true;
        }
        return false;
    }

    @Override // p000X.InterfaceC21924Bnj
    public final boolean BYz() {
        if (BW9() && A01(this).BYz()) {
            return true;
        }
        return false;
    }

    public B7B(User user, Integer num, String str, String str2) {
        this.A0W = C25920wp.A0w();
        this.A0G = false;
        this.A0Z = C25920wp.A0w();
        this.A0b = C25960wt.A0o();
        this.A0Y = C25920wp.A0w();
        this.A0a = C25960wt.A0o();
        this.A0X = C25920wp.A0w();
        this.A06 = null;
        this.A02 = 0;
        this.A01 = 0;
        this.A0V = str;
        this.A0M = null;
        this.A0Q = null;
        this.A0O = null;
        this.A0N = null;
        this.A0T = num;
        this.A0U = str2;
        this.A0S = user;
        this.A0R = null;
        this.A0P = null;
        this.A08 = null;
        this.A05 = null;
        this.mBrandSurveyImpression = null;
    }

    public B7B(C98y c98y, Integer num, String str) {
        this.A0W = C25920wp.A0w();
        this.A0G = false;
        this.A0Z = C25920wp.A0w();
        this.A0b = C25960wt.A0o();
        this.A0Y = C25920wp.A0w();
        this.A0a = C25960wt.A0o();
        this.A0X = C25920wp.A0w();
        this.A06 = null;
        this.A02 = 0;
        this.A01 = 0;
        this.A0V = str;
        this.A0N = c98y;
        this.A0U = c98y.A0Y;
        this.A0S = c98y.A0D;
        this.A0T = num;
        this.A0M = null;
        this.A0Q = null;
        this.A0O = null;
        this.A0R = null;
        this.A0P = null;
        this.A08 = null;
        this.A05 = null;
        this.mBrandSurveyImpression = null;
    }

    public B7B(B77 b77, User user, String str) {
        this.A0W = C25920wp.A0w();
        this.A0G = false;
        this.A0Z = C25920wp.A0w();
        this.A0b = C25960wt.A0o();
        this.A0Y = C25920wp.A0w();
        this.A0a = C25960wt.A0o();
        this.A0X = C25920wp.A0w();
        this.A06 = null;
        this.A02 = 0;
        this.A01 = 0;
        this.A0V = str;
        this.A0O = b77;
        this.A0M = null;
        this.A0Q = null;
        this.A0T = AnonymousClass006.A00;
        this.A0U = b77.A00.A3C;
        this.A0S = user;
        this.A0N = null;
        this.A0R = null;
        this.A0P = null;
        this.A08 = null;
        this.A05 = null;
        this.mBrandSurveyImpression = null;
    }

    public B7B(C18451ACn c18451ACn, B70 b70, String str) {
        this.A0W = C25920wp.A0w();
        this.A0G = false;
        this.A0Z = C25920wp.A0w();
        this.A0b = C25960wt.A0o();
        this.A0Y = C25920wp.A0w();
        this.A0a = C25960wt.A0o();
        this.A0X = C25920wp.A0w();
        this.A06 = null;
        this.A02 = 0;
        this.A01 = 0;
        this.A0V = str;
        this.A0T = AnonymousClass006.A0E;
        this.A0A = b70;
        this.A0O = null;
        this.A0M = null;
        this.A0Q = null;
        this.A0U = "RECONSIDERATION_INJECTED_STORY";
        this.A0S = null;
        this.A0N = null;
        this.A0R = null;
        this.A0P = null;
        this.A08 = null;
        this.A05 = null;
        this.A06 = c18451ACn;
        this.mBrandSurveyImpression = null;
    }

    public B7B(final C5KV c5kv, User user, Integer num, String str, String str2) {
        ASV asv;
        this.A0W = C25920wp.A0w();
        this.A0G = false;
        this.A0Z = C25920wp.A0w();
        this.A0b = C25960wt.A0o();
        this.A0Y = C25920wp.A0w();
        this.A0a = C25960wt.A0o();
        this.A0X = C25920wp.A0w();
        this.A06 = null;
        this.A02 = 0;
        this.A01 = 0;
        this.A0V = str;
        this.A0U = str2;
        this.A0T = num;
        this.A0S = user;
        this.A0M = null;
        this.A0Q = null;
        this.A0O = null;
        this.A0N = null;
        this.A0R = null;
        this.A0P = null;
        this.A08 = null;
        this.A05 = null;
        if (C37479Jei.A03.compareAndSet(false, true)) {
            C35734Iir c35734Iir = new C35734Iir();
            C0h2 A00 = C17300gs.A00();
            C0OR.A06(A00);
            A00.AKr(c35734Iir);
        }
        if (num.intValue() != 22) {
            asv = new ASV(c5kv) { // from class: X.9O4
                {
                    JX1 jx1 = J4N.A02;
                }
            };
        } else {
            asv = new ASV(c5kv) { // from class: X.9O3
                {
                    JX1 jx1 = J4N.A01;
                }
            };
        }
        this.A0B = asv;
        this.mBrandSurveyImpression = null;
    }

    public B7B(C158758xl c158758xl, String str) {
        this.A0W = C25920wp.A0w();
        this.A0G = false;
        this.A0Z = C25920wp.A0w();
        this.A0b = C25960wt.A0o();
        this.A0Y = C25920wp.A0w();
        this.A0a = C25960wt.A0o();
        this.A0X = C25920wp.A0w();
        this.A06 = null;
        this.A02 = 0;
        this.A01 = 0;
        this.A0V = str;
        this.A0T = AnonymousClass006.A0M;
        this.mBrandResearchSurvey = c158758xl;
        String str2 = c158758xl.A06;
        String str3 = c158758xl.A08;
        this.mBrandSurveyImpression = new B73(str2, str3);
        this.A0Q = null;
        B7P b7p = new B7P(new B7I());
        this.A0M = b7p;
        B7I b7i = b7p.A0f;
        b7i.A4Y = str;
        b7i.A4l = str3;
        this.A0N = null;
        this.A0R = null;
        this.A0P = null;
        this.A08 = null;
        this.A05 = null;
        this.A0O = null;
        this.A08 = null;
        this.A05 = null;
        this.A0U = str2;
        this.A0S = null;
    }

    public B7B(B7P b7p, C20518B6w c20518B6w, B76 b76, C20520B6y c20520B6y, B74 b74, C20521B6z c20521B6z, C158328x1 c158328x1, B70 b70, B7A b7a, User user, Integer num, String str) {
        this.A0W = C25920wp.A0w();
        this.A0G = false;
        this.A0Z = C25920wp.A0w();
        this.A0b = C25960wt.A0o();
        this.A0Y = C25920wp.A0w();
        this.A0a = C25960wt.A0o();
        this.A0X = C25920wp.A0w();
        this.A06 = null;
        this.A02 = 0;
        this.A01 = 0;
        this.A0V = str;
        this.A0O = null;
        this.A0N = null;
        this.mBrandSurveyImpression = null;
        int intValue = num.intValue();
        switch (intValue) {
            case 0:
                C37786JmD.A07(b7a, "Netego bakeoff units needs to have a SimpleAction");
                this.A0U = b7a.getId();
                this.A0T = AnonymousClass006.A15;
                this.A0R = b7a;
                this.A0P = null;
                this.A08 = null;
                this.A0A = null;
                this.A05 = null;
                this.A0M = b7p;
                this.A0Q = null;
                this.A0S = null;
                this.A07 = null;
                return;
            case 1:
                C37786JmD.A07(c20520B6y, "Netego ad4ad unit needs to have an Ad4ad object");
                this.A0U = c20520B6y.A00.A02;
                this.A0T = AnonymousClass006.A01;
                this.A0P = c20520B6y;
                this.A08 = null;
                this.A0A = null;
                this.A0R = null;
                this.A05 = null;
                this.A0M = b7p;
                this.A0Q = null;
                this.A0S = user;
                this.A07 = null;
                return;
            case 2:
                C37786JmD.A07(c20521B6z, "Netego SU unit needs to have an SU object");
                this.A0U = c20521B6z.getId();
                this.A0T = AnonymousClass006.A1C;
                this.A0P = null;
                this.A08 = c20521B6z;
                this.A0A = null;
                this.A0R = null;
                this.A05 = null;
                this.A0M = null;
                this.A0Q = null;
                this.A0S = null;
                this.A07 = null;
                return;
            case 3:
                C37786JmD.A07(b7a, "Netego quality survey needs to have a SimpleAction");
                this.A0U = b7a.getId();
                this.A0T = AnonymousClass006.A0u;
                this.A0R = b7a;
                this.A0P = null;
                this.A08 = null;
                this.A0A = null;
                this.A0M = null;
                this.A0Q = null;
                this.A0S = null;
                this.A09 = null;
                this.A04 = null;
                this.A05 = null;
                this.A07 = null;
                return;
            case 4:
                C37786JmD.A07(b7a, "Story creation upsell needs to have a SimpleAction");
                this.A0U = b7a.getId();
                this.A0T = AnonymousClass006.A03;
                this.A0R = b7a;
                this.A0P = null;
                this.A08 = null;
                this.A0A = null;
                this.A0M = null;
                this.A0Q = null;
                this.A0S = null;
                this.A09 = null;
                this.A04 = null;
                this.A05 = null;
                this.A07 = null;
                return;
            case 5:
                C37786JmD.A07(c158328x1, "Netego suggested clips unit needs to have an suggested clips object");
                this.A0U = c158328x1.getId();
                this.A0T = AnonymousClass006.A1L;
                this.A0P = null;
                this.A08 = null;
                this.A0A = null;
                this.A0R = null;
                this.A0M = null;
                this.A0Q = null;
                this.A0S = null;
                this.A09 = c158328x1;
                this.A04 = null;
                this.A05 = null;
                this.A07 = null;
                return;
            case 6:
            case 7:
                C37786JmD.A07(b70, "Netego PFY unit needs to have an suggested products object");
                this.A0U = b70.getId();
                if (intValue != 6) {
                    this.A0T = AnonymousClass006.A05;
                } else {
                    this.A0T = AnonymousClass006.A04;
                }
                this.A0P = null;
                this.A08 = null;
                this.A0A = b70;
                this.A0R = null;
                this.A0M = null;
                this.A0Q = null;
                this.A0S = null;
                this.A09 = null;
                this.A04 = null;
                this.A05 = null;
                this.A07 = null;
                return;
            case 8:
                C37786JmD.A07(null, "Netego shops for you unit needs to have an suggested shops object");
                throw null;
            case 9:
                C37786JmD.A07(b7a, "Ads consent growth story needs to have a SimpleAction");
                this.A0U = b7a.getId();
                this.A0T = AnonymousClass006.A07;
                this.A0R = b7a;
                this.A0P = null;
                this.A08 = null;
                this.A0A = null;
                this.A0M = null;
                this.A0Q = null;
                this.A0S = null;
                this.A09 = null;
                this.A04 = null;
                this.A05 = null;
                return;
            case 10:
                C37786JmD.A07(b74, "Bloks netego needs to have a BloksStoryNetego.");
                this.A0U = b74.A01.A05;
                this.A0T = AnonymousClass006.A08;
                this.A0P = null;
                this.A08 = null;
                this.A0A = null;
                this.A0R = null;
                this.A0M = null;
                this.A0Q = null;
                this.A0S = null;
                this.A09 = null;
                this.A04 = null;
                this.A05 = null;
                this.A07 = b74;
                return;
            case 11:
                C37786JmD.A07(c20518B6w, "Netego ACR unit needs to have an ACR in Story object");
                this.A0U = c20518B6w.getId();
                this.A0T = AnonymousClass006.A09;
                this.A0P = null;
                this.A08 = null;
                this.A0A = null;
                this.A0R = null;
                this.A0M = null;
                this.A0Q = null;
                this.A0S = null;
                this.A09 = null;
                this.A04 = c20518B6w;
                this.A05 = null;
                this.A07 = null;
                return;
            case IgReactQEModule.CONFIG_KEY_OFFSET /* 12 */:
                C37786JmD.A07(b76, "Netego trending prompts unit needs to have a prompts in story object");
                this.A0U = b76.getId();
                this.A0T = AnonymousClass006.A0A;
                this.A0P = null;
                this.A08 = null;
                this.A0A = null;
                this.A0R = null;
                this.A0M = null;
                this.A0Q = null;
                this.A0S = null;
                this.A09 = null;
                this.A04 = null;
                this.A05 = b76;
                this.A07 = null;
                return;
            default:
                this.A0R = null;
                this.A0P = null;
                this.A08 = null;
                this.A0A = null;
                this.A0M = null;
                this.A0Q = null;
                this.A0S = null;
                this.A09 = null;
                this.A07 = null;
                this.A04 = null;
                this.A05 = null;
                throw C25950ws.A0k("Unsupported netego type");
        }
    }

    public B7B(B7P b7p, B7O b7o, User user, String str) {
        this.A0W = C25920wp.A0w();
        this.A0G = false;
        this.A0Z = C25920wp.A0w();
        this.A0b = C25960wt.A0o();
        this.A0Y = C25920wp.A0w();
        this.A0a = C25960wt.A0o();
        this.A0X = C25920wp.A0w();
        this.A06 = null;
        this.A02 = 0;
        this.A01 = 0;
        this.A0V = str;
        this.A0M = b7p;
        this.A0Q = b7o;
        this.A0O = null;
        this.A0T = AnonymousClass006.A01;
        this.A0U = b7p.A0f.A4Y;
        this.A0S = user;
        this.A0N = null;
        this.A0R = null;
        this.A0P = null;
        this.A08 = null;
        this.A0A = null;
        this.A0C = null;
        this.A09 = null;
        this.A04 = null;
        this.A05 = null;
        this.A00 = 0;
        this.mBrandSurveyImpression = null;
        if (!b7p.A3V().isEmpty()) {
            Iterator it = b7p.A3V().iterator();
            while (it.hasNext()) {
                C150658fD.A0S(it).A1C = str;
            }
        }
    }

    public B7B(B7P b7p, User user, Integer num, String str) {
        this.A0W = C25920wp.A0w();
        this.A0G = false;
        this.A0Z = C25920wp.A0w();
        this.A0b = C25960wt.A0o();
        this.A0Y = C25920wp.A0w();
        this.A0a = C25960wt.A0o();
        this.A0X = C25920wp.A0w();
        this.A06 = null;
        this.A02 = 0;
        this.A01 = 0;
        this.A0V = str;
        this.A0M = b7p;
        this.A0Q = null;
        this.A0O = null;
        this.A0T = num;
        this.A0U = b7p.A0f.A4Y;
        this.A0S = user;
        this.A0N = null;
        this.A0R = null;
        this.A0P = null;
        this.A08 = null;
        this.A0C = null;
        this.A00 = 0;
        if (!b7p.A3V().isEmpty()) {
            Iterator it = b7p.A3V().iterator();
            while (it.hasNext()) {
                C150658fD.A0S(it).A1C = str;
            }
        }
        this.mBrandSurveyImpression = null;
    }

    public B7B(Integer num, List list) {
        Integer num2;
        this.A0W = C25920wp.A0w();
        this.A0G = false;
        this.A0Z = C25920wp.A0w();
        this.A0b = C25960wt.A0o();
        this.A0Y = C25920wp.A0w();
        this.A0a = C25960wt.A0o();
        this.A0X = C25920wp.A0w();
        this.A06 = null;
        this.A02 = 0;
        this.A01 = 0;
        int intValue = num.intValue();
        String A00 = 1 != intValue ? "story_interstitial_chaining" : AnonymousClass000.A00(78);
        this.A0V = A00;
        this.A0M = null;
        this.A0Q = null;
        this.A0O = null;
        this.A0N = null;
        this.A0S = null;
        this.A0U = A00;
        this.A0R = null;
        this.A0P = null;
        this.mBrandSurveyImpression = null;
        if (intValue == 0) {
            this.A0E = list;
            num2 = AnonymousClass006.A0B;
        } else if (intValue == 1) {
            num2 = AnonymousClass006.A0D;
        } else {
            this.A0E = null;
            throw C25950ws.A0k("unsupported story interstitial type");
        }
        this.A0T = num2;
    }
}
