package p000X;
/* renamed from: X.0gD  reason: invalid class name */
/* loaded from: classes.dex */
public final class C0gD {
    public static String A00(int i) {
        switch (i) {
            case 1013:
                return "NAVIGATION_REEL_FEED_TIMELINE";
            case 1024:
                return "NAVIGATION_SAC_CREATE_PASSWORD";
            case 1066:
                return "NAVIGATION_INSTAGRAM_SHOPPING_MINI_SHOP_STOREFRONT";
            case 1113:
                return "NAVIGATION_STORY_EMOJI";
            case 1114:
                return "NAVIGATION_FOLLOW_LIST_SORTING_SELECTION";
            case 1148:
                return "NAVIGATION_CLIPS_TEMPLATE_BROWSER";
            case 1193:
                return "NAVIGATION_SUNDIAL_STACKED_TIMELINE_BOTTOM_SHEET_VC";
            case 1210:
                return "NAVIGATION_BLENDED_SEARCH_EDIT_RECENT";
            case 1247:
                return "NAVIGATION_COMMENTS_V2_SINGLE_FEED";
            case 1274:
                return "NAVIGATION_MESSAGE_THREAD_FILTER_TYPE";
            case 1289:
                return "NAVIGATION_IG_CAMERA_MINI_GALLERY_CATEGORY_PAGE";
            case 1349:
                return "NAVIGATION_FOLLOW_REQUESTS";
            case 1351:
                return "NAVIGATION_FAVORITES_MANAGEMENT";
            case 1374:
                return "NAVIGATION_PRIVATE_STORIES_SHARE_SHEET";
            case 1377:
                return "NAVIGATION_PROMOTE_ERROR";
            case 1395:
                return "NAVIGATION_MEMORIES_STICKER_LIST";
            case 1402:
                return "NAVIGATION_MUSIC_DURATION_PICKER";
            case 1446:
                return "NAVIGATION_CLIPS_VIEWER_FEED_CONTEXTUAL_LOCATION";
            case 1449:
                return "NAVIGATION_FEED_CONTEXTUAL_SELF_PROFILE";
            case 1487:
                return "NAVIGATION_EDIT_POST";
            case 1510:
                return "NAVIGATION_DIRECT_REACTION_FRAGMENT";
            case 1528:
                return "NAVIGATION_STORY_PROMPT_PARTICIPANT_CONTEXT_SHEET";
            case 1534:
                return "NAVIGATION_DIRECT_THREAD_DETAILS_REDESIGN";
            case 1541:
                return "NAVIGATION_COMMENTS_V2_FEED_TIMELINE_FOLLOWING";
            case 1552:
                return "NAVIGATION_USER_PREVIEW";
            case 1554:
                return "NAVIGATION_CONTENT_APPRECIATION";
            case 1557:
                return "NAVIGATION_CLIPS_USER_DETAIL_RIGHT_PANEL";
            case 1562:
                return "NAVIGATION_TABBED_GALLERY_CAMERA";
            case 1564:
                return "NAVIGATION_SELF_SETTINGS";
            case 1580:
                return "NAVIGATION_COM_INSTAGRAM_EQUITY_PRONOUNS_EDIT_PRONOUNS_SCREEN";
            case 1590:
                return "NAVIGATION_CLIPS_DRAFTS";
            case 1666:
                return "NAVIGATION_TWO_FAC";
            case 1689:
                return "NAVIGATION_PROMOTE_ADS_MANAGER_FRAGMENT";
            case 1705:
                return "NAVIGATION_SELF_LIKERS";
            case 1716:
                return "NAVIGATION_ACCOUNT_SWITCH_FRAGMENT";
            case 1730:
                return "NAVIGATION_RESELECT_COVER_PHOTO_FRAGMENT";
            case 1741:
                return "NAVIGATION_CLIPS_VIEWER_REEL_DIRECT";
            case 1790:
                return "NAVIGATION_SELF_COMMENTS_V2_CLIPS_VIEWER_FEED_CONTEXTUAL_SELF_PROFILE";
            case 1862:
                return "NAVIGATION_THEME_SETTINGS";
            case 1868:
                return "NAVIGATION_SUNDIAL_MUSIC_BROWSER";
            case 1941:
                return "NAVIGATION_CLIPS_VIEWER_STORY_MENTIONS_ACTIVITY_FEED";
            case 1970:
                return "NAVIGATION_NEWSFEED_FILTER_SELECTOR";
            case 1983:
                return "NAVIGATION_EMOJI_PICKER_SHEET";
            case 1985:
                return "NAVIGATION_CLIPS_VIEWER_CLIPS_TAB";
            case 1998:
                return "NAVIGATION_CONTACT_SHEET";
            case 2033:
                return "NAVIGATION_DIRECT_CUSTOM_EMOJI_REACTIONS_LIST_FRAGMENT";
            case 2093:
                return "NAVIGATION_PANAVIDEO_SHARE_SHEET";
            case 2094:
                return "NAVIGATION_CLIPS_VIEWER_FEED_CONTEXTUAL_MAP";
            case 2127:
                return "NAVIGATION_SAVED_COLLECTIONS_LIST";
            case 2128:
                return "NAVIGATION_CLIPS_PRECAPTURE_CAMERA";
            case 2157:
                return "NAVIGATION_IGTV_SERIES_PROFILE_LIST";
            case 2178:
                return "NAVIGATION_DIRECT_STICKER_TAB_TRAY_FRAGMENT";
            case 2205:
                return "NAVIGATION_CLIPS_VIEWER_REEL_PUSH_NOTIFICATION";
            case 2256:
                return "NAVIGATION_DISCOVER_PEOPLE";
            case 2261:
                return "NAVIGATION_MEDIA_VIEW";
            case 2265:
                return "NAVIGATION_CONTENT_SEARCH";
            case 2293:
                return "NAVIGATION_FEED_CONTEXTUAL_ADS_CHAIN";
            case 2352:
                return "NAVIGATION_QP_FULLSCREEN";
            case 2353:
                return "NAVIGATION_DIRECT_THREAD_MEMBERS_LIST";
            case 2360:
                return "NAVIGATION_PHOTO_VIEW_STORY_STICKER";
            case 2385:
                return "NAVIGATION_GUIDE_GRID_PROFILE";
            case 2422:
                return "NAVIGATION_LIVE_FEED_TIMELINE";
            case 2458:
                return "NAVIGATION_CLIPS_COVER_PHOTO_PICKER";
            case 2470:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_REEL_SEARCH_ITEM_HEADER";
            case 2491:
                return "NAVIGATION_EDIT_PROFILE_MULTIPLE_LINKS";
            case 2496:
                return "NAVIGATION_FEED_CONTEXTUAL_HASHTAG";
            case 2509:
                return "NAVIGATION_CAMERA_TRANSLATION_SHEET";
            case 2533:
                return "NAVIGATION_CAMERA_NAV";
            case 2552:
                return "NAVIGATION_DIRECT_POSTCAPTURE_CAMERA";
            case 2583:
                return "NAVIGATION_STORY_STICKERS_TRAY";
            case 2589:
                return "NAVIGATION_SETTINGS_PRIVACY_OPTIONS";
            case 2591:
                return "NAVIGATION_IGLOGOUT_VIEW_CONTROLLER";
            case 2605:
                return "NAVIGATION_STORY_ATTRIBUTION_BOTTOM_SHEET";
            case 2611:
                return "NAVIGATION_LOGINACTIVITY";
            case 2627:
                return "NAVIGATION_CLIPS_VIEWER_COMMENTS_V2_CLIPS_VIEWER_CLIPS_NETEGO";
            case 2649:
                return "NAVIGATION_LEAD_ADS";
            case 2656:
                return "NAVIGATION_REEL_COUNTDOWN_STICKER_CONSUMPTION_SHEET_FRAGMENT";
            case 2657:
                return "NAVIGATION_CLIPS_TEMPLATE_PAGE";
            case 2661:
                return "NAVIGATION_COM_INSTAGRAM_PORTABLE_SETTINGS_HIDE_LIKES_AND_VIEW_COUNTS_SETTINGS";
            case 2706:
                return "NAVIGATION_BLOCK_OPTIONS_BOTTOM_SHEET";
            case 2715:
                return "NAVIGATION_PROMOTE_AUDIENCE";
            case 2746:
                return "NAVIGATION_DIRECT_MEDIA_PICKER_PHOTOS_FRAGMENT";
            case 2748:
                return "NAVIGATION_IG_REELS_SHARE_SHEET_ADV_SETTINGS";
            case 2759:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_REEL_CLIPS_NETEGO";
            case 2773:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_NEWSFEED_YOU";
            case 2781:
                return "NAVIGATION_CLIPS_VIEWER_CLIPS_SUGGESTED_FEED_CONTEXTUAL_CHAIN";
            case 2787:
                return "NAVIGATION_CLIPS_VIEWER_LIVE";
            case 2806:
                return "NAVIGATION_DIRECT_JOIN_BROADCAST_CHAT_NUX";
            case 2839:
                return "NAVIGATION_COMMENTS_V2_NEWSFEED_YOU";
            case 2874:
                return "NAVIGATION_STORIES_ATTRIBUTION_CONTEXT_SHEET";
            case 2884:
                return "NAVIGATION_DATA_USAGE_SETTINGS";
            case 2892:
                return "NAVIGATION_EDIT_REEL_HIGHLIGHTS";
            case 2944:
                return "NAVIGATION_NEWSFEED_YOU";
            case 2947:
                return "NAVIGATION_REEL_DASHBOARD_ADD_TO_STORY_CAMERA_FRAGMENT";
            case 2960:
                return "NAVIGATION_IG_DIRECT_NOTES_SELF_SHEET";
            case 2981:
                return "NAVIGATION_CLIPS_VIEWER_COMMENTS_V2_PUSH";
            case 2985:
                return "NAVIGATION_REEL_PROMPT_SHARE_FRAGMENT";
            case 2991:
                return "NAVIGATION_IGSUNDIAL_DRAFTI_CLOUD_NUXVIEW_CONTROLLER";
            case 3000:
                return "NAVIGATION_CLIPS_VIEWER_REEL_ACTIVITY_FEED";
            case 3001:
                return "NAVIGATION_CLIPS_VIEWER_PREVIEW_GUIDE_DETAIL_PROFILE";
            case 3020:
                return "NAVIGATION_PEOPLE_TAGGING_SEARCH";
            case 3041:
                return "NAVIGATION_CLIPS_AD_CTA";
            case 3065:
                return "NAVIGATION_REEL_POLL_VOTERS_LIST";
            case 3069:
                return "NAVIGATION_CLIPS_VIEWER_COMMENTS_V2_CLIPS_VIEWER_CLIPS_PROFILE";
            case 3081:
                return "NAVIGATION_MODAL_COMMENT_COMPOSER_NEWSFEED_YOU";
            case 3094:
                return "NAVIGATION_DIRECT_MEDIA_PICKER_WATERFALL";
            case 3140:
                return "NAVIGATION_CLIPS_VIEWER_CLIPS_NETEGO";
            case 3150:
                return "NAVIGATION_TABBED_EXPLORER_SHEET";
            case 3196:
                return "NAVIGATION_DIRECT_SEARCH_SECURE_THREAD";
            case 3216:
                return "NAVIGATION_STORY_EMOJI_PICKER_TRAY";
            case 3254:
                return "NAVIGATION_COMMENTS_V2_IGSTORY_VIEWER_VIEW_CONTROLLER";
            case 3258:
                return "NAVIGATION_IGSUNDIAL_ADD_CLIP_VIEW_CONTROLLER";
            case 3269:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_REEL_STORY_VIEWER_LIST";
            case 3316:
                return "NAVIGATION_TRIM_EDITOR";
            case 3322:
                return "NAVIGATION_STORY_PREVIEW_XPOSTING_SHARE_SHEET";
            case 3325:
                return "NAVIGATION_DIRECT_GIF_TRAY_FRAGMENT";
            case 3384:
                return "NAVIGATION_VIDEO_VIEW";
            case 3401:
                return "NAVIGATION_IGCONTENT_SCHEDULING_VIEW_CONTROLLER";
            case 3427:
                return "NAVIGATION_PROMOTE_REVIEW";
            case 3441:
                return "NAVIGATION_FOLLOWERS";
            case 3443:
                return "NAVIGATION_CLIPS_VIEWER_FEED_CONTEXTUAL_SAVED_COLLECTIONS";
            case 3450:
                return "NAVIGATION_REELS_ACHIEVEMENTS";
            case 3463:
                return "NAVIGATION_CAMERA_SETTINGS";
            case 3480:
                return "NAVIGATION_MESSAGE_SEARCH_MESSAGE_LIST_FRAGMENT";
            case 3486:
                return "NAVIGATION_CLIPS_VIEWER_CLIPS_VIEWER_EXPLORE_POPULAR_MINOR_UNIT";
            case 3519:
                return "NAVIGATION_REEL_HIGHLIGHTS_COVER_TITLE";
            case 3540:
                return "NAVIGATION_INSTAGRAM_SHOPPING_TAGGING_FEED";
            case 3595:
                return "NAVIGATION_CLIPS_VIEWER_AUDIO_PAGE";
            case 3607:
                return "NAVIGATION_CLIPS_VIEWER_ORIGINAL_CREATOR_VIDEO";
            case 3636:
                return "NAVIGATION_IGSUNDIAL_INTEREST_TARGETING_VIEW_CONTROLLER";
            case 3638:
                return "NAVIGATION_COMMENTS_V2_FEED_CONTEXTUAL_CHAIN";
            case 3642:
                return "NAVIGATION_SHOPS_SERP_BLOKS";
            case 3648:
                return "NAVIGATION_MUSIC_OVERLAY_DETAIL";
            case 3677:
                return "NAVIGATION_MULTI_BLOCK_BOTTOM_SHEET";
            case 3702:
                return "NAVIGATION_PRO2PRO_BLOCKING";
            case 3703:
                return "NAVIGATION_COM_INSTAGRAM_INSIGHTS_MEDIA_REFRESH_STORIES_CORE";
            case 3715:
                return "NAVIGATION_ACTIONABLE_CONFIRMATION_TOAST_LIST";
            case 3746:
                return "NAVIGATION_IG_CAMERA_END_EFFECT_INFO_SHEET";
            case 3748:
                return "NAVIGATION_USER_LIST_GROUP_HASHTAGS_AND_CREATORS_AND_BUSINESSES";
            case 3750:
                return "NAVIGATION_ACTION_LIST_VIEW_CONTROLLER";
            case 3761:
                return "NAVIGATION_STORIES_CAMERA_SETTINGS";
            case 3766:
                return "NAVIGATION_COM_INSTAGRAM_INSIGHTS_ACCOUNT_TIMEFRAME_SUMMARY_CONTAINER";
            case 3772:
                return "NAVIGATION_DIRECT_RECIPIENT_PICKER";
            case 3781:
                return "NAVIGATION_FEED_CONTEXTUAL_GROUP_PROFILE";
            case 3815:
                return "NAVIGATION_HIGHLIGHTS_ADD_SHEET";
            case 3846:
                return "NAVIGATION_LINK_STICKER_CREATION";
            case 3847:
                return "NAVIGATION_PROFILE_SOCIAL_CONTEXT";
            case 3865:
                return "NAVIGATION_COM_INSTAGRAM_INSIGHTS_ACCOUNT_AUDIENCE_BREAKOUT_TIMEFRAME_CONTAINER";
            case 3937:
                return "NAVIGATION_FEED_CONTEXTUAL_LOCATION";
            case 3940:
                return "NAVIGATION_CLIPS_VIEWER_DISCOVERY_MAP_LOCATION_DETAIL_GRID";
            case 3967:
                return "NAVIGATION_DIRECT_ROLL_CALL_CARD_GALLERY_FRAGMENT";
            case 4003:
                return "NAVIGATION_CLIPS_SHARE_SHEET_PREVIEW_PAGE";
            case 4021:
                return "NAVIGATION_RECIPE_SHEET";
            case 4033:
                return "NAVIGATION_INFO_PAGE_MODULE";
            case 4058:
                return "NAVIGATION_CLIPS_VIEWER_REEL_DIRECT_INBOX";
            case 4072:
                return "NAVIGATION_SECURITY_CHECKUP_LANDING";
            case 4089:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_FEED_CONTEXTUAL_PROFILE";
            case 4092:
                return "NAVIGATION_CLIPS_VIEWER_REEL_HIGHLIGHT_PROFILE";
            case 4107:
                return "NAVIGATION_SELF_FOLLOWERS";
            case 4141:
                return "NAVIGATION_COMMENTS_V2_FEED_CONTEXTUAL_PROFILE";
            case 4178:
                return "IG_APP_USER_FLOWS_APP_FOREGROUND_FLOW";
            case 4196:
                return "NAVIGATION_DIRECT_STORY_AUDIENCE_PICKER";
            case 4232:
                return "NAVIGATION_EFFECT_PAGE";
            case 4253:
                return "NAVIGATION_CLIPS_VIEWER_FEED_POST_STICKER";
            case 4266:
                return "NAVIGATION_USER_LIST_GROUP_MOST_SEEN_IN_FEED";
            case 4268:
                return "NAVIGATION_ANYTIME_MENTIONS_LIST";
            case 4275:
                return "NAVIGATION_MODAL_COMMENT_COMPOSER_FEED_TIMELINE";
            case 4278:
                return "NAVIGATION_CLIPS_DURATION_PICKER";
            case 4299:
                return "NAVIGATION_CLIPS_VIEWER_FEED_TIMELINE_OLDER";
            case 4301:
                return "NAVIGATION_CLIPS_VIEWER_SUNDIAL_VIEWER";
            case 4309:
                return "NAVIGATION_COMMENTS_V2_IGMAIN_FEED_VIEW_CONTROLLER";
            case 4328:
                return "NAVIGATION_CLIPS_DRAFTS_SEE_ALL";
            case 4366:
                return "NAVIGATION_EMPTY_REPORT_BOTTOM_SHEET_FRAGMENT";
            case 4373:
                return "NAVIGATION_REEL_FEED_POST_SHARE_FRAGMENT";
            case 4395:
                return "NAVIGATION_CLIPS_VIEWER_CLIPS_VIEWER_CLIPS_NETEGO";
            case 4418:
                return "NAVIGATION_STORY_EMOJI_PICKER";
            case 4431:
                return "NAVIGATION_ACCOUNT_DISCOVERY";
            case 4471:
                return "NAVIGATION_REEL_MEMORIES_SHARE_FRAGMENT";
            case 4511:
                return "NAVIGATION_DIRECT_UNIFIED_EXPRESSION";
            case 4543:
                return "NAVIGATION_SERP_TAGS";
            case 4591:
                return "NAVIGATION_IG_SUNDIAL_POST_UPLOAD_METADATA_EDITOR";
            case 4678:
                return "NAVIGATION_FEED_CONTEXTUAL_MAP";
            case 4688:
                return "NAVIGATION_DRAFTS_BROWSER";
            case 4742:
                return "NAVIGATION_COM_BLOKS_WWW_IG_IXT_TRIGGERS_SCREEN_IG_ACCOUNT_STATUS";
            case 4760:
                return "NAVIGATION_SHARE_MEDIA_OPTIONS";
            case 4767:
                return "NAVIGATION_SESSION_ACTIVITY";
            case 4820:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_REEL_CLIPS_VIEWER";
            case 4836:
                return "NAVIGATION_DIRECT_THREAD_PRIVACY_SAFETY";
            case 4842:
                return "NAVIGATION_IG_CAMERA_MUSIC";
            case 4851:
                return "NAVIGATION_REEL_FEED_TIMELINE_CONTEXT_SHEET_CAPTION";
            case 4867:
                return "NAVIGATION_COM_INSTAGRAM_INSIGHTS_ACCOUNT_INTEGRATED_MEDIA_GRID_CONTAINER";
            case 4870:
                return "NAVIGATION_STORIES_PRECAPTURE_CAMERA";
            case 4872:
                return "NAVIGATION_CLIPS_VIEWER_REEL_DIRECT_THREAD";
            case 4875:
                return "NAVIGATION_COMMENTS_V2_FEED_TIMELINE_OLDER";
            case 4879:
                return "NAVIGATION_CLIPS_VIEWER_SELF_REEL_FEED_TIMELINE";
            case 4887:
                return "NAVIGATION_EDIT_MEDIA_INFO";
            case 4903:
                return "NAVIGATION_SERP";
            case 4910:
                return "NAVIGATION_FEED_CONTEXTUAL_KEYWORD";
            case 4913:
                return "NAVIGATION_REEL_COMPOSER_CAMERA";
            case 4920:
                return "NAVIGATION_CLIPS_VIEWER_REEL_COMMENT";
            case 4981:
                return "NAVIGATION_CLIPS_VIEWER_ACTIVITY_CENTER";
            case 5020:
                return "NAVIGATION_IG_ROOMS_INCALL_PEOPLE";
            case 5035:
                return "NAVIGATION_RECIPE_SHEET_PARENT";
            case 5064:
                return "NAVIGATION_RAGESHAKE_BOTTOM_SHEET";
            case 5080:
                return "NAVIGATION_CLIPS_VIEWER_CLIPS_REMIX_PAGE";
            case 5091:
                return "NAVIGATION_DIRECT_THREAD_PRESENTER";
            case 5099:
                return "NAVIGATION_CLIPS_VIEWER_FEED_CONTEXTUAL_SELF_PROFILE";
            case 5101:
                return "NAVIGATION_SELF_FOLLOWING";
            case 5106:
                return "NAVIGATION_ACTIVITY_CENTER";
            case 5121:
                return "NAVIGATION_CLIPS_VIEWER_VIDEO";
            case 5140:
                return "NAVIGATION_IN_APP_BROWSER_V2";
            case 5145:
                return "NAVIGATION_CLIPS_VIEWER_FEED_CONTEXTUAL_SAVED_COLLECTIONS_MIXED_UNCONNECTED";
            case 5148:
                return "NAVIGATION_SINGLE_FEED_NOTIFICATION";
            case 5168:
                return "NAVIGATION_ONBOARDING_CHECKLIST_FRAGMENT";
            case 5213:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_EXPLORE_POPULAR_MINOR_UNIT";
            case 5254:
                return "NAVIGATION_COM_INSTAGRAM_PORTABLE_SETTINGS_MESSAGES_SETTINGS";
            case 5284:
                return "NAVIGATION_CLIPS_MUSIC_EDITOR";
            case 5289:
                return "NAVIGATION_GALLERY_GRID_FORMATS_BOTTOM_SHEET";
            case 5315:
                return "NAVIGATION_SERP_NON_PROFILED";
            case 5343:
                return "NAVIGATION_ACTION_CHAINING_CONTAINER";
            case 5391:
                return "NAVIGATION_DATEPICKER";
            case 5397:
                return "NAVIGATION_MEDIA_VIEW_STORY_STICKER";
            case 5423:
                return "NAVIGATION_MUSIC_BROWSER";
            case 5434:
                return "NAVIGATION_IGDIRECT_CREATE_ROLL_CALL_VIEW_CONTROLLER";
            case 5467:
                return "NAVIGATION_CANVAS";
            case 5476:
                return "NAVIGATION_ASSET_LIBRARY";
            case 5486:
                return "NAVIGATION_DIRECT_NOTES_AUDIENCE_VIEW_CONTROLLER";
            case 5530:
                return "NAVIGATION_AUDIO_PAGE_CLIPS_TAB";
            case 5535:
                return "NAVIGATION_SEE_ALL_SUGGESTED_USER_FRAGMENT";
            case 5545:
                return "NAVIGATION_DIRECT_THREAD_DETAIL";
            case 5614:
                return "NAVIGATION_DIRECT_PENDING_INBOX";
            case 5624:
                return "NAVIGATION_REEL_HIGHLIGHTS_COVER_PIC";
            case 5639:
                return "NAVIGATION_STORY_CLIPS_DRAFTS_CAMERA";
            case 5666:
                return "NAVIGATION_CLIPS_VIEWER_COMMENTS_V2_CLIPS_VIEWER_REEL_FEED_TIMELINE";
            case 5680:
                return "NAVIGATION_CLIPS_POSTCAPTURE_CAMERA";
            case 5683:
                return "NAVIGATION_IGPRO_CATEGORY_SELECTION_SEARCH_VIEW_CONTROLLER";
            case 5690:
                return "NAVIGATION_CLIPS_VIEWER_COMMENTS_V2_CLIPS_VIEWER_DIRECT";
            case 5705:
                return "NAVIGATION_ADS_MANAGER";
            case 5718:
                return "NAVIGATION_FEED_TIMELINE_FAVORITES";
            case 5732:
                return "NAVIGATION_NOTE_QUICK_REPLY_SHEET";
            case 5776:
                return "NAVIGATION_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_INTERACTIONS_SCREEN";
            case 5794:
                return "NAVIGATION_CLIPS_VIEWER_REEL_CLIPS_NETEGO";
            case 5797:
                return "NAVIGATION_CLIPS_VIEWER_FEED_SAVED_COLLECTIONS_CLIPS";
            case 5804:
                return "NAVIGATION_SELL_PRODUCT_ROW";
            case 5806:
                return "NAVIGATION_CLIPS_VIEWER_THIRD_PARTY_URL";
            case 5811:
                return "NAVIGATION_PENDING_INBOX_FOLDER";
            case 5832:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_PUSH_NOTIF";
            case 5860:
                return "NAVIGATION_DIRECT_CONTENT_SEARCH";
            case 5865:
                return "NAVIGATION_BOTTOM_SHEET_PROFILE";
            case 5928:
                return "NAVIGATION_NOTES_CREATION_SHEET_V2";
            case 5941:
                return "NAVIGATION_IGTV_CREATION_GALLERY";
            case 5971:
                return "NAVIGATION_AYMH_PASSWORD_INPUT";
            case 6000:
                return "NAVIGATION_CLIPS_STICKER_TRAY";
            case 6021:
                return "NAVIGATION_ARCHIVE_STORIES";
            case 6034:
                return "NAVIGATION_COMMENT_LIKERS";
            case 6082:
                return "NAVIGATION_REEL_FEED_TIMELINE_CONTEXT_SHEET_PROMPT";
            case 6103:
                return "NAVIGATION_COM_INSTAGRAM_MWB_SI_CONTENT_FILTER_SETTINGS";
            case 6111:
                return "NAVIGATION_COM_INSTAGRAM_PRO_HOME_SURFACE";
            case 6132:
                return "NAVIGATION_CLIPS_VIEWER_PLAYGROUND_TEMPLATE_PAGE";
            case 6170:
                return "NAVIGATION_CLIPS_VIEWER_VISUAL_REPLY";
            case 6173:
                return "NAVIGATION_WEB_VIEW";
            case 6214:
                return "NAVIGATION_CLIPS_VIEWER_SAVED";
            case 6237:
                return "NAVIGATION_STORIES_VIEWER";
            case 6250:
                return "NAVIGATION_SELF_COMMENTS_V2_PUSH";
            case 6271:
                return "NAVIGATION_CLIPS_VIEWER_EFFECT_PAGE";
            case 6272:
                return "NAVIGATION_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_STORY_REPLIES_SCREEN";
            case 6309:
                return "NAVIGATION_SETTINGS_ACCESSIBILITY_OPTIONS";
            case 6332:
                return "NAVIGATION_RESTRICT_HALF_SHEET";
            case 6350:
                return "NAVIGATION_COMMENTS_V2_FEED_CONTEXTUAL_HASHTAG";
            case 6381:
                return "NAVIGATION_EDIT_PROFILE_NAME";
            case 6400:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_FEED_CONTEXTUAL_SAVED_COLLECTIONS";
            case 6407:
                return "NAVIGATION_COM_INSTAGRAM_PORTABLE_SETTINGS_HIDE_STORY_AND_LIVE_FROM";
            case 6415:
                return "NAVIGATION_COM_BLOKS_WWW_MINISHOP_COLLECTIONS";
            case 6441:
                return "NAVIGATION_CLIPS_REMIX_OPTIONS";
            case 6448:
                return "NAVIGATION_SUNDIAL_DRAFTS_COMPOSER";
            case 6449:
                return "NAVIGATION_CLIPS_VIEWER_FEED_HASHTAG";
            case 6454:
                return "NAVIGATION_PRIVATE_ACCOUNT_SETTING";
            case 6497:
                return "NAVIGATION_DIRECT_MESSAGE_ACTIONS_FRAGMENT";
            case 6500:
                return "NAVIGATION_COMPOSER_MUSIC_EDITOR_FRAGMENT";
            case 6528:
                return "NAVIGATION_DIRECT_MESSAGE_ACTIONS_BAR";
            case 6529:
                return "NAVIGATION_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_COMMENTS_SCREEN";
            case 6533:
                return "NAVIGATION_REGISTRATION_ACCOUNT_LINKING_WELCOME";
            case 6548:
                return "NAVIGATION_FEED_HASHTAG";
            case 6561:
                return "NAVIGATION_MEDIA_BROADCAST_SHARE";
            case 6592:
                return "NAVIGATION_CLIPS_VIEWER_CLIPS_VIEWER_CLIPS_PROFILE";
            case 6599:
                return "NAVIGATION_ARCHIVE_FEED";
            case 6632:
                return "NAVIGATION_COM_BLOKS_WWW_FBPAY_HUB_LANDING";
            case 6636:
                return "NAVIGATION_CLIPS_VIEWER_CLIPS_PROFILE";
            case 6638:
                return "NAVIGATION_CLIPS_TIMELINE_EDITOR";
            case 6644:
                return "NAVIGATION_CLIPS_PROFILE";
            case 6684:
                return "NAVIGATION_CLIPS_EDITOR";
            case 6698:
                return "NAVIGATION_AYMH";
            case 6706:
                return "IG_APP_USER_FLOWS_NAVIGATION";
            case 6709:
                return "NAVIGATION_CONTEXT_SHEET_CAPTION";
            case 6712:
                return "NAVIGATION_CALENDAR_ARCHIVE";
            case 6748:
                return "NAVIGATION_DIRECT_INTEROP_REACHABILITY_SETTINGS";
            case 6760:
                return "NAVIGATION_IG_CAMERA_MINI_GALLERY";
            case 6764:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_FEED_TIMELINE_MIXED_UNCONNECTED";
            case 6775:
                return "NAVIGATION_COM_INSTAGRAM_BULLYING_PRIVACY_LIMITS_ENTRYPOINT";
            case 6825:
                return "NAVIGATION_ANYTIME_MENTIONS_SEARCH";
            case 6852:
                return "NAVIGATION_STORY_GIFS";
            case 6892:
                return "NAVIGATION_MUSIC_OVERLAY_SEARCH_RESULTS";
            case 6903:
                return "NAVIGATION_DIRECT_AGGREGATED_MEDIA";
            case 6910:
                return "NAVIGATION_GENERIC_SURVEY";
            case 6915:
                return "NAVIGATION_SAVED";
            case 6930:
                return "NAVIGATION_CLIPS_VIEWER_REEL_FEED_TIMELINE";
            case 6931:
                return "NAVIGATION_DIRECT_FORWARDING_SHEET";
            case 6952:
                return "NAVIGATION_FACT_CHECK_INFO_SHEET";
            case 7019:
                return "NAVIGATION_DIRECT_THREAD_GALLERY";
            case 7028:
                return "NAVIGATION_STORIES_AVATAR_STICKER_PICKER_GRID";
            case 7046:
                return "NAVIGATION_PROFILE_CREATION_SHEET";
            case 7054:
                return "NAVIGATION_ACCOUNT_TRANSPARENCY_BLOKS";
            case 7091:
                return "NAVIGATION_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_ACCOUNT_HISTORY_SCREEN";
            case 7105:
                return "NAVIGATION_QUICK_REPLY_LIST";
            case 7114:
                return "NAVIGATION_THREAD_THEME_PICKER";
            case 7129:
                return "NAVIGATION_MUTUAL_FULL_LIST";
            case 7163:
                return "NAVIGATION_PROFILE_EDIT_USERNAME";
            case 7173:
                return "NAVIGATION_DIRECT_QUICK_CAMERA_FRAGMENT";
            case 7188:
                return "NAVIGATION_COMMENTS_V2_SINGLE_FEED_NOTIFICATION";
            case 7208:
                return "NAVIGATION_COMMENTS_V2_FEED_CONTEXTUAL_KEYWORD";
            case 7228:
                return "NAVIGATION_CLIPS_VIEWER_REEL_STORY_VIEWER_LIST";
            case 7238:
                return "NAVIGATION_AR_LINK_CANDIDATE_DETECTED";
            case 7244:
                return "NAVIGATION_COM_INSTAGRAM_TRANSPARENCY_PRODUCTS_CONTENT_CONTROLS_SCREEN";
            case 7275:
                return "NAVIGATION_CLIPS_VIEWER_SERP_TOP_MINOR_UNIT";
            case 7281:
                return "NAVIGATION_GROUP_PROFILE";
            case 7342:
                return "NAVIGATION_CLIPS_VIEWER_SELF_COMMENTS_V2_IGSUNDIAL_FEED_VIEW_CONTROLLER";
            case 7357:
                return "NAVIGATION_PROMOTE_BUDGET_AND_DURATION";
            case 7423:
                return "NAVIGATION_DIRECT_INBOX";
            case 7453:
                return "NAVIGATION_EXPLORE_ACCOUNTS_BY_CATEGORY";
            case 7490:
                return "NAVIGATION_DIRECT_VISUAL_REPLY_FRAGMENT";
            case 7504:
                return "NAVIGATION_COMMENTS_V2";
            case 7505:
                return "NAVIGATION_DIRECT_NEW_COLLECTION";
            case 7520:
                return "NAVIGATION_DIRECT";
            case 7535:
                return "NAVIGATION_USER_PASSWORD_RECOVERY";
            case 7562:
                return "NAVIGATION_CLIPS_VIEWER_REEL_LIKER_LIST";
            case 7569:
                return "NAVIGATION_TEMPLATE_GALLERY";
            case 7576:
                return "NAVIGATION_BUGREPORTER_COMPOSER";
            case 7612:
                return "NAVIGATION_CLIPS_VIEWER_FEED_TIMELINE_FOLLOWING";
            case 7642:
                return "NAVIGATION_DATA_SAVER_OPTIONS";
            case 7643:
                return "NAVIGATION_SETTINGS_CATEGORY_OPTIONS";
            case 7647:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_FEED_HASHTAG";
            case 7734:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_REEL_PROFILE";
            case 7738:
                return "NAVIGATION_DISCOVERY_MAP_TYPEAHEAD";
            case 7743:
                return "NAVIGATION_DIRECT_RICH_REACTIONS_LIST";
            case 7751:
                return "NAVIGATION_USER_LIST_GROUP_NON_RECIP_FOLLOWERS";
            case 7764:
                return "NAVIGATION_SERP_PLACES";
            case 7831:
                return "NAVIGATION_CLIPS_VIEWER_IGTV_SERIES";
            case 7861:
                return "NAVIGATION_SUNDIAL_COMPOSER";
            case 7906:
                return "NAVIGATION_CLIPS_VIEWER_SELF_CLIPS_PROFILE";
            case 7910:
                return "NAVIGATION_DELETE_REVAMP_BOTTOM_SHEET";
            case 7912:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_FEED_TIMELINE_EXPLORE_STORY";
            case 7922:
                return "NAVIGATION_MUSIC_SEARCH";
            case 7961:
                return "NAVIGATION_FEED_TIMELINE_FOLLOWING";
            case 8013:
                return "NAVIGATION_MUSIC_SETTINGS";
            case 8015:
                return "NAVIGATION_DIRECT_MESSAGES_OPTIONS";
            case 8046:
                return "NAVIGATION_DIRECT_THREAD";
            case 8065:
                return "NAVIGATION_DIRECT_CARD_GALLERY";
            case 8108:
                return "NAVIGATION_MEDIA_NOTIFICATIONS_SHEET";
            case 8166:
                return "NAVIGATION_ACTION_CHAINING";
            case 8180:
                return "NAVIGATION_CLIPS_VIEWER_PUSH_NOTIF";
            case 8186:
                return "NAVIGATION_BLOKS_UNKNOWN";
            case 8190:
                return "NAVIGATION_SELF_COMMENTS_V2_CLIPS_VIEWER_NEWSFEED_YOU";
            case 8206:
                return "NAVIGATION_FEED_SHORT_URL";
            case 8213:
                return "NAVIGATION_IGSUNDIAL_SHARE_SHEET_V2_VIEW_CONTROLLER";
            case 8228:
                return "NAVIGATION_COMMENTS_V2_FEED_TIMELINE";
            case 8234:
                return "NAVIGATION_IGPRO_VALUE_PROPOSITION_VIEW_CONTROLLER";
            case 8242:
                return "NAVIGATION_CLIPS_VIEWER_EXPLORE_POPULAR_MINOR_UNIT";
            case 8259:
                return "NAVIGATION_SAVE_TO_COLLECTIONS_TRAY";
            case 8276:
                return "NAVIGATION_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_ACTIVITY_CENTER_RECENTLY_DELETED_SCREEN";
            case 8309:
                return "NAVIGATION_CLIPS_VIEWER_COMMENTS_V2_NEWSFEED_YOU";
            case 8316:
                return "NAVIGATION_RTC_CALL_LAUNCHER";
            case 8394:
                return "NAVIGATION_AR_LINK_SCAN_CAMERA";
            case 8403:
                return "NAVIGATION_COUNTDOWN_STICKER_LIST";
            case 8470:
                return "NAVIGATION_FOLLOWING";
            case 8502:
                return "NAVIGATION_MESSAGE_SEARCH_SCRIM_SCREEN_FRAGMENT";
            case 8507:
                return "NAVIGATION_MULTIBLOCK_VIEW_CONTROLLER";
            case 8508:
                return "NAVIGATION_NEW_COLLECTION_VIEW_CONTROLLER";
            case 8522:
                return "NAVIGATION_COMMENTS_V2_FEED_CONTEXTUAL_SELF_PROFILE";
            case 8546:
                return "NAVIGATION_RTC_CALL";
            case 8598:
                return "NAVIGATION_SIDE_TRAY_PROFILE";
            case 8621:
                return "NAVIGATION_AUDIENCE_SELECTION";
            case 8629:
                return "NAVIGATION_COLLECTION_CANVAS_DESTINATION_VIEW";
            case 8645:
                return "NAVIGATION_SELF_COMMENTS_V2";
            case 8725:
                return "NAVIGATION_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_ACTIVITY_CENTER_ENTRY_BUSINESS_SCREEN";
            case 8739:
                return "NAVIGATION_ONBOARDING_CHECKLIST";
            case 8790:
                return "NAVIGATION_CUSTOM_ALERT";
            case 8818:
                return "NAVIGATION_CLIPS_VIEWER_REEL_SINGLE_POST";
            case 8819:
                return "NAVIGATION_FEED_CONTEXTUAL";
            case 8830:
                return "NAVIGATION_DISCOVERY_MAP";
            case 8860:
                return "NAVIGATION_RETRO_REGISTRATION_LOGIN";
            case 8878:
                return "NAVIGATION_MEDIA_CAPTURE";
            case 8895:
                return "NAVIGATION_ADD_ACCOUNT_BOTTOM_SHEET";
            case 8900:
                return "NAVIGATION_REEL_MORE_OPTIONS";
            case 8910:
                return "NAVIGATION_INLINE_ADD_TO_HIGHLIGHT";
            case 8912:
                return "NAVIGATION_DIRECT_THREAD_INFO";
            case 8919:
                return "NAVIGATION_FEED_CONTEXTUAL_SAVED_COLLECTIONS";
            case 8921:
                return "NAVIGATION_SEARCH_TYPEAHEAD";
            case 8950:
                return "NAVIGATION_PRIVACY_SWITCH_BOTTOM_SHEET";
            case 8951:
                return "NAVIGATION_TAKE_A_BREAK";
            case 8965:
                return "NAVIGATION_TAGS_LIST_REEL_FEED_TIMELINE";
            case 8992:
                return "NAVIGATION_STORIES_QUESTION_STICKER_MUSIC_RESPONSE_BROWSER";
            case 9012:
                return "NAVIGATION_SINGLE_FEED";
            case 9020:
                return "NAVIGATION_CLIPS_VIEWER_FEED_TIMELINE";
            case 9028:
                return "NAVIGATION_CLIPS_VIEWER_DIRECT";
            case 9031:
                return "NAVIGATION_BLOCK_LIST_TAB_VIEW";
            case 9033:
                return "NAVIGATION_BROADCAST_ACTIVITY";
            case 9038:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_FEED_TIMELINE";
            case 9043:
                return "NAVIGATION_REEL_COMPOSER_PREVIEW";
            case 9053:
                return "NAVIGATION_CLIPS_VIEWER_SINGLE_FEED";
            case 9101:
                return "NAVIGATION_CROSSPOSTING_UNIFIED_ONBOARDING_FRAGMENT";
            case 9186:
                return "NAVIGATION_CLIPS_VIEWER_FEED_TIMELINE_OLDER_MIXED_UNCONNECTED";
            case 9187:
                return "NAVIGATION_CAA_LOGIN_ONE_TAP_LOG_OUT_FRAGMENT";
            case 9196:
                return "NAVIGATION_COM_INSTAGRAM_INSIGHTS_MEDIA_REFRESH_CLIPS_PROMOTIONS_SURFACE";
            case 9229:
                return "NAVIGATION_CLIPS_VIEWER_CLIPS_VIEWER_FEED_TIMELINE";
            case 9248:
                return "NAVIGATION_CLIPS_AUDITION";
            case 9298:
                return "NAVIGATION_IGSUNDIAL_REMIX_NUX_INFORMATION_SHEET_VIEW_CONTROLLER";
            case 9341:
                return "NAVIGATION_DIRECT_GIF";
            case 9356:
                return "NAVIGATION_NOTIFICATIONS";
            case 9357:
                return "NAVIGATION_DPA_SHOWCASE_PAGE";
            case 9366:
                return "NAVIGATION_PEOPLE_TAGGING";
            case 9394:
                return "NAVIGATION_IGQPPEEK_PROMO_DISCLAIMER_VIEW_CONTROLLER";
            case 9409:
                return "NAVIGATION_SELF_COMMENTS_V2_CLIPS_VIEWER_SELF_CLIPS_PROFILE";
            case 9442:
                return "NAVIGATION_PRIVACY_OPTIONS";
            case 9455:
                return "NAVIGATION_AVATAR_STICKERS_UPSELL";
            case 9465:
                return "NAVIGATION_COM_INSTAGRAM_INSIGHTS_MEDIA_REFRESH_POSTS_PROMOTIONS_SURFACE";
            case 9513:
                return "NAVIGATION_CLIPS_VIEWER_SERP_TOP_MIXED_CONTENT_MINOR_UNIT";
            case 9533:
                return "NAVIGATION_STORY_VIEWER_MUSIC_SHEET";
            case 9543:
                return "NAVIGATION_CLIPS_VIEWER_SINGLE_FEED_PROFILE";
            case 9561:
                return "NAVIGATION_EDIT_PROFILE_BIO_LINKS_CUSTOM_LINK";
            case 9588:
                return "NAVIGATION_DIRECT_AGGREGATED_MEDIA_VIEWER";
            case 9609:
                return "NAVIGATION_DISCOVERY_MAP_LOCATION_DETAIL";
            case 9621:
                return "NAVIGATION_CLIPS_AUDIO_MIX_EDITOR";
            case 9622:
                return "NAVIGATION_FEED_POST_STICKER";
            case 9630:
                return "NAVIGATION_CLIPS_VIEWER";
            case 9659:
                return "NAVIGATION_CLIPS_VIEWER_EXTERNAL_URL";
            case 9663:
                return "NAVIGATION_CLIPS_VIEWER_FEED_CONTEXTUAL_PROFILE_MIXED_UNCONNECTED";
            case 9695:
                return "NAVIGATION_DIRECT_THREAD_COLOR_PICKER_FRAGMENT";
            case 9723:
                return "NAVIGATION_AR_LINK_VIEW_CONTROLLER";
            case 9732:
                return "NAVIGATION_CLIPS_VIEWER_POST_LIVE";
            case 9791:
                return "NAVIGATION_IG_CAMERA_MINI_GALLERY_SEARCH_PAGE";
            case 9841:
                return "NAVIGATION_LIVE_BROADCAST";
            case 9851:
                return "NAVIGATION_FEED_CONTEXTUAL_CHAIN";
            case 9878:
                return "NAVIGATION_GUIDES_PROFILE_TAB";
            case 9926:
                return "NAVIGATION_SINGLE_FEED_ARCHIVE_FEED";
            case 9928:
                return "NAVIGATION_REEL_CLPS_RESHARE_FRAGMENT";
            case 10003:
                return "NAVIGATION_CLIPS_VIEWER_GUIDE_DETAIL_PROFILE";
            case 10005:
                return "NAVIGATION_VIEWER_POST_LIVE";
            case 10006:
                return "NAVIGATION_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_FEED_MEDIA_SCREEN";
            case 10008:
                return "NAVIGATION_MUSIC_STICKER_BROWSER_SAVED";
            case 10110:
                return "NAVIGATION_SELF_PROFILE";
            case 10119:
                return "NAVIGATION_ATTRIBUTION_QUICK_CAMERA_FRAGMENT";
            case 10139:
                return "NAVIGATION_PHOTO_FILTER";
            case 10140:
                return "NAVIGATION_CAPTIONS_SETTINGS";
            case 10170:
                return "NAVIGATION_LOGIN_LANDING";
            case 10186:
                return "NAVIGATION_STORY_INTERACTIVE_VOTERS";
            case 10202:
                return "NAVIGATION_COMMENTS_V2_FEED_POST_STICKER";
            case 10209:
                return "NAVIGATION_COM_INSTAGRAM_INSIGHTS_ACCOUNT_REACH_BREAKOUT_TIMEFRAME_CONTAINER";
            case 10222:
                return "NAVIGATION_PEEK_MEDIA";
            case 10250:
                return "NAVIGATION_COM_INSTAGRAM_PORTABLE_SETTINGS_PROFESSIONAL_SETTINGS";
            case 10265:
                return "NAVIGATION_MUSIC_IN_FEED";
            case 10299:
                return "NAVIGATION_CAROUSEL_GALLERY";
            case 10370:
                return "NAVIGATION_FEED_PRECAPTURE_CAMERA";
            case 10373:
                return "NAVIGATION_DIRECT_NOTES_COMPOSER";
            case 10379:
                return "NAVIGATION_BROWSER_HISTORY";
            case 10423:
                return "NAVIGATION_SUNDIAL_STACKED_TIMELINE_VC";
            case 10435:
                return "NAVIGATION_CLIPS_SHARE_SHEET_ADD_TOPICS_PAGE";
            case 10438:
                return "NAVIGATION_DIRECT_SAVE_TO_COLLECTION";
            case 10489:
                return "NAVIGATION_EDIT_RECENT";
            case 10501:
                return "NAVIGATION_FEED_TIMELINE_OLDER";
            case 10511:
                return "NAVIGATION_SELF_COMMENTS_V2_CLIPS_VIEWER_PUSH_NOTIF";
            case 10518:
                return "NAVIGATION_SUBSCRIBED_CREATOR_LIST_FRAGMENT";
            case 10522:
                return "NAVIGATION_STORY_POLL_TAB_ALL_VOTERS";
            case 10559:
                return "NAVIGATION_MEDIA_MUTE_SHEET";
            case 10560:
                return "NAVIGATION_STORY_SETTINGS_LIST";
            case 10585:
                return "NAVIGATION_LIVE_BROADCAST_ENDING";
            case 10597:
                return "NAVIGATION_COMMENTS_V2_IGSUNDIAL_FEED_VIEW_CONTROLLER";
            case 10604:
                return "NAVIGATION_COM_BLOKS_WWW_BLOKS_CPDP_LIGHTBOX";
            case 10624:
                return "NAVIGATION_GALLERY_COVER_PHOTO_PICKER_FRAGMENT";
            case 10742:
                return "NAVIGATION_PRO_VALUE_PROPOSITION_PAGE";
            case 10760:
                return "NAVIGATION_COM_INSTAGRAM_PORTABLE_SETTINGS_HELP";
            case 10762:
                return "NAVIGATION_PASSWORD_LOOKUP";
            case 10797:
                return "NAVIGATION_IGFXCALFULL_SCREEN_LOADING_VIEW_CONTROLLER";
            case 10900:
                return "NAVIGATION_SELF_COMMENTS_V2_SINGLE_FEED_ARCHIVE_FEED";
            case 10933:
                return "NAVIGATION_CLIPS_VIEWER_FEED_CONTEXTUAL_CHAIN";
            case 10948:
                return "NAVIGATION_CLIPS_VIEWER_FEED_TIMELINE_MIXED_UNCONNECTED";
            case 10950:
                return "NAVIGATION_MUSIC_ON_PROFILE";
            case 10957:
                return "NAVIGATION_PROFILE_PICTURE_PREVIEW";
            case 10978:
                return "NAVIGATION_MUSIC_NOTES_EDITOR_SHEET";
            case 10994:
                return "NAVIGATION_DISCOVERY_MAP_LOCATION_LIST";
            case 11031:
                return "NAVIGATION_SAC_CREATE_USERNAME";
            case 11063:
                return "NAVIGATION_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_LIKED_MEDIA_SCREEN";
            case 11092:
                return "NAVIGATION_CLIPS_VIEWER_AUDIO_PAGE_CLIPS_TAB";
            case 11106:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_CLIPS_TAB";
            case 11127:
                return "NAVIGATION_CLIPS_VIEWER_PRO_INSPIRATION_HUB_CLIPS_NETEGO";
            case 11137:
                return "NAVIGATION_SINGLE_FEED_PROFILE";
            case 11144:
                return "NAVIGATION_DIRECT_REPLY_TO_AUTHOR";
            case 11191:
                return "NAVIGATION_CLIPS_SHARE_SHEET";
            case 11253:
                return "NAVIGATION_AR_EFFECT";
            case 11269:
                return "NAVIGATION_REPORTING_CONFIRMATION_V2_BOTTOM_SHEET_FRAGMENT";
            case 11274:
                return "NAVIGATION_SAVE_TO_COLLECTIONS_VIEW_CONTROLLER";
            case 11300:
                return "NAVIGATION_LIVE_TITLE_COMPOSER";
            case 11301:
                return "NAVIGATION_FEED_TIMELINE";
            case 11327:
                return "NAVIGATION_CLIPS_VIEWER_FEED_TIMELINE_EXPLORE_STORY";
            case 11394:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_ACTIVITY_CENTER";
            case 11428:
                return "NAVIGATION_SETTINGS_BUSINESS_OPTIONS";
            case 11450:
                return "NAVIGATION_VIDEO_VIEW_COUNT_USER_LIST";
            case 11499:
                return "NAVIGATION_DIRECT_MESSAGE_ACTIONS_VIEW_CONTROLLER";
            case 11511:
                return "NAVIGATION_USAGE_INSIGHTS_BLOCKING";
            case 11546:
                return "NAVIGATION_RESTRICT_CONFIRMATION_MODAL_SHEET";
            case 11598:
                return "NAVIGATION_ZOOM";
            case 11631:
                return "NAVIGATION_STORIES_GALLERY";
            case 11656:
                return "NAVIGATION_CLIPS_VIEWER_SERP_REELS_SUBTAB";
            case 11700:
                return "NAVIGATION_CLIPS_GALLERY";
            case 11711:
                return "NAVIGATION_SELF_UNIFIED_FOLLOW_LISTS";
            case 11716:
                return "NAVIGATION_STORY_MORE_OPTIONS";
            case 11767:
                return "NAVIGATION_SERP_REELS_SUBTAB";
            case 11777:
                return "NAVIGATION_REEL_MENTION_RESHARE_CAMERA_FRAGMENT";
            case 11783:
                return "NAVIGATION_FEED_LOCATION";
            case 11805:
                return "NAVIGATION_SERP_USERS";
            case 11830:
                return "NAVIGATION_IG_IAB_AUTOFILL_BOTTOM_SHEET_APPLY";
            case 11879:
                return "NAVIGATION_CLIPS_VIEWER_COMMENTS_V2_CLIPS_VIEWER_FEED_CONTEXTUAL_CHAIN";
            case 11885:
                return "NAVIGATION_LIKERS";
            case 11889:
                return "NAVIGATION_PEEK_CLIPS";
            case 11897:
                return "NAVIGATION_QUICK_CAPTURE_ADD_TO_STORY_DUAL_DESTINATION_FRAGMENT";
            case 11925:
                return "NAVIGATION_SELF_COMMENTS_V2_SINGLE_FEED_NOTIFICATION";
            case 11926:
                return "NAVIGATION_CLIPS_VIEWER_FEED_CONTEXTUAL_PROFILE";
            case 11928:
                return "NAVIGATION_MUTUAL";
            case 11929:
                return "NAVIGATION_SELF_COMMENTS_V2_FEED_CONTEXTUAL_SELF_PROFILE";
            case 11934:
                return "NAVIGATION_REEL_DASHBOARD_ACTIONS_FRAGMENT";
            case 11941:
                return "NAVIGATION_COM_INSTAGRAM_INTERACTIONS_ABOUT_THIS_ACCOUNT";
            case 11971:
                return "NAVIGATION_CLIPS_VIEWER_CLIPS_HASHTAG";
            case 12003:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_SERP_TOP_MINOR_UNIT";
            case 12004:
                return "NAVIGATION_UNIVERSAL_CREATION_MENU";
            case 12030:
                return "NAVIGATION_BROWSER_VIEW_CONTROLLER";
            case 12051:
                return "NAVIGATION_APPRECIATION_GIFTING_BOTTOM_SHEET";
            case 12053:
                return "NAVIGATION_INSTAGRAM_SHOPPING_PDP";
            case 12057:
                return "NAVIGATION_DIRECT_INTEROP_REACHABILITY_SETTINGS_OPTIONS";
            case 12062:
                return "NAVIGATION_FEED_CONTEXTUAL_TAG_CONTROL";
            case 12123:
                return "NAVIGATION_LIVE_BROADCAST_POOR_FEEDBACK";
            case 12126:
                return "NAVIGATION_DIRECT_PRIVATE_REPLY_MESSENGER";
            case 12129:
                return "NAVIGATION_SHARE_REELS_ADVANCED_SETTINGS";
            case 12167:
                return "NAVIGATION_UPCOMING_EVENT_BOTTOM_SHEET";
            case 12216:
                return "NAVIGATION_DIRECT_INDIVIDUAL_STACK_CARD_GALLERY_FRAGMENT";
            case 12232:
                return "NAVIGATION_REPORTING_TAGS";
            case 12247:
                return "NAVIGATION_RESTRICT_LIST";
            case 12280:
                return "NAVIGATION_ADVANCED_POST_SETTINGS";
            case 12403:
                return "NAVIGATION_ADS_ACTION_REASONS";
            case 12431:
                return "NAVIGATION_PROMPT_STICKER_EDIT";
            case 12454:
                return "NAVIGATION_CLIPS_PEOPLE_TAGGING";
            case 12471:
                return "NAVIGATION_CLIPS_VIEWER_CLIPS_SOCIAL";
            case 12475:
                return "NAVIGATION_PROMOTE_DESTINATION";
            case 12485:
                return "NAVIGATION_DIRECT_THREAD_ADD_MEMBER";
            case 12487:
                return "NAVIGATION_RAGE_SHAKE_CONFIRMATION";
            case 12488:
                return "NAVIGATION_VIDEO_EDIT";
            case 12495:
                return "NAVIGATION_PHOTO_VIEW";
            case 12530:
                return "NAVIGATION_USER_LIST_GROUP_LEAST_INTERACTED_WITH_FOLLOWERS";
            case 12582:
                return "NAVIGATION_DIRECT_REACTIONS_PICKER_FRAGMENT";
            case 12583:
                return "NAVIGATION_COM_INSTAGRAM_INSIGHTS_MEDIA_REFRESH_COMMON_CAROUSEL_PROFILE_SURFACE";
            case 12599:
                return "NAVIGATION_FOLLOWING_SHEET";
            case 12600:
                return "NAVIGATION_EDIT_PROFILE_USERNAME";
            case 12629:
                return "NAVIGATION_IG_IAB_AUTOFILL_BOTTOM_SHEET_OPT_IN";
            case 12656:
                return "NAVIGATION_ADS_ACTIONS_THANK_YOU";
            case 12681:
                return "NAVIGATION_UNIFIED_FOLLOW_LISTS";
            case 12737:
                return "NAVIGATION_SAVED_AUDIO_LIST";
            case 12757:
                return "NAVIGATION_CLIPS_VIEWER_SELF_REEL_PROFILE";
            case 12772:
                return "NAVIGATION_DIRECT_STORY_VIEWER_FRAGMENT";
            case 12781:
                return "NAVIGATION_CLIPS_VIEWER_COMMENTS_V2_CLIPS_VIEWER_FEED_TIMELINE";
            case 12785:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_REEL_FEED_TIMELINE";
            case 12840:
                return "NAVIGATION_NOTES_AUDIENCE_PICKER_SHEET";
            case 12860:
                return "NAVIGATION_CLIPS_VIEWER_SINGLE_FEED_ARCHIVE_FEED";
            case 12905:
                return "NAVIGATION_LIVE_VIDEO_NOTIFICATIONS_SHEET";
            case 12915:
                return "NAVIGATION_COM_INSTAGRAM_INSIGHTS_MEDIA_REFRESH_CLIPS_CORE";
            case 12966:
                return "NAVIGATION_SERP_AUDIO";
            case 13026:
                return "NAVIGATION_PROFILE_EDIT_BIO";
            case 13049:
                return "NAVIGATION_FEATURED_USER";
            case 13111:
                return "NAVIGATION_LOCATION_PICKER";
            case 13117:
                return "NAVIGATION_BLOCK_VIEW_CONTROLLER";
            case 13119:
                return "NAVIGATION_CONTEXTUAL_NUDGES_GENERIC_VC";
            case 13169:
                return "NAVIGATION_IG_VIDEO_SHARING_SETTINGS";
            case 13173:
                return "NAVIGATION_STORIES_ARCHIVE_HOME";
            case 13191:
                return "NAVIGATION_COMMENTS_V2_PUSH";
            case 13202:
                return "NAVIGATION_CLIPS_VIEWER_REEL_FOLLOW_LIST";
            case 13217:
                return "NAVIGATION_CLIPS_VIEWER_REEL_ARCHIVE";
            case 13235:
                return "NAVIGATION_IG_IXT_ACTIVITING_INDICATING";
            case 13244:
                return "NAVIGATION_AUDIO_PAGE";
            case 13250:
                return "NAVIGATION_PROFILE_EDIT_FULL_NAME";
            case 13251:
                return "NAVIGATION_COM_INSTAGRAM_INSIGHTS_MEDIA_REFRESH_POSTS_CORE";
            case 13300:
                return "NAVIGATION_INSTANT_SHOPPING";
            case 13311:
                return "NAVIGATION_DIRECT_STORY_INBOX";
            case 13356:
                return "NAVIGATION_REPLAY_LIVE_VIEWER";
            case 13360:
                return "NAVIGATION_VIDEO_CALL_STATUS_BAR";
            case 13391:
                return "NAVIGATION_SWITCH_PRIVACY";
            case 13404:
                return "NAVIGATION_SERP_TOP";
            case 13423:
                return "NAVIGATION_CLIPS_VIEWER_CLIPS_VIEWER_CLIPS_TAB";
            case 13451:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_CLIPS_PROFILE";
            case 13500:
                return "NAVIGATION_GALLERY_PICKER";
            case 13534:
                return "NAVIGATION_STORY_BLOKS_ACTION_WRAPPER";
            case 13585:
                return "NAVIGATION_DIRECT_SUNDIAL_FEED";
            case 13595:
                return "NAVIGATION_CLIPS_VIEWER_COMMENTS_V2_CLIPS_VIEWER_REEL_CLIPS_NETEGO";
            case 13612:
                return "NAVIGATION_SELF_CLIPS_PROFILE";
            case 13614:
                return "NAVIGATION_COM_INSTAGRAM_SETTINGS_ABOUT";
            case 13629:
                return "NAVIGATION_CLIPS_VIEWER_STORY_STICKER";
            case 13642:
                return "NAVIGATION_CLIPS_VIEWER_REEL_PROFILE";
            case 13671:
                return "NAVIGATION_FOLLOW_UP_BOTTOM_SHEET";
            case 13689:
                return "NAVIGATION_RESTRICT_LIST_VIEW";
            case 13705:
                return "NAVIGATION_CLIPS_SHARE_SHEET_PROFILE_CROP";
            case 13707:
                return "NAVIGATION_CLIPS_VIEWER_REEL_FEED_CONTEXTUAL_POST_ITEM_HEADER";
            case 13752:
                return "NAVIGATION_RESTRICT_LIST_TAB_VIEW";
            case 13828:
                return "NAVIGATION_EDIT_LINKS_LIST_FRAGMENT";
            case 13840:
                return "NAVIGATION_FACEBOOK_SERVICE_HELPER";
            case 13851:
                return "NAVIGATION_LOCATION_MAP_ARCHIVE";
            case 13884:
                return "NAVIGATION_PROFILE_CHAINING_VIEW";
            case 13886:
                return "NAVIGATION_DIRECT_REACTION_SELECTION";
            case 13897:
                return "NAVIGATION_NOTES_CREATION_SHEET";
            case 13929:
                return "NAVIGATION_ARCHIVE_STORIES_TAB";
            case 13932:
                return "NAVIGATION_COM_INSTAGRAM_GROWTH_SCREENS_MUTED_USERS";
            case 13942:
                return "NAVIGATION_ACCOUNT_PRIVACY_OPTION";
            case 13985:
                return "NAVIGATION_LIVE_ARCHIVE";
            case 14004:
                return "NAVIGATION_COM_INSTAGRAM_MENTAL_WELL_BEING_TIME_SPENT_SCREEN_SHELL_COMPONENT";
            case 14014:
                return "NAVIGATION_COLLABORATOR_SEARCH";
            case 14018:
                return "NAVIGATION_COM_INSTAGRAM_PORTABLE_SETTINGS_ARCHIVING_AND_DOWNLOADING";
            case 14030:
                return "NAVIGATION_CLIPS_VIEWER_FEED_CONTEXTUAL_HASHTAG";
            case 14032:
                return "NAVIGATION_IGPRO_CATEGORY_SELECTION_LIST_VIEW_CONTROLLER";
            case 14063:
                return "NAVIGATION_SELF_COMMENTS_V2_FEED_TIMELINE";
            case 14090:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_CLIPS_SUGGESTED_FEED_CONTEXTUAL_CHAIN";
            case 14102:
                return "NAVIGATION_PENDING_INBOX";
            case 14253:
                return "NAVIGATION_DIRECT_PRECAPTURE_CAMERA";
            case 14255:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_FEED_CONTEXTUAL_CHAIN";
            case 14276:
                return "NAVIGATION_BLOCKED_LIST";
            case 14314:
                return "NAVIGATION_VIEWER_LIST_SEARCH";
            case 14319:
                return "NAVIGATION_CLIPS_VIEWER_SINGLE_FEED_NOTIFICATION";
            case 14370:
                return "NAVIGATION_BLOCK_LIST_VIEW";
            case 14400:
                return "NAVIGATION_CLIPS_VIEWER_REEL_SEARCH_ITEM_HEADER";
            case 14434:
                return "NAVIGATION_COMMENT_TOOLS_UPSELL_VIEW";
            case 14438:
                return "NAVIGATION_REEL_VIEWER_SETTINGS";
            case 14443:
                return "NAVIGATION_SELF_COMMENTS_V2_IGMAIN_FEED_VIEW_CONTROLLER";
            case 14461:
                return "NAVIGATION_EXPLORE_POPULAR";
            case 14473:
                return "NAVIGATION_FAN_CLUB_SUBSCRIPTIONS";
            case 14551:
                return "NAVIGATION_STORIES_AD4AD";
            case 14568:
                return "NAVIGATION_DIRECT_MULTIEDIT_COMPOSER";
            case 14586:
                return "NAVIGATION_LIVE_COBROADCAST";
            case 14591:
                return "NAVIGATION_DIRECT_THREAD_DETAILS_NOTIFICATION";
            case 14594:
                return "NAVIGATION_FEED_CONTEXTUAL_PROFILE";
            case 14688:
                return "NAVIGATION_PAGE_VIEW";
            case 14703:
                return "NAVIGATION_DIRECT_THREAD_GALLERY_PREVIEW";
            case 14742:
                return "NAVIGATION_REEL_MULTIEDIT_COMPOSER";
            case 14765:
                return "NAVIGATION_LIKERS_CHRONO";
            case 14768:
                return "NAVIGATION_FEED_SAVED_COLLECTIONS";
            case 14783:
                return "NAVIGATION_USER_LIST_GROUP_LEAST_INTERACTED_WITH";
            case 14815:
                return "NAVIGATION_PBIA_PROXY_PROFILE";
            case 14841:
                return "NAVIGATION_ANYTIME_MENTIONS";
            case 14852:
                return "NAVIGATION_COM_BLOKS_WWW_BLOKS_SCREEN_IXT_SCREEN_SUPPORT_INBOX_ITEMS_LIST";
            case 14853:
                return "NAVIGATION_DIRECT_THREAD_SHARED_MEDIA";
            case 14860:
                return "NAVIGATION_LEAD_AD_QUESTION_PAGE";
            case 14867:
                return "NAVIGATION_REEL_HIGHLIGHTS_GALLERY";
            case 14904:
                return "NAVIGATION_DIRECT_BROADCAST_CHATS_ACTIVITY_FEED";
            case 14924:
                return "NAVIGATION_IGPRO_CATEGORY_SELECTION_OPTIMIZED_VIEW_CONTROLLER";
            case 14931:
                return "NAVIGATION_CLIPS_VIEWER_FEED_TIMELINE_FAVORITES";
            case 14957:
                return "NAVIGATION_NAMETAG";
            case 14976:
                return "NAVIGATION_COM_INSTAGRAM_PORTABLE_SETTINGS_HIDE_TAGS_AND_MENTIONS_SETTINGS";
            case 15001:
                return "NAVIGATION_CONTENT_SEARCH_RESULT_LIST";
            case 15014:
                return "NAVIGATION_STORIES_POSTCAPTURE_CAMERA";
            case 15026:
                return "NAVIGATION_IGSUNDIAL_AUDIO_CONTROL_VIEW_CONTROLLER";
            case 15061:
                return "NAVIGATION_BUG_REPORTING";
            case 15103:
                return "NAVIGATION_SETTINGS_ACCOUNT_OPTIONS";
            case 15120:
                return "NAVIGATION_UNKNOWN";
            case 15128:
                return "NAVIGATION_FEED_SAVED_COLLECTIONS_CLIPS";
            case 15162:
                return "NAVIGATION_PROMOTE_AUDIENCE_LOCATION";
            case 15165:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_AUDIO_PAGE";
            case 15184:
                return "NAVIGATION_METADATA_THUMBNAIL_PREVIEW";
            case 15202:
                return "NAVIGATION_STORY_DRAFTS_BROWSER";
            case 15262:
                return "NAVIGATION_IG_RTC_AR_BLOKS_ACTION_WRAPPER";
            case 15277:
                return "NAVIGATION_ROLL_CALL_SHEET";
            case 15281:
                return "NAVIGATION_EDIT_PROFILE";
            case 15348:
                return "NAVIGATION_COM_INSTAGRAM_PORTABLE_SETTINGS_PRIVACY_ACTIVITY_STATUS";
            case 15372:
                return "NAVIGATION_MIXED_ATTRIBUTION_BOTTOM_SHEET";
            case 15395:
                return "NAVIGATION_ADD_ACCOUNT_HALF_SHEET";
            case 15413:
                return "NAVIGATION_LIVE_QUESTION_SHEET";
            case 15419:
                return "NAVIGATION_DIRECT_THREAD_INVITE_LINK_PREVIEW";
            case 15427:
                return "NAVIGATION_REEL_PROFILE_AR_EFFECT";
            case 15453:
                return "NAVIGATION_ANYTIME_MENTION_SEARCH_SHEET";
            case 15468:
                return "NAVIGATION_GALLERY_FOLDER_PICKER_BOTTOMSHEET_FRAGMENT";
            case 15487:
                return "NAVIGATION_COMMENT_COMPOSING";
            case 15525:
                return "NAVIGATION_DIRECT_THREAD_SHARED_POSTS";
            case 15574:
                return "NAVIGATION_LINKS_SHEET";
            case 15584:
                return "NAVIGATION_COM_INSTAGRAM_INTERACTIONS_FORMER_USERNAMES";
            case 15588:
                return "NAVIGATION_CLIPS_VIEWER_REEL_FEED_TIMELINE_ITEM_HEADER";
            case 15645:
                return "NAVIGATION_CLIPS_VIEWER_COMMENTS_V2_CLIPS_VIEWER_CLIPS_TAB";
            case 15675:
                return "NAVIGATION_BROADCAST_CHAT_THREAD";
            case 15683:
                return "NAVIGATION_REEL_FEED_TIMELINE_CONTEXT_SHEET_AVATAR_STICKER_UPSELL";
            case 15708:
                return "NAVIGATION_EDIT_PROFILE_PICTURE_BOTTOM_SHEET";
            case 15709:
                return "NAVIGATION_CLIPS_VIEWER_COMMENTS_V2_CLIPS_VIEWER_EXPLORE_POPULAR_MINOR_UNIT";
            case 15732:
                return "NAVIGATION_ARCHIVE_HOME";
            case 15747:
                return "NAVIGATION_STORY_SHARE_SHEET_LOADING";
            case 15775:
                return "NAVIGATION_CHOOSE_CATEGORY_WITH_SEARCH";
            case 15787:
                return "NAVIGATION_CREATE_REEL_HIGHLIGHTS";
            case 15789:
                return "NAVIGATION_CLIPS_VIEWER_COMMENTS_V2_IGSUNDIAL_FEED_VIEW_CONTROLLER";
            case 15807:
                return "NAVIGATION_TAGS_LIST";
            case 15809:
                return "NAVIGATION_DISCOVERY_MAP_LOCATION_DETAIL_GRID";
            case 15811:
                return "NAVIGATION_AUDIO_PAGE_QP_CONTAINER";
            case 15819:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_DIRECT";
            case 15845:
                return "NAVIGATION_REPORTING_CONTAINER";
            case 15861:
                return "NAVIGATION_SWITCH_TO_BUSINESS_ACCOUNT";
            case 15900:
                return "NAVIGATION_COMMENTS_V2_CLIPS_VIEWER_CLIPS_NETEGO";
            case 15901:
                return "NAVIGATION_CLIPS_VIEWER_DIRECT_INBOX_SEARCH_RESHARED_CONTENT";
            case 15919:
                return "NAVIGATION_CLIPS_VIEWER_CLIPS_VIEWER_FEED_CONTEXTUAL_CHAIN";
            case 15938:
                return "NAVIGATION_STORIES_TRANSLATION_SHEET";
            case 15951:
                return "NAVIGATION_LIVE_VIEWER";
            case 15978:
                return "NAVIGATION_DIRECT_RECIPIENT_LIST";
            case 15993:
                return "NAVIGATION_COMMENTS_V2_FEED_CONTEXTUAL_SAVED_COLLECTIONS";
            case 15997:
                return "NAVIGATION_VIDEO_CALL";
            case 16006:
                return "NAVIGATION_SAC_WELCOME_PAGE";
            case 16060:
                return "NAVIGATION_DIRECT_RESHARE_SHEET";
            case 16105:
                return "NAVIGATION_PROFILE";
            case 16115:
                return "NAVIGATION_COM_INSTAGRAM_PORTABLE_SETTINGS_SETTINGS";
            case 16118:
                return "NAVIGATION_RETRO_REGISTRATION_SIGN_UP";
            case 16169:
                return "NAVIGATION_CLIPS_VIEWER_REEL_CLIPS_VIEWER";
            case 16171:
                return "NAVIGATION_ALBUM_PICKER";
            case 16178:
                return "NAVIGATION_HASHTAG_PREVIEW";
            case 16220:
                return "NAVIGATION_USER_DELETED_MEDIA";
            case 16246:
                return "NAVIGATION_REEL_SETTINGS";
            case 16255:
                return "NAVIGATION_REEL_DASHBOARD";
            case 16267:
                return "NAVIGATION_DIRECT_MESSAGE_LIST";
            case 16311:
                return "NAVIGATION_CLIPS_VIEWER_FEED_CONTEXTUAL_KEYWORD";
            case 16315:
                return "NAVIGATION_DIRECT_AVATAR_STICKER_PICKER_GRID";
            case 16316:
                return "NAVIGATION_AUTO_CREATED_REELS";
            case 16332:
                return "NAVIGATION_CLIPS_VIEWER_NEWSFEED_YOU";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
