package p000X;
/* renamed from: X.0gI  reason: invalid class name */
/* loaded from: classes.dex */
public final class C0gI {
    public static String A00(int i) {
        return i != 3528 ? i != 3675 ? i != 6382 ? i != 9014 ? i != 9825 ? i != 11550 ? i != 13570 ? i != 13826 ? i != 14326 ? i != 14439 ? "UNDEFINED_QPL_EVENT" : "IG_BRAND_EXPERIENCE_QP_PROFILE_PAGE" : "IG_BRAND_EXPERIENCE_QP_FEED_BANNER" : "IG_BRAND_EXPERIENCE_QP_PROFILE_PAGE_PROMPT" : "IG_BRAND_EXPERIENCE_QP_ACTIVITY_FEED_HEADER" : "IG_BRAND_EXPERIENCE_QP_FEED_HEADER" : "IG_BRAND_EXPERIENCE_QP_OTHER_PROFILE_PAGE_HEADER" : "IG_BRAND_EXPERIENCE_QP_ACTIVITY_FEED_PROMPT" : "IG_BRAND_EXPERIENCE_QP_THREAD_LOADED" : "IG_BRAND_EXPERIENCE_QP_OTHER_PROFILE_PAGE_PROMPT" : "IG_BRAND_EXPERIENCE_QP_FEED_PROMPT";
    }
}
