package p000X;
/* renamed from: X.0ZT  reason: invalid class name */
/* loaded from: classes.dex */
public final class C0ZT {
    public static String A00(int i) {
        return i != 3005 ? i != 6977 ? i != 7610 ? i != 10247 ? i != 10442 ? i != 10691 ? i != 11466 ? i != 11866 ? i != 14352 ? i != 14485 ? "UNDEFINED_QPL_EVENT" : "BUSINESS_INBOX_IN_MESSENGER_INBOX_LOAD_COMPLETE" : "BUSINESS_INBOX_IN_MESSENGER_ACCOUNT_SWITCH_COMPLETION_FAILURE" : "BUSINESS_INBOX_IN_MESSENGER_NOTIFICATION_CLICK" : "BUSINESS_INBOX_IN_MESSENGER_ACCOUNT_SWITCH_START" : "BUSINESS_INBOX_IN_MESSENGER_ACCOUNT_SWITCH_MISSING_INFO_FAILURE" : "BUSINESS_INBOX_IN_MESSENGER_ACCOUNT_SWITCH_LOGOUT_COMPLETE" : "BUSINESS_INBOX_IN_MESSENGER_THREAD_LOAD_COMPLETE" : "BUSINESS_INBOX_IN_MESSENGER_INBOX_LOAD_TTRC" : "BUSINESS_INBOX_IN_MESSENGER_ACCOUNT_SWITCH_LOGIN_START" : "BUSINESS_INBOX_IN_MESSENGER_ACCOUNT_SWITCH_LOGIN_COMPLETE";
    }
}
