package p000X;
/* renamed from: X.0Zw  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C14000Zw {
    public static String A00(int i) {
        return i != 1 ? i != 2 ? i != 3 ? i != 4 ? i != 5 ? i != 3230 ? i != 5181 ? i != 6412 ? i != 10774 ? i != 11327 ? i != 15100 ? i != 15497 ? i != 15994 ? "UNDEFINED_QPL_EVENT" : "CPDP_LOADED" : "COMMERCE_POA_SELLER_RNR_DETAILED_REVIEW" : "COMMERCE_REVIEW_UNIFIED_COMPOSER" : "COMMERCE_SELLER_RNR_COLLECTION_SURFACE" : "COMMERCE_LOAD_VARIANT_SELECTORS" : "COMMERCE_LOAD_PIVOTS" : "COMMERCE_SELLER_RNR_COLLECTION_SURFACE_TTI" : "COMMERCE_LOAD_CPDP" : "COMMERCE_REVIEW_COMPOSER_TTI" : "COMMERCE_B2C_TTI" : "COMMERCE_ANDROID_COMMERCE_VIEW_PRODUCT_DETAILS" : "COMMERCE_ANDROID_COMMERCE_VIEW_STOREFRONT" : "COMMERCE_ANDROID_COMMERCE_VIEW_STOREFRONT_COLLECTION";
    }
}
