package p000X;
/* renamed from: X.0bh  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C14980bh {
    public static String A00(int i) {
        return i != 3386 ? i != 3533 ? i != 4068 ? i != 4557 ? i != 5455 ? i != 6907 ? i != 8831 ? i != 10780 ? i != 15429 ? i != 15447 ? "UNDEFINED_QPL_EVENT" : "FAN_RECOGNITION_REELS_COMPOSER_OPEN" : "FAN_RECOGNITION_WETW_LIST_VIEW_FOLLOW_BOTTOMSHEET" : "FAN_RECOGNITION_WETW_FOLLOWER_SETTINGS" : "FAN_RECOGNITION_WETW_LIST_VIEW" : "FAN_RECOGNITION_NEW_FAN_LIST_VIEW" : "FAN_RECOGNITION_WETW_BOARDS_LIST_VIEW" : "FAN_RECOGNITION_STORIES_COMPOSER_OPEN" : "FAN_RECOGNITION_WETW_NATIVE_CREATOR_SETTINGS" : "FAN_RECOGNITION_POST_COMPOSER_OPEN" : "FAN_RECOGNITION_FAN_RECOGNITION_CUSTOMIZATION_VIEW";
    }
}
