package p000X;

import com.facebook.cameracore.ardelivery.xplat.modelmanager.versionfetcher.ARDRemoteModelVersionFetcher;
/* renamed from: X.0c0  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C15160c0 {
    public static String A00(int i) {
        switch (i) {
            case 1001:
                return "FB_HORIZON_HORIZON_HOME_ASSET_VOLUME";
            case 1051:
                return "FB_HORIZON_VERTS_CONNECT";
            case 1106:
                return "FB_HORIZON_USER_CARD_LOAD";
            case 1172:
                return "FB_HORIZON_MEDIA_SHARE_TO_FB_FEED";
            case 1258:
                return "FB_HORIZON_SHARING_FB_STORIES";
            case 1350:
                return "FB_HORIZON_HOMEWORLD_PERSISTENCE_TEXTURE_LOADING";
            case 1510:
                return "FB_HORIZON_REMOTE_DEEPLINK_LAUNCH";
            case 1521:
                return "FB_HORIZON_SHARING_PHOTO_UPLOAD";
            case 1703:
                return "FB_HORIZON_SOCIAL_PANEL_FOLLOWING_LIST_LOAD";
            case 1757:
                return "FB_HORIZON_SUGGESTED_WORLDS_LOAD";
            case 2013:
                return "FB_HORIZON_LOAD_SOCIAL_ALL_COMPONENT";
            case 2029:
                return "FB_HORIZON_CANT_MISS_EVENTS_LOAD";
            case 2044:
                return "FB_HORIZON_DECLINE_PARTY_INVITE";
            case 2265:
                return "FB_HORIZON_EDIT_MODE_AUTOSAVE";
            case 2435:
                return "FB_HORIZON_HOMEWORLD_PERSISTENCE_OBJECT_LOADING";
            case 2533:
                return "FB_HORIZON_ASSET_SPAWN";
            case 2613:
                return "FB_HORIZON_INTENT_HANGOUT_LOAD";
            case 2725:
                return "FB_HORIZON_PROJECTILE_POOL_SETUP";
            case 2828:
                return "FB_HORIZON_PARTY_GAMES_LOAD";
            case 2830:
                return "FB_HORIZON_PEOPLE_SEARCH";
            case 2835:
                return "FB_HORIZON_HANGOUT_LOAD";
            case 2866:
                return "FB_HORIZON_SAVED_WORLDS_LOAD";
            case 2934:
                return "FB_HORIZON_HORIZON_UNITY_ASSET_BUNDLE";
            case 3112:
                return "FB_HORIZON_QUEST_ENTRY_INSTANTIATION";
            case 3192:
                return "FB_HORIZON_MESSAGING_OVERLAY";
            case 3249:
                return "FB_HORIZON_INTENT_ATTEND_LOAD";
            case 3294:
                return "FB_HORIZON_FRIENDS_ACTIVE_LOAD";
            case 3549:
                return "FB_HORIZON_PEOPLE_TAB_LOAD";
            case ARDRemoteModelVersionFetcher.REQUEST_CACHE_TTL_SECONDS /* 3600 */:
                return "FB_HORIZON_HOMEWORLD_FETCH_PERSISTENCE";
            case 3871:
                return "FB_HORIZON_INTENT_CREATE_LOAD";
            case 3903:
                return "FB_HORIZON_MEDIA_SHARE_TO_FB_REELS";
            case 4051:
                return "FB_HORIZON_FEATURED_PUI_OPEN_E2E";
            case 4182:
                return "FB_HORIZON_ACCEPT_PARTY_INVITE";
            case 4270:
                return "FB_HORIZON_WELCOME_BOARD_PUI_LOAD";
            case 4307:
                return "FB_HORIZON_NEW_WORLDS_TOP_CREATORS_LOAD";
            case 4358:
                return "FB_HORIZON_INTEGRITY_REC2VIDEO_GENERATION";
            case 4361:
                return "FB_HORIZON_USER_PRESENCE_ONLINE_STATUS_TEXT";
            case 4659:
                return "FB_HORIZON_INTENT_PLAY_LOAD";
            case 4914:
                return "FB_HORIZON_IDENTITY_PANEL_LOAD";
            case 5036:
                return "FB_HORIZON_HOMEWORLD_PICTURE_FRAME_GAME_OBJECT_LOADING";
            case 5337:
                return "FB_HORIZON_SEARCH_RESULT_LOAD";
            case 5399:
                return "FB_HORIZON_CREATOR_RULES_GAME_OBJECT_LOADING";
            case 5448:
                return "FB_HORIZON_JOIN_PARTY_FROM_INVITE";
            case 5696:
                return "FB_HORIZON_MEDIA_SHARE_TO_MESSENGER";
            case 6237:
                return "FB_HORIZON_STANDALONE_RUNTIME_SERVICE_INITIALIZATION";
            case 6255:
                return "FB_HORIZON_PARTICLE_FX_LOAD";
            case 6389:
                return "FB_HORIZON_PARTY_GESTURE_SEND_INVITE";
            case 6438:
                return "FB_HORIZON_PROJECTILE_LAUNCHER";
            case 6452:
                return "FB_HORIZON_FRIENDS_VISITED_LOAD";
            case 6492:
                return "FB_HORIZON_NEW_TRENDING_LOAD";
            case 6655:
                return "FB_HORIZON_START_TRAVEL_FROM_REMOTE_LAUNCH_IN_APP_RUNNING";
            case 6777:
                return "FB_HORIZON_HOMEWORLD_PICTURE_FRAME_PERSONALIZATION_LOADING";
            case 6811:
                return "FB_HORIZON_WORLD_DETAIL_LOAD";
            case 6816:
                return "FB_HORIZON_LEADERBOARD_LOAD";
            case 6818:
                return "FB_HORIZON_REMOTE_DEEPLINK_LAUNCH_FROM_APP_RUNNUNG";
            case 6969:
                return "FB_HORIZON_GAUNTLET_TEST_BRIDGE_LATENCY";
            case 7179:
                return "FB_HORIZON_SHARING_VIDEO_UPLOAD";
            case 7222:
                return "FB_HORIZON_IN_WORLD_INVENTORY_LOAD";
            case 7274:
                return "FB_HORIZON_PVP_FEED_LOAD";
            case 7292:
                return "FB_HORIZON_CONNECT_TO_PARTY_VOIP";
            case 7301:
                return "FB_HORIZON_LOAD_NEARBY_COMPONENT";
            case 7477:
                return "FB_HORIZON_RECEIVE_REMOTE_LAUNCH_NOTIFICATION";
            case 7737:
                return "FB_HORIZON_WORLD_TAB_LEADERBOARD_LOAD";
            case 7897:
                return "FB_HORIZON_WORLD_TAB_OPEN_E2E";
            case 7946:
                return "FB_HORIZON_SERVICE_GRAPH_LOAD";
            case 8095:
                return "FB_HORIZON_FEATURED_EVENTS_LOAD";
            case 8248:
                return "FB_HORIZON_PEOPLE_TAB_ALL_LOAD";
            case 8472:
                return "FB_HORIZON_PROFILE_PANEL_LOAD";
            case 8500:
                return "FB_HORIZON_EXPLORATION_ONLY_LOAD";
            case 8655:
                return "FB_HORIZON_EDIT_MODE_MUTATION";
            case 8674:
                return "FB_HORIZON_LINK_SHARE_TO_FB_GROUPS";
            case 8816:
                return "FB_HORIZON_HANDLE_REMOTE_LAUNCH_IN_APP_RUNNING";
            case 8852:
                return "FB_HORIZON_HORIZON_SPAWN_ASSET_SG";
            case 8884:
                return "FB_HORIZON_WELCOME_BOARD_LOAD";
            case 8914:
                return "FB_HORIZON_LOADING_SCREEN";
            case 8947:
                return "FB_HORIZON_PUI_OPEN_NATIVE";
            case 9234:
                return "FB_HORIZON_WORLD_TAB_DAY_ZERO_LOAD";
            case 9262:
                return "FB_HORIZON_GLOBAL_NAV_LOAD";
            case 9404:
                return "FB_HORIZON_APP_LOAD";
            case 9784:
                return "FB_HORIZON_EDIT_MODE_ENTITY_PROPERTY_EDIT";
            case 9824:
                return "FB_HORIZON_FEED_LOAD";
            case 9848:
                return "FB_HORIZON_LOAD_FRIEND_REQUEST_COMPONENT";
            case 9951:
                return "FB_HORIZON_PROJECTILE_LAUNCHER_COLLISION";
            case 10204:
                return "FB_HORIZON_RECENTLY_VISITED_LOAD";
            case 10214:
                return "FB_HORIZON_SHARING_REELS_SAVE_DRAFTS";
            case 10396:
                return "FB_HORIZON_LEAVE_HW_PARTY";
            case 10591:
                return "FB_HORIZON_LINK_SHARE_TO_MESSENGER";
            case 10619:
                return "FB_HORIZON_ASSET_LIBRARY";
            case 10655:
                return "FB_HORIZON_WORLD_NAVIGATION";
            case 10816:
                return "FB_HORIZON_IWP_ENTITLEMENT";
            case 10886:
                return "FB_HORIZON_USER_PRESENCE_ONLINE_STATUS";
            case 11378:
                return "FB_HORIZON_FEATURE_LAOD";
            case 11396:
                return "FB_HORIZON_PVE_FEED_LOAD";
            case 11424:
                return "FB_HORIZON_FRIENDS_ACTIVITY_LOAD";
            case 11534:
                return "FB_HORIZON_LOAD_FRIENDS_COMPONENT";
            case 11604:
                return "FB_HORIZON_WORLD_TAB_FOR_YOU_LOAD";
            case 11712:
                return "FB_HORIZON_CANCEL_PARTY_INVITE";
            case 11962:
                return "FB_HORIZON_MEDIA_SHARE_TO_FB_GROUPS";
            case 12040:
                return "FB_HORIZON_ART_FEED_LOAD";
            case 12075:
                return "FB_HORIZON_HOMEWORLD_PICTURE_FRAME_REACT_PANEL_LOADING";
            case 12362:
                return "FB_HORIZON_LINK_SHARE_TO_FB_FEED";
            case 12505:
                return "FB_HORIZON_SHARING_TO_FB";
            case 12535:
                return "FB_HORIZON_SHARING_IG_STORIES";
            case 12620:
                return "FB_HORIZON_WORLD_TAB_JOIN_NOW_LOAD";
            case 12879:
                return "FB_HORIZON_LINK_SHARING_GENERATE";
            case 13029:
                return "FB_HORIZON_CONNECT_TO_PARTY_VOIP_VERTS";
            case 13032:
                return "FB_HORIZON_HORIZON_PUI_TEST_WWW";
            case 13702:
                return "FB_HORIZON_INSTANCES_INVITED_LOAD";
            case 13723:
                return "FB_HORIZON_MEDIA_SHARE_TO_HZ_WORLDS";
            case 13853:
                return "FB_HORIZON_IWP_ITEM_PURCHASE";
            case 13858:
                return "FB_HORIZON_PEOPLE_NEARBY_SHELF_LOAD";
            case 14040:
                return "FB_HORIZON_SIMILAR_USERS_RECOMMENDED_LOAD";
            case 14123:
                return "FB_HORIZON_MIXED_CONTENT_LOAD";
            case 14186:
                return "FB_HORIZON_PROFILE_PANEL_2_LOAD";
            case 14405:
                return "FB_HORIZON_HANDLE_REMOTE_LAUNCH_IN_APP_START";
            case 14427:
                return "FB_HORIZON_SUGGESTED_WORLDS_HANG_OUT_LOAD";
            case 14487:
                return "FB_HORIZON_FEATURED_GAMES_LOAD";
            case 14747:
                return "FB_HORIZON_LOAD_RECENTLY_NEARBY_COMPONENT";
            case 14762:
                return "FB_HORIZON_MESSAGING_OVERLAY_LOAD";
            case 14779:
                return "FB_HORIZON_PUZZLE_LOAD";
            case 14788:
                return "FB_HORIZON_FEATURED_PUI_PRE_OPEN";
            case 14836:
                return "FB_HORIZON_EXPLORATION_LOAD";
            case 14854:
                return "FB_HORIZON_SEND_PARTY_INVITE";
            case 14916:
                return "FB_HORIZON_SHARING_VIDEO_PLAYBACK";
            case 15170:
                return "FB_HORIZON_HOMEWORLD_SAVE_PERSISTENCE";
            case 15218:
                return "FB_HORIZON_VFX_ASSET_BUNDLE_LOAD";
            case 15297:
                return "FB_HORIZON_ASSET_FETCH";
            case 15355:
                return "FB_HORIZON_LIKED_LOAD";
            case 15473:
                return "FB_HORIZON_SCENE_TRANSITION_MANAGER";
            case 15627:
                return "FB_HORIZON_IWP_ITEM_CREATION";
            case 15700:
                return "FB_HORIZON_QUEST_PUI_PANEL_COMPONENT";
            case 15865:
                return "FB_HORIZON_PERSISTENT_VARIABLES_LOAD";
            case 15873:
                return "FB_HORIZON_INTEGRITY_REC2VIDEO_LAUNCH";
            case 15899:
                return "FB_HORIZON_MOST_VISITED_LOAD";
            case 15945:
                return "FB_HORIZON_JOIN_PARTY_FROM_GESTURE";
            case 16052:
                return "FB_HORIZON_WORLD_TAB_SPOTLIGHT_LOAD";
            case 16091:
                return "FB_HORIZON_SAVE_SNAPSHOT_TO_DISK";
            case 16155:
                return "FB_HORIZON_HORIZON_REC_VIEWER";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
