package p000X;
/* renamed from: X.0cH  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C15330cH {
    public static String A00(int i) {
        return i != 1187 ? i != 5826 ? i != 6829 ? i != 7413 ? i != 8148 ? i != 8177 ? i != 9166 ? i != 10367 ? i != 12626 ? i != 14660 ? "UNDEFINED_QPL_EVENT" : "FB_SHOPS_QUESTIONS_AND_ANSWERS_LIKE_A_QUESTION" : "FB_SHOPS_QUESTIONS_AND_ANSWERS_DELETE_A_QUESTION" : "FB_SHOPS_QUESTIONS_AND_ANSWERS_LIKE_AN_ANSWER" : "FB_SHOPS_QUESTIONS_AND_ANSWERS_LAZY_LOAD_PDP_MODULE" : "FB_SHOPS_QUESTIONS_AND_ANSWERS_SCREEN_TTRC" : "FB_SHOPS_QUESTIONS_AND_ANSWERS_ANSWER_A_QUESTION" : "FB_SHOPS_QUESTIONS_AND_ANSWERS_ALL_QNA_PAGINATION" : "FB_SHOPS_QUESTIONS_AND_ANSWERS_UNLIKE_A_QUESTION" : "FB_SHOPS_QUESTIONS_AND_ANSWERS_ASK_A_QUESTION" : "FB_SHOPS_QUESTIONS_AND_ANSWERS_UNLIKE_AN_ANSWER";
    }
}
