package p000X;
/* renamed from: X.0jW  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C18610jW {
    public static String A00(int i) {
        switch (i) {
            case 1110:
                return "MANAGED_MOBILE_ERRORS_AUTH_OPERATION_LISTENER_ERROR";
            case 1142:
                return "MANAGED_MOBILE_ERRORS_SURFACE_UNTRUSTED_CALLER_NAVIGATION";
            case 1156:
                return "MANAGED_MOBILE_ERRORS_FEEDBACK_REACTIONS_SETTINGS_QUERY_PRE_ERROR";
            case 1285:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_EVALUATOR_ERROR";
            case 1368:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_RECLASSIFICATION";
            case 1488:
                return "MANAGED_MOBILE_ERRORS_LITHO_VIDEO_ATTACHMENT_UNEXPECTED_EVENT";
            case 1569:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_HOME_MOBILE_ERROR_EVENT";
            case 1653:
                return "MANAGED_MOBILE_ERRORS_MESSENGER_UNIVERSAL_SEARCH_UNEXPECTED_EVENT";
            case 1729:
                return "MANAGED_MOBILE_ERRORS_IG_DIRECT_XMA_UNEXPECTED_EVENT";
            case 2330:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_SPONSORED_ITEM_DELIVERED_OUTSIDE_ACP";
            case 2352:
                return "MANAGED_MOBILE_ERRORS_LITHO_BOOKMARKS_UNEXPECTED_EVENT";
            case 2375:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_DIRECT_MOBILE_ERROR_EVENT";
            case 2403:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_STORIES_CANDID_ERROR";
            case 3009:
                return "MANAGED_MOBILE_ERRORS_SHARED_PREFERENCES_STORAGE_SYNC_FAILED";
            case 3098:
                return "MANAGED_MOBILE_ERRORS_IG_FLASH_LOCAL_DATA_SOURCE_UNEXPECTED_EVENT";
            case 3232:
                return "MANAGED_MOBILE_ERRORS_PUBLISHER_DB_SERIALIZATION_FAILURE";
            case 3235:
                return "MANAGED_MOBILE_ERRORS_SCREEN_SHARE_AUDIO_RECORD_INIT_FAILURE";
            case 3255:
                return "MANAGED_MOBILE_ERRORS_IG_COMMENT_BOTTOM_SHEET_ERROR_EVENT";
            case 3305:
                return "MANAGED_MOBILE_ERRORS_XAPP_PRIVACY_COMM_EVENT";
            case 3634:
                return "MANAGED_MOBILE_ERRORS_IG_FAST_AND_SAFE_SOFT_ERROR";
            case 3854:
                return "MANAGED_MOBILE_ERRORS_LITHO_COMMENTS_UNEXPECTED_EVENT";
            case 4031:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_MANUAL_APP_RESTART";
            case 4154:
                return "MANAGED_MOBILE_ERRORS_PUBLISHER_ZERO_TARGET_ID_ERROR";
            case 4184:
                return "MANAGED_MOBILE_ERRORS_MSYS_INITIALIZATION_401_LOGOUT";
            case 4367:
                return "MANAGED_MOBILE_ERRORS_IG_USER_DETAILS_GRID_TAP_OUT_OF_BOUNDS_ERROR_EVENT";
            case 4379:
                return "MANAGED_MOBILE_ERRORS_LITHO_PROFILE_UNEXPECTED_EVENT";
            case 4505:
                return "MANAGED_MOBILE_ERRORS_FB_USER_SESSION_EMPTY_SESSION_VC";
            case 4513:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_WEARABLES_MOBILE_ERROR_EVENT";
            case 4517:
                return "MANAGED_MOBILE_ERRORS_GAMES_UNEXPECTED_EVENT";
            case 4993:
                return "MANAGED_MOBILE_ERRORS_INJECTED_TOO_EARLY";
            case 5057:
                return "MANAGED_MOBILE_ERRORS_DUAL_SEND_TEST_UNEXPECTED_EVENT";
            case 5315:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_BLOCKED_FLOW";
            case 5390:
                return "MANAGED_MOBILE_ERRORS_FIXIE_MME_MAIN_THREAD_IPC";
            case 5422:
                return "MANAGED_MOBILE_ERRORS_LITHO_REELS_UNEXPECTED_EVENT";
            case 5507:
                return "MANAGED_MOBILE_ERRORS_LITHO_GROOT_VIDEO_UNEXPECTED_EVENT";
            case 5568:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_CAMERA_MOBILE_ERROR_EVENT";
            case 5691:
                return "MANAGED_MOBILE_ERRORS_MQD_STALL";
            case 5790:
                return "MANAGED_MOBILE_ERRORS_IG_NDX_UNEXPECTED_EVENT";
            case 5793:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_TEMPORARY_DECLASSIFICATION";
            case 6231:
                return "MANAGED_MOBILE_ERRORS_EVENT_MIXVM_ERROR";
            case 6283:
                return "MANAGED_MOBILE_ERRORS_MESSENGER_PAGE_TO_ADMIN_SWITCH_NULL_ADMIN_CONTEXT_EVENT";
            case 6318:
                return "MANAGED_MOBILE_ERRORS_FNL_MSYS_REGRESSSION_MME_EVENT";
            case 6355:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_IGDS_BOTTOM_SHEET_MOBILE_ERROR_EVENT";
            case 6569:
                return "MANAGED_MOBILE_ERRORS_AVATAR_COVER_PHOTO_UGC_DIMENSIONS_EVENT";
            case 6636:
                return "MANAGED_MOBILE_ERRORS_CONNECTIVITY_UNEXPECTED_EVENT";
            case 6821:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_ANDROID_VIDEO_GLADOS_TEMPLATE_BLOKS_PAYLOAD_EXCEPTION";
            case 6841:
                return "MANAGED_MOBILE_ERRORS_HOST_PROFILE_ID_OVERWRITE";
            case 7024:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_FEED_TBI_UNEXPECTED_EVENT";
            case 7045:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_COMMENTS_UNEXPECTED_EVENT";
            case 7100:
                return "MANAGED_MOBILE_ERRORS_MEDIA_UPLOADER_ZERO_TARGET_ID_ERROR";
            case 7192:
                return "MANAGED_MOBILE_ERRORS_TAB_ANALYTICS_NAME_EMPTY";
            case 7199:
                return "MANAGED_MOBILE_ERRORS_IG_CONSENT_ALASKA_NATIVE_SOFT_ERROR";
            case 7232:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_ATTEST_PLAYINTEGRITY_UNEXPECTED_EVENT";
            case 7293:
                return "MANAGED_MOBILE_ERRORS_SHARED_PREFERENCES_ORPHANED_EXTERNAL_KEY";
            case 7558:
                return "MANAGED_MOBILE_ERRORS_LEGACY_THREADS_DB2_RECREATED_EVENT";
            case 7644:
                return "MANAGED_MOBILE_ERRORS_PROFILE_ANDROID_UNEXPECTED_GRAPHQL_INPUT_EVENT";
            case 7841:
                return "MANAGED_MOBILE_ERRORS_VIDEO_PLAYBACK_ERROR";
            case 7857:
                return "MANAGED_MOBILE_ERRORS_SHARED_PREFERENCES_EXTERNAL_WRITE_FAILED";
            case 7932:
                return "MANAGED_MOBILE_ERRORS_IG_1PD_INSTALL_ERROR_EVENT";
            case 7950:
                return "MANAGED_MOBILE_ERRORS_FB_MEDIA_UPLOADER_ERROR";
            case 8116:
                return "MANAGED_MOBILE_ERRORS_ANDROID_SHARING_UNEXPECTED_EVENT";
            case 8122:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_PRIVACY_VIOLATION_EVENT";
            case 8178:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_DEEPLINK_UNEXPECTED_EVENT";
            case 8273:
                return "MANAGED_MOBILE_ERRORS_INCORRECT_LEGACY_TRANSFORM_MATRIX";
            case 8446:
                return "MANAGED_MOBILE_ERRORS_API_UNEXPECTED_EVENT_TEST";
            case 8480:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_IAA_STORIES_NON_GAP_ZERO_RULES";
            case 8488:
                return "MANAGED_MOBILE_ERRORS_LITHO_WATCH_UNEXPECTED_EVENT";
            case 8504:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_INTENT_AWARE_ADS_STORIES_UNEXPECTED_EVENT";
            case 8617:
                return "MANAGED_MOBILE_ERRORS_MOBILE_CONFIG_INJECTED_TOO_EARLY";
            case 8646:
                return "MANAGED_MOBILE_ERRORS_IG_BOOST_UNEXPECTED_EVENT";
            case 8728:
                return "MANAGED_MOBILE_ERRORS_MESSENGER_QUICK_PROMOTION_UNEXPECTED_EVENT";
            case 8832:
                return "MANAGED_MOBILE_ERRORS_IG_LITHO_REELS_CLIP_ITEM_ERROR_EVENT";
            case 8878:
                return "MANAGED_MOBILE_ERRORS_LOCALE_UNEXPECTED_EVENT";
            case 8900:
                return "MANAGED_MOBILE_ERRORS_IG_UHL_LIVE_CHAT";
            case 8992:
                return "MANAGED_MOBILE_ERRORS_ACCOUNT_STATUS_UNEXPECTED_EVENT";
            case 9024:
                return "MANAGED_MOBILE_ERRORS_VIEWER_CONTEXT_CACHE_OVERWRITE_EVENT";
            case 9393:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_STORIES_MOBILE_ERROR_EVENT";
            case 9551:
                return "MANAGED_MOBILE_ERRORS_TRANSCODE_FAILURE_UNSUPPORTED_CODEC";
            case 9557:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_REPEATED_NAVIGATION";
            case 9592:
                return "MANAGED_MOBILE_ERRORS_XAPP_PRIVACY_DEEPLINK_EVENT";
            case 9631:
                return "MANAGED_MOBILE_ERRORS_MESSAGING_PRIVACY_VAULTING_ERROR_EVENT";
            case 9666:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_NAS_UNEXPECTED_EVENT";
            case 9670:
                return "MANAGED_MOBILE_ERRORS_HOST_PROFILE_ID_MISMATCH";
            case 9864:
                return "MANAGED_MOBILE_ERRORS_IG_TIGON_SERVICE_LAYER_ERROR_EVENT";
            case 9920:
                return "MANAGED_MOBILE_ERRORS_CLIPS_VIDEO_SUBTITLES_CUING_MISMATCH";
            case 10098:
                return "MANAGED_MOBILE_ERRORS_PROFILE_ANDROID_UNEXPECTED_EVENT";
            case 10188:
                return "MANAGED_MOBILE_ERRORS_LITHO_PHOTO_ATTACHMENT_UNEXPECTED_EVENT";
            case 10198:
                return "MANAGED_MOBILE_ERRORS_MESSENGER_PAGE_TO_ADMIN_SWITCH_NULL_ADMIN_CONTEXT_2_EVENT";
            case 10306:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_FEED_RENDERING_UNEXPECTED_EVENT";
            case 10319:
                return "MANAGED_MOBILE_ERRORS_OXYGEN_INSTALL_SDK";
            case 10341:
                return "MANAGED_MOBILE_ERRORS_LSS_MIB_UNEXPECTED_EVENT";
            case 10408:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_REEL_TRAY_MANAGER";
            case 10523:
                return "MANAGED_MOBILE_ERRORS_IG_STORY_PREFETCH_ODML_UNEXPECTED_EVENT";
            case 10541:
                return "MANAGED_MOBILE_ERRORS_ROOMS_UNEXPECTED_EVENT";
            case 10646:
                return "MANAGED_MOBILE_ERRORS_SESSIONLESS_MOBILE_CONFIG_INJECTED_TOO_EARLY";
            case 10662:
                return "MANAGED_MOBILE_ERRORS_LITHO_STRICT_MODE_VIOLATION";
            case 10718:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_DIRECT_CHANNELS_IMPRESSION";
            case 10955:
                return "MANAGED_MOBILE_ERRORS_MEMORY_UNEXPECTED_EVENT";
            case 11013:
                return "MANAGED_MOBILE_ERRORS_IG_ZERO_UNEXPECTED_EVENT";
            case 11220:
                return "MANAGED_MOBILE_ERRORS_ANDROID_PATTERN_FNL";
            case 11232:
                return "MANAGED_MOBILE_ERRORS_INJECTED_TOO_EARLY_EXPANSION";
            case 11326:
                return "MANAGED_MOBILE_ERRORS_LITHO_SEARCH_UNEXPECTED_EVENT";
            case 11827:
                return "MANAGED_MOBILE_ERRORS_VIEWER_CONTEXT_ACCESS_IN_EXECUTOR_UNEXPECTED_EVENT";
            case 11873:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_EXPLORE_MOBILE_ERROR_EVENT";
            case 11894:
                return "MANAGED_MOBILE_ERRORS_ANDROID_VIDEO_ERROR";
            case 11967:
                return "MANAGED_MOBILE_ERRORS_USER_DATA_USAGE_ON_NON_UI_THREAD";
            case 12019:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_DECLASSIFICATION";
            case 12052:
                return "MANAGED_MOBILE_ERRORS_PUBLISHER_DB_DESERIALIZATION_FAILURE";
            case 12126:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_UI_TOAST_ERROR_EVENT";
            case 12281:
                return "MANAGED_MOBILE_ERRORS_FIXIE_ERROR";
            case 12459:
                return "MANAGED_MOBILE_ERRORS_REELS_CAROUSEL_RENDERING_CONFIG_ERROR";
            case 12515:
                return "MANAGED_MOBILE_ERRORS_CLIPS_GRID_NULL_IMAGE_PREVIEW";
            case 12526:
                return "MANAGED_MOBILE_ERRORS_FEEDBACK_REACTIONS_SETTINGS_QUERY_POST_ERROR";
            case 12583:
                return "MANAGED_MOBILE_ERRORS_UI_GRAPH_UNEXPECTED_EVENT";
            case 12597:
                return "MANAGED_MOBILE_ERRORS_LITHO_EVENTS_TAB_UNEXPECTED_EVENTS";
            case 13039:
                return "MANAGED_MOBILE_ERRORS_ANDROID_VIDEO_PLAYBACK_UNEXPECTED_EVENT";
            case 13144:
                return "MANAGED_MOBILE_ERRORS_HOST_PROFILE_ID_FORMAT_ERROR";
            case 13476:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_PRIVACY_UNWRAP";
            case 13519:
                return "MANAGED_MOBILE_ERRORS_FBUSERSESSION_PROVIDER_EMPTY_VC_CACHE_ERROR";
            case 13533:
                return "MANAGED_MOBILE_ERRORS_TEST_EVENT_CREATION";
            case 13612:
                return "MANAGED_MOBILE_ERRORS_LITHO_NOTIFICATIONS_UNEXPECTED_EVENT";
            case 13764:
                return "MANAGED_MOBILE_ERRORS_PROFILE_ANDROID_CONTEXT_CONFLICT_EVENT";
            case 13840:
                return "MANAGED_MOBILE_ERRORS_LITHO_GROUP_MALL_UNEXPECTED_EVENT";
            case 13863:
                return "MANAGED_MOBILE_ERRORS_IG_SOCIAL_CONTEXT_TEXT_USERNAMES_EMPTY_LIST";
            case 13927:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_CLIPS_PAGINATION_TOKEN_ERROR_EVENT";
            case 13988:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_ADS_MOBILE_ERROR_EVENT";
            case 14018:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_ATTEST_KEYSTORE_UNEXPECTED_EVENT";
            case 14078:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_CREATION_UNEXPECTED_EVENT";
            case 14138:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_MISSING_CONSENT_ERROR";
            case 14262:
                return "MANAGED_MOBILE_ERRORS_GEMSTONE_UNEXPECTED_EVENT";
            case 14378:
                return "MANAGED_MOBILE_ERRORS_TIGON_UNEXPECTED_ERROR_EVENT";
            case 14402:
                return "MANAGED_MOBILE_ERRORS_ANDROID_PATTERN_VIDEO";
            case 14461:
                return "MANAGED_MOBILE_ERRORS_IG_ADS_SOFT_ERROR";
            case 14481:
                return "MANAGED_MOBILE_ERRORS_LITHO_NEWSFEED_UNEXPECTED_EVENT";
            case 14487:
                return "MANAGED_MOBILE_ERRORS_LITHO_COMPASS_ITEM_UNEXPECTED_EVENT";
            case 14505:
                return "MANAGED_MOBILE_ERRORS_APP_INIT_NOT_RESPONDING";
            case 14545:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_FEED_LITHO_ATTACH_WITHOUT_BIND_EVENT";
            case 14649:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_IMAGE_INFRA";
            case 14703:
                return "MANAGED_MOBILE_ERRORS_QPL_INJECTED_TOO_EARLY";
            case 14797:
                return "MANAGED_MOBILE_ERRORS_FIXIE_MME_IPC";
            case 14904:
                return "MANAGED_MOBILE_ERRORS_IG_REELS_CLIPS_PAGINATION_TOKEN_ADS_ERROR_EVENT";
            case 15258:
                return "MANAGED_MOBILE_ERRORS_IG_SIGNALS_UNEXPECTED_EVENT";
            case 15345:
                return "MANAGED_MOBILE_ERRORS_IG_ANDROID_PROFILE_UNEXPECTED_EVENT";
            case 15663:
                return "MANAGED_MOBILE_ERRORS_DEFAULT_MEDIA_TRANSCODER_ERROR";
            case 15721:
                return "MANAGED_MOBILE_ERRORS_MOBILE_ZONE_UNKNOWN_POLICY_ERROR";
            case 15744:
                return "MANAGED_MOBILE_ERRORS_LITHO_INSPIRATION_UNEXPECTED_EVENT";
            case 15786:
                return "MANAGED_MOBILE_ERRORS_IG_FNCR_MOBILE_ERROR_EVENT";
            case 15796:
                return "MANAGED_MOBILE_ERRORS_LITHO_STORY_VIEWER_UNEXPECTED_EVENT";
            case 15805:
                return "MANAGED_MOBILE_ERRORS_KATANA_CONSENT_ALASKA_NATIVE_SOFT_ERROR";
            case 15959:
                return "MANAGED_MOBILE_ERRORS_NATIVE_TEMPLATE_UNEXPECTED_EVENT";
            case 16155:
                return "MANAGED_MOBILE_ERRORS_LITHO_WATCH_RECYCLER_UNEXPECTED_EVENT";
            case 16341:
                return "MANAGED_MOBILE_ERRORS_LITHO_LOCATION_PICKER_UNEXPECTED_EVENT";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
