package p000X;
/* renamed from: X.0jv  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C18860jv {
    public static String A00(int i) {
        return i != 1164 ? i != 1679 ? i != 2126 ? i != 9108 ? i != 9494 ? i != 11217 ? i != 12408 ? i != 12517 ? i != 13146 ? i != 14358 ? "UNDEFINED_QPL_EVENT" : "MESSAGING_EFFICIENCY_MQTT_CONNECT_TO_MAILBOX_SYNC" : "MESSAGING_EFFICIENCY_NETWORK_CONNECTION_LIFECYCLE" : "MESSAGING_EFFICIENCY_CHATD_CONNECT_TO_ACT_SYNC" : "MESSAGING_EFFICIENCY_DISKIO_WATCHDOG_TRACING" : "MESSAGING_EFFICIENCY_MSYS_MAILBOX_INIT_SYNC" : "MESSAGING_EFFICIENCY_E2EE_DATA_FRESH" : "MESSAGING_EFFICIENCY_MSYS_INIT_SYNC" : "MESSAGING_EFFICIENCY_MQTT_NETWORK_CONNECTION" : "MESSAGING_EFFICIENCY_MQTT_CONNECTION" : "MESSAGING_EFFICIENCY_NOTIFICATION_TO_SYNC";
    }
}
