package p000X;

import ch.boye.httpclientandroidlib.HttpStatus;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S0100000_I2;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S0400000_I2;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S0700000_I2;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S1200000_I2;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape1S0100000_I2_1;
import com.facebook.react.modules.dialog.DialogModule;
import com.facebook.react.modules.intent.IntentModule;
import com.instagram.api.schemas.ACRType;
import com.instagram.api.schemas.IGAdsStoryInteractiveMediaInfoDataDesignOptionEnum;
import com.instagram.api.schemas.IGPostTriggerExperience;
import com.instagram.api.schemas.IntentAwareAdsFormatType;
import com.instagram.api.schemas.MultiAuthorStoryType;
import com.instagram.api.schemas.RIXUChainingSourceType;
import com.instagram.api.schemas.RIXUCoverCTAPosition;
import com.instagram.api.schemas.RIXUCoverChainingType;
import com.instagram.api.schemas.RIXUCoverPreviewType;
import com.instagram.api.schemas.RIXUCoverSize;
import com.instagram.api.schemas.RIXUCtaType;
import com.instagram.api.schemas.RingSpec;
import com.instagram.api.schemas.StoryPromptTappableData;
import com.instagram.api.schemas.StoryTrendingPromptSubType;
import com.instagram.api.schemas.TrackData;
import com.instagram.common.typedurl.ImageUrl;
import com.instagram.model.mediasize.ExtendedImageUrl;
import com.instagram.model.mediasize.ImageInfo;
import com.instagram.model.reels.HighlightReelTypeStr;
import com.instagram.model.reels.ReelType;
import com.instagram.model.reels.sponsored.AutoGeneratedCardType;
import com.instagram.model.reels.sponsored.ReelCarouselType;
import com.instagram.model.venue.LocationDict;
import com.instagram.react.modules.product.IgReactMediaPickerNativeModule;
import com.instagram.sponsored.signals.model.AdsIAWRatingInfo;
import com.instagram.sponsored.signals.model.AdsRatingInfo;
import com.instagram.user.model.User;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import org.webrtc.MediaStreamTrack;
/* renamed from: X.AXh  reason: case insensitive filesystem */
/* loaded from: classes4.dex */
public final class C18968AXh {
    public static BAX parseFromJson(KJP kjp) {
        return (BAX) C150618f9.A0S(kjp, 93);
    }

    public static void A00(KJQ kjq, BAX bax) {
        kjq.A0K();
        C158748xk c158748xk = bax.A08;
        if (c158748xk != null) {
            kjq.A0V("acr_in_story");
            kjq.A0K();
            ACRType aCRType = c158748xk.A00;
            if (aCRType != null) {
                kjq.A0e("acr_collection_type", aCRType.A00);
            }
            Long l = c158748xk.A04;
            if (l != null) {
                kjq.A0d("acr_metadata_id", l.longValue());
            }
            String str = c158748xk.A07;
            if (str != null) {
                kjq.A0e("action_text", str);
            }
            String str2 = c158748xk.A08;
            if (str2 != null) {
                kjq.A0e("audio_cluster_id", str2);
            }
            String str3 = c158748xk.A09;
            if (str3 != null) {
                kjq.A0e("content_body_text", str3);
            }
            String str4 = c158748xk.A0A;
            if (str4 != null) {
                kjq.A0e("content_header_text", str4);
            }
            Long l2 = c158748xk.A05;
            if (l2 != null) {
                kjq.A0d("id", l2.longValue());
            }
            B7P b7p = c158748xk.A02;
            if (b7p != null) {
                kjq.A0V("preview_media");
                B7P.A1T(kjq, b7p);
            }
            Long l3 = c158748xk.A06;
            if (l3 != null) {
                kjq.A0d("reels_collection_id", l3.longValue());
            }
            ReelType reelType = c158748xk.A03;
            if (reelType != null) {
                kjq.A0e("reels_collection_type", reelType.A00);
            }
            List list = c158748xk.A0D;
            if (list != null) {
                Iterator A0n = C25940wr.A0n(kjq, "source_media_list", list);
                while (A0n.hasNext()) {
                    B7P A0G = C150628fA.A0G(A0n);
                    if (A0G != null) {
                        B7P.A1T(kjq, A0G);
                    }
                }
                kjq.A0G();
            }
            C150638fB.A1J(kjq, c158748xk.A0B);
            C157738w3 c157738w3 = c158748xk.A01;
            if (c157738w3 != null) {
                kjq.A0V("track_schema");
                kjq.A0K();
                C157728w2 c157728w2 = c157738w3.A01;
                kjq.A0V("metadata");
                C18907AUx.A00(kjq, c157728w2);
                TrackData trackData = c157738w3.A00;
                kjq.A0V("track");
                C18906AUw.A00(kjq, trackData);
                kjq.A0H();
            }
            String str5 = c158748xk.A0C;
            if (str5 != null) {
                kjq.A0e("tracking_token", str5);
            }
            kjq.A0H();
        }
        String str6 = bax.A1B;
        if (str6 != null) {
            kjq.A0e("actor_id", str6);
        }
        C158808xq c158808xq = bax.A0F;
        if (c158808xq != null) {
            kjq.A0V("ad4ad");
            kjq.A0K();
            kjq.A0e("action_text", c158808xq.A00);
            String str7 = c158808xq.A01;
            if (str7 != null) {
                kjq.A0e("coupon_offer_id", str7);
            }
            C150698fH.A1N(kjq, c158808xq.A02);
            kjq.A0e(DialogModule.KEY_MESSAGE, c158808xq.A03);
            kjq.A0e(DialogModule.KEY_TITLE, c158808xq.A04);
            kjq.A0e("tracking_token", c158808xq.A05);
            kjq.A0H();
        }
        Long l4 = bax.A14;
        if (l4 != null) {
            kjq.A0d("ad_expiry_timestamp_in_millis", l4.longValue());
        }
        C158918y1 c158918y1 = bax.A0N;
        if (c158918y1 != null) {
            kjq.A0V("ad_pod_rules");
            kjq.A0K();
            kjq.A0e("ad_pod_id", c158918y1.A02);
            kjq.A0c("index_in_ad_pod", c158918y1.A00);
            kjq.A0c("num_ads_in_ad_pod", c158918y1.A01);
            kjq.A0H();
        }
        AdsIAWRatingInfo adsIAWRatingInfo = bax.A0T;
        if (adsIAWRatingInfo != null) {
            kjq.A0V("ads_iaw_rating_info");
            C19061AaW.A00(kjq, adsIAWRatingInfo);
        }
        AdsRatingInfo adsRatingInfo = bax.A0U;
        if (adsRatingInfo != null) {
            kjq.A0V("ads_rating_and_review_info");
            C19062AaX.A00(kjq, adsRatingInfo);
        }
        String str8 = bax.A1C;
        if (str8 != null) {
            kjq.A0e("app_id", str8);
        }
        String str9 = bax.A1D;
        if (str9 != null) {
            kjq.A0e("archive_id", str9);
        }
        Boolean bool = bax.A0W;
        if (bool != null) {
            kjq.A0f("birthday_badge_enabled", bool.booleanValue());
        }
        C158818xr c158818xr = bax.A0G;
        if (c158818xr != null) {
            kjq.A0V("bloks_netego");
            kjq.A0K();
            kjq.A0e("bloks_app_id", c158818xr.A03);
            String str10 = c158818xr.A04;
            if (str10 != null) {
                kjq.A0e("cta_button_text", str10);
            }
            kjq.A0e("cta_style", c158818xr.A02.A00);
            kjq.A0c("duration", c158818xr.A00);
            kjq.A0f("force_isolate_cta_button", c158818xr.A08);
            C150698fH.A1N(kjq, c158818xr.A05);
            kjq.A0f("is_cta_button_enabled", c158818xr.A09);
            KtCSuperShape1S0100000_I2_1 ktCSuperShape1S0100000_I2_1 = c158818xr.A01;
            kjq.A0V("payload");
            kjq.A0K();
            C5v5 c5v5 = (C5v5) ktCSuperShape1S0100000_I2_1.A00;
            if (c5v5 != null) {
                kjq.A0V("layout");
                C5v5.A01.A01(kjq, c5v5.A00);
            }
            kjq.A0H();
            C150638fB.A1J(kjq, c158818xr.A06);
            kjq.A0e("tracking_token", c158818xr.A07);
            kjq.A0H();
        }
        String str11 = bax.A1E;
        if (str11 != null) {
            kjq.A0e("campaign_id", str11);
        }
        Boolean bool2 = bax.A0X;
        if (bool2 != null) {
            kjq.A0f("can_react_with_avatar", bool2.booleanValue());
        }
        Boolean bool3 = bax.A0Y;
        if (bool3 != null) {
            kjq.A0f("can_reply", bool3.booleanValue());
        }
        Boolean bool4 = bax.A0Z;
        if (bool4 != null) {
            kjq.A0f("can_reshare", bool4.booleanValue());
        }
        Integer num = bax.A0t;
        if (num != null) {
            kjq.A0c("carousel_opt_in_position", num.intValue());
        }
        ReelCarouselType reelCarouselType = bax.A0O;
        if (reelCarouselType != null) {
            kjq.A0e("carousel_rendering_type", reelCarouselType.A00);
        }
        List list2 = bax.A1P;
        if (list2 != null) {
            Iterator A0n2 = C25940wr.A0n(kjq, "carousel_transformation_cards_v2", list2);
            while (A0n2.hasNext()) {
                AutoGeneratedCardType autoGeneratedCardType = (AutoGeneratedCardType) A0n2.next();
                if (autoGeneratedCardType != null) {
                    kjq.A0Z(autoGeneratedCardType.A00);
                }
            }
            kjq.A0G();
        }
        C159418yy c159418yy = bax.A0S;
        if (c159418yy != null) {
            kjq.A0V("client_gap_rules");
            C19058AaT.A00(kjq, c159418yy);
        }
        Float f = bax.A0r;
        if (f != null) {
            kjq.A0b("client_prefetch_score", f.floatValue());
        }
        Boolean bool5 = bax.A0a;
        if (bool5 != null) {
            kjq.A0f("contains_stitched_media_blocked_by_rm", bool5.booleanValue());
        }
        C158888xy c158888xy = bax.A0J;
        if (c158888xy != null) {
            kjq.A0V("continue_shopping_in_story");
            C18974AXn.A00(kjq, c158888xy);
        }
        List list3 = bax.A1Q;
        if (list3 != null) {
            Iterator A0n3 = C25940wr.A0n(kjq, "cop_render_output", list3);
            while (A0n3.hasNext()) {
                C156218tb c156218tb = (C156218tb) A0n3.next();
                if (c156218tb != null) {
                    AU6.A00(kjq, c156218tb);
                }
            }
            kjq.A0G();
        }
        C158778xn c158778xn = bax.A0B;
        if (c158778xn != null) {
            kjq.A0V("cover_media");
            kjq.A0K();
            List list4 = c158778xn.A04;
            if (list4 != null) {
                Iterator A0n4 = C25940wr.A0n(kjq, "crop_rect", list4);
                while (A0n4.hasNext()) {
                    C150638fB.A1K(kjq, A0n4);
                }
                kjq.A0G();
            }
            C158768xm c158768xm = c158778xn.A00;
            kjq.A0V("cropped_image_version");
            C18967AXg.A00(kjq, c158768xm);
            C158768xm c158768xm2 = c158778xn.A01;
            if (c158768xm2 != null) {
                kjq.A0V("full_image_version");
                C18967AXg.A00(kjq, c158768xm2);
            }
            C150698fH.A1J(kjq, c158778xn.A02);
            String str12 = c158778xn.A03;
            if (str12 != null) {
                kjq.A0e("upload_id", str12);
            }
            kjq.A0H();
        }
        Long l5 = bax.A15;
        if (l5 != null) {
            kjq.A0d("created_at", l5.longValue());
        }
        List list5 = bax.A1R;
        if (list5 != null) {
            Iterator A0n5 = C25940wr.A0n(kjq, "disabled_reply_types", list5);
            while (A0n5.hasNext()) {
                C150618f9.A1P(kjq, A0n5);
            }
            kjq.A0G();
        }
        Long l6 = bax.A16;
        if (l6 != null) {
            kjq.A0d("expiring_at", l6.longValue());
        }
        String str13 = bax.A1F;
        if (str13 != null) {
            kjq.A0e("first_item_photo_url", str13);
        }
        Boolean bool6 = bax.A0b;
        if (bool6 != null) {
            kjq.A0f("has_besties_media", bool6.booleanValue());
        }
        Boolean bool7 = bax.A0c;
        if (bool7 != null) {
            kjq.A0f("has_candid_media", bool7.booleanValue());
        }
        Boolean bool8 = bax.A0d;
        if (bool8 != null) {
            kjq.A0f("has_fan_club_media", bool8.booleanValue());
        }
        Boolean bool9 = bax.A0e;
        if (bool9 != null) {
            kjq.A0f("has_pride_media", bool9.booleanValue());
        }
        Boolean bool10 = bax.A0f;
        if (bool10 != null) {
            kjq.A0f("has_video", bool10.booleanValue());
        }
        Boolean bool11 = bax.A0g;
        if (bool11 != null) {
            kjq.A0f("hide_from_feed_unit", bool11.booleanValue());
        }
        HighlightReelTypeStr highlightReelTypeStr = bax.A0A;
        if (highlightReelTypeStr != null) {
            kjq.A0e("highlight_reel_type", highlightReelTypeStr.A00);
        }
        C150618f9.A1N(kjq, bax.A1G);
        C156558u9 c156558u9 = bax.A00;
        if (c156558u9 != null) {
            kjq.A0V("ig_ads_story_interactive_media_info_data");
            kjq.A0K();
            IGAdsStoryInteractiveMediaInfoDataDesignOptionEnum iGAdsStoryInteractiveMediaInfoDataDesignOptionEnum = c156558u9.A00;
            if (iGAdsStoryInteractiveMediaInfoDataDesignOptionEnum != null) {
                kjq.A0e("interactive_media_design_option", iGAdsStoryInteractiveMediaInfoDataDesignOptionEnum.A00);
            }
            Boolean bool12 = c156558u9.A01;
            if (bool12 != null) {
                kjq.A0f("is_interactive_media_available", bool12.booleanValue());
            }
            Float f2 = c156558u9.A02;
            if (f2 != null) {
                kjq.A0b("safezone_left_and_right", f2.floatValue());
            }
            Float f3 = c156558u9.A03;
            if (f3 != null) {
                kjq.A0b("safezone_top_and_bottom", f3.floatValue());
            }
            kjq.A0H();
        }
        Long l7 = bax.A17;
        if (l7 != null) {
            kjq.A0d("imbe_megaphone_reel_id", l7.longValue());
        }
        C156618uF c156618uF = bax.A01;
        if (c156618uF != null) {
            kjq.A0V("intent_aware_ads_info");
            kjq.A0K();
            C156608uE c156608uE = c156618uF.A00;
            if (c156608uE != null) {
                kjq.A0V("format_info");
                kjq.A0K();
                IntentAwareAdsFormatType intentAwareAdsFormatType = c156608uE.A00;
                if (intentAwareAdsFormatType != null) {
                    kjq.A0e("format", intentAwareAdsFormatType.A00);
                }
                C150638fB.A1J(kjq, c156608uE.A01);
                kjq.A0H();
            }
            String str14 = c156618uF.A04;
            if (str14 != null) {
                kjq.A0e("insertion_mechanism", str14);
            }
            Boolean bool13 = c156618uF.A01;
            if (bool13 != null) {
                kjq.A0f("is_seed_ad_eligible", bool13.booleanValue());
            }
            String str15 = c156618uF.A05;
            if (str15 != null) {
                kjq.A0e("multi_ads_first_ad_id", str15);
            }
            Integer num2 = c156618uF.A02;
            if (num2 != null) {
                kjq.A0c("multi_ads_type", num2.intValue());
            }
            String str16 = c156618uF.A06;
            if (str16 != null) {
                kjq.A0e("multi_ads_unit_id", str16);
            }
            String str17 = c156618uF.A07;
            if (str17 != null) {
                kjq.A0e("seed_ad_id", str17);
            }
            Integer num3 = c156618uF.A03;
            if (num3 != null) {
                kjq.A0c("seed_ad_position", num3.intValue());
            }
            String str18 = c156618uF.A08;
            if (str18 != null) {
                kjq.A0e("seed_ad_token", str18);
            }
            String str19 = c156618uF.A09;
            if (str19 != null) {
                kjq.A0e("trigger_type", str19);
            }
            kjq.A0H();
        }
        String str20 = bax.A1H;
        if (str20 != null) {
            kjq.A0e("interaction_timestamp", str20);
        }
        C159178yW c159178yW = bax.A0P;
        if (c159178yW != null) {
            kjq.A0V("invalidation_rules");
            AYD.A00(kjq, c159178yW);
        }
        Boolean bool14 = bax.A0h;
        if (bool14 != null) {
            kjq.A0f("is_ads_sensitive", bool14.booleanValue());
        }
        Boolean bool15 = bax.A0i;
        if (bool15 != null) {
            kjq.A0f("is_cacheable", bool15.booleanValue());
        }
        Boolean bool16 = bax.A0j;
        if (bool16 != null) {
            kjq.A0f("is_converted_to_clips", bool16.booleanValue());
        }
        Boolean bool17 = bax.A0k;
        if (bool17 != null) {
            kjq.A0f("is_cta_sticker_available", bool17.booleanValue());
        }
        Boolean bool18 = bax.A0l;
        if (bool18 != null) {
            kjq.A0f("is_fb_post_from_fb_story", bool18.booleanValue());
        }
        Boolean bool19 = bax.A0m;
        if (bool19 != null) {
            kjq.A0f("is_nux", bool19.booleanValue());
        }
        Boolean bool20 = bax.A0n;
        if (bool20 != null) {
            kjq.A0f("is_pinned_highlight", bool20.booleanValue());
        }
        List list6 = bax.A1S;
        if (list6 != null) {
            Iterator A0n6 = C25940wr.A0n(kjq, DialogModule.KEY_ITEMS, list6);
            while (A0n6.hasNext()) {
                B7P A0G2 = C150628fA.A0G(A0n6);
                if (A0G2 != null) {
                    B7P.A1T(kjq, A0G2);
                }
            }
            kjq.A0G();
        }
        Float f4 = bax.A0s;
        if (f4 != null) {
            kjq.A0b(C34900Hva.A00(145), f4.floatValue());
        }
        Long l8 = bax.A18;
        if (l8 != null) {
            kjq.A0d(C34900Hva.A00(58), l8.longValue());
        }
        Integer num4 = bax.A0u;
        if (num4 != null) {
            kjq.A0c("media_count", num4.intValue());
        }
        List list7 = bax.A1T;
        if (list7 != null) {
            Iterator A0n7 = C25940wr.A0n(kjq, "media_ids", list7);
            while (A0n7.hasNext()) {
                C150618f9.A1P(kjq, A0n7);
            }
            kjq.A0G();
        }
        C158548xO c158548xO = bax.A07;
        if (c158548xO != null) {
            kjq.A0V("media_preview");
            kjq.A0K();
            C150698fH.A1N(kjq, c158548xO.A02);
            ImageInfo imageInfo = c158548xO.A01;
            kjq.A0V("image_versions2");
            C18963AXc.A00(kjq, imageInfo);
            kjq.A0c("media_type", c158548xO.A00);
            String str21 = c158548xO.A03;
            if (str21 != null) {
                kjq.A0e("preview", str21);
            }
            kjq.A0H();
        }
        Boolean bool21 = bax.A0o;
        if (bool21 != null) {
            kjq.A0f("muted", bool21.booleanValue());
        }
        B7P b7p2 = bax.A05;
        if (b7p2 != null) {
            kjq.A0V("netego_background_media");
            B7P.A1T(kjq, b7p2);
        }
        String str22 = bax.A1I;
        if (str22 != null) {
            kjq.A0e("netego_type", str22);
        }
        Integer num5 = bax.A0v;
        if (num5 != null) {
            kjq.A0c("next_button_index", num5.intValue());
        }
        C158908y0 c158908y0 = bax.A0M;
        if (c158908y0 != null) {
            kjq.A0V("owner");
            kjq.A0K();
            String str23 = c158908y0.A05;
            if (str23 != null) {
                kjq.A0e("challenge_id", str23);
            }
            Float f5 = c158908y0.A03;
            if (f5 != null) {
                kjq.A0b("lat", f5.floatValue());
            }
            Float f6 = c158908y0.A04;
            if (f6 != null) {
                kjq.A0b("lng", f6.floatValue());
            }
            LocationDict locationDict = c158908y0.A02;
            if (locationDict != null) {
                kjq.A0V("location_dict");
                AYJ.A00(kjq, locationDict);
            }
            C150668fE.A15(kjq, c158908y0.A06);
            kjq.A0e("pk", c158908y0.A07);
            ImageUrl imageUrl = c158908y0.A01;
            if (imageUrl != null) {
                kjq.A0V("profile_pic_url");
                C3O4.A01(kjq, imageUrl);
            }
            String str24 = c158908y0.A08;
            if (str24 != null) {
                kjq.A0e("profile_pic_username", str24);
            }
            String str25 = c158908y0.A09;
            if (str25 != null) {
                kjq.A0e("short_name", str25);
            }
            MultiAuthorStoryType multiAuthorStoryType = c158908y0.A00;
            if (multiAuthorStoryType != null) {
                C150688fG.A1O(kjq, multiAuthorStoryType.A00);
            }
            kjq.A0H();
        }
        String str26 = bax.A1J;
        if (str26 != null) {
            kjq.A0e("page_id", str26);
        }
        List list8 = bax.A1U;
        if (list8 != null) {
            Iterator A0n8 = C25940wr.A0n(kjq, "post_trigger_experience_eligibilities", list8);
            while (A0n8.hasNext()) {
                IGPostTriggerExperience iGPostTriggerExperience = (IGPostTriggerExperience) A0n8.next();
                if (iGPostTriggerExperience != null) {
                    kjq.A0Z(iGPostTriggerExperience.A00);
                }
            }
            kjq.A0G();
        }
        Integer num6 = bax.A0w;
        if (num6 != null) {
            kjq.A0c("prefetch_count", num6.intValue());
        }
        B7P b7p3 = bax.A06;
        if (b7p3 != null) {
            kjq.A0V("prefetch_media_item");
            B7P.A1T(kjq, b7p3);
        }
        Integer num7 = bax.A0x;
        if (num7 != null) {
            kjq.A0c("priority_index", num7.intValue());
        }
        Long l9 = bax.A19;
        if (l9 != null) {
            kjq.A0d("promotion_id", l9.longValue());
        }
        Integer num8 = bax.A0y;
        if (num8 != null) {
            kjq.A0c("ranked_position", num8.intValue());
        }
        C158788xo c158788xo = bax.A0C;
        if (c158788xo != null) {
            kjq.A0V("ranker_scores");
            kjq.A0K();
            Double d = c158788xo.A00;
            if (d != null) {
                kjq.A0a("fp", d.doubleValue());
            }
            Double d2 = c158788xo.A01;
            if (d2 != null) {
                kjq.A0a("ptap", d2.doubleValue());
            }
            Double d3 = c158788xo.A02;
            if (d3 != null) {
                kjq.A0a("vm", d3.doubleValue());
            }
            kjq.A0H();
        }
        C158888xy c158888xy2 = bax.A0K;
        if (c158888xy2 != null) {
            kjq.A0V("reconsideration_injected_story");
            C18974AXn.A00(kjq, c158888xy2);
        }
        C158888xy c158888xy3 = bax.A0L;
        if (c158888xy3 != null) {
            kjq.A0V("reconsideration_products_for_you_in_story");
            C18974AXn.A00(kjq, c158888xy3);
        }
        C158798xp c158798xp = bax.A0D;
        if (c158798xp != null) {
            kjq.A0V("reel_toast");
            kjq.A0K();
            ImageUrl imageUrl2 = c158798xp.A00;
            if (imageUrl2 != null) {
                kjq.A0V("image_url");
                C3O4.A01(kjq, imageUrl2);
            }
            C150698fH.A1M(kjq, c158798xp.A01);
        }
        ReelType reelType2 = bax.A0E;
        if (reelType2 != null) {
            kjq.A0e("reel_type", reelType2.A00);
        }
        C158758xl c158758xl = bax.A09;
        if (c158758xl != null) {
            kjq.A0V("research_survey");
            kjq.A0K();
            String str27 = c158758xl.A04;
            if (str27 != null) {
                kjq.A0e("ad_id", str27);
            }
            Boolean bool22 = c158758xl.A01;
            if (bool22 != null) {
                kjq.A0f("is_demo", bool22.booleanValue());
            }
            C5Li c5Li = c158758xl.A00;
            if (c5Li != null) {
                kjq.A0V("learn_more");
                kjq.A0K();
                kjq.A0e("body", c5Li.A01);
                C96235Lh c96235Lh = c5Li.A00;
                if (c96235Lh != null) {
                    kjq.A0V("call_to_action");
                    kjq.A0K();
                    kjq.A0e(DialogModule.KEY_TITLE, c96235Lh.A00);
                    kjq.A0e("url", c96235Lh.A01);
                    kjq.A0H();
                }
                kjq.A0e(DialogModule.KEY_TITLE, c5Li.A02);
                kjq.A0H();
            }
            String str28 = c158758xl.A05;
            if (str28 != null) {
                kjq.A0e(AnonymousClass000.A00(361), str28);
            }
            List list9 = c158758xl.A09;
            if (list9 != null) {
                Iterator A0n9 = C25940wr.A0n(kjq, "questions", list9);
                while (A0n9.hasNext()) {
                    C96245Lj c96245Lj = (C96245Lj) A0n9.next();
                    if (c96245Lj != null) {
                        kjq.A0K();
                        List list10 = c96245Lj.A04;
                        if (list10 != null) {
                            Iterator A0n10 = C25940wr.A0n(kjq, "answers", list10);
                            while (A0n10.hasNext()) {
                                C96225Lg c96225Lg = (C96225Lg) A0n10.next();
                                if (c96225Lg != null) {
                                    kjq.A0K();
                                    Integer num9 = c96225Lg.A00;
                                    if (num9 != null) {
                                        kjq.A0c(AnonymousClass000.A00(353), num9.intValue());
                                    }
                                    kjq.A0e("text", c96225Lg.A01);
                                    kjq.A0e(IntentModule.EXTRA_MAP_KEY_FOR_VALUE, c96225Lg.A02);
                                    kjq.A0H();
                                }
                            }
                            kjq.A0G();
                        }
                        kjq.A0e("qid", c96245Lj.A01);
                        kjq.A0e(DialogModule.KEY_TITLE, c96245Lj.A02);
                        Integer num10 = c96245Lj.A00;
                        if (num10 != null) {
                            kjq.A0c(AnonymousClass000.A00(HttpStatus.SC_PAYMENT_REQUIRED), num10.intValue());
                        }
                        C150688fG.A1O(kjq, c96245Lj.A03);
                        kjq.A0H();
                    }
                }
                kjq.A0G();
            }
            Boolean bool23 = c158758xl.A02;
            if (bool23 != null) {
                kjq.A0f("show_primer", bool23.booleanValue());
            }
            Boolean bool24 = c158758xl.A03;
            if (bool24 != null) {
                kjq.A0f(AnonymousClass000.A00(387), bool24.booleanValue());
            }
            kjq.A0e("survey_id", c158758xl.A06);
            kjq.A0e("survey_type", c158758xl.A07);
            String str29 = c158758xl.A08;
            if (str29 != null) {
                kjq.A0e("tracking_token", str29);
            }
            kjq.A0H();
        }
        C159348yo c159348yo = bax.A0R;
        if (c159348yo != null) {
            kjq.A0V("ring_glyph");
            AZ3.A00(kjq, c159348yo, true);
        }
        RingSpec ringSpec = bax.A03;
        if (ringSpec != null) {
            kjq.A0V("ring_spec");
            C18885AUb.A00(kjq, ringSpec);
        }
        Integer num11 = bax.A0z;
        if (num11 != null) {
            kjq.A0c("seen", num11.intValue());
        }
        List list11 = bax.A1V;
        if (list11 != null) {
            Iterator A0n11 = C25940wr.A0n(kjq, AnonymousClass000.A00(33), list11);
            while (A0n11.hasNext()) {
                C150618f9.A1P(kjq, A0n11);
            }
            kjq.A0G();
        }
        Integer num12 = bax.A10;
        if (num12 != null) {
            kjq.A0c("seen_ranked_position", num12.intValue());
        }
        Boolean bool25 = bax.A0p;
        if (bool25 != null) {
            kjq.A0f("should_treat_link_sticker_as_cta", bool25.booleanValue());
        }
        Boolean bool26 = bax.A0q;
        if (bool26 != null) {
            kjq.A0f("show_nux_tooltip", bool26.booleanValue());
        }
        C159198yZ c159198yZ = bax.A0Q;
        if (c159198yZ != null) {
            kjq.A0V("simple_action");
            AYT.A00(kjq, c159198yZ);
        }
        String str30 = bax.A1K;
        if (str30 != null) {
            kjq.A0e("smart_reel_type", str30);
        }
        String str31 = bax.A1L;
        if (str31 != null) {
            kjq.A0e("social_context", str31);
        }
        String str32 = bax.A1M;
        if (str32 != null) {
            kjq.A0e("source_token", str32);
        }
        Integer num13 = bax.A11;
        if (num13 != null) {
            kjq.A0c("story_duration_secs", num13.intValue());
        }
        Integer num14 = bax.A12;
        if (num14 != null) {
            kjq.A0c("story_wedge_size", num14.intValue());
        }
        String str33 = bax.A1N;
        if (str33 != null) {
            kjq.A0e("strong_id__", str33);
        }
        C158328x1 c158328x1 = bax.A0I;
        if (c158328x1 != null) {
            kjq.A0V("suggested_clips_story_netego");
            kjq.A0K();
            C150618f9.A1N(kjq, c158328x1.A09);
            Integer num15 = c158328x1.A07;
            if (num15 != null) {
                kjq.A0c("netego_subtype", num15.intValue());
            }
            Integer num16 = c158328x1.A06;
            if (num16 != null) {
                kjq.A0c("duration", num16.intValue());
            }
            C150638fB.A1J(kjq, c158328x1.A0D);
            String str34 = c158328x1.A0C;
            if (str34 != null) {
                kjq.A0e("action_text", str34);
            }
            String str35 = c158328x1.A0E;
            if (str35 != null) {
                kjq.A0e("tracking_token", str35);
            }
            Integer num17 = c158328x1.A08;
            if (num17 != null) {
                kjq.A0c("type", num17.intValue());
            }
            kjq.A0e("play_type", c158328x1.A05.A00);
            String str36 = c158328x1.A0A;
            if (str36 != null) {
                kjq.A0e("contextual_type", str36);
            }
            String str37 = c158328x1.A0B;
            if (str37 != null) {
                kjq.A0e("contextual_type_text", str37);
            }
            kjq.A0f("play_preview_only_with_wifi", c158328x1.A0H);
            kjq.A0V("clips");
            kjq.A0J();
            for (C745741a c745741a : c158328x1.A0F) {
                if (c745741a != null) {
                    C3XR.A00(kjq, c745741a);
                }
            }
            kjq.A0G();
            kjq.A0f(MediaStreamTrack.AUDIO_TRACK_KIND, c158328x1.A0G);
            RIXUCoverSize rIXUCoverSize = c158328x1.A03;
            if (rIXUCoverSize != null) {
                kjq.A0e("layout_cover_size", rIXUCoverSize.A00);
            }
            RIXUCtaType rIXUCtaType = c158328x1.A04;
            if (rIXUCtaType != null) {
                kjq.A0e("cta_type", rIXUCtaType.A00);
            }
            if (c158328x1.A00 != null) {
                kjq.A0V("cover_definition");
                KtCSuperShape0S0400000_I2 ktCSuperShape0S0400000_I2 = c158328x1.A00;
                kjq.A0K();
                KtCSuperShape0S0400000_I2 ktCSuperShape0S0400000_I22 = (KtCSuperShape0S0400000_I2) ktCSuperShape0S0400000_I2.A00;
                if (ktCSuperShape0S0400000_I22 != null) {
                    kjq.A0V("elements");
                    kjq.A0K();
                    KtCSuperShape0S0100000_I2 ktCSuperShape0S0100000_I2 = (KtCSuperShape0S0100000_I2) ktCSuperShape0S0400000_I22.A00;
                    if (ktCSuperShape0S0100000_I2 != null) {
                        kjq.A0V("bottom_left");
                        AUZ.A00(ktCSuperShape0S0100000_I2, kjq);
                    }
                    KtCSuperShape0S0100000_I2 ktCSuperShape0S0100000_I22 = (KtCSuperShape0S0100000_I2) ktCSuperShape0S0400000_I22.A01;
                    if (ktCSuperShape0S0100000_I22 != null) {
                        kjq.A0V("bottom_right");
                        AUZ.A00(ktCSuperShape0S0100000_I22, kjq);
                    }
                    KtCSuperShape0S0100000_I2 ktCSuperShape0S0100000_I23 = (KtCSuperShape0S0100000_I2) ktCSuperShape0S0400000_I22.A02;
                    if (ktCSuperShape0S0100000_I23 != null) {
                        kjq.A0V("top_left");
                        AUZ.A00(ktCSuperShape0S0100000_I23, kjq);
                    }
                    KtCSuperShape0S0100000_I2 ktCSuperShape0S0100000_I24 = (KtCSuperShape0S0100000_I2) ktCSuperShape0S0400000_I22.A03;
                    if (ktCSuperShape0S0100000_I24 != null) {
                        kjq.A0V("top_right");
                        AUZ.A00(ktCSuperShape0S0100000_I24, kjq);
                    }
                    kjq.A0H();
                }
                Number number = (Number) ktCSuperShape0S0400000_I2.A01;
                if (number != null) {
                    kjq.A0c("preview_length_in_sec", number.intValue());
                }
                Number number2 = (Number) ktCSuperShape0S0400000_I2.A02;
                if (number2 != null) {
                    kjq.A0c("preview_stagger_in_sec", number2.intValue());
                }
                RIXUCoverPreviewType rIXUCoverPreviewType = (RIXUCoverPreviewType) ktCSuperShape0S0400000_I2.A03;
                if (rIXUCoverPreviewType != null) {
                    kjq.A0e("preview_type", rIXUCoverPreviewType.A00);
                }
                kjq.A0H();
            }
            if (c158328x1.A01 != null) {
                kjq.A0V("chaining_behavior_definition");
                KtCSuperShape0S0700000_I2 ktCSuperShape0S0700000_I2 = c158328x1.A01;
                kjq.A0K();
                RIXUCoverChainingType rIXUCoverChainingType = (RIXUCoverChainingType) ktCSuperShape0S0700000_I2.A00;
                if (rIXUCoverChainingType != null) {
                    kjq.A0e("chaining_type", rIXUCoverChainingType.A00);
                }
                RIXUChainingSourceType rIXUChainingSourceType = (RIXUChainingSourceType) ktCSuperShape0S0700000_I2.A01;
                if (rIXUChainingSourceType != null) {
                    kjq.A0e("contextual_path", rIXUChainingSourceType.A00);
                }
                Boolean bool27 = (Boolean) ktCSuperShape0S0700000_I2.A02;
                if (bool27 != null) {
                    kjq.A0f("disable_android_flash_cache_read", bool27.booleanValue());
                }
                Boolean bool28 = (Boolean) ktCSuperShape0S0700000_I2.A03;
                if (bool28 != null) {
                    kjq.A0f("disable_ios_shared_cache", bool28.booleanValue());
                }
                Boolean bool29 = (Boolean) ktCSuperShape0S0700000_I2.A04;
                if (bool29 != null) {
                    kjq.A0f("enable_prefetch", bool29.booleanValue());
                }
                List list12 = (List) ktCSuperShape0S0700000_I2.A05;
                if (list12 != null) {
                    Iterator A0n12 = C25940wr.A0n(kjq, "injected_clips", list12);
                    while (A0n12.hasNext()) {
                        C745741a c745741a2 = (C745741a) A0n12.next();
                        if (c745741a2 != null) {
                            C3XR.A00(kjq, c745741a2);
                        }
                    }
                    kjq.A0G();
                }
                Number number3 = (Number) ktCSuperShape0S0700000_I2.A06;
                if (number3 != null) {
                    kjq.A0c("prefetch_page_size", number3.intValue());
                }
                kjq.A0H();
            }
            if (c158328x1.A02 != null) {
                kjq.A0V("additional_cover_cta");
                KtCSuperShape0S1200000_I2 ktCSuperShape0S1200000_I2 = c158328x1.A02;
                kjq.A0K();
                RIXUCtaType rIXUCtaType2 = (RIXUCtaType) ktCSuperShape0S1200000_I2.A00;
                if (rIXUCtaType2 != null) {
                    kjq.A0e("cta_type", rIXUCtaType2.A00);
                }
                RIXUCoverCTAPosition rIXUCoverCTAPosition = (RIXUCoverCTAPosition) ktCSuperShape0S1200000_I2.A01;
                if (rIXUCoverCTAPosition != null) {
                    kjq.A0e("position_type", rIXUCoverCTAPosition.A00);
                }
                C150658fD.A1O(kjq, ktCSuperShape0S1200000_I2.A02);
                kjq.A0H();
            }
            kjq.A0H();
        }
        C158878xx c158878xx = bax.A0H;
        if (c158878xx != null) {
            kjq.A0V("suggested_users");
            kjq.A0K();
            kjq.A0e("action_text", c158878xx.A03);
            kjq.A0c("duration", c158878xx.A00);
            kjq.A0f("dynamic_width_enabled", c158878xx.A08);
            kjq.A0f("gradient_animation_enabled", c158878xx.A09);
            kjq.A0d("id", c158878xx.A01);
            kjq.A0f("is_unit_dismissable", c158878xx.A0A);
            kjq.A0f("large_profile_pictures_enabled", c158878xx.A0B);
            kjq.A0f("load_animation_enabled", c158878xx.A0C);
            kjq.A0f("multiple_gradients_enabled", c158878xx.A0D);
            kjq.A0e("netego_type", c158878xx.A02.A00);
            kjq.A0f("no_follow_confirmation", c158878xx.A0E);
            kjq.A0e("ranking_algorithm", c158878xx.A04);
            kjq.A0f("shuffle_enabled", c158878xx.A0F);
            kjq.A0f("smaller_follow_tap_target_enabled", c158878xx.A0G);
            Iterator A0n13 = C25940wr.A0n(kjq, "suggestions", c158878xx.A07);
            while (A0n13.hasNext()) {
                C158898xz c158898xz = (C158898xz) A0n13.next();
                if (c158898xz != null) {
                    kjq.A0K();
                    kjq.A0e("algorithm", c158898xz.A09);
                    String str38 = c158898xz.A0A;
                    if (str38 != null) {
                        kjq.A0e(C25910wo.A00(120), str38);
                    }
                    String str39 = c158898xz.A0B;
                    if (str39 != null) {
                        kjq.A0e("caption", str39);
                    }
                    C1BT c1bt = c158898xz.A01;
                    if (c1bt != null) {
                        kjq.A0V(C25910wo.A00(140));
                        kjq.A0K();
                        kjq.A0c(IgReactMediaPickerNativeModule.HEIGHT, c1bt.A00);
                        kjq.A0e("url", c1bt.A02);
                        kjq.A0c(IgReactMediaPickerNativeModule.WIDTH, c1bt.A01);
                        kjq.A0H();
                    }
                    Boolean bool30 = c158898xz.A03;
                    if (bool30 != null) {
                        kjq.A0f("followed_by", bool30.booleanValue());
                    }
                    Boolean bool31 = c158898xz.A04;
                    if (bool31 != null) {
                        kjq.A0f("has_stories", bool31.booleanValue());
                    }
                    String str40 = c158898xz.A0C;
                    if (str40 != null) {
                        kjq.A0e("icon", str40);
                    }
                    Boolean bool32 = c158898xz.A05;
                    if (bool32 != null) {
                        kjq.A0f(C25910wo.A00(385), bool32.booleanValue());
                    }
                    List list13 = c158898xz.A0G;
                    if (list13 != null) {
                        Iterator A0n14 = C25940wr.A0n(kjq, "large_urls", list13);
                        while (A0n14.hasNext()) {
                            C150618f9.A1P(kjq, A0n14);
                        }
                        kjq.A0G();
                    }
                    Integer num18 = c158898xz.A08;
                    if (num18 != null) {
                        kjq.A0c("media_count", num18.intValue());
                    }
                    List list14 = c158898xz.A0H;
                    if (list14 != null) {
                        Iterator A0n15 = C25940wr.A0n(kjq, "media_ids", list14);
                        while (A0n15.hasNext()) {
                            C150618f9.A1P(kjq, A0n15);
                        }
                        kjq.A0G();
                    }
                    List list15 = c158898xz.A0I;
                    if (list15 != null) {
                        Iterator A0n16 = C25940wr.A0n(kjq, "media_infos", list15);
                        while (A0n16.hasNext()) {
                            C150618f9.A1P(kjq, A0n16);
                        }
                        kjq.A0G();
                    }
                    C1AW c1aw = c158898xz.A00;
                    if (c1aw != null) {
                        kjq.A0V("preview_media");
                        kjq.A0K();
                        List list16 = c1aw.A01;
                        if (list16 != null) {
                            Iterator A0n17 = C25940wr.A0n(kjq, "posts", list16);
                            while (A0n17.hasNext()) {
                                B7P A0G3 = C150628fA.A0G(A0n17);
                                if (A0G3 != null) {
                                    B7P.A1T(kjq, A0G3);
                                }
                            }
                            kjq.A0G();
                        }
                        C150648fC.A12(kjq, c1aw.A00);
                        kjq.A0H();
                    }
                    Float f7 = c158898xz.A06;
                    if (f7 != null) {
                        kjq.A0b("score", f7.floatValue());
                    }
                    kjq.A0e("social_context", c158898xz.A0D);
                    List list17 = c158898xz.A0J;
                    if (list17 != null) {
                        Iterator A0n18 = C25940wr.A0n(kjq, "social_context_facepile_users", list17);
                        while (A0n18.hasNext()) {
                            C150628fA.A1T(kjq, A0n18);
                        }
                        kjq.A0G();
                    }
                    List list18 = c158898xz.A0K;
                    if (list18 != null) {
                        Iterator A0n19 = C25940wr.A0n(kjq, C25910wo.A00(1423), list18);
                        while (A0n19.hasNext()) {
                            C150618f9.A1P(kjq, A0n19);
                        }
                        kjq.A0G();
                    }
                    User user = c158898xz.A02;
                    kjq.A0V("user");
                    C19651AkM.A04(kjq, user);
                    HashMap hashMap = c158898xz.A0F;
                    if (hashMap != null) {
                        Iterator A0h = C150618f9.A0h(kjq, "user_story", hashMap);
                        while (A0h.hasNext()) {
                            C150618f9.A1O(kjq, A0h);
                        }
                        kjq.A0H();
                    }
                    String str41 = c158898xz.A0E;
                    if (str41 != null) {
                        kjq.A0e("uuid", str41);
                    }
                    Float f8 = c158898xz.A07;
                    if (f8 != null) {
                        kjq.A0b(IntentModule.EXTRA_MAP_KEY_FOR_VALUE, f8.floatValue());
                    }
                    kjq.A0H();
                }
            }
            kjq.A0G();
            kjq.A0e(DialogModule.KEY_TITLE, c158878xx.A05);
            kjq.A0e("tracking_token", c158878xx.A06);
            kjq.A0H();
        }
        C7jU c7jU = bax.A04;
        if (c7jU != null) {
            kjq.A0V("superlative_data");
            kjq.A0K();
            List list19 = c7jU.A00;
            if (list19 != null) {
                Iterator A0n20 = C25940wr.A0n(kjq, AnonymousClass000.A00(924), list19);
                while (A0n20.hasNext()) {
                    C5KV c5kv = (C5KV) A0n20.next();
                    if (c5kv != null) {
                        kjq.A0K();
                        List list20 = c5kv.A02;
                        if (list20 != null) {
                            Iterator A0n21 = C25940wr.A0n(kjq, AnonymousClass000.A00(842), list20);
                            while (A0n21.hasNext()) {
                                C5KW c5kw = (C5KW) A0n21.next();
                                if (c5kw != null) {
                                    C122586vW.A00(kjq, c5kw);
                                }
                            }
                            kjq.A0G();
                        }
                        kjq.A0e("template_id", c5kv.A01);
                        C5KW c5kw2 = c5kv.A00;
                        if (c5kw2 != null) {
                            kjq.A0V(AnonymousClass000.A00(943));
                            C122586vW.A00(kjq, c5kw2);
                        }
                        kjq.A0H();
                    }
                }
                kjq.A0G();
            }
            kjq.A0H();
        }
        C150638fB.A1J(kjq, bax.A1O);
        C156948um c156948um = bax.A02;
        if (c156948um != null) {
            kjq.A0V("trending_prompts_in_story");
            kjq.A0K();
            String str42 = c156948um.A04;
            if (str42 != null) {
                kjq.A0e("action_text", str42);
            }
            String str43 = c156948um.A05;
            if (str43 != null) {
                kjq.A0e("cursor", str43);
            }
            Long l10 = c156948um.A02;
            if (l10 != null) {
                kjq.A0d("id", l10.longValue());
            }
            Boolean bool33 = c156948um.A00;
            if (bool33 != null) {
                kjq.A0f("is_shuffle", bool33.booleanValue());
            }
            Boolean bool34 = c156948um.A01;
            if (bool34 != null) {
                kjq.A0f("is_unit_dismissable", bool34.booleanValue());
            }
            String str44 = c156948um.A06;
            if (str44 != null) {
                kjq.A0e("netego_title", str44);
            }
            String str45 = c156948um.A07;
            if (str45 != null) {
                kjq.A0e("netego_type", str45);
            }
            String str46 = c156948um.A08;
            if (str46 != null) {
                kjq.A0e("tracking_token", str46);
            }
            List list21 = c156948um.A09;
            if (list21 != null) {
                Iterator A0n22 = C25940wr.A0n(kjq, "trending_prompts", list21);
                while (A0n22.hasNext()) {
                    C157588vo c157588vo = (C157588vo) A0n22.next();
                    if (c157588vo != null) {
                        kjq.A0K();
                        C157598vp c157598vp = c157588vo.A01;
                        if (c157598vp != null) {
                            kjq.A0V("logging_info");
                            kjq.A0K();
                            Iterator A0n23 = C25940wr.A0n(kjq, "media_logging_infos", c157598vp.A01);
                            while (A0n23.hasNext()) {
                                C157608vq c157608vq = (C157608vq) A0n23.next();
                                if (c157608vq != null) {
                                    kjq.A0K();
                                    kjq.A0e("media_id", c157608vq.A01);
                                    kjq.A0e("media_subtype", c157608vq.A00.A00);
                                    kjq.A0H();
                                }
                            }
                            kjq.A0G();
                            StoryTrendingPromptSubType storyTrendingPromptSubType = c157598vp.A00;
                            if (storyTrendingPromptSubType != null) {
                                kjq.A0e("prompt_subtype", storyTrendingPromptSubType.A00);
                            }
                            kjq.A0H();
                        }
                        Iterator A0n24 = C25940wr.A0n(kjq, "media_infos", c157588vo.A02);
                        while (A0n24.hasNext()) {
                            B7P A0G4 = C150628fA.A0G(A0n24);
                            if (A0G4 != null) {
                                B7P.A1T(kjq, A0G4);
                            }
                        }
                        kjq.A0G();
                        StoryPromptTappableData storyPromptTappableData = c157588vo.A00;
                        kjq.A0V("prompt_sticker");
                        C18896AUm.A00(kjq, storyPromptTappableData);
                        Iterator A0n25 = C25940wr.A0n(kjq, "reel_pks", c157588vo.A03);
                        while (A0n25.hasNext()) {
                            C150618f9.A1P(kjq, A0n25);
                        }
                        kjq.A0G();
                        kjq.A0H();
                    }
                }
                kjq.A0G();
            }
            Long l11 = c156948um.A03;
            if (l11 != null) {
                kjq.A0d("type", l11.longValue());
            }
            kjq.A0H();
        }
        Long l12 = bax.A1A;
        if (l12 != null) {
            kjq.A0d("unique_integer_reel_id", l12.longValue());
        }
        C150648fC.A12(kjq, bax.A0V);
        List list22 = bax.A1W;
        if (list22 != null) {
            Iterator A0n26 = C25940wr.A0n(kjq, "video_to_carousel_cut_secs", list22);
            while (A0n26.hasNext()) {
                C150638fB.A1K(kjq, A0n26);
            }
            kjq.A0G();
        }
        List list23 = bax.A1X;
        if (list23 != null) {
            Iterator A0n27 = C25940wr.A0n(kjq, "video_to_carousel_cut_thumbnails", list23);
            while (A0n27.hasNext()) {
                ExtendedImageUrl extendedImageUrl = (ExtendedImageUrl) A0n27.next();
                if (extendedImageUrl != null) {
                    C18962AXb.A00(kjq, extendedImageUrl);
                }
            }
            kjq.A0G();
        }
        Integer num19 = bax.A13;
        if (num19 != null) {
            kjq.A0c("viewer_prefetch_count", num19.intValue());
        }
        kjq.A0H();
    }
}
