package p000X;
/* renamed from: X.0kE  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C19050kE {
    public static String A00(int i) {
        switch (i) {
            case 1048:
                return "MESSENGER_DESKTOP_SEND_MESSAGE_E2E";
            case 1187:
                return "MESSENGER_DESKTOP_MQTT_RTSTREAMTRANSPORT_LIFECYCLE";
            case 1294:
                return "MESSENGER_DESKTOP_SEND_MESSAGE_LEGACY";
            case 1314:
                return "MESSENGER_DESKTOP_LOGIN_TO_RTC_READY";
            case 1476:
                return "MESSENGER_DESKTOP_LOWER_RAISED_HAND_IMPRESSION";
            case 1612:
                return "MESSENGER_DESKTOP_COMPOSER_TYPING_LATENCY";
            case 1687:
                return "MESSENGER_DESKTOP_REDUX_DISPATCH";
            case 1945:
                return "MESSENGER_DESKTOP_CREATE_MESSENGER_WINDOW";
            case 2008:
                return "MESSENGER_DESKTOP_APP_START_TO_SYNC_COMPLETED";
            case 2067:
                return "MESSENGER_DESKTOP_RTC_REMOVE_PARTICIPANT";
            case 2091:
                return "MESSENGER_DESKTOP_ARMADILLO_LOAD_MESSAGES_FROM_ECHO_START";
            case 2151:
                return "MESSENGER_DESKTOP_LOGIN_TO_CHAT_READY";
            case 2305:
                return "MESSENGER_DESKTOP_ROOMS_INCOMING_DIALOG_START_TO_READY";
            case 2434:
                return "MESSENGER_DESKTOP_MOUNT_MESSAGES_LIST_CONTENT_ITEM";
            case 3387:
                return "MESSENGER_DESKTOP_RTC_JOIN_ROOM";
            case 3648:
                return "MESSENGER_DESKTOP_CREATE_COMMUNITY_CHAT";
            case 3757:
                return "MESSENGER_DESKTOP_RTC_PUSH_NOTIF_TO_INCOMING_CALL_DIALOG";
            case 3774:
                return "MESSENGER_DESKTOP_LOAD_COMMUNITY_THREADS";
            case 4202:
                return "MESSENGER_DESKTOP_RTC_VIEW_CALL_PARTICIPANTS";
            case 4305:
                return "MESSENGER_DESKTOP_RTC_START_CALL_TO_END_CALL";
            case 4313:
                return "MESSENGER_DESKTOP_GET_PROMOTIONS_FOR_USER";
            case 4448:
                return "MESSENGER_DESKTOP_CHANGE_JOIN_PERMISSION";
            case 4493:
                return "MESSENGER_DESKTOP_RN_EXCEPTION_HANDLER";
            case 5211:
                return "MESSENGER_DESKTOP_WARM_START_TO_WINDOW_OPEN";
            case 5337:
                return "MESSENGER_DESKTOP_REMOTE_PARTICIPANT_JOIN";
            case 5499:
                return "MESSENGER_DESKTOP_OSMETA_MESSENGER_UPGRADE_COMPLETED_TO_RTC_READY";
            case 5665:
                return "MESSENGER_DESKTOP_DELETE_THREAD";
            case 5806:
                return "MESSENGER_DESKTOP_SEND_MESSAGE";
            case 5954:
                return "MESSENGER_DESKTOP_MARK_PROMOTION_IMPRESSION";
            case 6039:
                return "MESSENGER_DESKTOP_LOAD_EARLIER_THREADS";
            case 6192:
                return "MESSENGER_DESKTOP_APP_START_TO_LOGIN_RENDERED";
            case 6303:
                return "MESSENGER_DESKTOP_OSMETA_READ_ACCESS_TOKEN";
            case 6342:
                return "MESSENGER_DESKTOP_GRID_PARTICIPANT_SHOWN";
            case 6398:
                return "MESSENGER_DESKTOP_APP_START_TO_APP_QUIT";
            case 6630:
                return "MESSENGER_DESKTOP_LOAD_THREADS";
            case 6840:
                return "MESSENGER_DESKTOP_SSO_LOGIN_STARTED_TO_CHAT_READY";
            case 7005:
                return "MESSENGER_DESKTOP_RSYS_REDUCER_ACTION_PROCESSING";
            case 7295:
                return "MESSENGER_DESKTOP_APP_MODEL_RSYS_CLIENT_TO_SEND";
            case 7537:
                return "MESSENGER_DESKTOP_DELETE_COMMUNITY_CHAT";
            case 7623:
                return "MESSENGER_DESKTOP_RTC_DECLINE_JOIN_REQUEST";
            case 7829:
                return "MESSENGER_DESKTOP_THREAD_SEARCH_RESULTS";
            case 7846:
                return "MESSENGER_DESKTOP_RTC_OUTGOING_CALL_INTENT_TO_START_CALL";
            case 7854:
                return "MESSENGER_DESKTOP_MANUAL_TRACE";
            case 8122:
                return "MESSENGER_DESKTOP_OSMETA_READ_USER_ID";
            case 8154:
                return "MESSENGER_DESKTOP_THREAD_SEARCH";
            case 8182:
                return "MESSENGER_DESKTOP_MARK_PROMOTION_ACTION";
            case 8777:
                return "MESSENGER_DESKTOP_IDLE_WATCHDOG";
            case 8779:
                return "MESSENGER_DESKTOP_AUTO_HAND_LOWERING";
            case 8831:
                return "MESSENGER_DESKTOP_OPEN_THREAD";
            case 8856:
                return "MESSENGER_DESKTOP_CHAT_NICKNAMES_DIALOG";
            case 9100:
                return "MESSENGER_DESKTOP_LOGIN_TO_ROOMS_TRAY_READY";
            case 9291:
                return "MESSENGER_DESKTOP_OPEN_MEDIA_GALLERY";
            case 9361:
                return "MESSENGER_DESKTOP_OSMETA_MESSENGER_UPGRADE_COMPLETED_TO_APP_READY";
            case 9404:
                return "MESSENGER_DESKTOP_OPEN_CHAT_HEADS_WINDOW";
            case 9761:
                return "MESSENGER_DESKTOP_CPU_WATCHDOG";
            case 9850:
                return "MESSENGER_DESKTOP_SSO_LOGIN_STARTED_TO_RTC_READY";
            case 9881:
                return "MESSENGER_DESKTOP_REPORT_BUG";
            case 9894:
                return "MESSENGER_DESKTOP_RTC_START_COWATCH";
            case 10269:
                return "MESSENGER_DESKTOP_APP_START_TO_ROOMS_TRAY_READY";
            case 10732:
                return "MESSENGER_DESKTOP_LOAD_EARLIER_MESSAGES";
            case 10875:
                return "MESSENGER_DESKTOP_RTC_OUTGOING_CALL";
            case 11539:
                return "MESSENGER_DESKTOP_OPEN_THREAD_TO_MESSAGES_RENDERED";
            case 11614:
                return "MESSENGER_DESKTOP_APP_START_TO_RTC_READY";
            case 12526:
                return "MESSENGER_DESKTOP_JOIN_COMMUNITY_CHAT";
            case 12643:
                return "MESSENGER_DESKTOP_RTC_END_CALL";
            case 12740:
                return "MESSENGER_DESKTOP_APP_START_TO_CHAT_READY";
            case 13098:
                return "MESSENGER_DESKTOP_OSMETA_MESSENGER_USER_UPGRADE";
            case 13176:
                return "MESSENGER_DESKTOP_LOAD_THREAD_FROM_SEARCH";
            case 13409:
                return "MESSENGER_DESKTOP_LOAD_MESSAGES";
            case 13487:
                return "MESSENGER_DESKTOP_APP_START_TO_APP_READY";
            case 13537:
                return "MESSENGER_DESKTOP_LEAVE_COMMUNITY_CHAT";
            case 13578:
                return "MESSENGER_DESKTOP_END_AND_REMOVE_CALL";
            case 13710:
                return "MESSENGER_DESKTOP_APP_START_TO_SSO_READY";
            case 13894:
                return "MESSENGER_DESKTOP_RTC_INITIAL_CALL_ACTION_DISPATCH_TO_START_CALL";
            case 13944:
                return "MESSENGER_DESKTOP_MSYS_SYNC";
            case 14250:
                return "MESSENGER_DESKTOP_RTC_INCOMING_CALL_TO_START_CALL";
            case 14326:
                return "MESSENGER_DESKTOP_RTC_START_CAMERA_TO_END_CAMERA";
            case 14413:
                return "MESSENGER_DESKTOP_USER_CREATE_NEW_THREAD";
            case 14432:
                return "MESSENGER_DESKTOP_RENAME_CHAT";
            case 14523:
                return "MESSENGER_DESKTOP_OBJECT_COUNTER";
            case 14574:
                return "MESSENGER_DESKTOP_RTC_OPEN_CALL_WINDOW_TO_START_CALL";
            case 14735:
                return "MESSENGER_DESKTOP_RTC_START_ARFX_TO_END_ARFX";
            case 15106:
                return "MESSENGER_DESKTOP_OPEN_THREAD_TO_LOAD_EARLIER_MESSAGES";
            case 15260:
                return "MESSENGER_DESKTOP_RTC_START_SCREEN_SHARING_TO_END_SCREEN_SHARING";
            case 15373:
                return "MESSENGER_DESKTOP_SSO_LOGIN_STARTED_TO_ROOMS_TRAY_READY";
            case 15488:
                return "MESSENGER_DESKTOP_DECLINE_CALL";
            case 15847:
                return "MESSENGER_DESKTOP_INCOMING_CALL_DIALOG_START_TO_INCOMING_CALL_DIALOG_READY";
            case 16066:
                return "MESSENGER_DESKTOP_SSO_INTERSTITIAL_SHOWN_TO_INTERSTITIAL_COMPLETE";
            case 16195:
                return "MESSENGER_DESKTOP_SUCCESSFUL_THREAD_SEARCH";
            case 16258:
                return "MESSENGER_DESKTOP_LOAD_NEWER_MESSAGES";
            case 16286:
                return "MESSENGER_DESKTOP_MISSED_CALL_DIALOG_START_TO_MISSED_CALL_DIALOG_READY";
            case 16316:
                return "MESSENGER_DESKTOP_GRID_PARTICIPANT_REMOVED";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
