package p000X;
/* renamed from: X.0kO  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C19140kO {
    public static String A00(int i) {
        return i != 1 ? i != 2 ? i != 3 ? i != 4 ? i != 5 ? i != 2062 ? i != 5022 ? i != 7302 ? i != 11495 ? i != 12478 ? "UNDEFINED_QPL_EVENT" : "MESSENGER_INTEGRITY_TIME_TO_RESTRICT_ON_ANDROID_AND_IOS" : "MESSENGER_INTEGRITY_TIME_TO_UNBLOCK_ON_FACEBOOK_ON_ANDROID_AND_IOS" : "MESSENGER_INTEGRITY_TIME_TO_UNRESTRICT_ON_ANDROID_AND_IOS" : "MESSENGER_INTEGRITY_TIME_TO_BLOCK_ON_FACEBOOK_ON_ANDROID_AND_IOS" : "MESSENGER_INTEGRITY_IMPERSONATION_FETCH_SELECTED_USER_EVENT" : "MESSENGER_INTEGRITY_IMPERSONATION_FETCH_USER_EVENT" : "MESSENGER_INTEGRITY_TIME_TO_UNBLOCK_ON_ANDROID_AND_IOS" : "MESSENGER_INTEGRITY_TIME_TO_BLOCK_ON_ANDROID_AND_IOS" : "MESSENGER_INTEGRITY_TIME_TO_LOAD_PROACTIVE_WARNING_INFO_ANDROID" : "MESSENGER_INTEGRITY_TIME_TO_LOAD_FEEDBACK_TAGS_ANDROID";
    }
}
