package p000X;
/* renamed from: X.0kY  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C19230kY {
    public static String A00(int i) {
        switch (i) {
            case 1004:
                return "MESSENGER_PRE_ARMADILLO_MEDIA_RENDER";
            case 1022:
                return "MESSENGER_PRE_THREADLIST_TO_GROUP_THREADVIEW";
            case 1032:
                return "MESSENGER_SEND_MESSAGE";
            case 1187:
                return "MESSENGER_PRE_ADVANCED_CRYPTO_PROFILE_POPOVER";
            case 1506:
                return "MESSENGER_PRE_SEARCH_TYPEAHEAD";
            case 1842:
                return "MESSENGER_PRE_ADVANCED_CRYPTO_COMPOSE_MESSAGE";
            case 1945:
                return "MESSENGER_PRE_THREADLIST_TO_THREADVIEW";
            case 2133:
                return "MESSENGER_PRE_ADVANCED_CRYPTO_UNREGISTER_DEVICE";
            case 2869:
                return "MESSENGER_PRE_ADVANCED_CRYPTO_MESSAGE_SEND_ENQUEUE";
            case 3332:
                return "MESSENGER_PRE_ADVANCED_CRYPTO_THREAD_SETTINGS";
            case 3428:
                return "MESSENGER_PRE_ACT_MESSAGE_RECEIVE";
            case 3821:
                return "MESSENGER_PRE_THREADLIST_TO_ADVANCED_CRYPTO_GROUP_THREADVIEW";
            case 3925:
                return "MESSENGER_PRE_STELLA_PACKAGE_ENABLED";
            case 3949:
                return "MESSENGER_PRE_TINCAN_MESSAGE_SEND_ENQUEUE";
            case 4064:
                return "MESSENGER_PRE_ADVANCED_CRYPTO_MESSAGE_REACTION_SEND_ENQUEUE";
            case 4221:
                return "MESSENGER_PRE_BUG_REPORTING_PERSIST_REPORT";
            case 4234:
                return "MESSENGER_PRE_BUG_REPORTING_UPLOAD_ATTACHMENT";
            case 4391:
                return "MESSENGER_PRE_STELLA_BROADCAST_COUNT";
            case 4570:
                return "MESSENGER_PRE_ADVANCED_CRYPTO_GROUP_THREAD_MAKE_ADMIN";
            case 4792:
                return "MESSENGER_PRE_ADVANCED_CRYPTO_REGISTER_DEVICE";
            case 4892:
                return "MESSENGER_PRE_ADVANCED_CRYPTO_GROUP_THREAD_ADD_MEMBER";
            case 4893:
                return "MESSENGER_PRE_ARMADILLO_CONNECTION";
            case 5197:
                return "MESSENGER_PRE_CHANNELS_FOLDER_SELECTIVE_SYNC";
            case 5506:
                return "MESSENGER_PRE_CARRIER_MESSAGING_COMPOSE_MESSAGE";
            case 6047:
                return "MESSENGER_PRE_ACT_MESSAGE_SEND";
            case 6272:
                return "MESSENGER_PRE_TINCAN_COMPOSE_MESSAGE";
            case 7199:
                return "MESSENGER_PRE_MESSENGER_APP_USERFLOW";
            case 7210:
                return "MESSENGER_PRE_RTC_OUTGOING_CALL_USER_FLOW";
            case 7388:
                return "MESSENGER_PRE_BUG_REPORTING";
            case 7819:
                return "MESSENGER_PRE_RAGE_SHAKE_BUG_REPORTING";
            case 8104:
                return "MESSENGER_PRE_COMPOSE_MESSAGE";
            case 8292:
                return "MESSENGER_PRE_BUG_REPORTING_UPLOAD_REPORT";
            case 8519:
                return "MESSENGER_PRE_THREADLIST_ITEM_CLICK";
            case 9769:
                return "MESSENGER_PRE_EXTERNAL_INTENT";
            case 10324:
                return "MESSENGER_PRE_ADVANCED_CRYPTO_CREATE_GROUP_THREAD";
            case 10355:
                return "MESSENGER_PRE_SEARCH_CONTACT";
            case 10499:
                return "MESSENGER_PRE_VIEW_STORIES";
            case 10878:
                return "MESSENGER_PRE_COMPOSE_NEW_MESSAGE_BUTTON";
            case 10935:
                return "MESSENGER_PRE_ACT_MESSAGE_SEND_MEDIA";
            case 11014:
                return "MESSENGER_PRE_LOG_EVENT";
            case 11150:
                return "MESSENGER_PRE_BUG_REPORTING_FINALIZE_REPORT";
            case 11200:
                return "MESSENGER_PRE_ADVANCED_CRYPTO_THREAD_VIEW";
            case 11333:
                return "MESSENGER_PRE_ADVANCED_CRYPTO_GROUP_THREAD_REMOVE_MEMBER";
            case 11509:
                return "MESSENGER_PRE_THREADLIST_TO_ADVANCED_CRYPTO_THREADVIEW";
            case 11830:
                return "MESSENGER_PRE_SEARCHBAR_QUERY_VALIDATION";
            case 11966:
                return "MESSENGER_PRE_SOFT_ERROR";
            case 12021:
                return "MESSENGER_PRE_THREADLIST_TO_CARRIER_MESSAGING_THREADVIEW";
            case 12058:
                return "MESSENGER_PRE_SCREEN_ON_OFF_BROADCAST_RECEIVER";
            case 12674:
                return "MESSENGER_PRE_SEARCHBAR_QUERY";
            case 12740:
                return "MESSENGER_PRE_THREAD_MEDIA_LOAD_SUMMARY";
            case 13175:
                return "MESSENGER_PRE_MESSAGE_SEND_ENQUEUE";
            case 13253:
                return "MESSENGER_PRE_INBOX_FOLDERS_SWITCH";
            case 13451:
                return "MESSENGER_PRE_TOGGLE_SECRET_CONVERSATION_BUTTON";
            case 13585:
                return "MESSENGER_PRE_ARMADILLO_THREADVIEW_SCROLL_PERF";
            case 13927:
                return "MESSENGER_PRE_CARRIER_MESSAGING_MESSAGE_SEND_ENQUEUE";
            case 14090:
                return "MESSENGER_PRE_THREADLIST_TO_TINCAN_THREADVIEW";
            case 14103:
                return "MESSENGER_PRE_GOTO_SECRET_CONVERSATION";
            case 14370:
                return "MESSENGER_PRE_SEARCH_MESSAGES";
            case 16063:
                return "MESSENGER_PRE_RTC_INCOMING_CALL_USER_FLOW";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
