package p000X;
/* renamed from: X.0ka  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C19250ka {
    public static String A00(int i) {
        return i != 1077 ? i != 1433 ? i != 2617 ? i != 4591 ? i != 4766 ? i != 6629 ? i != 12707 ? i != 14710 ? i != 15301 ? "UNDEFINED_QPL_EVENT" : "MESSENGER_PRESENCE_ACTIVE_STATUS_SETTING_ENTER" : "MESSENGER_PRESENCE_HIGHLIGHTS_TAB_FEED_PREFETCH" : "MESSENGER_PRESENCE_HIGHLIGHTS_TAB_FEED_TTRC" : "MESSENGER_PRESENCE_HIGHLIGHTS_TAB_FEED_TTCC" : "MESSENGER_PRESENCE_INBOX_ACTIVE_NOW_LOADING_NON_COLDSTART" : "MESSENGER_PRESENCE_INBOX_TRAY_LOADING" : "MESSENGER_PRESENCE_INBOX_ACTIVE_NOW_INITIAL_LOADING" : "MESSENGER_PRESENCE_INBOX_ACTIVE_NOW_LOADING_COLD_START" : "MESSENGER_PRESENCE_INBOX_ACTIVE_NOW_LOADING";
    }
}
