package p000X;
/* renamed from: X.0kq  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C19410kq {
    public static String A00(int i) {
        return i != 1913 ? i != 2514 ? i != 2984 ? i != 3156 ? i != 3594 ? i != 4064 ? i != 5147 ? i != 11024 ? i != 14154 ? "UNDEFINED_QPL_EVENT" : "MESSENGER_WELLBEING_HIDDEN_WORDS_UPSELL_NUX_TURN_ON_TRACING" : "MESSENGER_WELLBEING_USER_UNBLOCK_TRACING" : "MESSENGER_WELLBEING_USER_BLOCK_TRACING" : "MESSENGER_WELLBEING_KINDNESS_REMINDER_IN_THREAD_BANNER_TRACING" : "MESSENGER_WELLBEING_HIDDEN_WORDS_UPSELL_NUX_TRACING" : "MESSENGER_WELLBEING_ACTION_ACCEPT_MESSAGE_REQUEST" : "MESSENGER_WELLBEING_ACTION_DELETE_MESSAGE_REQUEST" : "MESSENGER_WELLBEING_UPDATE_REACHABILITY_SETTING" : "MESSENGER_WELLBEING_HIDDEN_WORDS_UPSELL_POST_DELETE_TRACING";
    }
}
