package p000X;
/* renamed from: X.0lK  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C19680lK {
    public static String A00(int i) {
        return i != 1 ? i != 2 ? i != 3 ? i != 4 ? i != 6 ? i != 7 ? i != 11 ? i != 8774 ? i != 10342 ? i != 12004 ? i != 12270 ? i != 13316 ? i != 15347 ? i != 16 ? i != 17 ? "UNDEFINED_QPL_EVENT" : "MOBILECONFIG_MOBILECONFIG_SYNC_FETCH" : "MOBILECONFIG_AFTER_LOGIN" : "MOBILECONFIG_VALIDATE_PARAMS_MAP_MERGE_V2" : "MOBILECONFIG_IG4A_TRANSLATION_TABLE" : "MOBILECONFIG_PARAMS_MAP_MERGE_V2" : "MOBILECONFIG_PARAMS_MAP_FACTORY_CREATE" : "MOBILECONFIG_ADMINID_INIT" : "MOBILECONFIG_API_CONSISTENCY_LOGGING_JSON" : "MOBILECONFIG_MOBILECONFIG_SYNC_FETCH_IOS" : "MOBILECONFIG_BUFFER_PATH_MIGRATION" : "MOBILECONFIG_NULL_BUFFER" : "MOBILECONFIG_SESSIONLESS_INIT" : "MOBILECONFIG_SESSION_BASED_INIT" : "MOBILECONFIG_JAVA_MANAGER_CREATION" : "MOBILECONFIG_NATIVE_MANAGER_CREATION";
    }
}
