package p000X;

import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.os.Bundle;
import android.telephony.PhoneNumberUtils;
import android.text.Spannable;
import android.text.TextUtils;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentActivity;
import ch.boye.httpclientandroidlib.HttpStatus;
import com.facebook.analytics.structuredlogger.base.USLEBaseShape0S0000000;
import com.facebook.browser.lite.extensions.igcallextension.IGCallExtensionModel;
import com.facebook.common.stringformat.StringFormatUtil;
import com.facebook.endtoend.EndToEnd;
import com.facebook.fbreactmodules.datepicker.DatePickerDialogModule;
import com.facebook.iabadscontext.DisclaimerBodyUrlRanges;
import com.facebook.iabadscontext.DisclaimerText;
import com.facebook.iabadscontext.IABAdsContext;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S0101000_I2;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S1210000_I2;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S3000000_I2;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape1S1100000_I2_1;
import com.facebook.react.modules.dialog.DialogModule;
import com.facebook.redex.IDxCListenerShape10S1200000_2_I2;
import com.facebook.redex.IDxDListenerShape316S0100000_3_I2;
import com.facebook.redex.IDxObjectShape229S0100000_5_I2;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.instagram.api.schemas.IGPostClickEligibleExperienceTypes;
import com.instagram.api.schemas.ProductReviewStatus;
import com.instagram.api.schemas.SellerShoppableFeedType;
import com.instagram.barcelona.R;
import com.instagram.bloks.hosting.IgBloksScreenConfig;
import com.instagram.canvas.CanvasActivity;
import com.instagram.feed.media.ClickToMessagingAdsInfo;
import com.instagram.feed.media.OnFeedMessages;
import com.instagram.feed.media.ReelCTA;
import com.instagram.leadads.activity.LeadAdsActivity;
import com.instagram.model.androidlink.AndroidLink;
import com.instagram.model.mediasize.ExtendedImageUrl;
import com.instagram.model.mediasize.ImageInfo;
import com.instagram.model.reels.Reel;
import com.instagram.model.reels.sponsored.AutoGeneratedCardType;
import com.instagram.model.shopping.Merchant;
import com.instagram.model.shopping.Product;
import com.instagram.model.shopping.ProductDetailsProductItemDict;
import com.instagram.model.shopping.ProductImageContainer;
import com.instagram.model.shopping.ProductTag;
import com.instagram.realtimeclient.RealtimeSubscription;
import com.instagram.service.session.UserSession;
import com.instagram.user.model.User;
import java.util.ArrayList;
import java.util.BitSet;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import kotlin.jvm.internal.KtLambdaShape28S0200000_I2_12;
import kotlin.jvm.internal.KtLambdaShape91S0100000_I2_71;
import org.webrtc.MediaStreamTrack;
/* renamed from: X.Am6  reason: case insensitive filesystem */
/* loaded from: classes4.dex */
public final class C19757Am6 {
    public static B7P A00(B7P b7p, C19356AfS c19356AfS) {
        AutoGeneratedCardType autoGeneratedCardType;
        B7P b7p2;
        Reel reel = c19356AfS.A0D;
        if (reel != null) {
            B7I b7i = b7p.A0f;
            if (C25930wq.A1Y(b7i.A1c) && (autoGeneratedCardType = b7i.A1T) != null && AutoGeneratedCardType.COLLECTION.equals(autoGeneratedCardType) && (b7p2 = C150688fG.A0K(reel.A0P(c19356AfS.A0U), 0).A0M) != null) {
                return b7p2;
            }
        }
        return b7p;
    }

    public static void A01(AbstractC18180if abstractC18180if, B7P b7p, C19356AfS c19356AfS) {
        ((C31693GTx) abstractC18180if.A01(C31693GTx.class, new IDxObjectShape229S0100000_5_I2(abstractC18180if, 6))).A01(b7p, c19356AfS.A0T.getModuleName());
    }

    public static void A03(InterfaceC21924Bnj interfaceC21924Bnj, B7P b7p, AndroidLink androidLink, C19356AfS c19356AfS) {
        String str;
        Uri uri;
        String str2;
        String A0C;
        UserSession userSession = c19356AfS.A0U;
        C0TD c0td = C0TD.A05;
        boolean z = false;
        if (C70763jC.A0E(c0td, userSession, 36324831934816969L)) {
            str = androidLink.A0G;
            if (C70763jC.A0E(c0td, userSession, 36324831934882506L) && !TextUtils.isEmpty(str)) {
                z = true;
            }
        } else {
            str = null;
        }
        String str3 = androidLink.A05;
        str3.getClass();
        String str4 = androidLink.A0I;
        if (z) {
            uri = C0gL.A00;
        } else {
            uri = C0gL.A01;
        }
        Uri.Builder buildUpon = uri.buildUpon();
        buildUpon.appendQueryParameter("id", str3);
        if (!TextUtils.isEmpty(str4)) {
            buildUpon.appendQueryParameter("referrer", str4);
        }
        if (!TextUtils.isEmpty(str)) {
            buildUpon.appendQueryParameter("listing", str);
        }
        String obj = buildUpon.build().toString();
        A0G(interfaceC21924Bnj, c19356AfS, "appinstall", obj);
        A01(userSession, b7p, c19356AfS);
        FragmentActivity fragmentActivity = c19356AfS.A0R;
        if (!C34j.A00.A00(fragmentActivity, userSession, obj)) {
            C7GT.A04(fragmentActivity, EnumC170649fW.AD_DESTINATION_APP_STORE, obj);
        }
        C31871GcC.A00(userSession).A07(EnumC171529jz.APP_INSTALL);
        String str5 = "";
        if (C70763jC.A0E(c0td, userSession, 36322435343064407L)) {
            String A03 = C19763AmC.A03(b7p, userSession);
            if (A03 == null) {
                A03 = "";
            }
            C105346Hq.A00(fragmentActivity.getApplicationContext(), userSession).A04(str3, A03);
        }
        if (C70763jC.A0E(c0td, userSession, 36325081042920347L)) {
            String A032 = C19763AmC.A03(b7p, userSession);
            Reel reel = c19356AfS.A0D;
            if (reel != null) {
                A0C = reel.BDU(userSession);
            } else {
                B7O b7o = c19356AfS.A0E;
                if (b7o != null) {
                    A0C = b7o.A0b;
                } else {
                    A0C = C19763AmC.A0C(b7p, userSession);
                }
            }
            if (A0C != null) {
                str5 = A0C;
            }
            if (A032 != null) {
                Context applicationContext = fragmentActivity.getApplicationContext();
                C25920wp.A1Q(userSession, applicationContext);
                ((C7nV) userSession.A01(C7nV.class, new KtLambdaShape28S0200000_I2_12(applicationContext, 16, userSession))).A01(str3, A032, str5);
            }
        }
        C0OR.A0B(userSession, 0);
        if (C70763jC.A0E(c0td, ((C19477AhU) userSession.A01(C19477AhU.class, new KtLambdaShape91S0100000_I2_71(userSession, 9))).A00, 36327048137942887L) && (str2 = androidLink.A07) != null && str4 != null) {
            C19477AhU.A01(true, str2, str4);
        }
    }

    /* JADX WARN: Code restructure failed: missing block: B:100:0x037f, code lost:
        r0 = "audio_page";
     */
    /* JADX WARN: Code restructure failed: missing block: B:101:0x0382, code lost:
        r0 = "clips_viewer_video";
     */
    /* JADX WARN: Code restructure failed: missing block: B:102:0x0384, code lost:
        A0J(r33, r1, r36, r0);
     */
    /* JADX WARN: Code restructure failed: missing block: B:103:0x0387, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:104:0x0388, code lost:
        A0F(r33, r1, r36);
     */
    /* JADX WARN: Code restructure failed: missing block: B:105:0x038b, code lost:
        throw null;
     */
    /* JADX WARN: Code restructure failed: missing block: B:106:0x038c, code lost:
        A0A(r33, r34, r1, r36);
     */
    /* JADX WARN: Code restructure failed: missing block: B:107:0x038f, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:108:0x0390, code lost:
        A04(r33, r34, r1, r36);
     */
    /* JADX WARN: Code restructure failed: missing block: B:109:0x0393, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:110:0x0394, code lost:
        A09(r33, r34, r1, r36);
     */
    /* JADX WARN: Code restructure failed: missing block: B:111:0x0397, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:112:0x0398, code lost:
        A0C(r33, r34, r1, r36);
     */
    /* JADX WARN: Code restructure failed: missing block: B:113:0x039b, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:114:0x039c, code lost:
        A0E(r33, r34, r1, r36, true);
     */
    /* JADX WARN: Code restructure failed: missing block: B:115:0x039f, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:116:0x03a0, code lost:
        r1 = r1.A0E;
        r1.getClass();
        A0G(r33, r36, "profilevisit", r1);
     */
    /* JADX WARN: Code restructure failed: missing block: B:117:0x03ac, code lost:
        if (r36.A0N != false) goto L85;
     */
    /* JADX WARN: Code restructure failed: missing block: B:118:0x03ae, code lost:
        p000X.C3QO.A00();
     */
    /* JADX WARN: Code restructure failed: missing block: B:119:0x03b1, code lost:
        throw null;
     */
    /* JADX WARN: Code restructure failed: missing block: B:120:0x03b2, code lost:
        A07(r33, r34, r1, r36);
     */
    /* JADX WARN: Code restructure failed: missing block: B:121:0x03b5, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:122:0x03b6, code lost:
        A05(r33, A00(r34, r36), r1, r36);
     */
    /* JADX WARN: Code restructure failed: missing block: B:123:0x03bd, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:124:0x03be, code lost:
        A08(r33, r34, r1, r36);
     */
    /* JADX WARN: Code restructure failed: missing block: B:125:0x03c1, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:126:0x03c2, code lost:
        A0B(r33, r34, r1, r36);
     */
    /* JADX WARN: Code restructure failed: missing block: B:127:0x03c5, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:128:0x03c6, code lost:
        A06(r33, r34, r1, r36);
     */
    /* JADX WARN: Code restructure failed: missing block: B:129:0x03c9, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:130:0x03ca, code lost:
        A03(r33, r34, r1, r36);
     */
    /* JADX WARN: Code restructure failed: missing block: B:131:0x03cd, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:132:0x03ce, code lost:
        A0D(r33, r34, r1, r36);
     */
    /* JADX WARN: Code restructure failed: missing block: B:133:0x03d1, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:218:?, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:219:?, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:61:0x02bd, code lost:
        if (p000X.C0OR.A0I(r1, new p000X.C155948pf(null, false)) == false) goto L49;
     */
    /* JADX WARN: Code restructure failed: missing block: B:63:0x02c1, code lost:
        if (r1.A00 != false) goto L51;
     */
    /* JADX WARN: Code restructure failed: missing block: B:65:0x02cd, code lost:
        if (r34.A3I().size() >= r16) goto L55;
     */
    /* JADX WARN: Code restructure failed: missing block: B:66:0x02cf, code lost:
        p000X.C41448Lrm.A00(p000X.EnumC171539k0.OEM_FALLBACK_OEM_STORE_NOT_FOUND, p000X.EnumC40482LMv.A0B, r17, null, null, 60);
        p000X.C70743jA.A03(r0, null, 2131832023, 0);
     */
    /* JADX WARN: Code restructure failed: missing block: B:67:0x02e4, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:88:0x0349, code lost:
        if (r0.A00 >= 1) goto L123;
     */
    /* JADX WARN: Code restructure failed: missing block: B:90:0x034d, code lost:
        p000X.C41448Lrm.A00(null, p000X.EnumC40482LMv.A0B, r17, null, null, 60);
        r1 = (com.instagram.model.androidlink.AndroidLink) r34.A3I().get(1);
     */
    /* JADX WARN: Code restructure failed: missing block: B:91:0x0363, code lost:
        if (r1 == null) goto L100;
     */
    /* JADX WARN: Code restructure failed: missing block: B:92:0x0365, code lost:
        r0 = p000X.C67033Pm.A00(r1);
        r0.getClass();
     */
    /* JADX WARN: Code restructure failed: missing block: B:93:0x0370, code lost:
        switch(r0.ordinal()) {
            case 0: goto L98;
            case 1: goto L96;
            case 2: goto L94;
            case 3: goto L92;
            case 4: goto L90;
            case 5: goto L88;
            case 6: goto L86;
            case 7: goto L81;
            case 8: goto L79;
            case 9: goto L62;
            case 10: goto L71;
            case 11: goto L77;
            case 12: goto L75;
            case 13: goto L73;
            case 14: goto L69;
            case 15: goto L68;
            case 16: goto L68;
            case 17: goto L67;
            case 18: goto L64;
            case 19: goto L60;
            case 20: goto L73;
            default: goto L59;
        };
     */
    /* JADX WARN: Code restructure failed: missing block: B:94:0x0373, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:95:0x0374, code lost:
        A02(r33, r34, r1, r36);
     */
    /* JADX WARN: Code restructure failed: missing block: B:96:0x0377, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:97:0x0378, code lost:
        A0H(r34, r36);
     */
    /* JADX WARN: Code restructure failed: missing block: B:98:0x037b, code lost:
        return;
     */
    /* JADX WARN: Code restructure failed: missing block: B:99:0x037c, code lost:
        r0 = "clips_profile";
     */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public static void A04(InterfaceC21924Bnj interfaceC21924Bnj, B7P b7p, AndroidLink androidLink, C19356AfS c19356AfS) {
        IgBloksScreenConfig A0U;
        C70653iv A06;
        Context context;
        String A0C;
        String queryParameter;
        KtCSuperShape0S0101000_I2 ktCSuperShape0S0101000_I2;
        C155948pf c155948pf;
        int i;
        C18644AJz c18644AJz;
        String str = androidLink.A0C;
        str.getClass();
        Uri A01 = C23320rx.A01(str);
        String queryParameter2 = A01.getQueryParameter("app_id");
        queryParameter2.getClass();
        String queryParameter3 = A01.getQueryParameter(DialogModule.KEY_TITLE);
        boolean z = true;
        char c = 65535;
        switch (queryParameter2.hashCode()) {
            case -1772578244:
                if (queryParameter2.equals("com.bloks.www.minishops.ad.collection")) {
                    c = 0;
                    break;
                }
                break;
            case -713377845:
                if (queryParameter2.equals("com.bloks.www.bloks_application_direct_install")) {
                    c = 1;
                    break;
                }
                break;
            case -344245188:
                if (queryParameter2.equals("com.bloks.www.showcase_page")) {
                    c = 2;
                    break;
                }
                break;
            case 897070470:
                if (queryParameter2.equals("com.bloks.www.minishops.ad.storefront")) {
                    c = 3;
                    break;
                }
                break;
            case 1937695241:
                if (queryParameter2.equals("com.bloks.www.minishops.ad.dynamic.shop.collection")) {
                    c = 4;
                    break;
                }
                break;
            case 2046366777:
                if (queryParameter2.equals("com.bloks.www.minishop.collections")) {
                    c = 5;
                    break;
                }
                break;
        }
        switch (c) {
            case 0:
                A0G(interfaceC21924Bnj, c19356AfS, "mini_shop_collection", str);
                C18862ASx A0G = AbstractC19674Akj.A00.A0G(c19356AfS.A0R, EnumC171159gM.A0E, c19356AfS.A0U, null, c19356AfS.A0T.getModuleName());
                A0G.A08 = b7p.A0f.A4Y;
                A0G.A0I = true;
                A0G.A0K = true;
                A0G.A0G = queryParameter3;
                if (b7p.A4E()) {
                    A0G.A0H = true;
                }
                A0G.A00();
                return;
            case 1:
                UserSession userSession = c19356AfS.A0U;
                C136537oj A00 = C104426Ec.A00(userSession);
                A00.A00 = false;
                FragmentActivity fragmentActivity = c19356AfS.A0R;
                Context applicationContext = fragmentActivity.getApplicationContext();
                Fragment fragment = c19356AfS.A0Q;
                SharedPreferences sharedPreferences = A00.A01;
                String A002 = AnonymousClass000.A00(HttpStatus.SC_RESET_CONTENT);
                UserSession userSession2 = A00.A02.A00;
                C0TD c0td = C0TD.A05;
                boolean z2 = sharedPreferences.getBoolean(A002, C70763jC.A0E(c0td, userSession2, 36322753170709988L));
                int A012 = C25950ws.A01(1, applicationContext, userSession);
                String queryParameter4 = A01.getQueryParameter("referrer_data");
                String queryParameter5 = A01.getQueryParameter("dso_id");
                String queryParameter6 = A01.getQueryParameter(C25910wo.A00(746));
                String queryParameter7 = A01.getQueryParameter("ais_surface");
                String queryParameter8 = A01.getQueryParameter(C25910wo.A00(89));
                String queryParameter9 = A01.getQueryParameter("store_id");
                String queryParameter10 = A01.getQueryParameter("tracking_token");
                if (queryParameter6 != null && queryParameter5 != null && queryParameter8 != null && queryParameter4 != null && queryParameter9 != null && queryParameter10 != null) {
                    KtCSuperShape0S3000000_I2 ktCSuperShape0S3000000_I2 = new KtCSuperShape0S3000000_I2(queryParameter5, queryParameter6, queryParameter10, 0);
                    C0OR.A0C(fragment, C25910wo.A00(48));
                    C20950nT A013 = C20950nT.A01((InterfaceC19580l7) fragment, userSession);
                    C01R A02 = C150708fI.A02();
                    A02.markerStart(0);
                    C41448Lrm c41448Lrm = new C41448Lrm(A013, ktCSuperShape0S3000000_I2, A02);
                    c41448Lrm.A06.markerStart(279584123, 0);
                    C70763jC.A0E(c0td, userSession, 36321915652021343L);
                    if (!C6XX.A00.get() && !EndToEnd.isRunningEndToEndTest()) {
                        if (queryParameter9.equals("xiaomi")) {
                            String queryParameter11 = A01.getQueryParameter("market_package_name");
                            if (queryParameter11 != null) {
                                String A003 = AnonymousClass000.A00(676);
                                if (queryParameter11.equals(A003)) {
                                    PackageManager packageManager = applicationContext.getPackageManager();
                                    C0OR.A06(packageManager);
                                    if (!C0OR.A0I(C19445Agx.A00(packageManager, AnonymousClass000.A00(675), "22.11.09.732"), new C155948pf(null, false))) {
                                        c155948pf = C19445Agx.A00(packageManager, A003, "18.6.0");
                                        break;
                                    }
                                }
                            }
                            c155948pf = new C155948pf(null, false);
                            break;
                        } else if (queryParameter9.equals(AnonymousClass000.A00(741)) && (queryParameter = A01.getQueryParameter("market_package_name")) != null) {
                            String A004 = AnonymousClass000.A00(674);
                            if (queryParameter.equals(A004)) {
                                EnumC171539k0 enumC171539k0 = null;
                                int i2 = 0;
                                try {
                                } catch (PackageManager.NameNotFoundException e) {
                                    C0LJ.A0E("DirectInstallButtonListenerProvider", "Fallback to old Samsung install API", e);
                                    enumC171539k0 = EnumC171539k0.OEM_FALLBACK_OEM_STORE_NOT_FOUND;
                                }
                                if (applicationContext.getPackageManager() == null) {
                                    ktCSuperShape0S0101000_I2 = new KtCSuperShape0S0101000_I2(0, 0, EnumC171539k0.OEM_FALLBACK_INVALID_CONTEXT);
                                    break;
                                } else {
                                    ApplicationInfo applicationInfo = applicationContext.getPackageManager().getApplicationInfo(A004, 128);
                                    C0OR.A06(applicationInfo);
                                    Bundle bundle = applicationInfo.metaData;
                                    if (bundle != null && (i2 = bundle.getInt("com.sec.android.app.samsungapps.GalaxyStoreDownloadService.vesrion", -1)) < 1) {
                                        enumC171539k0 = EnumC171539k0.OEM_FALLBACK_UNSUPPORTED_OEM_STORE_VERSION;
                                    }
                                    ktCSuperShape0S0101000_I2 = new KtCSuperShape0S0101000_I2(i2, 0, enumC171539k0);
                                }
                            }
                        }
                    }
                    c41448Lrm.A02(EnumC40482LMv.A04);
                    C41438LrK A005 = C125006zX.A00(queryParameter5);
                    A8J a8j = new A8J(userSession);
                    A8K a8k = new A8K(userSession);
                    synchronized (A005.A04) {
                        int i3 = A005.A02.A02;
                        boolean z3 = true;
                        if (i3 != 12) {
                            z3 = false;
                            if (i3 != 10) {
                            }
                        }
                        PackageManager packageManager2 = applicationContext.getPackageManager();
                        boolean z4 = false;
                        if (packageManager2 != null && packageManager2.getLaunchIntentForPackage(queryParameter8) != null) {
                            z4 = true;
                        }
                        if (!z3 || !z4) {
                            A005.A00 = new KtCSuperShape0S1210000_I2(C25980wv.A0A(applicationContext), new C40863Lce(new KtCSuperShape0S3000000_I2(queryParameter5, queryParameter6, queryParameter10, 0), new C40988LgP(A005), c41448Lrm, a8j, a8k, queryParameter8, queryParameter4), queryParameter9, z4);
                        }
                    }
                    A0U = C25950ws.A0U(userSession);
                    A0U.A0P = "com.bloks.www.bloks_unified_application_direct_install";
                    HashMap A0z = C25920wp.A0z();
                    HashMap A0z2 = C25920wp.A0z();
                    HashMap A0z3 = C25920wp.A0z();
                    new BitSet(0);
                    A0z.put("tracking_token", queryParameter10);
                    A0z.put("dso_id", queryParameter5);
                    A0z.put("app_id", queryParameter6);
                    A0z.put("auto_open_enabled", Boolean.valueOf(z2));
                    if (queryParameter7 != null) {
                        A0z.put("app_surface", queryParameter7);
                    }
                    boolean A0E = C70763jC.A0E(c0td, userSession, 36320644341700715L);
                    c41448Lrm.A02(EnumC40482LMv.A0M);
                    A06 = C70653iv.A06("com.bloks.www.bloks_unified_application_direct_install", GWJ.A02(A0z), A0z2);
                    C70653iv.A09(A06, 719983200);
                    A06.A03 = null;
                    A06.A02 = null;
                    A06.A04 = null;
                    A06.A0F(A0z3);
                    context = fragmentActivity;
                    if (!A0E) {
                        A06.A0C(context, A0U);
                        String str2 = "";
                        if (C70763jC.A0E(c0td, userSession, 36322435343064407L) && C70763jC.A0E(c0td, userSession, 36322435343129944L)) {
                            String A03 = C19763AmC.A03(b7p, userSession);
                            if (A03 == null) {
                                A03 = "";
                            }
                            C7nX A006 = C105346Hq.A00(fragmentActivity.getApplicationContext(), userSession);
                            String str3 = androidLink.A05;
                            str3.getClass();
                            A006.A04(str3, A03);
                        }
                        if (C70763jC.A0E(c0td, userSession, 36325081042920347L) && C70763jC.A0E(c0td, userSession, 36325081042985884L)) {
                            String A032 = C19763AmC.A03(b7p, userSession);
                            Reel reel = c19356AfS.A0D;
                            if (reel != null) {
                                A0C = reel.BDU(userSession);
                            } else {
                                B7O b7o = c19356AfS.A0E;
                                if (b7o != null) {
                                    A0C = b7o.A0b;
                                } else {
                                    A0C = C19763AmC.A0C(b7p, userSession);
                                }
                            }
                            if (A0C != null) {
                                str2 = A0C;
                            }
                            if (A032 != null) {
                                Context applicationContext2 = fragmentActivity.getApplicationContext();
                                C25920wp.A1Q(userSession, applicationContext2);
                                String str4 = androidLink.A05;
                                str4.getClass();
                                ((C7nV) userSession.A01(C7nV.class, new KtLambdaShape28S0200000_I2_12(applicationContext2, 16, userSession))).A01(str4, A032, str2);
                                return;
                            }
                            return;
                        }
                        return;
                    }
                } else {
                    C18350ix.A00().Cv8("directInstall", "DirectInstallModel null due to missing direct install data");
                    C70743jA.A03(fragmentActivity, "open_link_generic_error", 2131832023, 0);
                    return;
                }
                break;
            case 2:
                A0G(interfaceC21924Bnj, c19356AfS, "dpa_showcase", str);
                UserSession userSession3 = c19356AfS.A0U;
                String AkB = B7P.A0H(b7p, userSession3).AkB();
                FragmentActivity fragmentActivity2 = c19356AfS.A0R;
                String A0d = C25940wr.A0d(fragmentActivity2.getResources(), AkB, 2131826240);
                A0U = C25950ws.A0U(userSession3);
                A0U.A0g = true;
                A0U.A0P = EnumC171169gN.A0u.toString();
                A0U.A05 = new C20038AuC(A0d);
                if (c19356AfS.A0D != null) {
                    i = 719983200;
                    c18644AJz = new C18644AJz(fragmentActivity2);
                    String A033 = C19763AmC.A03(b7p, userSession3);
                    A033.getClass();
                    Map map = c18644AJz.A04;
                    map.put("ad_id", A033);
                    BitSet bitSet = c18644AJz.A01;
                    bitSet.set(0);
                    String BIM = b7p.BIM();
                    BIM.getClass();
                    map.put("tracking_token", BIM);
                    bitSet.set(2);
                    map.put("media_id", b7p.A0f.A4Y);
                    bitSet.set(1);
                    Reel reel2 = c19356AfS.A0D;
                    reel2.getClass();
                    map.put("reel_id", reel2.getId());
                    map.put("reel_index", C25980wv.A0d(c19356AfS.A06));
                    map.put("tray_position", C25980wv.A0d(c19356AfS.A07));
                    String str5 = c19356AfS.A0L;
                    str5.getClass();
                    map.put("tray_session_id", str5);
                    String str6 = c19356AfS.A0M;
                    str6.getClass();
                    map.put("viewer_session_id", str6);
                } else {
                    B7O b7o2 = c19356AfS.A0E;
                    if (b7o2 != null && b7o2.A0d != null && C70763jC.A0E(C0TD.A05, userSession3, 36320824730327301L)) {
                        C0OR.A0B(userSession3, 0);
                        B7O b7o3 = c19356AfS.A0E;
                        C0OR.A0B(b7o3, 0);
                        String A0Z = C150618f9.A0Z();
                        ((B1J) userSession3.A01(B1J.class, BVS.A00)).A00.put(A0Z, b7o3);
                        i = 719983200;
                        c18644AJz = new C18644AJz(fragmentActivity2);
                        String A034 = C19763AmC.A03(b7p, userSession3);
                        A034.getClass();
                        Map map2 = c18644AJz.A04;
                        map2.put("ad_id", A034);
                        BitSet bitSet2 = c18644AJz.A01;
                        bitSet2.set(0);
                        String BIM2 = b7p.BIM();
                        BIM2.getClass();
                        map2.put("tracking_token", BIM2);
                        bitSet2.set(2);
                        map2.put("tray_session_id", A0Z);
                        map2.put("media_id", b7p.A0f.A4Y);
                        bitSet2.set(1);
                    } else {
                        return;
                    }
                }
                if (c18644AJz.A01.nextClearBit(0) >= 3) {
                    A06 = C70653iv.A06("com.bloks.www.showcase_page", GWJ.A02(c18644AJz.A04), c18644AJz.A03);
                    C70653iv.A09(A06, i);
                    A06.A03 = null;
                    A06.A02 = null;
                    A06.A04 = null;
                    A06.A0F(c18644AJz.A02);
                    context = c18644AJz.A00;
                    break;
                } else {
                    throw C25930wq.A0X("Missing Required Props");
                }
            case 3:
                A0G(interfaceC21924Bnj, c19356AfS, "mini_shop_collection", str);
                AbstractC19674Akj abstractC19674Akj = AbstractC19674Akj.A00;
                FragmentActivity fragmentActivity3 = c19356AfS.A0R;
                UserSession userSession4 = c19356AfS.A0U;
                C4u2 c4u2 = c19356AfS.A0T;
                if (c19356AfS.A0D == null) {
                    z = false;
                }
                abstractC19674Akj.A0J(A01, fragmentActivity3, b7p, c4u2, userSession4, z).A03();
                return;
            case 4:
                A0G(interfaceC21924Bnj, c19356AfS, "mini_shop_collection", str);
                AM3 A0E2 = AbstractC19674Akj.A00.A0E(c19356AfS.A0R, b7p, androidLink, c19356AfS.A0U, A01.getQueryParameter("shopping_session_id"));
                A0E2.A01 = queryParameter3;
                String moduleName = c19356AfS.A0T.getModuleName();
                C0OR.A0B(moduleName, 0);
                A0E2.A00 = moduleName;
                UserSession userSession5 = A0E2.A05;
                USLEBaseShape0S0000000 A0I = C25930wq.A0I(C25920wp.A0L(C20950nT.A01(C20202Ax3.A00, userSession5), "shops_dynamic_collection_page_entry"), 2705);
                if (C25920wp.A1V(A0I)) {
                    C25990ww.A19(A0I, "mini_shop_dynamic_collection");
                    C154938ni A007 = C154938ni.A00();
                    A007.A0C("shopping_session_id", A0E2.A06);
                    A007.A0F(A0E2.A00);
                    C150628fA.A1B(A0I, A007);
                    C154178mD c154178mD = new C154178mD();
                    B7P b7p2 = A0E2.A03;
                    C150688fG.A1I(c154178mD, b7p2.A0f.A4Y);
                    c154178mD.A0C("tracking_token", b7p2.A31());
                    A0I.A0P(c154178mD, "ig_media_info");
                    A0I.BbJ();
                }
                KtCSuperShape1S1100000_I2_1 A008 = C19034AZw.A00(A0E2.A03, A0E2.A04, userSession5, A0E2.A00);
                AbstractC19674Akj.A03();
                String str7 = A008.A01;
                String str8 = A0E2.A01;
                Bundle A07 = C25930wq.A07();
                A07.putSerializable("bloks_params", (HashMap) A008.A00);
                Fragment A009 = C19730Ale.A00(A07, userSession5, str7, "mini_shop_dynamic_collection", str8);
                C31878GcM A0Q = C25920wp.A0Q(A0E2.A02, userSession5);
                A0Q.A03 = A009;
                A0Q.A04();
                return;
            case 5:
                A0G(interfaceC21924Bnj, c19356AfS, "organic_shop_collection", str);
                String queryParameter12 = A01.getQueryParameter("encoded_collection_id");
                queryParameter12.getClass();
                C18854ASo A0O = AbstractC19674Akj.A00.A0O(c19356AfS.A0R, c19356AfS.A0U, queryParameter12);
                A0O.A00 = A01.getQueryParameter("ad_id");
                A0O.A01 = A01.getQueryParameter("first_entry_point");
                A0O.A02 = b7p.A0f.A4Y;
                A0O.A01(A01.getQueryParameter("pinned_product_ids"));
                A0O.A03 = c19356AfS.A0T.getModuleName();
                A0O.A04 = A01.getQueryParameter("shopping_session_id");
                A0O.A05 = queryParameter3;
                A0O.A06 = A01.getQueryParameter("tracking_token");
                UserSession userSession6 = A0O.A09;
                C18684ALn c18684ALn = new C18684ALn(A0O.A08, (int) C70763jC.A03(C0TD.A05, userSession6, 36603472233107575L));
                A0U = C25950ws.A0U(userSession6);
                A0U.A0S = A0O.A05;
                A0U.A0M = Integer.valueOf((int) R.layout.mini_shop_collection_loading_screen);
                A0U.A0P = "instagram_shopping_product_collection";
                String str9 = A0O.A0A;
                Map map3 = c18684ALn.A06;
                map3.put("encoded_collection_id", str9);
                BitSet bitSet3 = c18684ALn.A03;
                bitSet3.set(0);
                map3.put("ad_id", A0O.A00);
                map3.put("first_entry_point", A0O.A01);
                map3.put("media_id", A0O.A02);
                List list = A0O.A07;
                if (list != null && !list.isEmpty()) {
                    map3.put("pinned_product_ids", list);
                }
                map3.put("prior_module", A0O.A03);
                map3.put("shopping_session_id", A0O.A04);
                map3.put("tracking_token", A0O.A06);
                map3.put("layout_format", "MOBILE");
                if (bitSet3.nextClearBit(0) >= 1) {
                    A06 = C70653iv.A06("com.bloks.www.minishop.collections", GWJ.A02(map3), c18684ALn.A05);
                    C70653iv.A09(A06, c18684ALn.A01);
                    A06.A03 = null;
                    A06.A02 = null;
                    A06.A04 = null;
                    A06.A0F(c18684ALn.A04);
                    context = c18684ALn.A02;
                    break;
                } else {
                    throw C25930wq.A0X("Missing Required Props");
                }
            default:
                throw C25930wq.A0X(C073900b.A0L("Unexpected destination: ", queryParameter2));
        }
        A06.A0B(context, A0U);
    }

    public static void A05(InterfaceC21924Bnj interfaceC21924Bnj, B7P b7p, AndroidLink androidLink, C19356AfS c19356AfS) {
        Uri uri;
        Collection emptyList;
        Intent putExtra;
        int[] iArr;
        B7I b7i = b7p.A0f;
        String str = b7i.A4f;
        if (str != null) {
            uri = C23320rx.A01(str);
        } else {
            uri = null;
        }
        A0G(interfaceC21924Bnj, c19356AfS, b7i.A47, null);
        UserSession userSession = c19356AfS.A0U;
        C32895GyE A00 = C32895GyE.A00(userSession);
        FragmentActivity fragmentActivity = c19356AfS.A0R;
        A00.A06(fragmentActivity);
        if (uri != null && C19059AaU.A01(uri, "AdCTAOpenerHelper")) {
            C0OR.A0B(userSession, 1);
            HashMap A002 = C19059AaU.A00(uri);
            if (A002 == null) {
                C18350ix.A00().Cv8("InstantShoppingInstagramBloksScreenUtil", StringFormatUtil.formatStrLocaleSafe("Invalid serverParamsString or nativeAdType to open Bloks screen from %s", "AdCTAOpenerHelper"));
                return;
            }
            String A003 = B7I.A00(b7i);
            Integer num = null;
            String A0b = C150698fH.A0b(b7p.A2c(userSession));
            EnumC23771CjE Av2 = b7p.Av2();
            if (Av2 != null) {
                num = Integer.valueOf(Av2.A00);
            }
            String A08 = C19745Alu.A08(b7p, userSession);
            ImmutableMap.Builder builder = new ImmutableMap.Builder();
            builder.put("m_pk", A003);
            if (A0b != null) {
                builder.put("a_pk", A0b);
            }
            String A0u = C91564uW.A0u(num);
            if (A0u != null) {
                builder.put("m_t", A0u);
            }
            builder.put("follow_status", A08);
            ImmutableMap build = builder.build();
            C0OR.A06(build);
            IgBloksScreenConfig A0U = C25950ws.A0U(userSession);
            A0U.A0P = AnonymousClass000.A00(1067);
            C70653iv A06 = C70653iv.A06("com.bloks.www.fam.native.ads.bloks.main.controller", A002, build);
            A06.A00 = 719983200;
            C5sW A02 = C69803bw.A02(A0U, A06);
            C31878GcM A0Q = C25920wp.A0Q(fragmentActivity, userSession);
            A0Q.A03 = A02;
            A0Q.A04();
            return;
        }
        int nextInt = new Random().nextInt();
        C01R.A0p.markerStart(373302739, nextInt);
        Intent putExtra2 = new Intent(fragmentActivity, CanvasActivity.class).putExtra("IgSessionManager.SESSION_TOKEN_KEY", userSession.token).putExtra(AnonymousClass000.A00(214), androidLink.A0A).putExtra(AnonymousClass000.A00(498), androidLink.A09).putExtra(AnonymousClass000.A00(213), true);
        C4u2 c4u2 = c19356AfS.A0T;
        Intent putExtra3 = putExtra2.putExtra(AnonymousClass000.A00(HttpStatus.SC_SERVICE_UNAVAILABLE), c4u2.getModuleName()).putExtra(AnonymousClass000.A00(HttpStatus.SC_GATEWAY_TIMEOUT), c4u2.isSponsoredEligible());
        B7O b7o = c19356AfS.A0E;
        if (b7o != null) {
            emptyList = b7o.A00;
        } else {
            List A0J = C19763AmC.A0J(b7p, userSession);
            if (A0J != null) {
                emptyList = C25950ws.A0w(A0J);
            } else {
                emptyList = Collections.emptyList();
            }
        }
        Intent putExtra4 = putExtra3.putStringArrayListExtra(AnonymousClass000.A00(506), C25950ws.A0w(emptyList)).putExtra(AnonymousClass000.A00(HttpStatus.SC_HTTP_VERSION_NOT_SUPPORTED), nextInt);
        Reel reel = c19356AfS.A0D;
        String A004 = AnonymousClass000.A00(499);
        String A005 = AnonymousClass000.A00(HttpStatus.SC_NOT_IMPLEMENTED);
        String A006 = AnonymousClass000.A00(HttpStatus.SC_BAD_GATEWAY);
        if (reel != null) {
            putExtra = putExtra4.putExtra(AnonymousClass000.A00(HttpStatus.SC_INSUFFICIENT_STORAGE), reel.getId()).putExtra(AnonymousClass000.A00(509), c19356AfS.A0M).putExtra(AnonymousClass000.A00(94), c19356AfS.A06).putExtra(AnonymousClass000.A00(93), c19356AfS.A0L).putExtra(AnonymousClass000.A00(508), c19356AfS.A07).putExtra(A006, b7i.A4Y);
            iArr = c19356AfS.A0P;
        } else {
            putExtra = putExtra4.putExtra(A006, b7i.A4Y).putExtra(A005, c19356AfS.A0P);
            iArr = c19356AfS.A00;
            A005 = AnonymousClass000.A00(500);
        }
        putExtra.putExtra(A005, iArr).putExtra(A004, c19356AfS.A04);
        C0jI.A02(fragmentActivity, putExtra4);
    }

    public static void A06(InterfaceC21924Bnj interfaceC21924Bnj, B7P b7p, AndroidLink androidLink, C19356AfS c19356AfS) {
        String str = androidLink.A0C;
        str.getClass();
        A0G(interfaceC21924Bnj, c19356AfS, "deeplink", str);
        if (str.startsWith("instagram://extbrowser")) {
            A01(c19356AfS.A0U, b7p, c19356AfS);
        }
        UserSession userSession = c19356AfS.A0U;
        FragmentActivity fragmentActivity = c19356AfS.A0R;
        Context applicationContext = fragmentActivity.getApplicationContext();
        EnumC171469jt enumC171469jt = EnumC171469jt.PAGE_INSTAGRAM_STREAM;
        C25940wr.A1S(userSession, 0, applicationContext);
        if (!C19451Ah4.A00(fragmentActivity, applicationContext, enumC171469jt, b7p, null, userSession, null, null, null, null)) {
            C7GT.A04(fragmentActivity, EnumC170649fW.AD_DESTINATION_DEEPLINK, str);
        }
        C31871GcC.A00(userSession).A07(EnumC171529jz.APP_DEEPLINK);
    }

    /* JADX WARN: Code restructure failed: missing block: B:50:0x0154, code lost:
        if (r2 == p000X.EnumC171169gN.A1p) goto L46;
     */
    /* JADX WARN: Code restructure failed: missing block: B:59:0x019c, code lost:
        if (r7.A1G.Arw().equals(java.lang.Boolean.TRUE) == false) goto L54;
     */
    /* JADX WARN: Code restructure failed: missing block: B:67:0x01bc, code lost:
        if (r7.A1G.Aaf().equals("IG_BOOST") == false) goto L68;
     */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public static void A07(InterfaceC21924Bnj interfaceC21924Bnj, B7P b7p, AndroidLink androidLink, C19356AfS c19356AfS) {
        FragmentActivity fragmentActivity;
        ExtendedImageUrl A2M;
        int i;
        boolean z;
        String str;
        boolean z2;
        boolean z3;
        C158628xW c158628xW;
        Boolean BW4;
        UserSession userSession = c19356AfS.A0U;
        User A0H = B7P.A0H(b7p, userSession);
        String str2 = null;
        A0G(interfaceC21924Bnj, c19356AfS, "leadads", null);
        AbstractC70323iD.getInstance().getPerformanceLogger(userSession).CvT(AnonymousClass006.A01, null, "lead_gen");
        String A38 = b7p.A38(c19356AfS.A03);
        Bundle A07 = C25930wq.A07();
        String str3 = androidLink.A0F;
        if (str3 != null) {
            str2 = str3;
        }
        A07.putString("formID", str2);
        if (A38 != null && b7p.BSR()) {
            B7P A2H = b7p.A2H(c19356AfS.A03);
            A2H.getClass();
            fragmentActivity = c19356AfS.A0R;
            A2M = A2H.A2M(fragmentActivity);
        } else {
            fragmentActivity = c19356AfS.A0R;
            A2M = b7p.A2M(fragmentActivity);
        }
        A07.putParcelable("brandingImageURI", A2M);
        A07.putString("igUserName", A0H.BKR());
        if (!A0H.A3d()) {
            A07.putString("igUserId", A0H.getId());
        }
        boolean z4 = false;
        if (b7p.A2c(userSession) != null && A0H.A0n() != null) {
            i = A0H.A0n().intValue();
        } else {
            i = 0;
        }
        A07.putInt(AnonymousClass000.A00(996), i);
        A07.putParcelable(AnonymousClass000.A00(1105), A0H.B4d());
        B7I b7i = b7p.A0f;
        A07.putString("mediaID", b7i.A4Y);
        A07.putString("adID", C19763AmC.A03(b7p, userSession));
        A07.putString("app", "instagram");
        A07.putString("trackingToken", b7p.BIM());
        A07.putInt("carouselIndex", c19356AfS.A03);
        A07.putInt("mediaPosition", c19356AfS.A05);
        A07.putBoolean(AnonymousClass000.A00(394), C19753Am2.A0D(userSession, C19763AmC.A03(b7p, userSession)));
        C0OR.A0B(userSession, 0);
        B7O A0H2 = C150628fA.A0H(b7p, userSession);
        if (A0H2 != null) {
            z = A0H2.A0g;
        } else {
            C158628xW c158628xW2 = b7i.A1G;
            if (c158628xW2 != null && c158628xW2.Aaf() != null) {
                z = true;
            }
            z = false;
        }
        A07.putBoolean(AnonymousClass000.A00(290), z);
        B7O A0H3 = C150628fA.A0H(b7p, userSession);
        if (A0H3 == null || (str = A0H3.A0K) == null) {
            C158628xW c158628xW3 = b7i.A1G;
            if (c158628xW3 != null && c158628xW3.Aaf() != null) {
                str = b7i.A1G.Aaf();
            } else {
                str = "UNKNOWN";
            }
            C0OR.A06(str);
        }
        A07.putString(AnonymousClass000.A00(991), str);
        B7O A0H4 = C150628fA.A0H(b7p, userSession);
        if (A0H4 != null) {
            z2 = A0H4.A0u;
        } else {
            C158628xW c158628xW4 = b7i.A1G;
            if (c158628xW4 != null && c158628xW4.Arw() != null) {
                z2 = true;
            }
            z2 = false;
        }
        A07.putBoolean(AnonymousClass000.A00(139), z2);
        if (b7p.A4Q() || ((c158628xW = b7i.A1G) != null && (BW4 = c158628xW.BW4()) != null && BW4.booleanValue())) {
            z4 = true;
        }
        A07.putBoolean("is_sensitive_vertical_ad", z4);
        A07.putString(AnonymousClass000.A00(718), A38);
        EnumC171169gN enumC171169gN = c19356AfS.A0V;
        C0OR.A0B(enumC171169gN, 0);
        if (enumC171169gN != EnumC171169gN.A1y && enumC171169gN != EnumC171169gN.A18 && enumC171169gN != EnumC171169gN.A2R) {
            z3 = false;
        }
        z3 = true;
        A07.putBoolean(AnonymousClass000.A00(1070), z3);
        A07.putString("entry_point", enumC171169gN.toString());
        Intent intent = new Intent(fragmentActivity, LeadAdsActivity.class);
        intent.putExtras(A07);
        intent.putExtra("IgSessionManager.SESSION_TOKEN_KEY", userSession.token);
        C32895GyE.A00(userSession).A06(fragmentActivity);
        C0jI.A02(fragmentActivity, intent);
    }

    public static void A08(InterfaceC21924Bnj interfaceC21924Bnj, B7P b7p, AndroidLink androidLink, C19356AfS c19356AfS) {
        String str = androidLink.A0C;
        str.getClass();
        A0G(interfaceC21924Bnj, c19356AfS, "map", str);
        UserSession userSession = c19356AfS.A0U;
        A01(userSession, b7p, c19356AfS);
        Reel reel = c19356AfS.A0D;
        FragmentActivity fragmentActivity = c19356AfS.A0R;
        if (reel != null) {
            C69893c5.A03(fragmentActivity, c19356AfS.A08, new Intent(AnonymousClass000.A00(19)).setFlags(268435456).setData(C23320rx.A01(str)));
        } else {
            C7GT.A04(fragmentActivity, EnumC170649fW.AD_DESTINATION_MAP, str);
        }
        C31871GcC.A00(userSession).A07(EnumC171529jz.MAP);
    }

    public static void A09(InterfaceC21924Bnj interfaceC21924Bnj, B7P b7p, AndroidLink androidLink, C19356AfS c19356AfS) {
        EnumC171159gM enumC171159gM;
        String str = androidLink.A0C;
        A0G(interfaceC21924Bnj, c19356AfS, "mini_shop_collection", str);
        str.getClass();
        Uri A01 = C23320rx.A01(str);
        String queryParameter = A01.getQueryParameter("collection_id");
        if (TextUtils.isEmpty(queryParameter)) {
            enumC171159gM = EnumC171159gM.A0E;
        } else {
            enumC171159gM = EnumC171159gM.A0C;
        }
        String queryParameter2 = A01.getQueryParameter("business_user_id");
        queryParameter2.getClass();
        String queryParameter3 = A01.getQueryParameter("business_username");
        queryParameter3.getClass();
        EnumC170999g5 A00 = C18985AXy.A00(A01.getQueryParameter("collection_type"));
        C18862ASx A0G = AbstractC19674Akj.A00.A0G(c19356AfS.A0R, enumC171159gM, c19356AfS.A0U, null, c19356AfS.A0T.getModuleName());
        A0G.A0A = queryParameter3;
        A0G.A09 = queryParameter2;
        A0G.A0G = queryParameter3;
        A0G.A08 = b7p.A0f.A4Y;
        A0G.A0I = true;
        if (enumC171159gM == EnumC171159gM.A0C) {
            queryParameter.getClass();
            A0G.A01(A00, queryParameter);
        }
        if (enumC171159gM == EnumC171159gM.A0E) {
            A0G.A0B = "instant_collection";
            if (b7p.A4E()) {
                A0G.A0H = true;
            }
        }
        A0G.A00();
    }

    public static void A0A(InterfaceC21924Bnj interfaceC21924Bnj, B7P b7p, AndroidLink androidLink, C19356AfS c19356AfS) {
        String str = androidLink.A0C;
        A0G(interfaceC21924Bnj, c19356AfS, "mini_shop_storefront", str);
        str.getClass();
        Uri A01 = C23320rx.A01(str);
        String queryParameter = A01.getQueryParameter("merchant_id");
        queryParameter.getClass();
        String queryParameter2 = A01.getQueryParameter("business_username");
        queryParameter2.getClass();
        AbstractC19674Akj abstractC19674Akj = AbstractC19674Akj.A00;
        FragmentActivity fragmentActivity = c19356AfS.A0R;
        UserSession userSession = c19356AfS.A0U;
        C4u2 c4u2 = c19356AfS.A0T;
        C19537AiU A0K = abstractC19674Akj.A0K(fragmentActivity, SellerShoppableFeedType.NONE, c4u2, userSession, null, c4u2.getModuleName(), "ad_feed", queryParameter, queryParameter2);
        A0K.A02 = b7p;
        A0K.A0H = C25930wq.A1Y(c19356AfS.A0D);
        A0K.A03();
    }

    public static void A0B(InterfaceC21924Bnj interfaceC21924Bnj, B7P b7p, AndroidLink androidLink, C19356AfS c19356AfS) {
        String str = androidLink.A0C;
        str.getClass();
        A0G(interfaceC21924Bnj, c19356AfS, "phone", str);
        UserSession userSession = c19356AfS.A0U;
        C4u2 c4u2 = c19356AfS.A0T;
        ((C31693GTx) userSession.A01(C31693GTx.class, new IDxObjectShape229S0100000_5_I2(userSession, 6))).A01(b7p, c4u2.getModuleName());
        FragmentActivity fragmentActivity = c19356AfS.A0R;
        String moduleName = c4u2.getModuleName();
        C18836ARs c18836ARs = c19356AfS.A0G;
        C25940wr.A1S(userSession, 0, str);
        C7nW c7nW = new C7nW(userSession, b7p.BIM(), moduleName);
        c7nW.A03(C7G5.A05(fragmentActivity, AnonymousClass000.A00(1001)));
        if (c18836ARs != null) {
            c18836ARs.A01();
        }
        C3L5 A04 = C150708fI.A04(userSession);
        String formatNumber = PhoneNumberUtils.formatNumber(C8QA.A0c(str, "tel:", "", false), C70253i2.A02().getCountry());
        C0OR.A06(formatNumber);
        A04.A09(C25920wp.A0n(fragmentActivity, formatNumber, 2131822824), new IDxCListenerShape10S1200000_2_I2(fragmentActivity, c7nW, str, 6));
        A04.A02 = new B9Z(c18836ARs, c7nW);
        new GZ6(A04).A01(fragmentActivity);
        C7nW.A02(c7nW, AnonymousClass000.A00(701));
        C31871GcC.A00(userSession).A07(EnumC171529jz.PHONE_CALL);
    }

    /* JADX WARN: Code restructure failed: missing block: B:21:0x006e, code lost:
        if (r11 == null) goto L40;
     */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public static void A0C(InterfaceC21924Bnj interfaceC21924Bnj, B7P b7p, AndroidLink androidLink, C19356AfS c19356AfS) {
        C20020Ats A0H;
        Integer num;
        B7P b7p2;
        ProductImageContainer productImageContainer;
        Merchant merchant;
        String str;
        ExtendedImageUrl extendedImageUrl;
        List A3K;
        Object obj;
        String str2 = androidLink.A0C;
        A0G(interfaceC21924Bnj, c19356AfS, "shopping_pdp", str2);
        UserSession userSession = c19356AfS.A0U;
        b7p.A2c(userSession).getClass();
        if (str2 != null) {
            Uri A01 = C23320rx.A01(str2);
            String A012 = C19686Akv.A01(androidLink);
            Product A00 = C19686Akv.A00(b7p, androidLink);
            boolean equals = RealtimeSubscription.GRAPHQL_MQTT_VERSION.equals(C23320rx.A01(str2).getQueryParameter(AnonymousClass000.A00(289)));
            if (A00 == null && A012 != null) {
                if (b7p.BSR() && (A3K = b7p.A3K()) != null) {
                    Iterator it = A3K.iterator();
                    while (true) {
                        obj = null;
                        if (!it.hasNext()) {
                            break;
                        }
                        Object next = it.next();
                        C156888ug c156888ug = ((B7P) next).A0f.A0W;
                        if (c156888ug != null) {
                            obj = c156888ug.A06;
                        }
                        if (C0OR.A0I(obj, A012)) {
                            obj = next;
                            break;
                        }
                    }
                    b7p2 = (B7P) obj;
                }
                b7p2 = b7p;
                C156888ug c156888ug2 = b7p2.A0f.A0W;
                A00 = null;
                if (c156888ug2 != null) {
                    String str3 = c156888ug2.A06;
                    String str4 = c156888ug2.A05;
                    String str5 = c156888ug2.A01;
                    String str6 = c156888ug2.A02;
                    String str7 = c156888ug2.A03;
                    String str8 = c156888ug2.A04;
                    ImageInfo A2N = b7p2.A2N();
                    if (A2N != null) {
                        List list = A2N.A05;
                        if (list != null && (extendedImageUrl = (ExtendedImageUrl) list.get(0)) != null) {
                            str = extendedImageUrl.A0A;
                        } else {
                            str = null;
                        }
                        productImageContainer = new ProductImageContainer(A2N, str);
                    } else {
                        productImageContainer = null;
                    }
                    Merchant merchant2 = c156888ug2.A00;
                    if (merchant2 != null) {
                        merchant = new Merchant(merchant2.A00, merchant2.A01, merchant2.A02, merchant2.A03, merchant2.A04, merchant2.A05, merchant2.A06, merchant2.A07, merchant2.A08);
                    } else {
                        merchant = null;
                    }
                    A00 = new Product(merchant, productImageContainer, str3, str4, str5, str6, str7, str8);
                }
            }
            if (A00 != null) {
                c19356AfS.A0I = A00.A00.A0j;
                AbstractC19674Akj abstractC19674Akj = AbstractC19674Akj.A00;
                FragmentActivity fragmentActivity = c19356AfS.A0R;
                C4u2 c4u2 = c19356AfS.A0T;
                String queryParameter = A01.getQueryParameter("entry_point");
                queryParameter.getClass();
                A0H = abstractC19674Akj.A0I(fragmentActivity, c4u2, A00, userSession, queryParameter, null);
            } else if (!TextUtils.isEmpty(A012)) {
                AbstractC19674Akj abstractC19674Akj2 = AbstractC19674Akj.A00;
                FragmentActivity fragmentActivity2 = c19356AfS.A0R;
                A012.getClass();
                ProductReviewStatus productReviewStatus = ProductReviewStatus.APPROVED;
                String A0e = C150678fF.A0e(str2);
                A0e.getClass();
                String BKR = b7p.A2c(userSession).BKR();
                C4u2 c4u22 = c19356AfS.A0T;
                String queryParameter2 = A01.getQueryParameter("entry_point");
                queryParameter2.getClass();
                A0H = abstractC19674Akj2.A0H(fragmentActivity2, productReviewStatus, c4u22, userSession, A012, A0e, BKR, queryParameter2, null);
                A0H.A0V = C19686Akv.A04(androidLink);
            } else {
                throw C25930wq.A0X("Product or product ID is not found");
            }
            A0H.A0W = equals;
            int i = c19356AfS.A03;
            if (-1 != i) {
                num = Integer.valueOf(i);
            } else {
                num = null;
            }
            A0H.A03(b7p, num);
            A0H.A0X = true;
            A0H.A0Z = true;
            C37786JmD.A0D(C25930wq.A1Y(A0H.A03));
            C20020Ats.A01(A0H, false);
            return;
        }
        throw C25930wq.A0X("DeeplinkUri is null");
    }

    public static void A0D(InterfaceC21924Bnj interfaceC21924Bnj, B7P b7p, AndroidLink androidLink, C19356AfS c19356AfS) {
        String A0C;
        List emptyList;
        String str;
        IGCallExtensionModel iGCallExtensionModel;
        IABAdsContext iABAdsContext;
        String A03;
        C5K7 c5k7;
        Integer num;
        EnumC1026665s enumC1026665s;
        List<IGPostClickEligibleExperienceTypes> list;
        EnumC1026665s enumC1026665s2;
        C158628xW c158628xW;
        String str2 = androidLink.A0K;
        str2.getClass();
        A0G(interfaceC21924Bnj, c19356AfS, "webclick", str2);
        FragmentActivity fragmentActivity = c19356AfS.A0R;
        UserSession userSession = c19356AfS.A0U;
        C4u2 c4u2 = c19356AfS.A0T;
        if (!C7GT.A08(fragmentActivity, userSession, str2, c4u2.getModuleName())) {
            Reel reel = c19356AfS.A0D;
            if (reel != null) {
                A0C = reel.BDU(userSession);
            } else {
                B7O b7o = c19356AfS.A0E;
                if (b7o != null) {
                    A0C = b7o.A0b;
                } else {
                    A0C = C19763AmC.A0C(b7p, userSession);
                }
            }
            Fragment fragment = c19356AfS.A0Q;
            EnumC171169gN enumC171169gN = c19356AfS.A0V;
            B7I b7i = b7p.A0f;
            String str3 = b7i.A4Y;
            String A032 = C19763AmC.A03(b7p, userSession);
            B7O b7o2 = c19356AfS.A0E;
            if (b7o2 != null) {
                emptyList = b7o2.A00;
            } else {
                List A0J = C19763AmC.A0J(b7p, userSession);
                if (A0J != null) {
                    emptyList = C25950ws.A0w(A0J);
                } else {
                    emptyList = Collections.emptyList();
                }
            }
            String str4 = androidLink.A0H;
            String moduleName = c4u2.getModuleName();
            String str5 = c19356AfS.A0M;
            String str6 = c19356AfS.A0L;
            String A0D = C19763AmC.A0D(b7p, userSession);
            C0OR.A0B(userSession, 0);
            B7O A0H = C150628fA.A0H(b7p, userSession);
            if (A0H != null) {
                str = A0H.A0O;
            } else {
                C158628xW c158628xW2 = b7i.A1G;
                if (c158628xW2 != null) {
                    str = c158628xW2.B1b();
                } else {
                    str = null;
                }
            }
            String BIM = b7p.BIM();
            if (!C17570hg.A08(str) && C70763jC.A0E(C0TD.A05, userSession, 36323053818355323L)) {
                iGCallExtensionModel = new IGCallExtensionModel(BIM, str);
            } else {
                iGCallExtensionModel = null;
            }
            String str7 = null;
            if (C70763jC.A0E(C0TD.A05, userSession, 36326841979512598L) && (A03 = C19763AmC.A03(b7p, userSession)) != null) {
                B7O A0H2 = C150628fA.A0H(b7p, userSession);
                if (A0H2 == null || (c158628xW = A0H2.A0D.A0f.A1G) == null || (c5k7 = c158628xW.A07) == null) {
                    C158628xW c158628xW3 = b7i.A1G;
                    if (c158628xW3 != null) {
                        c5k7 = c158628xW3.A07;
                    } else {
                        c5k7 = null;
                    }
                }
                ArrayList A0w = C25920wp.A0w();
                if (c5k7 != null && (list = c5k7.A01) != null) {
                    for (IGPostClickEligibleExperienceTypes iGPostClickEligibleExperienceTypes : list) {
                        int ordinal = iGPostClickEligibleExperienceTypes.ordinal();
                        if (ordinal != 3) {
                            if (ordinal != 2) {
                                if (ordinal != 1) {
                                    enumC1026665s2 = EnumC1026665s.UNSET_OR_UNRECOGNIZED_ENUM_VALUE;
                                } else {
                                    enumC1026665s2 = EnumC1026665s.IAB_META_CHECKOUT_FIRMLY;
                                }
                            } else {
                                enumC1026665s2 = EnumC1026665s.IAB_META_CHECKOUT_SDK;
                            }
                        } else {
                            enumC1026665s2 = EnumC1026665s.IAB_META_CHECKOUT_SCA;
                        }
                        A0w.add(enumC1026665s2);
                    }
                }
                LinkedHashMap A0o = C25970wu.A0o();
                if (c5k7 != null) {
                    List<C5K8> list2 = c5k7.A02;
                    if (list2 != null) {
                        for (C5K8 c5k8 : list2) {
                            ArrayList A0w2 = C25920wp.A0w();
                            List<C5K9> list3 = c5k8.A02;
                            if (list3 != null) {
                                for (C5K9 c5k9 : list3) {
                                    int i = 0;
                                    int A05 = C25970wu.A05(c5k9.A01);
                                    Integer num2 = c5k9.A00;
                                    if (num2 != null) {
                                        i = num2.intValue();
                                    }
                                    A0w2.add(new DisclaimerBodyUrlRanges(A05, i, c5k9.A02));
                                }
                            }
                            IGPostClickEligibleExperienceTypes iGPostClickEligibleExperienceTypes2 = c5k8.A00;
                            if (iGPostClickEligibleExperienceTypes2 != null) {
                                int ordinal2 = iGPostClickEligibleExperienceTypes2.ordinal();
                                if (ordinal2 != 3) {
                                    if (ordinal2 != 2) {
                                        if (ordinal2 != 1) {
                                            enumC1026665s = EnumC1026665s.UNSET_OR_UNRECOGNIZED_ENUM_VALUE;
                                        } else {
                                            enumC1026665s = EnumC1026665s.IAB_META_CHECKOUT_FIRMLY;
                                        }
                                    } else {
                                        enumC1026665s = EnumC1026665s.IAB_META_CHECKOUT_SDK;
                                    }
                                } else {
                                    enumC1026665s = EnumC1026665s.IAB_META_CHECKOUT_SCA;
                                }
                                A0o.put(enumC1026665s, new DisclaimerText(c5k8.A01, A0w2));
                            }
                        }
                    }
                    num = c5k7.A00;
                } else {
                    num = null;
                }
                ImmutableList A0Q = C25970wu.A0Q(C00I.A0N(A0w));
                User user = b7i.A1i;
                if (user != null) {
                    str7 = user.B4d().getUrl();
                }
                iABAdsContext = new IABAdsContext(A0Q, num, A03, str7, C0ZV.A00, A0o);
            } else {
                iABAdsContext = null;
            }
            C7GT.A02(iGCallExtensionModel, fragment, iABAdsContext, userSession, enumC171169gN, null, str2, str3, A032, str4, moduleName, A0C, str5, str6, A0D, emptyList);
        }
    }

    /* JADX WARN: Code restructure failed: missing block: B:52:0x00ea, code lost:
        if (r15.A3d() != r7) goto L94;
     */
    /* JADX WARN: Code restructure failed: missing block: B:5:0x001e, code lost:
        if (p000X.C70763jC.A0E(p000X.C0TD.A05, r2, 36326618641213121L) == false) goto L113;
     */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public static void A0E(InterfaceC21924Bnj interfaceC21924Bnj, B7P b7p, AndroidLink androidLink, C19356AfS c19356AfS, boolean z) {
        boolean z2;
        String str;
        String str2;
        String str3;
        String str4;
        String str5;
        EnumC171469jt enumC171469jt;
        ClickToMessagingAdsInfo A28;
        boolean z3;
        String str6;
        OnFeedMessages onFeedMessages;
        String str7;
        EnumC171029g9 enumC171029g9;
        UserSession userSession = c19356AfS.A0U;
        boolean A1Z = C25920wp.A1Z(userSession, b7p);
        if (!b7p.A4Q()) {
            z2 = true;
        }
        z2 = false;
        Boolean valueOf = Boolean.valueOf(z2);
        if (c19356AfS.A0D == null) {
            C25920wp.A11(C37511yy.A02(C70173gG.A03(userSession)), "has_seen_direct_reply_bottom_sheet", true);
            FragmentActivity fragmentActivity = c19356AfS.A0R;
            C32614Gsp A00 = C6N7.A00(userSession);
            if (valueOf.booleanValue()) {
                b7p.A2c(userSession);
                C18952AWr.A01(userSession);
                throw null;
            }
            b7p.A2c(userSession);
            C19763AmC.A03(b7p, userSession);
            C18952AWr.A00(b7p, userSession);
            EnumC171469jt enumC171469jt2 = EnumC171469jt.PAGE_INSTAGRAM_STREAM;
            Integer valueOf2 = Integer.valueOf(c19356AfS.A03);
            C0OR.A0B(userSession, 0);
            if (!C19451Ah4.A00(fragmentActivity, fragmentActivity, enumC171469jt2, b7p, null, userSession, valueOf2, "feed_ufi", null, null)) {
                throw C25950ws.A0n();
            }
            C150698fH.A1T(A00, A1Z);
        }
        int ordinal = c19356AfS.A0V.ordinal();
        switch (ordinal) {
            case 3:
                str = "row_cta";
                break;
            case 5:
                str = "profile_cta";
                break;
            case 6:
                str = "feed_contextual_profile_cta";
                break;
            case 7:
                str = "reel_profile_cta";
                break;
            case 8:
                str = "comment_cta";
                break;
            case 100:
                str = "like_cta";
                break;
            case 110:
                str = "single_media_cta";
                break;
            case 117:
                str = "clips_cta";
                break;
            default:
                switch (ordinal) {
                    case 7:
                    case HttpStatus.SC_SWITCHING_PROTOCOLS /* 101 */:
                    case HttpStatus.SC_PROCESSING /* 102 */:
                    case 106:
                    case 111:
                    case 112:
                    case 113:
                        str = "reel_cta";
                        break;
                    default:
                        str = null;
                        break;
                }
        }
        Reel reel = c19356AfS.A0D;
        String str8 = null;
        if (reel != null) {
            str2 = reel.getId();
        } else {
            str2 = null;
        }
        if (c19356AfS.A0D != null) {
            str3 = c19356AfS.A0J;
        } else {
            str3 = null;
        }
        if (C19763AmC.A03(b7p, userSession) != null) {
            str4 = C19763AmC.A03(b7p, userSession);
        } else {
            str4 = "";
        }
        if (!b7p.A45() || androidLink == null || (str5 = androidLink.A0E) == null || !C70763jC.A0E(C0TD.A05, userSession, 36319677974058291L)) {
            str5 = null;
        }
        C20562B8r c20562B8r = c19356AfS.A0B;
        if (c20562B8r != null && ((enumC171029g9 = c20562B8r.A0Z) == EnumC171029g9.A08 || enumC171029g9 == EnumC171029g9.A09)) {
            enumC171469jt = EnumC171469jt.PAGE_INSTAGRAM_EXPLORE_CONTEXTUAL;
        } else if (c19356AfS.A0D != null) {
            enumC171469jt = EnumC171469jt.PAGE_INSTAGRAM_STORY;
        } else {
            enumC171469jt = EnumC171469jt.PAGE_INSTAGRAM_STREAM;
        }
        C0OR.A0B(userSession, 0);
        String A03 = C19763AmC.A03(b7p, userSession);
        B7O A0H = C150628fA.A0H(b7p, userSession);
        if (A0H != null) {
            A28 = A0H.A0B;
        } else {
            A28 = b7p.A28();
        }
        User A2c = b7p.A2c(userSession);
        if (A2c != null) {
            z3 = true;
        }
        z3 = false;
        Spannable spannable = null;
        if (z3) {
            str6 = C19763AmC.A0D(b7p, userSession);
        } else if (A2c != null) {
            str6 = A2c.BKR();
        } else {
            str6 = null;
        }
        if (A28 != null) {
            onFeedMessages = A28.A00;
        } else {
            onFeedMessages = null;
        }
        if (str6 != null && onFeedMessages != null) {
            spannable = C19679Ako.A00(onFeedMessages, str6);
        }
        if (A28 != null && C25940wr.A1Z(A28.A03, A1Z) && spannable != null && spannable.length() != 0 && C70763jC.A0E(C0TD.A05, userSession, 36324376668348883L)) {
            str7 = RealtimeSubscription.GRAPHQL_MQTT_VERSION;
        } else {
            str7 = "0";
        }
        C32422GpQ A0O = C25920wp.A0O(userSession);
        A0O.A0P("direct_v2/click_to_direct_ad_interaction_trigger/");
        C25990ww.A1E(A0O);
        A0O.A0U("ad_id", A03);
        C128227Fr.A03(C25940wr.A0O(A0O, "should_enable_ctd_thread_landing", str7));
        if (z2) {
            b7p.A2c(userSession);
            C18952AWr.A01(userSession);
            throw null;
        }
        b7p.A2c(userSession);
        FragmentActivity fragmentActivity2 = c19356AfS.A0R;
        C18952AWr.A00(b7p, userSession);
        Context applicationContext = fragmentActivity2.getApplicationContext();
        AIR air = c19356AfS.A0F;
        Integer valueOf3 = Integer.valueOf(c19356AfS.A06);
        C25930wq.A1Q(applicationContext, 3, enumC171469jt);
        if (!C19451Ah4.A00(fragmentActivity2, applicationContext, enumC171469jt, b7p, air, userSession, valueOf3, str, str2, str3)) {
            AbstractC31842GbY A0X = C25970wu.A0X(fragmentActivity2);
            if (A0X != null) {
                C29418FVh c29418FVh = (C29418FVh) A0X;
                if (c29418FVh.A0M) {
                    c29418FVh.A0B = new BKK(androidLink, c19356AfS, A0X, str5, str, str4);
                    A0X.A08();
                } else {
                    A0I(c19356AfS, str);
                }
            } else {
                return;
            }
        }
        User user = b7p.A0f.A1i;
        if (user != null) {
            str8 = user.getId();
        }
        C19394Ag7.A01(userSession, str8, "cta_click_send_message");
        if (z) {
            A0G(interfaceC21924Bnj, c19356AfS, "clicktodirect", str5);
            C31871GcC.A00(userSession).A06(EnumC171529jz.CLICK_TO_DIRECT);
        }
    }

    public static void A0F(InterfaceC21924Bnj interfaceC21924Bnj, AndroidLink androidLink, C19356AfS c19356AfS) {
        String str = androidLink.A0C;
        A0G(interfaceC21924Bnj, c19356AfS, "igtv_channel", str);
        str.getClass();
        String queryParameter = C23320rx.A01(str).getQueryParameter("user_id");
        queryParameter.getClass();
        new APG(c19356AfS.A0U, c19356AfS.A0T.getModuleName()).A00(queryParameter, "ad_cta_igtv_channel_link");
        throw null;
    }

    public static void A0G(InterfaceC21924Bnj interfaceC21924Bnj, C19356AfS c19356AfS, String str, String str2) {
        String str3;
        Merchant merchant;
        EnumC171169gN enumC171169gN = EnumC171169gN.A2C;
        EnumC171169gN enumC171169gN2 = c19356AfS.A0V;
        if (enumC171169gN == enumC171169gN2) {
            B7O b7o = c19356AfS.A0E;
            if (b7o != null) {
                str3 = b7o.A0L;
            } else {
                str3 = null;
            }
            C4u2 c4u2 = c19356AfS.A0T;
            String obj = enumC171169gN2.toString();
            B7P b7p = c19356AfS.A0A;
            b7p.getClass();
            UserSession userSession = c19356AfS.A0U;
            USLEBaseShape0S0000000 A0I = C25930wq.A0I(C25920wp.A0L(C20950nT.A01(c4u2, userSession), "instagram_ad_shopping_sheet_action"), 1651);
            ArrayList A39 = b7p.A39();
            Long l = null;
            if (C0hB.A00(A39)) {
                merchant = null;
            } else {
                ProductDetailsProductItemDict productDetailsProductItemDict = ((ProductTag) A39.get(0)).A02;
                C0OR.A0B(productDetailsProductItemDict, 0);
                merchant = productDetailsProductItemDict.A0C;
            }
            if (str3 == null) {
                str3 = C19763AmC.A03(b7p, userSession);
            }
            if (merchant != null && str3 != null) {
                User A0H = B7P.A0H(b7p, userSession);
                C150688fG.A0u(A0I, C25920wp.A0e(A0H.getId()));
                A0I.A0S("ad_id", C25920wp.A0e(str3));
                C150688fG.A19(A0I, A0H.AjD().toString());
                C150668fE.A0m(A0I, null);
                B7I b7i = b7p.A0f;
                C150658fD.A17(A0I, B7P.A0M(A0I, b7p, b7i));
                String str4 = merchant.A06;
                str4.getClass();
                C150618f9.A0u(A0I, str4);
                C150698fH.A19(A0I, obj);
                C25950ws.A1K(A0I, str);
                C150698fH.A11(A0I, obj);
                C150688fG.A1A(A0I, b7p.BIM());
                C150698fH.A10(A0I, str2);
                C150648fC.A0x(A0I, C18978AXr.A01(merchant));
                ArrayList A3E = b7p.A3E(true);
                ArrayList A0w = C25920wp.A0w();
                if (!C0hB.A00(A3E)) {
                    Iterator it = A3E.iterator();
                    while (it.hasNext()) {
                        A0w.add(C25920wp.A0e(C150628fA.A0j(it)));
                    }
                }
                A0I.A0u(A0w);
                ArrayList A3E2 = b7p.A3E(true);
                HashMap A0z = C25920wp.A0z();
                if (!C0hB.A00(A3E2)) {
                    Iterator it2 = A3E2.iterator();
                    while (it2.hasNext()) {
                        Product A0Q = C150638fB.A0Q(it2);
                        String A0y = C91534uT.A0y(A0Q);
                        A0y.getClass();
                        Long A0e = C25920wp.A0e(A0y);
                        List list = (List) A0z.get(A0e);
                        if (list != null) {
                            list.add(C25920wp.A0e(A0Q.A00.A0j));
                        } else {
                            ArrayList A0w2 = C25920wp.A0w();
                            A0w2.add(C25920wp.A0e(A0Q.A00.A0j));
                            A0z.put(A0e, A0w2);
                        }
                    }
                }
                A0I.A0V("product_merchant_ids", A0z);
                ArrayList A3B = b7p.A3B();
                ArrayList A0w3 = C25920wp.A0w();
                if (!C0hB.A00(A3B)) {
                    Iterator it3 = A3B.iterator();
                    while (it3.hasNext()) {
                        A0w3.add(C73823yq.A01(C150658fD.A0h(it3)));
                    }
                }
                C150688fG.A1H(A0I, A0w3);
                B7I.A04(A0I, b7i);
                String str5 = b7i.A4o;
                if (str5 != null) {
                    l = C25920wp.A0e(str5);
                }
                A0I.A0h(l);
                B7P.A1N(A0I, b7p);
                C150688fG.A0y(A0I, C25920wp.A0e(A0H.getId()));
                C150658fD.A1H(A0I, b7p.A0O);
                C150688fG.A0q(A0I, C25930wq.A0U());
                ArrayList A3E3 = b7p.A3E(true);
                ArrayList A0w4 = C25920wp.A0w();
                if (!C0hB.A00(A3E3)) {
                    Iterator it4 = A3E3.iterator();
                    while (it4.hasNext()) {
                        ProductDetailsProductItemDict productDetailsProductItemDict2 = C150638fB.A0Q(it4).A00;
                        if (productDetailsProductItemDict2.A0H != null) {
                            A0w4.add(C25920wp.A0e(productDetailsProductItemDict2.A0j));
                        }
                    }
                }
                A0I.A0U("drops_product_ids", A0w4);
                A0I.BbJ();
                return;
            }
            return;
        }
        C4u2 c4u22 = c19356AfS.A0T;
        String obj2 = enumC171169gN2.toString();
        String str6 = c19356AfS.A0I;
        C19760Am9.A0G(c19356AfS.A0S, interfaceC21924Bnj, c19356AfS.A09, c4u22, c19356AfS.A0U, Float.valueOf(c19356AfS.A01), Float.valueOf(c19356AfS.A02), obj2, str, str2, str6, c19356AfS.A0K, c19356AfS.A0H);
    }

    public static void A0H(B7P b7p, C19356AfS c19356AfS) {
        AndroidLink androidLink;
        B7I b7i = b7p.A0f;
        List list = b7i.A5d;
        if (list != null && !list.isEmpty() && c19356AfS.A0O) {
            androidLink = C19571Aj2.A00(c19356AfS.A0R, b7p, c19356AfS.A0U, ((ReelCTA) C25990ww.A0d(b7i.A5d)).A0E);
        } else {
            androidLink = null;
        }
        C18836ARs c18836ARs = c19356AfS.A0G;
        if (c18836ARs != null) {
            c18836ARs.A01();
        }
        C19324Aes A0M = AbstractC19674Akj.A00.A0M(c19356AfS.A0R, c19356AfS.A0T, c19356AfS.A0U);
        A0M.A05 = AnonymousClass006.A0C;
        C20562B8r c20562B8r = c19356AfS.A0B;
        A0M.A01 = b7p;
        A0M.A02 = c20562B8r;
        InterfaceC21420BfR interfaceC21420BfR = c19356AfS.A0S;
        A0M.A03 = androidLink;
        A0M.A00 = interfaceC21420BfR;
        A0M.A04 = new IDxDListenerShape316S0100000_3_I2(c19356AfS, 20);
        A0M.A01();
    }

    public static void A0I(C19356AfS c19356AfS, String str) {
        if (str == null) {
            C18350ix.A00().Cv8("openDirectReplayFailed", C25950ws.A0t(c19356AfS.A0V, C25940wr.A0m("Entry point is null due to unmatched UrlSource: ")));
            C70743jA.A03(c19356AfS.A0R, "open_link_generic_error", 2131832023, 0);
            return;
        }
        Reel reel = c19356AfS.A0D;
        C25920wp.A11(C37511yy.A02(C70173gG.A03(c19356AfS.A0U)), "has_seen_direct_reply_bottom_sheet", true);
        throw C25950ws.A0n();
    }

    public static boolean A0J(InterfaceC21924Bnj interfaceC21924Bnj, AndroidLink androidLink, C19356AfS c19356AfS, String str) {
        String str2 = androidLink.A0C;
        A0G(interfaceC21924Bnj, c19356AfS, str, str2);
        UserSession userSession = c19356AfS.A0U;
        str2.getClass();
        C0OR.A0B(userSession, 0);
        return C19577Aj8.A01(C19577Aj8.A00(userSession, str2, MediaStreamTrack.VIDEO_TRACK_KIND), true);
    }

    public static void A02(InterfaceC21924Bnj interfaceC21924Bnj, B7P b7p, AndroidLink androidLink, C19356AfS c19356AfS) {
        C37786JmD.A0C(C25930wq.A1Z(C67033Pm.A00(androidLink), EnumC170649fW.AD_DESTINATION_AR_CAMERA));
        UserSession userSession = c19356AfS.A0U;
        User A0H = B7P.A0H(b7p, userSession);
        String str = androidLink.A0C;
        try {
            str.getClass();
            Uri A01 = C23320rx.A01(str);
            Integer A0O = C150698fH.A0O(C0OR.A0I(A01.getHost(), "ar_commerce") ? 1 : 0);
            if (AnonymousClass006.A00 != A0O && !C70763jC.A0E(C0TD.A05, userSession, 36316615662374119L)) {
                return;
            }
            A0G(interfaceC21924Bnj, c19356AfS, "ar_camera", str);
            C25257DKp c25257DKp = C25257DKp.A04;
            FragmentActivity fragmentActivity = c19356AfS.A0R;
            EnumC171709kH enumC171709kH = EnumC171709kH.A0C;
            String queryParameter = A01.getQueryParameter("effect_id");
            queryParameter.getClass();
            String queryParameter2 = A01.getQueryParameter(C25910wo.A00(146));
            queryParameter2.getClass();
            C25221DIt A00 = c25257DKp.A00(fragmentActivity, enumC171709kH, userSession, A0O, queryParameter, queryParameter2);
            A00.A02 = A01.getQueryParameter("device_position");
            A00.A04 = A01.getQueryParameter(DatePickerDialogModule.ARG_MODE);
            A00.A07 = A0H.BKR();
            A00.A06 = A0H.B4d().getUrl();
            A00.A03 = b7p.A0f.A4Y;
            A00.A01 = A01.getQueryParameter(C25910wo.A00(24));
            A00.A00 = A01.getQueryParameter("adgroup_id");
            A00.A05 = A01.getQueryParameter("product_id");
            A00.A00();
        } catch (SecurityException e) {
            C18350ix.A07("arads_camera_url_handler", e);
        }
    }
}
