package p000X;
/* renamed from: X.0lg  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C19900lg {
    public static String A00(int i) {
        switch (i) {
            case 1291:
                return "MSYS_TRACE_TAM_ARMADILLO_MEDIA_RECEIVE";
            case 1353:
                return "MSYS_TRACE_MSYS_LOCAL_SEND_SPEED";
            case 1419:
                return "MSYS_TRACE_RM_SEND_TO_SENT";
            case 1714:
                return "MSYS_TRACE_LABYRINTH_BACKUP_RESTORE_ECHO_SERIALIZATION";
            case 1996:
                return "MSYS_TRACE_MPL_MQTT_TO_SYNC";
            case 2041:
                return "MSYS_TRACE_SYNC";
            case 2263:
                return "MSYS_TRACE_LABYRINTH_BACKUP_UPLOAD_TASK_SERIALIZATION";
            case 2309:
                return "MSYS_TRACE_TAM_CARRIER_MESSAGE_SEND";
            case 2310:
                return "MSYS_TRACE_TAM_CARRIER_MESSAGE_RECEIVE";
            case 2435:
                return "MSYS_TRACE_CHATD_NOTIFICATION_RECEIVE";
            case 2493:
                return "MSYS_TRACE_RICH_MEDIA_SEND_LEGACY";
            case 2620:
                return "MSYS_TRACE_LABYRINTH_BACKUP_RESTORE";
            case 2726:
                return "MSYS_TRACE_MSG_LOCAL_SEND_SPEED";
            case 2911:
                return "MSYS_TRACE_OPEN_MESSAGING_SEND_TO_SENT";
            case 3133:
                return "MSYS_TRACE_MSYS_TASK_QUEUE_DELAY";
            case 3325:
                return "MSYS_TRACE_MESSAGE_SEND_TO_SENT";
            case 3420:
                return "MSYS_TRACE_ARMADILLO_RICH_MEDIA_SEND_TO_SEND";
            case 3424:
                return "MSYS_TRACE_MESSAGING_PLATFORM_TASK_PROCESSING";
            case 3483:
                return "MSYS_TRACE_TAM_ARMADILLO_MEDIA_DOWNLOAD";
            case 3515:
                return "MSYS_TRACE_NETWORK_BYTES_PER10S";
            case 3631:
                return "MSYS_TRACE_ACT_MESSAGE_RECEIVE";
            case 3691:
                return "MSYS_TRACE_SEND_TO_SENT";
            case 3751:
                return "MSYS_TRACE_MSYS_DB_METRICS_DATABASE_STATS";
            case 3765:
                return "MSYS_TRACE_MPL_INBOX_TTRC";
            case 4055:
                return "MSYS_TRACE_TRAFFIC_TOKEN_DEDUCT_FAILURE";
            case 4587:
                return "MSYS_TRACE_SEND_E2E";
            case 4891:
                return "MSYS_TRACE_MSYS_ARMADILLO_LOCAL_SEND_SPEED_RICH_MEDIA";
            case 4969:
                return "MSYS_TRACE_EXECUTION_QUEUE_CONGESTION";
            case 4987:
                return "MSYS_TRACE_TT_BOOTSTRAP_SYNC";
            case 5403:
                return "MSYS_TRACE_MEDIA_SEND_TO_SENT";
            case 5628:
                return "MSYS_TRACE_ARMADILLO_LOCAL_SEND_SPEED";
            case 6031:
                return "MSYS_TRACE_MCIEXECUTION_QUEUE_CONGESTION";
            case 6246:
                return "MSYS_TRACE_DASM_EXEC";
            case 6960:
                return "MSYS_TRACE_MPL_BADGE_READY";
            case 7497:
                return "MSYS_TRACE_CONNECTION_TOKEN";
            case 7529:
                return "MSYS_TRACE_BOOTSTRAP";
            case 7584:
                return "MSYS_TRACE_RESUME_SYNC";
            case 7604:
                return "MSYS_TRACE_LIGHTSPEED_TASK";
            case 7638:
                return "MSYS_TRACE_TAM_ARMADILLO_MEDIA_SEND";
            case 7789:
                return "MSYS_TRACE_TASKS_PER10";
            case 7883:
                return "MSYS_TRACE_TAM_ARMADILLO_MESSAGE_SEND";
            case 8079:
                return "MSYS_TRACE_RICH_MEDIA_DOWNLOAD";
            case 8109:
                return "MSYS_TRACE_MSYS_TASK_EXECUTION_PERF";
            case 8256:
                return "MSYS_TRACE_ARMADILLO_RICH_MEDIA_DOWNLOAD";
            case 8557:
                return "MSYS_TRACE_SYNC_RECEIVE";
            case 8790:
                return "MSYS_TRACE_MQTT_CONNECT";
            case 9255:
                return "MSYS_TRACE_ARMADILLO_TEXT_SEND_TO_SENT";
            case 9446:
                return "MSYS_TRACE_OPEN_TEXT_LOCAL_SEND_SPEED";
            case 9671:
                return "MSYS_TRACE_ALL";
            case 9917:
                return "MSYS_TRACE_TRACE_SYSTEM_DISABLED";
            case 10068:
                return "MSYS_TRACE_ECHO";
            case 10452:
                return "MSYS_TRACE_ACT_OFFLINE_SYNC";
            case 10493:
                return "MSYS_TRACE_MSYS_ARMADILLO_RICH_MEDIA_LOCAL_SEND_TO_SENT";
            case 10565:
                return "MSYS_TRACE_UNKNOWN";
            case 10619:
                return "MSYS_TRACE_ARMADILLO_MESSAGE_SEND_E2E";
            case 10867:
                return "MSYS_TRACE_MDMS_DEFERRED_DEPLOYMENT";
            case 11403:
                return "MSYS_TRACE_TEXT_RECEIVE_MSG";
            case 11426:
                return "MSYS_TRACE_RICH_MEDIA_SEND";
            case 11444:
                return "MSYS_TRACE_MPL_BADGE_TTRC";
            case 11467:
                return "MSYS_TRACE_TAM_TASK_DISPATCH";
            case 11602:
                return "MSYS_TRACE_MSYS_DB_METRICS_TABLE_STATS";
            case 11642:
                return "MSYS_TRACE_LABYRINTH_BACKUP_UPLOAD";
            case 11812:
                return "MSYS_TRACE_ARMADILLO_REGISTRATION";
            case 12004:
                return "MSYS_TRACE_TASK_CLIENT_MODE";
            case 12213:
                return "MSYS_TRACE_TEXT_SEND_LEGACY";
            case 12435:
                return "MSYS_TRACE_INIT_SYNC";
            case 12487:
                return "MSYS_TRACE_ARMADILLO_CONNECTION";
            case 12576:
                return "MSYS_TRACE_OCCAM_THREAD_MARK_READ";
            case 12736:
                return "MSYS_TRACE_LABYRINTH_BACKUP_UPLOAD_ISSUE_TASK";
            case 13544:
                return "MSYS_TRACE_CHATD_CONNECTION_TOKEN";
            case 13691:
                return "MSYS_TRACE_TAM_ARMADILLO_MESSAGE_RECEIVE";
            case 13990:
                return "MSYS_TRACE_ARMADILLO_MESSAGE_SEND_TO_SENT";
            case 14067:
                return "MSYS_TRACE_TAM_TRANSPORT_DISPATCH";
            case 14231:
                return "MSYS_TRACE_OPEN_MESSAGING_LOCAL_SEND_SPEED";
            case 14291:
                return "MSYS_TRACE_CHATD_MESSAGE_SEND";
            case 14454:
                return "MSYS_TRACE_TAM_ARMADILLO_GROUP_CREATE";
            case 14602:
                return "MSYS_TRACE_TRACE_DB_HEALTH";
            case 14890:
                return "MSYS_TRACE_TAM_MESSAGE_SEND";
            case 14938:
                return "MSYS_TRACE_MAILBOX_HEALTH_REPORT_DATA";
            case 15280:
                return "MSYS_TRACE_PRESENCE_REPORT_AVAILABILITY";
            case 15413:
                return "MSYS_TRACE_TEXT_SEND";
            case 15552:
                return "MSYS_TRACE_TAM_TASK_CLIENT_MODE";
            case 15626:
                return "MSYS_TRACE_OPEN_SEND_TO_INVALID_FBID";
            case 15828:
                return "MSYS_TRACE_MSYS_ARMADILLO_LOCAL_SEND_SPEED";
            case 15960:
                return "MSYS_TRACE_TAM_ARMADILLO_MEDIA_CAMERA_ROLL_BACKUP";
            case 16030:
                return "MSYS_TRACE_TAM_ARMADILLO_CAMERA_ROLL_BACKUP_SETTING_CHANGE";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
