package p000X;

import android.view.View;
import com.instagram.model.reels.sponsored.AutoGeneratedCardType;
import com.instagram.service.session.UserSession;
/* renamed from: X.BBl  reason: case insensitive filesystem */
/* loaded from: classes4.dex */
public final class C20616BBl implements InterfaceC21900BnL {
    public final C18704AMh A00;
    public final H0Z A01;
    public final C29417FVg A02;
    public final UserSession A03;

    @Override // p000X.InterfaceC21900BnL
    public final void A8d(GVQ gvq, GVQ gvq2, B7B b7b, C19741Alp c19741Alp) {
    }

    @Override // p000X.InterfaceC21900BnL
    public final void A8f(GVQ gvq, GVQ gvq2, B7B b7b, C19741Alp c19741Alp) {
    }

    @Override // p000X.InterfaceC21900BnL
    public final void A8j(GVQ gvq, GVQ gvq2, B7B b7b, C19741Alp c19741Alp) {
    }

    public C20616BBl(C18704AMh c18704AMh) {
        this.A00 = c18704AMh;
        UserSession userSession = c18704AMh.A05;
        this.A03 = userSession;
        C4u2 c4u2 = c18704AMh.A01;
        this.A01 = new H0Z(c4u2, userSession);
        this.A02 = new C29417FVg(c4u2, userSession);
    }

    @Override // p000X.InterfaceC21900BnL
    public final void A8i(View view, GVQ gvq, GVQ gvq2, B7B b7b, C19741Alp c19741Alp) {
        AutoGeneratedCardType autoGeneratedCardType;
        C25920wp.A1Q(view, b7b);
        C0OR.A0B(gvq, 3);
        if (C19760Am9.A0S(b7b, this.A00.A01)) {
            UserSession userSession = this.A03;
            C0TD c0td = C0TD.A05;
            if (C70763jC.A0E(c0td, userSession, 36311165348872637L)) {
                H0Z h0z = this.A01;
                if (b7b.A0T != AnonymousClass006.A01 || (((autoGeneratedCardType = B7B.A01(b7b).A0f.A1T) != null && AutoGeneratedCardType.ORIGINAL.equals(autoGeneratedCardType)) || b7b.mBrandResearchSurvey != null)) {
                    h0z.A04.put(b7b, view);
                }
                gvq.A01(h0z);
            }
            if (C70763jC.A0E(c0td, userSession, 36318617117266583L)) {
                C29417FVg c29417FVg = this.A02;
                ((AbstractC32982H0a) c29417FVg).A00.put(b7b, view);
                gvq.A01(c29417FVg);
            }
        }
    }
}
