package p000X;
/* renamed from: X.0pU  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C22080pU {
    public static String A00(int i) {
        return i != 2238 ? i != 6674 ? i != 7577 ? i != 7636 ? i != 7899 ? i != 9819 ? i != 10755 ? i != 13671 ? i != 14337 ? "UNDEFINED_QPL_EVENT" : "RP_CLASS_CATCHUP_CLASS_CATCHUP_HOST_BROADCAST_START" : "RP_CLASS_CATCHUP_CLASS_CATCHUP_LATE_JOINER_BROADCAST_STARTED" : "RP_CLASS_CATCHUP_CLASS_CATCHUP_HOST_BROADCAST_END" : "RP_CLASS_CATCHUP_CLASS_CATCHUP_JOINER_BROADCAST_STARTED" : "RP_CLASS_CATCHUP_CLASS_CATCHUP_JOINER_BROADCAST_ENDED" : "RP_CLASS_CATCHUP_CLASS_CATCHUP_JOINER_BROADCAST_CONSENT" : "RP_CLASS_CATCHUP_CLASS_CATCHUP_HOST_BROADCAST_CONSENT" : "RP_CLASS_CATCHUP_CLASS_CATCHUP_HOST_BROADCAST_CANCEL" : "RP_CLASS_CATCHUP_CLASS_CATCHUP_HOST_BROADCAST_CREATE";
    }
}
