package p000X;
/* renamed from: X.0qg  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C22650qg {
    public static String A00(int i) {
        return i != 4109 ? i != 6175 ? i != 8840 ? i != 9576 ? i != 10620 ? i != 11522 ? i != 12786 ? i != 14533 ? i != 14903 ? "UNDEFINED_QPL_EVENT" : "SMARTGLASSES_DEVICE_AR_WIRELESS_EVENT" : "SMARTGLASSES_DEVICE_AUTOCAPTURE_SESSION_END" : "SMARTGLASSES_DEVICE_SNAPPMANAGER_MCU" : "SMARTGLASSES_DEVICE_PHOTO_VIDEO_CAPTURE" : "SMARTGLASSES_DEVICE_SNASSISTANT_MAP_MESSAGE" : "SMARTGLASSES_DEVICE_AUTOCAPTURE_SESSION_BEGIN" : "SMARTGLASSES_DEVICE_SN_INTERACTION" : "SMARTGLASSES_DEVICE_TEST_EVENT_HN" : "SMARTGLASSES_DEVICE_AUTOCAPTURE_SESSION_PAUSE";
    }
}
