package p000X;
/* renamed from: X.0tN  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C24090tN {
    public static String A00(int i) {
        return i != 2928 ? i != 3230 ? i != 5621 ? i != 7988 ? i != 8334 ? i != 8602 ? i != 10325 ? i != 10680 ? i != 11875 ? i != 13214 ? "UNDEFINED_QPL_EVENT" : "WEARABLE_GALLERY_USER_INITIATED_MEDIA_SYNC" : "WEARABLE_GALLERY_RENDER_GRID_ITEM" : "WEARABLE_GALLERY_APP_START" : "WEARABLE_GALLERY_SELF_CARE_TIME_SPENT_IN_TRAY" : "WEARABLE_GALLERY_EDITOR_STICKER_SINGLE_STICKER_LOAD" : "WEARABLE_GALLERY_GRID_SCROLL_RENDER" : "WEARABLE_GALLERY_GET_FULL_RES_IMAGE_REQUEST" : "WEARABLE_GALLERY_RENDER_PAGER_ITEM" : "WEARABLE_GALLERY_EDITOR_PREVIEW_RENDER" : "WEARABLE_GALLERY_ANY_DIRECT_MEDIA_SYNC";
    }
}
