package p000X;
/* renamed from: X.0tg  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C24280tg {
    public static String A00(int i) {
        switch (i) {
            case 1351:
                return "WEARABLE_SCROLL_PERF_SETTINGS_BATTERY_SCROLL_PERF";
            case 1370:
                return "WEARABLE_SCROLL_PERF_SETTINGS_LANGUAGE_SCROLL_PERF";
            case 1417:
                return "WEARABLE_SCROLL_PERF_NOTIFICATION_GROUPS_LIST_SCROLL_PERF";
            case 1448:
                return "WEARABLE_SCROLL_PERF_SETTINGS_WIFI_SCROLL_PERF";
            case 1624:
                return "WEARABLE_SCROLL_PERF_SETTINGS_VOICE_ASSISTANT_SCROLL_PERF";
            case 2020:
                return "WEARABLE_SCROLL_PERF_SETTINGS_WEA_REMINDERS_SCROLL_PERF";
            case 2112:
                return "WEARABLE_SCROLL_PERF_STORIES_VIEWER_CAPTION_DIALOG_SCROLL_PERF";
            case 2348:
                return "WEARABLE_SCROLL_PERF_WEATHER_ADDED_LOCATIONS_SCROLL_PERF";
            case 2459:
                return "WEARABLE_SCROLL_PERF_LAUNCHER_APP_TRAY_SCROLL_PERF";
            case 2620:
                return "WEARABLE_SCROLL_PERF_SETTINGS_PASSCODE_SCROLL_PERF";
            case 2799:
                return "WEARABLE_SCROLL_PERF_WEATHER_SEARCH_LOCATIONS_SCROLL_PERF";
            case 2838:
                return "WEARABLE_SCROLL_PERF_SETTINGS_DICTATION_SCROLL_PERF";
            case 2864:
                return "WEARABLE_SCROLL_PERF_SETTINGS_CMAS_WEA_SCROLL_PERF";
            case 3037:
                return "WEARABLE_SCROLL_PERF_GALLERY_GRID_SCROLL_PERF";
            case 3103:
                return "WEARABLE_SCROLL_PERF_LAUNCHER_FACES_MANAGER_SCROLL_PERF";
            case 3272:
                return "WEARABLE_SCROLL_PERF_SETTINGS_ABOUT_SCROLL_PERF";
            case 3370:
                return "WEARABLE_SCROLL_PERF_SETTINGS_DEVICE_PERSONALIZATION_SCROLL_PERF";
            case 3401:
                return "WEARABLE_SCROLL_PERF_SETTINGS_APPS_SCROLL_PERF";
            case 3629:
                return "WEARABLE_SCROLL_PERF_SETTINGS_SELF_CARE_PERMISSIONS_SCROLL_PERF";
            case 3769:
                return "WEARABLE_SCROLL_PERF_CLOCK_STOPWATCH_LAPS_SCROLL_PERF";
            case 3801:
                return "WEARABLE_SCROLL_PERF_SETTINGS_ACCOUNTS_SCROLL_PERF";
            case 3885:
                return "WEARABLE_SCROLL_PERF_NOTIFICATION_PULLUP_SCROLL_PERF";
            case 3900:
                return "WEARABLE_SCROLL_PERF_SETTINGS_CELLULAR_SCROLL_PERF";
            case 4042:
                return "WEARABLE_SCROLL_PERF_SETTINGS_RESET_SCROLL_PERF";
            case 4063:
                return "WEARABLE_SCROLL_PERF_SETTINGS_MIRRORED_APP_NOTIFICATIONS_SCROLL_PERF";
            case 4335:
                return "WEARABLE_SCROLL_PERF_SETTINGS_APP_NOTIFICATIONS_SCROLL_PERF";
            case 4347:
                return "WEARABLE_SCROLL_PERF_LAUNCHER_PAGER_SCROLL_PERF";
            case 4768:
                return "WEARABLE_SCROLL_PERF_SETTINGS_PRIVACY_SCROLL_PERF";
            case 4950:
                return "WEARABLE_SCROLL_PERF_SETTINGS_BLUETOOTH_DISCOVER_SCROLL_PERF";
            case 5055:
                return "WEARABLE_SCROLL_PERF_COMMSHUB_CALLOG_SCROLL_PERF";
            case 5143:
                return "WEARABLE_SCROLL_PERF_CALENDAR_ACCOUNT_SETTINGS_SCROLL_PERF";
            case 5171:
                return "WEARABLE_SCROLL_PERF_SETTINGS_WEA_HISTORY_SCROLL_PERF";
            case 5475:
                return "WEARABLE_SCROLL_PERF_WORKOUT_AWD_SCROLL_PERF";
            case 5570:
                return "WEARABLE_SCROLL_PERF_WORKOUT_PREMADE_STORIES_SCROLL_PERF";
            case 6065:
                return "WEARABLE_SCROLL_PERF_SETTINGS_TALKBACK_VOLUME_SCROLL_PERF";
            case 6222:
                return "WEARABLE_SCROLL_PERF_SETTINGS_TALKBACK_SCROLL_PERF";
            case 6412:
                return "WEARABLE_SCROLL_PERF_SETTINGS_CAMERA_STORAGE_SCROLL_PERF";
            case 6501:
                return "WEARABLE_SCROLL_PERF_SETTINGS_WEA_MESSAGE_DETAIL_SCROLL_PERF";
            case 6546:
                return "WEARABLE_SCROLL_PERF_SETTINGS_APP_SETTINGS_SCROLL_PERF";
            case 6557:
                return "WEARABLE_SCROLL_PERF_COMMSHUB_INBOX_SCROLL_PERF";
            case 6790:
                return "WEARABLE_SCROLL_PERF_CONTROL_CENTER_PULLDOWN_SCROLL_PERF";
            case 6958:
                return "WEARABLE_SCROLL_PERF_SETTINGS_SYSTEM_UPDATES_SCROLL_PERF";
            case 7033:
                return "WEARABLE_SCROLL_PERF_SETTINGS_CAMERA_QUALITY_SCROLL_PERF";
            case 7081:
                return "WEARABLE_SCROLL_PERF_CLOCK_TIMER_PRESETS_SCROLL_PERF";
            case 7096:
                return "WEARABLE_SCROLL_PERF_SETTINGS_ABOUT_REGULATORY_SCROLL_PERF";
            case 7244:
                return "WEARABLE_SCROLL_PERF_SETTINGS_LOCATION_PERMISSIONS_SCROLL_PERF";
            case 7709:
                return "WEARABLE_SCROLL_PERF_SETTINGS_APP_ABOUT_SCROLL_PERF";
            case 7818:
                return "WEARABLE_SCROLL_PERF_SETTINGS_APP_UPDATES_SCROLL_PERF";
            case 8127:
                return "WEARABLE_SCROLL_PERF_SETTINGS_TALKBACK_VOICE_SCROLL_PERF";
            case 8214:
                return "WEARABLE_SCROLL_PERF_SETTINGS_NOTIFICATIONS_SCROLL_PERF";
            case 8220:
                return "WEARABLE_SCROLL_PERF_SETTINGS_RTT_SCROLL_PERF";
            case 8752:
                return "WEARABLE_SCROLL_PERF_STORIES_VIEWER_SELF_VIEW_SHEET_SCROLL_PERF";
            case 9227:
                return "WEARABLE_SCROLL_PERF_COMMSHUB_THREAD_VIEW_TRANSITION_FRAME_DROPS";
            case 9633:
                return "WEARABLE_SCROLL_PERF_SETTINGS_MAIN_SCROLL_PERF";
            case 9789:
                return "WEARABLE_SCROLL_PERF_MUSIC_BROWSE_SCROLL_PERF";
            case 9824:
                return "WEARABLE_SCROLL_PERF_NOTIFICATION_LIST_SCROLL_PERF";
            case 10105:
                return "WEARABLE_SCROLL_PERF_WEATHER_FULL_DAY_SCROLL_PERF";
            case 10345:
                return "WEARABLE_SCROLL_PERF_SETTINGS_SCREENSHOTS_SCROLL_PERF";
            case 10355:
                return "WEARABLE_SCROLL_PERF_SELFCARE_STICKER_TRAY_SCROLL_PERF";
            case 10579:
                return "WEARABLE_SCROLL_PERF_WEATHER_NEARBY_LOCATIONS_SCROLL_PERF";
            case 10636:
                return "WEARABLE_SCROLL_PERF_CLOCK_ALARM_LIST_SCROLL_PERF";
            case 10824:
                return "WEARABLE_SCROLL_PERF_CALENDAR_EVENT_LIST_SCROLL_PERF";
            case 10894:
                return "WEARABLE_SCROLL_PERF_SETTINGS_AUTOLOCK_TIME_SCROLL_PERF";
            case 11018:
                return "WEARABLE_SCROLL_PERF_SETTINGS_ACCESSIBILITY_SCROLL_PERF";
            case 11180:
                return "WEARABLE_SCROLL_PERF_SETTINGS_STORAGE_SCROLL_PERF";
            case 11364:
                return "WEARABLE_SCROLL_PERF_SETTINGS_PERMISSIONS_SCROLL_PERF";
            case 11428:
                return "WEARABLE_SCROLL_PERF_STORIES_REACTION_SHEET_SCROLL_PERF";
            case 11430:
                return "WEARABLE_SCROLL_PERF_SETTINGS_SYSTEM_SCROLL_PERF";
            case 11530:
                return "WEARABLE_SCROLL_PERF_SETTINGS_LOCATION_REQUESTS_SCROLL_PERF";
            case 11982:
                return "WEARABLE_SCROLL_PERF_STORIES_VIEWER_MEDIA_ZOOM_PERF";
            case 12106:
                return "WEARABLE_SCROLL_PERF_CALENDAR_EVENT_DETAIL_SCROLL_PERF";
            case 12307:
                return "WEARABLE_SCROLL_PERF_CONTROL_CENTER_SCROLL_PERF";
            case 12332:
                return "WEARABLE_SCROLL_PERF_SHARESHEET_MAIN_SCROLL_PERF";
            case 12529:
                return "WEARABLE_SCROLL_PERF_SETTINGS_CONNECTIVITY_SCROLL_PERF";
            case 12534:
                return "WEARABLE_SCROLL_PERF_THREAD_VIEW_SCROLL_PERF";
            case 12575:
                return "WEARABLE_SCROLL_PERF_SETTINGS_APP_PERMISSIONS_SCROLL_PERF";
            case 12670:
                return "WEARABLE_SCROLL_PERF_NOTIFICATION_DETAILS_SCROLL_PERF";
            case 12690:
                return "WEARABLE_SCROLL_PERF_WEATHER_FORECAST_SCROLL_PERF";
            case 12937:
                return "WEARABLE_SCROLL_PERF_SETTINGS_INPUTS_SCROLL_PERF";
            case 13223:
                return "WEARABLE_SCROLL_PERF_CALENDAR_ACCOUNTS_SCROLL_PERF";
            case 13345:
                return "WEARABLE_SCROLL_PERF_SETTINGS_DISPLAY_SCROLL_PERF";
            case 13635:
                return "WEARABLE_SCROLL_PERF_CONTACTS_VIEW_SCROLL_PERF";
            case 13782:
                return "WEARABLE_SCROLL_PERF_WORKOUT_TYPE_LIST_SCROLL_PERF";
            case 13959:
                return "WEARABLE_SCROLL_PERF_SETTINGS_SCREEN_WAKE_SCROLL_PERF";
            case 14103:
                return "WEARABLE_SCROLL_PERF_LAUNCHER_WIDGET_PICKER_SCROLL_PERF";
            case 14237:
                return "WEARABLE_SCROLL_PERF_SETTINGS_BACK_UP_SCROLL_PERF";
            case 14481:
                return "WEARABLE_SCROLL_PERF_SETTINGS_RTT_QUICK_REPLIES_SCROLL_PERF";
            case 14501:
                return "WEARABLE_SCROLL_PERF_MUSIC_PLAYLIST_SCROLL_PERF";
            case 15058:
                return "WEARABLE_SCROLL_PERF_CALENDAR_ADD_ACCOUNT_SCROLL_PERF";
            case 15465:
                return "WEARABLE_SCROLL_PERF_SETTINGS_USAGE_DATA_SCROLL_PERF";
            case 15553:
                return "WEARABLE_SCROLL_PERF_SETTINGS_CAMERA_GENERAL_SCROLL_PERF";
            case 15580:
                return "WEARABLE_SCROLL_PERF_SETTINGS_ALL_LANGUAGES_SCROLL_PERF";
            case 15887:
                return "WEARABLE_SCROLL_PERF_STORIES_VIEWER_LIST_SCROLL_PERF";
            case 16068:
                return "WEARABLE_SCROLL_PERF_SETTINGS_BLUETOOTH_SCROLL_PERF";
            case 16134:
                return "WEARABLE_SCROLL_PERF_SETTINGS_SOUND_AND_HAPTICS_SCROLL_PERF";
            case 16352:
                return "WEARABLE_SCROLL_PERF_SETTINGS_GALLERY_STORAGE_SCROLL_PERF";
            case 16359:
                return "WEARABLE_SCROLL_PERF_WORKOUT_PAST_WORKOUTS_SCROLL_PERF";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
