package p000X;
/* renamed from: X.0tj  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C24310tj {
    public static String A00(int i) {
        return i != 1772 ? i != 3613 ? i != 5120 ? i != 5171 ? i != 6137 ? i != 6428 ? i != 6860 ? i != 7104 ? i != 13418 ? i != 15968 ? "UNDEFINED_QPL_EVENT" : "WEARABLE_SETTINGS_PROVIDER_INSERT" : "WEARABLE_SETTINGS_PROVIDER_BULK_WRITE_TO_DB" : "WEARABLE_SETTINGS_PROVIDER_SYNC_TO_DEVICE" : "WEARABLE_SETTINGS_PROVIDER_BULK_SYNC" : "WEARABLE_SETTINGS_PROVIDER_WRITE_TO_DB" : "WEARABLE_SETTINGS_PROVIDER_GET" : "WEARABLE_SETTINGS_PROVIDER_QUERY" : "WEARABLE_SETTINGS_PROVIDER_COLD_START" : "WEARABLE_SETTINGS_PROVIDER_BULK_INSERT" : "WEARABLE_SETTINGS_PROVIDER_SYNC";
    }
}
