package p000X;
/* renamed from: X.0uo  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C24920uo {
    public static String A00(int i) {
        return i != 2 ? i != 4303 ? i != 4590 ? i != 6537 ? i != 7245 ? i != 9767 ? i != 10568 ? i != 13661 ? i != 10 ? i != 11 ? "UNDEFINED_QPL_EVENT" : "WORKPLACE_FRONTLINE_ACCESS_LOGOUT_OTHER_USER" : "WORKPLACE_FRONTLINE_ACCESS_FORCE_PASSWORD_RESET" : "WORKPLACE_FRONTLINE_ACCESS_CREATE_PERSON_IN_AREA" : "WORKPLACE_FRONTLINE_ACCESS_AREA_COORDINATOR_CREATE_PROVISION_REQUEST" : "WORKPLACE_FRONTLINE_ACCESS_AREA_COORDINATOR_VIEW_PENDING_PROVISION_REQUESTS" : "WORKPLACE_FRONTLINE_ACCESS_AREA_COORDINATOR_VIEW_AREA_MEMBERS" : "WORKPLACE_FRONTLINE_ACCESS_SEARCH_PERSON_IN_AREA" : "WORKPLACE_FRONTLINE_ACCESS_SEND_CLAIM_LINK_VIA_EMAIL" : "WORKPLACE_FRONTLINE_ACCESS_AREAS_FLOW_CREATE_PROVISION_REQUEST" : "WORKPLACE_FRONTLINE_ACCESS_ACCESS_CODE_DIALOG_DISPLAYED";
    }
}
