package p000X;
/* renamed from: X.0uy  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C25010uy {
    public static String A00(int i) {
        switch (i) {
            case 1651:
                return "WORKROOMS_MOBILE_APP_STARTUP";
            case 2055:
                return "WORKROOMS_MOBILE_COMPANION_JOIN";
            case 2735:
                return "WORKROOMS_MOBILE_CANVAS_CREATE_CANVAS";
            case 2936:
                return "WORKROOMS_MOBILE_AUTH_LOGIN_META_WORKS_ACCOUNT";
            case 3245:
                return "WORKROOMS_MOBILE_CALL_TOGGLE_AUDIO_MUTE";
            case 3393:
                return "WORKROOMS_MOBILE_LOBBY_TOGGLE_AUDIO_MUTE";
            case 3511:
                return "WORKROOMS_MOBILE_ASSETS_CHANGE_VIEW_MODE";
            case 4303:
                return "WORKROOMS_MOBILE_ADMIN_MUTE_PARTICIPANT";
            case 4714:
                return "WORKROOMS_MOBILE_FUNDAMENTALS_MENTION_USER";
            case 4843:
                return "WORKROOMS_MOBILE_ASSETS_PIN_ASSET";
            case 4959:
                return "WORKROOMS_MOBILE_CALL_SESSION_FLOW";
            case 5335:
                return "WORKROOMS_MOBILE_LOBBY_JOIN_CALL";
            case 5421:
                return "WORKROOMS_MOBILE_ADMIN_LOCK_ROOM";
            case 5494:
                return "WORKROOMS_MOBILE_SWITCH_CAMERA";
            case 6095:
                return "WORKROOMS_MOBILE_ASSETS_ADD_LINK";
            case 6228:
                return "WORKROOMS_MOBILE_WORKROOM_CREATION";
            case 6371:
                return "WORKROOMS_MOBILE_RAISE_HAND";
            case 6617:
                return "WORKROOMS_MOBILE_CALL_TOGGLE_VIDEO_MUTE";
            case 7210:
                return "WORKROOMS_MOBILE_JOIN_ROOM_CALL";
            case 7281:
                return "WORKROOMS_MOBILE_ASSETS_LOAD_SCREEN";
            case 7416:
                return "WORKROOMS_MOBILE_CANVAS_COPY_LINK";
            case 7524:
                return "WORKROOMS_MOBILE_ASSETS_DELETE_FILE";
            case 8409:
                return "WORKROOMS_MOBILE_CANVAS_DELETE_CANVAS";
            case 8500:
                return "WORKROOMS_MOBILE_MEETING_REMINDER_JOIN";
            case 8753:
                return "WORKROOMS_MOBILE_ASSETS_OPEN_PREVIEW";
            case 8984:
                return "WORKROOMS_MOBILE_ASSETS_DOWNLOAD_FILE";
            case 9377:
                return "WORKROOMS_MOBILE_COMPANION_VIEW";
            case 9468:
                return "WORKROOMS_MOBILE_LOBBY_TOGGLE_VIDEO_MUTE";
            case 9665:
                return "WORKROOMS_MOBILE_LOBBY_TOGGLE_BACKGROUND_BLUR";
            case 9863:
                return "WORKROOMS_MOBILE_CALL_TOGGLE_BACKGROUND_BLUR";
            case 12173:
                return "WORKROOMS_MOBILE_CANVAS_FETCH_CANVASES";
            case 12337:
                return "WORKROOMS_MOBILE_JOIN_PRECALL_LOBBY";
            case 12698:
                return "WORKROOMS_MOBILE_WORKROOM_LEAVE_WORKROOM";
            case 12955:
                return "WORKROOMS_MOBILE_REACTION";
            case 13391:
                return "WORKROOMS_MOBILE_CANVAS_LOAD_SCREEN";
            case 13474:
                return "WORKROOMS_MOBILE_ASSETS_UPLOAD_FILE";
            case 14166:
                return "WORKROOMS_MOBILE_WORKROOM_INVITE";
            case 14593:
                return "WORKROOMS_MOBILE_ASSETS_SHARE_FILE";
            case 14600:
                return "WORKROOMS_MOBILE_AUTH_LOGIN_BROWSER_TO_NATIVE_SSO";
            case 14622:
                return "WORKROOMS_MOBILE_FUNDAMENTALS_LOAD_WORKROOMS";
            case 15066:
                return "WORKROOMS_MOBILE_CANVAS_LOAD_LIST_SCREEN";
            case 15656:
                return "WORKROOMS_MOBILE_ADMIN_MUTE_ALL_PARTICIPANT";
            case 15790:
                return "WORKROOMS_MOBILE_ASSETS_COPY_LINK";
            case 16085:
                return "WORKROOMS_MOBILE_CANVAS_RENAME_CANVAS";
            case 16144:
                return "WORKROOMS_MOBILE_ASSETS_FETCH_ASSETS";
            case 16216:
                return "WORKROOMS_MOBILE_ADMIN_REMOVE_PARTICIPANT";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
