package p000X;
/* renamed from: X.0vC  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C25070vC {
    public static String A00(int i) {
        return i != 1724 ? i != 6050 ? i != 7216 ? i != 9782 ? i != 10045 ? i != 12254 ? i != 12679 ? i != 12824 ? i != 14251 ? i != 16069 ? "UNDEFINED_QPL_EVENT" : "WP_MCG_MIGRATION_LOAD_MCG_MIGRATION_OVERVIEW_CARD" : "WP_MCG_MIGRATION_MCG_LEARN_MORE_WILL_BE_ABLE_TO_MIGRATE" : "WP_MCG_MIGRATION_REVIEW_GUEST_SETTINGS" : "WP_MCG_MIGRATION_TRIALS_LEARN_MORE_DIALOG" : "WP_MCG_MIGRATION_MCG_LEARN_MORE" : "WP_MCG_MIGRATION_TRIALS_MIGRATE_DIALOG" : "WP_MCG_MIGRATION_MCG_UPGRADE_INSTANCE" : "WP_MCG_MIGRATION_TRIALS_ENABLE_GUESTS_DIALOG" : "WP_MCG_MIGRATION_TRIALS_UPGRADE_INSTANCE_DIALOG" : "WP_MCG_MIGRATION_MCG_LEARN_MORE_MOBILE";
    }
}
