package p000X;
/* renamed from: X.0vX  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C25240vX {
    public static String A00(int i) {
        switch (i) {
            case 1044:
                return "XROS_KERNEL_BENCHMARKS_MINI_VMAR_UNMAP_LATENCY";
            case 1084:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_MEM_THROUGHPUT_L1_U1_64KB";
            case 1297:
                return "XROS_KERNEL_BENCHMARKS_MINI_VMAR_BATCH_UNMAP_LATENCY";
            case 1446:
                return "XROS_KERNEL_BENCHMARKS_MINI_PROCESS_CREATION_LATENCY";
            case 1553:
                return "XROS_KERNEL_BENCHMARKS_MICRO_MPN_ALLOC_PAGE_ARCH_ZERO";
            case 1608:
                return "XROS_KERNEL_BENCHMARKS_MICRO_MPN_ALLOC_1_SMALL_PAGE_ZERO";
            case 1625:
                return "XROS_KERNEL_BENCHMARKS_MINI_VMAR_TOUCH_LATENCY";
            case 1664:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_8MB";
            case 1671:
                return "XROS_KERNEL_BENCHMARKS_MIN_PAGEFAULT_RESUME_LATENCY";
            case 1804:
                return "XROS_KERNEL_BENCHMARKS_MICRO_TICKS_READ_LATENCY";
            case 2148:
                return "XROS_KERNEL_BENCHMARKS_MINI_GET_SPINLOCKS_INFO";
            case 2223:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_TLB_32MB";
            case 2671:
                return "XROS_KERNEL_BENCHMARKS_MICRO_MPN_ALLOC_MULTI_SMALL_PAGE";
            case 2722:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_1MB";
            case 2785:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_GET_TICKS_DELTA_TIGHT_LOOP";
            case 2805:
                return "XROS_KERNEL_BENCHMARKS_NIMIMAL_MEM_THROUGHPUT_L1_16KB";
            case 2943:
                return "XROS_KERNEL_BENCHMARKS_MICRO_MPN_ALLOC_MULTI_LARGE_PAGE_ZERO";
            case 3128:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_32MB";
            case 3306:
                return "XROS_KERNEL_BENCHMARKS_MINI_VMAR_BATCH_TOUCH_LATENCY";
            case 3431:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_MEM_THROUGHPUT_L1_U1_4KB";
            case 3495:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_64KB";
            case 3515:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_TLB_512KB";
            case 3614:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_TLB_2MB";
            case 3978:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_MEM_THROUGHPUT_L1";
            case 4065:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_16MB";
            case 4383:
                return "XROS_KERNEL_BENCHMARKS_MINI_GET_PROCESS_INFO_LATENCY";
            case 4607:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_TLB_64MB";
            case 4716:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_64MB";
            case 4778:
                return "XROS_KERNEL_BENCHMARKS_MINI_GET_CPU_INFO_LATENCY";
            case 4937:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_TLB_256KB";
            case 4952:
                return "XROS_KERNEL_BENCHMARKS_MINI_FOOTPRINT_PROCESS_LOCAL_MEM";
            case 5217:
                return "XROS_KERNEL_BENCHMARKS_MINI_VMAR_BATCH_MAP_LATENCY";
            case 5349:
                return "XROS_KERNEL_BENCHMARKS_MINI_PAGESET_BATCH_FREE_LATENCY";
            case 5458:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_128KB";
            case 5466:
                return "XROS_KERNEL_BENCHMARKS_SYNTHETIC_SCHEDULER_FAKEIO";
            case 5687:
                return "XROS_KERNEL_BENCHMARKS_MIN_ONE_THREAD_MIGRATION_LATENCY";
            case 5738:
                return "XROS_KERNEL_BENCHMARKS_MICRO_MPN_ALLOC_MULTI_SMALL_PAGE_ZERO";
            case 6108:
                return "XROS_KERNEL_BENCHMARKS_MINI_PAGESET_FREE_LATENCY";
            case 6238:
                return "XROS_KERNEL_BENCHMARKS_MIN_WORKLOAD_CALLSTACK_SAMPLER_TIMING_TWO";
            case 6243:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_MEM_THROUGHPUT_L1_UNALIGNED1";
            case 6344:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_MEM_THROUGHPUT_L1_U1_16KB";
            case 6401:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_32KB";
            case 6410:
                return "XROS_KERNEL_BENCHMARKS_MICRO_MPN_ALLOC_UINT64_ZERO";
            case 6532:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_LOCAL_MEM_RESERVE_LARGE_RANGE";
            case 6644:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_TLB_4MB";
            case 7257:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_TLB_1MB";
            case 7259:
                return "XROS_KERNEL_BENCHMARKS_MICRO_MPN_ALLOC_1_LARGE_PAGE";
            case 7654:
                return "XROS_KERNEL_BENCHMARKS_MINI_VMAR_MAP_LATENCY";
            case 7980:
                return "XROS_KERNEL_BENCHMARKS_MINI_PAGESET_DESTROY_LATENCY";
            case 8558:
                return "XROS_KERNEL_BENCHMARKS_MINI_GET_SPINLOCKS_INFO_LATENCY";
            case 8622:
                return "XROS_KERNEL_BENCHMARKS_MINI_PAGESET_CREATE_LATENCY";
            case 8713:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_MEM_THROUGHPUT_L1_32KB";
            case 8930:
                return "XROS_KERNEL_BENCHMARKS_MINI_FOOTPRINT_THREAD_PSS";
            case 8943:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_LOCAL_MEM_ALLOC_1_LARGE_RW_PAGE";
            case 9020:
                return "XROS_KERNEL_BENCHMARKS_MICRO_MPN_ALLOC_1_SMALL_PAGE";
            case 9037:
                return "XROS_KERNEL_BENCHMARKS_MINI_FOOTPRINT_PROCESS_KERNEL_MEM";
            case 9179:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_8KB";
            case 9268:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_4MB";
            case 9310:
                return "XROS_KERNEL_BENCHMARKS_MICRO_EXPANDABLE_PORT_WRITE";
            case 9335:
                return "XROS_KERNEL_BENCHMARKS_MINI_THREAD_CREATION_LATENCY";
            case 9706:
                return "XROS_KERNEL_BENCHMARKS_MINI_PORT_WAKEUP_LATENCY";
            case 9774:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_SYSCALL_ROUNDTRIP";
            case 9827:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_MEM_THROUGHPUT_L1_U1_8KB";
            case 9904:
                return "XROS_KERNEL_BENCHMARKS_MINI_IPC_CHANNEL_THROUGHPUT_LARGE";
            case 10044:
                return "XROS_KERNEL_BENCHMARKS_SYNTHETIC_AUDIO_3_WORKERS_3_CPUS";
            case 10100:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_LOCAL_MEM_ALLOC_4_LARGE_RW_PAGE";
            case 10151:
                return "XROS_KERNEL_BENCHMARKS_MINI_PAGESET_BATCH_ALLOC_LATENCY";
            case 10214:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_IPC_CHANNEL_ROUNDTRIP";
            case 10331:
                return "XROS_KERNEL_BENCHMARKS_MINI_PAGESET_BATCH_DESTROY_LATENCY";
            case 10523:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_MEM_THROUGHPUT_L1_4KB";
            case 11010:
                return "XROS_KERNEL_BENCHMARKS_MIN_COW_LATENCY";
            case 11219:
                return "XROS_KERNEL_BENCHMARKS_MINI_IPC_CHANNEL_THROUGHPUT_SMALL_SLEEP";
            case 11526:
                return "XROS_KERNEL_BENCHMARKS_MIN_PAGEFAULT_LATENCY";
            case 11565:
                return "XROS_KERNEL_BENCHMARKS_MINI_PAGESET_BATCH_CREATE_LATENCY";
            case 11686:
                return "XROS_KERNEL_BENCHMARKS_MINI_FOOTPRINT_PROCESS_PSS";
            case 11733:
                return "XROS_KERNEL_BENCHMARKS_MICRO_PORT_WRITE";
            case 11738:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_512KB";
            case 11777:
                return "XROS_KERNEL_BENCHMARKS_MINI_IPC_CHANNEL_THROUGHPUT_LARGE_SLEEP";
            case 12021:
                return "XROS_KERNEL_BENCHMARKS_MIN_WORKLOAD_CALLSTACK_SAMPLER_TIMING_ONE";
            case 12087:
                return "XROS_KERNEL_BENCHMARKS_MINI_IPC_CHANNEL_THROUGHPUT_SMALL";
            case 12139:
                return "XROS_KERNEL_BENCHMARKS_MICRO_PORT_READ";
            case 12249:
                return "XROS_KERNEL_BENCHMARKS_MINI_GET_MEM_INFO_LATENCY";
            case 12366:
                return "XROS_KERNEL_BENCHMARKS_MINI_HANDLE_CREATION_FULL_LATENCY";
            case 12583:
                return "XROS_KERNEL_BENCHMARKS_MIN_PAGEFAULT_REPORT_LATENCY";
            case 12656:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_LOCAL_MEM_ALLOC_1_SMALL_RW_PAGE";
            case 12688:
                return "XROS_KERNEL_BENCHMARKS_MICRO_MPN_ALLOC_ARCH_ZERO";
            case 12983:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_TLB_16MB";
            case 13107:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_4KB";
            case 13198:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_LOCAL_MEM_FREE_128_SMALL_RW_PAGES";
            case 13313:
                return "XROS_KERNEL_BENCHMARKS_MINI_PAGESET_ALLOC_LATENCY";
            case 13323:
                return "XROS_KERNEL_BENCHMARKS_MICRO_MPN_ALLOC_1_LARGE_PAGE_ZERO";
            case 13330:
                return "XROS_KERNEL_BENCHMARKS_MICRO_MPN_ALLOC_MULTI_LARGE_PAGE";
            case 13480:
                return "XROS_KERNEL_BENCHMARKS_MINI_FOOTPRINT_THREAD_KERNEL_MEM";
            case 13647:
                return "XROS_KERNEL_BENCHMARKS_MICRO_EXPANDABLE_PORT_READ";
            case 13803:
                return "XROS_KERNEL_BENCHMARKS_MINI_HANDLE_CREATION_EMPTY_LATENCY";
            case 13909:
                return "XROS_KERNEL_BENCHMARKS_MINI_CONTEXT_SWITCH_LATENCY";
            case 13991:
                return "XROS_KERNEL_BENCHMARKS_MINI_SCHEDULING_LATENCY";
            case 14124:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_TLB_8MB";
            case 14454:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_MEM_THROUGHPUT_L1_64KB";
            case 14768:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_16KB";
            case 15050:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_MEM_THROUGHPUT_L1_U1_32KB";
            case 15060:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_LOCAL_MEM_ALLOC_4_SMALL_RW_PAGE";
            case 15481:
                return "XROS_KERNEL_BENCHMARKS_MINI_FOOTPRINT_THREAD_LOCAL_MEM";
            case 15482:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_MEM_THROUGHPUT_L1_8KB";
            case 15691:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_256KB";
            case 15800:
                return "XROS_KERNEL_BENCHMARKS_MINI_MISC_MEM_THROUGHPUT_2MB";
            case 16092:
                return "XROS_KERNEL_BENCHMARKS_MINIMAL_SYSCALL_COPY_FROM_USER";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
