package p000X;

import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S3200000_I2;
import com.instagram.clips.model.metadata.ClipsFanClubMetadata;
import com.instagram.direct.fragment.thread.welcomevideo.model.DirectChannelsWelcomeVideoMetadata;
import com.instagram.feed.media.CropCoordinates;
import com.instagram.pendingmedia.model.ClipInfo;
import java.util.List;
import java.util.Set;
/* renamed from: X.DSx  reason: case insensitive filesystem */
/* loaded from: classes5.dex */
public final class C25440DSx {
    public float A00;
    public KtCSuperShape0S3200000_I2 A01;
    public C1AO A02;
    public ClipsFanClubMetadata A03;
    public DSM A04;
    public DirectChannelsWelcomeVideoMetadata A05;
    public CropCoordinates A06;
    public EnumC23743Cil A07;
    public C159188yY A08;
    public ClipInfo A09;
    public DYR A0A;
    public Boolean A0B;
    public Boolean A0C;
    public Integer A0D;
    public String A0E;
    public String A0F;
    public String A0G;
    public String A0H;
    public String A0I;
    public String A0J;
    public String A0K;
    public String A0L;
    public String A0M;
    public String A0N;
    public String A0O;
    public String A0P;
    public String A0Q;
    public String A0R;
    public List A0S;
    public List A0T;
    public List A0U;
    public List A0V;
    public List A0W;
    public List A0X;
    public List A0Y;
    public List A0Z;
    public List A0a;
    public List A0b;
    public List A0c;
    public List A0d;
    public Set A0e;
    public boolean A0f;
    public boolean A0g;
    public boolean A0h;
    public boolean A0i;
    public boolean A0j;
    public boolean A0k;
    public boolean A0l;
    public boolean A0m;
    public boolean A0n;
    public boolean A0o;
    public boolean A0p;
    public boolean A0q;
    public boolean A0r;
    public boolean A0s;

    public C25440DSx(KtCSuperShape0S3200000_I2 ktCSuperShape0S3200000_I2, C1AO c1ao, ClipsFanClubMetadata clipsFanClubMetadata, DSM dsm, DirectChannelsWelcomeVideoMetadata directChannelsWelcomeVideoMetadata, CropCoordinates cropCoordinates, EnumC23743Cil enumC23743Cil, C159188yY c159188yY, ClipInfo clipInfo, DYR dyr, Integer num, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, List list, List list2, List list3, List list4, List list5, List list6, List list7, List list8, List list9, List list10, List list11, List list12, Set set, float f, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14, boolean z15, boolean z16) {
        C0OR.A0B(list, 8);
        C0ZV c0zv = C0ZV.A00;
        this.A0T = c0zv;
        this.A0S = c0zv;
        this.A0Z = c0zv;
        this.A0e = C81Q.A00;
        this.A0U = c0zv;
        this.A0b = c0zv;
        this.A0c = c0zv;
        this.A0V = c0zv;
        this.A0X = c0zv;
        this.A0a = c0zv;
        Boolean A0U = C25930wq.A0U();
        this.A0C = A0U;
        this.A0B = A0U;
        this.A0l = true;
        this.A07 = enumC23743Cil;
        this.A0F = str;
        this.A0G = str2;
        this.A0E = str3;
        this.A0L = str4;
        this.A0p = z;
        this.A06 = cropCoordinates;
        this.A0Z = list;
        this.A0q = z2;
        this.A0r = z3;
        this.A0o = z4;
        this.A0M = str5;
        this.A0N = str6;
        this.A0D = num;
        this.A0W = list2;
        this.A0I = str7;
        this.A09 = clipInfo;
        this.A0e = set;
        this.A0b = list3;
        this.A0c = list4;
        this.A0V = list5;
        this.A08 = c159188yY;
        this.A0U = list6;
        this.A0T = list7;
        this.A0S = list8;
        this.A0d = list9;
        this.A01 = ktCSuperShape0S3200000_I2;
        this.A03 = clipsFanClubMetadata;
        this.A0A = dyr;
        this.A04 = dsm;
        this.A0k = z5;
        this.A0g = z6;
        this.A0K = str10;
        this.A0j = z7;
        this.A0O = str8;
        this.A0h = z8;
        this.A0R = str9;
        this.A0X = list10;
        this.A0H = str11;
        this.A0a = list11;
        this.A0Y = list12;
        this.A0i = z9;
        this.A0f = z10;
        this.A0Q = str12;
        this.A0P = str13;
        this.A0m = z11;
        this.A0l = z12;
        this.A0n = z13;
        this.A02 = c1ao;
        this.A05 = directChannelsWelcomeVideoMetadata;
        this.A0J = str14;
        this.A0s = z14;
        this.A0B = Boolean.valueOf(z15);
        this.A0C = Boolean.valueOf(z16);
        this.A00 = f;
    }

    public C25440DSx() {
        C0ZV c0zv = C0ZV.A00;
        this.A0T = c0zv;
        this.A0S = c0zv;
        this.A0Z = c0zv;
        this.A0e = C81Q.A00;
        this.A0U = c0zv;
        this.A0b = c0zv;
        this.A0c = c0zv;
        this.A0V = c0zv;
        this.A0X = c0zv;
        this.A0a = c0zv;
        Boolean A0U = C25930wq.A0U();
        this.A0C = A0U;
        this.A0B = A0U;
        this.A0l = true;
    }
}
