package p000X;

import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S0200000_I2;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S1100000_I2;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S2010000_I2;
import com.instagram.api.schemas.BoostedActionStatus;
import com.instagram.api.schemas.CallToAction;
import com.instagram.api.schemas.Destination;
import com.instagram.api.schemas.DestinationRecommendationReason;
import com.instagram.common.typedurl.ImageUrl;
import com.instagram.leadgen.core.api.LeadForm;
import java.util.HashMap;
import java.util.List;
/* renamed from: X.GDc  reason: case insensitive filesystem */
/* loaded from: classes6.dex */
public final class C31370GDc {
    public int A00;
    public int A01;
    public int A02;
    public int A03;
    public KtCSuperShape0S0200000_I2 A04;
    public KtCSuperShape0S1100000_I2 A05;
    public KtCSuperShape0S2010000_I2 A06;
    public BoostedActionStatus A07;
    public CallToAction A08;
    public CallToAction A09;
    public CallToAction A0A;
    public Destination A0B;
    public Destination A0C;
    public Destination A0D;
    public DestinationRecommendationReason A0E;
    public ImageUrl A0F;
    public ImageUrl A0G;
    public LeadForm A0H;
    public Boolean A0I;
    public Boolean A0J;
    public Boolean A0K;
    public Boolean A0L;
    public String A0M;
    public String A0N;
    public String A0O;
    public String A0P;
    public String A0Q;
    public String A0R;
    public String A0S;
    public String A0T;
    public String A0U;
    public String A0V;
    public String A0W;
    public HashMap A0X;
    public List A0Y;
    public List A0Z;
    public List A0a;
    public List A0b;
    public List A0c;
    public List A0d;
    public boolean A0e;
    public boolean A0f;
    public boolean A0g;
    public boolean A0h;
    public boolean A0i;
    public boolean A0j;
    public boolean A0k;
    public boolean A0l;
    public boolean A0m;
    public boolean A0n;
    public boolean A0o;
    public boolean A0p;
}
