package p000X;

import com.instagram.api.schemas.PrivateReplyStatus;
import com.instagram.common.typedurl.ImageUrl;
import com.instagram.model.hashtag.Hashtag;
import java.util.List;
import java.util.Map;
/* renamed from: X.GDd  reason: case insensitive filesystem */
/* loaded from: classes6.dex */
public final class C31371GDd {
    public int A00;
    public long A01;
    public long A02;
    public PrivateReplyStatus A03;
    public ImageUrl A04;
    public ImageUrl A05;
    public ImageUrl A06;
    public ImageUrl A07;
    public EnumC23783CjR A08;
    public Hashtag A09;
    public GDH A0A;
    public C31219G7f A0B;
    public G24 A0C;
    public C30866FxG A0D;
    public Boolean A0E;
    public Boolean A0F;
    public Boolean A0G;
    public Boolean A0H;
    public Boolean A0I;
    public Long A0J;
    public Long A0K;
    public String A0L;
    public String A0M;
    public String A0N;
    public String A0O;
    public String A0P;
    public String A0Q;
    public String A0R;
    public String A0S;
    public String A0T;
    public String A0U;
    public String A0V;
    public String A0W;
    public String A0X;
    public String A0Y;
    public String A0Z;
    public String A0a;
    public String A0b;
    public String A0c;
    public String A0d;
    public String A0e;
    public String A0f;
    public String A0g;
    public String A0h;
    public String A0i;
    public List A0j;
    public List A0k;
    public List A0l;
    public List A0m;
    public List A0n;
    public List A0o;
    public List A0p;
    public List A0q;
    public Map A0r;
    public boolean A0t;
    public boolean A0s = false;
    public final Map A0w = C25920wp.A0z();
    public final Map A0u = C25920wp.A0z();
    public final Map A0v = C25920wp.A0z();
}
