package p000X;

import java.io.Serializable;
import org.webrtc.CameraVideoCapturer;
/* renamed from: X.4NQ  reason: invalid class name */
/* loaded from: classes2.dex */
public final class C4NQ implements Serializable {
    public final float A0X;
    public final float A0Y;
    public final float A0Z;
    public final float A0a;
    public final float A0b;
    public final float A0c;
    public final float A0d;
    public final float A0e;
    public final float A0f;
    public final float A0g;
    public final float A0h;
    public final float A0i;
    public final float A0j;
    public final int A0k;
    public final int A0l;
    public final int A0m;
    public final int A0n;
    public final int A0o;
    public final int A0p;
    public final int A0q;
    public final int A0r;
    public final int A0s;
    public final int A0t;
    public final int A0u;
    public final int A0v;
    public final int A0w;
    public final int A0x;
    public final int A0y;
    public final int A0z;
    public final int A10;
    public final int A11;
    public final int A12;
    public final int A13;
    public final int A14;
    public final int A15;
    public final int A16;
    public final int A17;
    public final int A18;
    public final int A19;
    public final int A1A;
    public final int A1B;
    public final boolean A1C;
    public final boolean A1D;
    public final boolean A1E;
    public final boolean A1F;
    public final boolean A1G;
    public final boolean A1H;
    public final boolean A1I;
    public final boolean A1J;
    public final boolean A1K;
    public final boolean A1L;
    public final boolean A1M;
    public final boolean A1N;
    public final boolean A1O;
    public final boolean A1P;
    public boolean A0S = false;
    public boolean A0U = false;
    public boolean A0T = false;
    public double A09 = 2.0d;
    public double A0A = 0.0d;
    public double A0B = 0.0d;
    public boolean A0N = false;
    public int A0J = CameraVideoCapturer.CameraStatistics.CAMERA_OBSERVER_PERIOD_MS;
    public double A01 = 2.0d;
    public double A02 = 1.2d;
    public int A0K = 0;
    public double A0C = 1.0d;
    public int A0L = 65;
    public boolean A0P = false;
    public boolean A0Q = false;
    public boolean A0R = false;
    public double A07 = 2.0d;
    public double A08 = 1.2d;
    public double A06 = 1.0d;
    public int A0M = 0;
    public double A03 = 0.0d;
    public double A00 = 0.0d;
    public int A0I = 75;
    public int A0D = 0;
    public int A0E = 0;
    public int A0F = 0;
    public int A0G = 0;
    public int A0H = 0;
    public boolean A0O = false;
    public boolean A0V = false;
    public double A04 = 0.0d;
    public double A05 = 0.0d;
    public boolean A0W = true;

    public C4NQ(C3LA c3la) {
        this.A13 = c3la.A0W;
        this.A14 = c3la.A0X;
        this.A12 = c3la.A0V;
        this.A11 = c3la.A0U;
        this.A10 = c3la.A0T;
        this.A0z = c3la.A0S;
        this.A18 = c3la.A0b;
        this.A19 = c3la.A0c;
        this.A0l = c3la.A0E;
        this.A1F = c3la.A0i;
        this.A0j = c3la.A0C;
        this.A1H = c3la.A0k;
        this.A1L = c3la.A0o;
        this.A0g = c3la.A09;
        this.A0h = c3la.A0A;
        this.A1G = c3la.A0j;
        this.A1E = c3la.A0h;
        this.A1D = c3la.A0g;
        this.A1C = c3la.A0f;
        this.A17 = c3la.A0a;
        this.A1M = c3la.A0p;
        this.A15 = c3la.A0Y;
        this.A1B = c3la.A0e;
        this.A1J = c3la.A0m;
        this.A0X = c3la.A00;
        this.A0Y = c3la.A01;
        this.A0y = c3la.A0R;
        this.A1A = c3la.A0d;
        this.A1O = c3la.A0r;
        this.A16 = c3la.A0Z;
        this.A1K = c3la.A0n;
        this.A1P = c3la.A0s;
        this.A0i = c3la.A0B;
        this.A1N = c3la.A0q;
        this.A0t = c3la.A0M;
        this.A0u = c3la.A0N;
        this.A0s = c3la.A0L;
        this.A0o = c3la.A0H;
        this.A0q = c3la.A0J;
        this.A0d = c3la.A06;
        this.A0m = c3la.A0F;
        this.A0n = c3la.A0G;
        this.A0v = c3la.A0O;
        this.A0w = c3la.A0P;
        this.A0Z = c3la.A02;
        this.A0a = c3la.A03;
        this.A0p = c3la.A0I;
        this.A1I = c3la.A0l;
        this.A0e = c3la.A07;
        this.A0f = c3la.A08;
        this.A0k = c3la.A0D;
        this.A0b = c3la.A04;
        this.A0c = c3la.A05;
        this.A0r = c3la.A0K;
        this.A0x = c3la.A0Q;
    }
}
