package p000X;

import com.google.common.collect.ImmutableSet;
/* renamed from: X.33q  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes2.dex */
public final class C621433q {
    public static final ImmutableSet A00;

    static {
        String[] strArr = new String[172];
        System.arraycopy(new String[]{"direct_reshare_select_recipient", "direct_compose_select_recipient", "direct_e2e_message_delivery_waterfall", "direct_edit_customize_reactions", "direct_enter_customize_reactions", "direct_enter_thread", "direct_exit_search", "direct_group_block_warning_dialog_action", "direct_group_creation_create", "direct_group_creation_enter", "direct_icebreaker_settings_events", "direct_inbox_action", "direct_inbox_manual_refresh", "direct_inbox_page_scroll", "direct_inbox_search_dwell_30s", "direct_inbox_search_impression", "direct_inbox_search_send", "direct_inbox_search_start", "direct_inbox_tab_impression", "direct_inbox_thread_impression", "direct_join_video_call", "direct_message_modal_send", "direct_message_modal_tap", "direct_mutation_drop", "direct_mutation_migration", "direct_new_message_button_tapped", "direct_omnipicker_search_send"}, 0, strArr, 0, 27);
        System.arraycopy(new String[]{"direct_omnipicker_thread_dwell30s", "direct_private_reply_events", "direct_quoted_reply_canceled", "direct_quoted_reply_click", "direct_quoted_reply_sent", "direct_request_fetch_failure", "direct_request_fetch_success", "direct_request_filter", "direct_requests_allow_swipe", "direct_requests_enter_pending_inbox", "direct_requests_thread_allow", "direct_share_extension_external", "direct_share_from_mention_view_story", "direct_share_media", "direct_share_sheet_facebook_story_row_impression", "direct_shh_mode_nux_impression", "direct_shh_mode_swipe_gesture", "direct_shh_mode_toggle_failed", "direct_start_video_call", "direct_story_playback_entry", "direct_suggested_recipient_impression", "direct_thread_action", "direct_thread_add_user", "direct_thread_admin_approval_toggle", "direct_thread_approve_request", "direct_thread_back", "direct_thread_change_group_photo"}, 0, strArr, 27, 27);
        System.arraycopy(new String[]{"direct_thread_change_theme", "direct_thread_demote_admin", "direct_thread_icebreaker_click", "direct_thread_icebreaker_impression", "direct_thread_leave", "direct_thread_move", "direct_thread_move_multiple", "direct_thread_promote_admin", "direct_thread_quickreply_click", "direct_thread_quickreply_impression", "direct_thread_remove_request", "direct_thread_remove_user", "direct_thread_see_all_requests", "direct_thread_tap_permanent_media", "direct_thread_tap_sender_profile", "direct_thread_tap_small_media_to_enlarge", "direct_thread_unseen_message_impression", "direct_vc_icon_impression", "fx_upsells_product", "giphy_gif_impression", "giphy_gif_send_attempt", "hrx_instagram_hide_message_tap_to_reveal", "hrx_instagram_thread_report_banner_shown", "hrx_instagram_thread_report_interaction_with_banner", "ig_android_direct_failed_to_replace_message", "ig_block_action", "ig_bulk_block_action"}, 0, strArr, 54, 27);
        System.arraycopy(new String[]{"ig_camera_open_blacklist", "ig_direct_active_now_click", "ig_direct_active_now_impression", "ig_direct_an_click_session_end", "ig_direct_inbox_fetch_success_rate", "ig_direct_iris_subscription", "ig_direct_thread_fetch_success_rate", "ig_live_viewer_invite_tap", "ig_unblock_action", "instagram_interop_upsell_and_upgrade_events", "instagram_waverly_ig_event", "mci_recipient_unsend_nux", "mci_sender_unsend_nux", "photo_cant_load", "quick_reply_client_count_anomaly", "quick_reply_restore", "reel_direct_thread_entry_with_group_stories_tray", "room_app_switch_tap", "room_button_tap", "room_create_tap", "room_creation_fail", "room_creation_flow_start", "room_description_sheet_impression", "room_dismiss_sheet", "room_end_tap", "room_ig_join_session_start", "room_join_tap"}, 0, strArr, 81, 27);
        System.arraycopy(new String[]{"room_login_fb_account_prompt_sheet_impression", "room_login_fb_account_success_sheet_impression", "room_login_fb_client_link_prompt_sheet_impression", "room_login_fb_client_link_start", "room_login_fb_client_link_success", "room_promotion_unit_impression", "room_promotion_unit_tap", "room_self_card_button_tap", "room_share_sheet_impression", "room_share_tap", "room_skip_tap", "room_tab_impression", "shops_product_picker_waterfall", "threads_app_status_upsell_impression", "threads_app_status_upsell_tap", "threads_app_upsell_click", "threads_app_upsell_impression", "ufix_ig_proactive_warnings_event", "ufix_ig_support_resources_csom_qp_event", "direct_composer_tap_voice_message", "direct_invalid_visual_media", "direct_reshare_button_tap", "direct_share_media", "direct_story_playback_navigation", "direct_story_session_summary", "ig_push_notification_user_action", "direct_mutation_waterfall"}, 0, strArr, 108, 27);
        System.arraycopy(new String[]{"direct_native_share_to_direct_text", "direct_native_share_to_direct_photo", "direct_requests_allow_multiple_confirm", "direct_requests_thread_decline", "direct_requests_decline_swipe", "direct_requests_decline_button_confirm", "direct_quick_reply_waterfall", "direct_suggested_thread_impression", "direct_candidates_impression", "direct_compose_unselect_recipient", "direct_compose_too_many_recipients_alert", "direct_compose_video_call_button", "direct_thread_add_people_button", "direct_thread_mute_button", "direct_thread_mute_mentions_button", "direct_thread_video_call_mute_button", "direct_thread_name_group", "direct_thread_leave_conversation_button", "direct_thread_link_tap", "direct_thread_tap_details_button", "direct_thread_tap_ar_effect", "direct_save_media", "direct_reshare_exit_flow", "direct_reshare_send", "direct_composer_tap_heart", "direct_composer_tap_emoji", "direct_composer_tap_text_field"}, 0, strArr, 135, 27);
        System.arraycopy(new String[]{"direct_composer_send_text", "direct_composer_gallery_cancel_button", "direct_composer_tap_gallery", "direct_composer_gallery_back_button", "direct_composer_gallery_send_media", "direct_composer_tap_gif", "direct_composer_tap_gif_random", "direct_message_waterfall", "direct_message_failed", "direct_message_mark_waterfall"}, 0, strArr, 162, 10);
        ImmutableSet A002 = ImmutableSet.A00("action_log_with_no_text_attributes", "direct_animated_media_size_filter", "direct_badge_consistency_check", "direct_blocked_composer_impression", "direct_business_interop_education_flow", "direct_compose_search", strArr);
        C0OR.A06(A002);
        A00 = A002;
    }
}
