package p000X;

import com.instagram.api.schemas.RingSpec;
import com.instagram.creation.capture.quickcapture.freetransform.transformmatrix.TransformMatrixConfig;
import com.instagram.creation.capture.quickcapture.gallery.gallerygrid.suggestions.model.GallerySuggestionsInfo;
import java.util.List;
import java.util.Set;
/* renamed from: X.DSy */
/* loaded from: classes5.dex */
public final class DSy {
    public long A00;
    public TransformMatrixConfig A01;
    public GallerySuggestionsInfo A02;
    public DYR A03;
    public DQZ A04;
    public DR4 A05;
    public DRP A06;
    public Boolean A07;
    public Integer A08;
    public Integer A09;
    public String A0A;
    public String A0B;
    public String A0C;
    public String A0D;
    public String A0E;
    public String A0F;
    public String A0G;
    public String A0H;
    public String A0I;
    public String A0J;
    public String A0K;
    public String A0L;
    public String A0M;
    public String A0N;
    public String A0O;
    public String A0P;
    public String A0Q;
    public String A0R;
    public String A0S;
    public String A0T;
    public List A0U;
    public List A0V;
    public List A0W;
    public List A0X;
    public List A0Y;
    public List A0Z;
    public List A0a;
    public List A0b;
    public List A0c;
    public List A0d;
    public List A0e;
    public Set A0f;
    public boolean A0g;
    public boolean A0h;
    public boolean A0i;
    public boolean A0j;
    public boolean A0k;
    public boolean A0l;
    public boolean A0m;
    public boolean A0n;
    public boolean A0o;
    public boolean A0p;
    public boolean A0q;
    public boolean A0r;
    public boolean A0s;
    public boolean A0t;
    public boolean A0u;
    public boolean A0v;
    public boolean A0w;
    public RingSpec A0x;
    public G9G A0y;
    public C159348yo A0z;
    public List A10;
    public Set A11;

    public DSy(RingSpec ringSpec, TransformMatrixConfig transformMatrixConfig, GallerySuggestionsInfo gallerySuggestionsInfo, DYR dyr, G9G g9g, DQZ dqz, DR4 dr4, DRP drp, C159348yo c159348yo, Boolean bool, Integer num, Integer num2, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, String str15, String str16, String str17, String str18, String str19, String str20, List list, List list2, List list3, List list4, List list5, List list6, List list7, List list8, List list9, List list10, List list11, List list12, Set set, Set set2, long j, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14, boolean z15, boolean z16, boolean z17) {
        this.A0p = z;
        this.A04 = dqz;
        this.A00 = j;
        this.A0O = str;
        this.A06 = drp;
        this.A0Z = list;
        this.A0a = list2;
        this.A0W = list3;
        this.A0X = list4;
        this.A0d = list5;
        this.A0c = list6;
        this.A0e = list7;
        this.A10 = list8;
        this.A0f = DOR.A01(set);
        this.A11 = set2;
        this.A0L = str2;
        this.A0K = str3;
        this.A0F = str4;
        this.A0J = str5;
        this.A0H = str6;
        this.A0A = str7;
        this.A0B = str8;
        this.A0T = str9;
        this.A0D = str10;
        this.A0E = str11;
        this.A0Q = str12;
        this.A0C = str13;
        this.A0M = str14;
        this.A0Y = list9;
        this.A0G = str15;
        this.A0g = z2;
        this.A0j = z3;
        this.A0t = z4;
        this.A0u = z5;
        this.A0i = z6;
        this.A0v = z7;
        this.A0r = z8;
        this.A0l = z9;
        this.A05 = dr4;
        this.A0P = str16;
        this.A08 = num;
        this.A0V = list10;
        this.A0U = list11;
        this.A0k = z10;
        this.A0s = z11;
        this.A0n = z12;
        this.A0m = z13;
        this.A0h = z15;
        this.A0q = z14;
        this.A09 = num2;
        this.A0S = str17;
        this.A0R = str18;
        this.A0x = ringSpec;
        this.A0z = c159348yo;
        this.A03 = dyr;
        this.A0o = z16;
        this.A0I = str19;
        this.A0b = list12;
        this.A01 = transformMatrixConfig;
        this.A07 = bool;
        this.A02 = gallerySuggestionsInfo;
        this.A0N = str20;
        this.A0w = z17;
        this.A0y = g9g;
    }

    public DSy() {
    }
}
