package p000X;
/* renamed from: X.66b  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes3.dex */
public enum EnumC1027566b {
    CLIENT_LOAD_OFFSITEAVAILABILITY_INIT,
    CLIENT_LOAD_OFFSITEAVAILABILITY_SUCCESS,
    CLIENT_LOAD_OFFSITEAVAILABILITY_FAIL,
    CLIENT_LOAD_OFFSITELOGINWITHAPP_INIT,
    CLIENT_LOAD_OFFSITELOGINWITHAPP_SUCCESS,
    CLIENT_LOAD_OFFSITELOGINWITHAPP_FAIL,
    CLIENT_LOAD_OFFSITEPAYMENTREQUEST_INIT,
    CLIENT_LOAD_OFFSITEPAYMENTREQUEST_SUCCESS,
    CLIENT_LOAD_OFFSITEPAYMENTREQUEST_FAIL,
    CLIENT_LOAD_OFFSITEPAYMENTHANDLED_INIT,
    CLIENT_LOAD_OFFSITEPAYMENTHANDLED_SUCCESS,
    CLIENT_LOAD_OFFSITEPAYMENTHANDLED_FAIL,
    CLIENT_LOAD_OFFSITEPAYMENTDETAILSCHANGED_INIT,
    CLIENT_LOAD_OFFSITEPAYMENTDETAILSCHANGED_SUCCESS,
    CLIENT_LOAD_OFFSITEPAYMENTDETAILSCHANGED_FAIL
}
