package p000X;
/* renamed from: X.Ci3  reason: case insensitive filesystem */
/* loaded from: classes5.dex */
public enum EnumC23699Ci3 {
    FILL,
    SMART_CROP_FILL_FROM_FIT,
    SMART_CROP_FILL_FROM_FREE_TRANSFORM,
    FIT,
    SMART_CROP_FIT,
    SMART_CROP_FREE_TRANSFORM,
    SMART_CROP_FREE_TRANSFORM_CACHED,
    SMART_TRACKING_FIT,
    SMART_TRACKING_FILL,
    SMART_TRACKING_FREE_TRANSFORM,
    SMART_TRACKING_PROCESSING,
    SMART_TRACKING_PROCESSING_TOOLTIP,
    SMART_TRACKING_PROCESSING_INVALID
}
