package p000X;
/* renamed from: X.0wj  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public enum EnumC25880wj {
    NO_ANR_DETECTED,
    DURING_ANR,
    ANR_RECOVERED,
    SIGQUIT_RECEIVED_AM_UNCONFIRMED_MT_BLOCKED,
    SIGQUIT_RECEIVED_AM_CONFIRMED_MT_BLOCKED,
    SIGQUIT_RECEIVED_AM_CONFIRMED_MT_UNBLOCKED,
    SIGQUIT_RECEIVED_AM_UNCONFIRMED_MT_UNBLOCKED,
    SIGQUIT_RECEIVED_AM_EXPIRED_MT_BLOCKED,
    NO_SIGQUIT_AM_CONFIRMED_MT_BLOCKED,
    NO_SIGQUIT_AM_CONFIRMED_MT_UNBLOCKED
}
