package p000X;
/* renamed from: X.FdK  reason: case insensitive filesystem */
/* loaded from: classes6.dex */
public enum EnumC29705FdK {
    COMMENT_DELETE_UPSELL_TYPE_NONE,
    COMMENT_DELETE_UPSELL_TYPE_HMC,
    COMMENT_DELETE_UPSELL_TYPE_BLOCK,
    COMMENT_DELETE_UPSELL_TYPE_HIDDEN_WORDS,
    COMMENT_DELETE_UPSELL_TYPE_HIDDEN_WORDS_V2,
    COMMENT_DELETE_UPSELL_TYPE_BLOCK_COMMENTS_FROM,
    COMMENT_DELETE_UPSELL_TYPE_HRT_BLOCK_COMMENTS_FROM
}
