package p000X;
/* renamed from: X.9fc  reason: invalid class name and case insensitive filesystem */
/* loaded from: classes4.dex */
public enum EnumC170709fc {
    UNRECOGNIZED(-1),
    HEADLINE_TYPE(22),
    SMART_OPT_IN_TYPE(23),
    VIDEO_TO_CAROUSEL_TYPE(44),
    IG_STORY_IMAGE_CROP(52),
    SHOWREEL_NATIVE_TYPE(65),
    CAPTION_CARD_TYPE(66),
    END_SCENE_TYPE(78),
    IG_GLADOS_VIDEO(80),
    CAPTION_LENGTH_OPTIMIZATION_TYPE(84),
    HANDLE_TYPE(94),
    MID_LENGTH_VIDEO_TO_CAROUSEL_TYPE(98),
    TEXT_FONT_SIZE_TYPE(109),
    TEXT_FONT_STYLE_TYPE(110),
    FEED_GLADOS_TEMPLATE(112),
    SMART_CAPTION_TYPE(113),
    IG_CV_TRANSFORMATION_TYPE(122),
    TEXT_FONT_COLOR_TYPE(125),
    IG_KEYWORD_EXTRACTION_AND_HIGHLIGHT(131),
    IG_STORY_COLLECTION_CARD(134),
    IG_GENERIC_PROFILE_CARD(139),
    TEXT_ALIGNMENT(168),
    IG_STORY_LEADGEN_CARD(171);
    
    public final int A00;

    EnumC170709fc(int i) {
        this.A00 = i;
    }
}
