package p000X;

import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S0000100_I2;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S0100000_I2;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S0200000_I2;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S1000000_I2;
import com.facebook.kotlin.compilerplugins.dataclassgenerate.superclass.KtCSuperShape0S1020000_I2;
import com.instagram.direct.model.thread.CreatorBroadcastThreadInfo;
import com.instagram.direct.model.thread.CreatorSubscriberThreadInfo;
import com.instagram.direct.model.thread.DiscoverableThreadInfo;
import com.instagram.direct.smartsuggestion.model.SmartSuggestion;
import com.instagram.user.model.User;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
/* renamed from: X.F7C */
/* loaded from: classes6.dex */
public class F7C extends C1n7 {
    public int A00;
    public int A01;
    public int A02;
    public int A04;
    public int A07;
    public int A08;
    public int A09;
    public int A0A;
    public int A0D;
    public KtCSuperShape0S0000100_I2 A0E;
    public KtCSuperShape0S0100000_I2 A0F;
    public KtCSuperShape0S0200000_I2 A0G;
    public KtCSuperShape0S0200000_I2 A0H;
    public KtCSuperShape0S1000000_I2 A0I;
    public KtCSuperShape0S1020000_I2 A0J;
    public C28790Eyx A0K;
    public C175869r9 A0L;
    public C31609GQd A0M;
    public C30042Fjd A0N;
    public GIU A0O;
    public C31355GCn A0P;
    public C31610GQe A0Q;
    public GV8 A0R;
    public C30776Fvg A0S;
    public A78 A0T;
    public C30057Fjs A0U;
    public CreatorBroadcastThreadInfo A0V;
    public CreatorSubscriberThreadInfo A0W;
    public DiscoverableThreadInfo A0X;
    public SmartSuggestion A0Z;
    public User A0a;
    public Boolean A0b;
    public Boolean A0c;
    public Boolean A0d;
    public Boolean A0e;
    public Boolean A0f;
    public Boolean A0g;
    public Boolean A0h;
    public Boolean A0i;
    public Boolean A0j;
    public Boolean A0k;
    public Boolean A0l;
    public Boolean A0m;
    public Boolean A0n;
    public Boolean A0o;
    public Boolean A0p;
    public Boolean A0q;
    public String A0r;
    public String A0s;
    public String A0t;
    public String A0u;
    public String A0v;
    public String A0w;
    public String A0x;
    public String A0y;
    public String A0z;
    public String A10;
    public String A11;
    public String A12;
    public HashMap A13;
    public List A16;
    public List A17;
    public List A18;
    public List A1A;
    public boolean A1C;
    public boolean A1D;
    public boolean A1E;
    public boolean A1F;
    public boolean A1G;
    public boolean A1H;
    public boolean A1I;
    public boolean A1J;
    public boolean A1K;
    public boolean A1L;
    public boolean A1M;
    public boolean A1N;
    public boolean A1O;
    public boolean A1P;
    public boolean A1Q;
    public boolean A1R;
    public boolean A1S;
    public List A1B = Collections.emptyList();
    public List A15 = Collections.emptyList();
    public List A19 = C25920wp.A0w();
    public HashMap A14 = C25920wp.A0z();
    public int A0C = 0;
    public int A0B = 0;
    public int A03 = -1;
    public int A05 = 0;
    public int A06 = -1;
    public EnumC29742Fdv A0Y = EnumC29742Fdv.INBOX;
}
