package p000X;
/* renamed from: X.JJH */
/* loaded from: classes7.dex */
public final class JJH {
    public final int A00;
    public final int A01;
    public final int A02;
    public final int A03;
    public final int A04;
    public final long A05;
    public final long A06;
    public final long A07;
    public final long A08;
    public final long A09;
    public final long A0A;
    public final long A0B;
    public final long A0C;
    public final long A0D;
    public final long A0E;
    public final long A0F;
    public final long A0G;
    public final long A0H;
    public final long A0I;
    public final long A0J;
    public final long A0K;
    public final long A0L;
    public final long A0M;
    public final long A0N;
    public final long A0O;
    public final long A0P;
    public final long A0Q;
    public final long A0R;
    public final long A0S;
    public final long A0T;
    public final String A0U;
    public final String A0V;
    public final String A0W;
    public final String A0X;
    public final String A0Y;
    public final String A0Z;
    public final boolean A0a;
    public final boolean A0b;
    public final boolean A0c;
    public final boolean A0d;
    public final boolean A0e;
    public final boolean A0f;

    public JJH(String str, String str2, String str3, String str4, String str5, String str6, int i, int i2, int i3, int i4, int i5, long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6) {
        this.A0Z = str;
        this.A00 = i;
        this.A0c = z;
        this.A02 = i2;
        this.A01 = i3;
        this.A04 = i4;
        this.A03 = i5;
        this.A0S = j;
        this.A0T = j2;
        this.A0B = j3;
        this.A0A = j4;
        this.A0L = j5;
        this.A0P = j6;
        this.A0N = j7;
        this.A0M = j8;
        this.A08 = j9;
        this.A09 = j10;
        this.A0X = str2;
        this.A0E = j11;
        this.A0I = j12;
        this.A0U = str3;
        this.A07 = j13;
        this.A0O = j14;
        this.A0b = z2;
        this.A06 = j15;
        this.A05 = j16;
        this.A0D = j17;
        this.A0C = j18;
        this.A0H = j19;
        this.A0G = j20;
        this.A0F = j21;
        this.A0R = j22;
        this.A0Q = j23;
        this.A0K = j24;
        this.A0J = j25;
        this.A0a = z3;
        this.A0Y = str4;
        this.A0W = str5;
        this.A0V = str6;
        this.A0d = z4;
        this.A0e = z5;
        this.A0f = z6;
    }
}
