package p000X;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
/* renamed from: X.JJL */
/* loaded from: classes7.dex */
public final class JJL {
    public EnumC36043IrA A00;
    public EnumC171429jp A01;
    public C2CV A02;
    public EnumC36041Ir8 A03;
    public C73823yq A04;
    public C0rZ A05;
    public C0rZ A06;
    public C0rZ A07;
    public Boolean A08;
    public Boolean A09;
    public Boolean A0A;
    public Boolean A0B;
    public Boolean A0C;
    public Boolean A0D;
    public Boolean A0E;
    public Double A0F;
    public Double A0G;
    public Double A0H;
    public Float A0I;
    public Float A0J;
    public Float A0K;
    public Float A0L;
    public Float A0M;
    public Float A0N;
    public Float A0O;
    public Float A0P;
    public Float A0Q;
    public Float A0R;
    public Float A0S;
    public Float A0T;
    public Float A0U;
    public Float A0V;
    public Float A0W;
    public Integer A0X;
    public Integer A0Y;
    public Integer A0Z;
    public Integer A0a;
    public Integer A0b;
    public Integer A0c;
    public Integer A0d;
    public Integer A0e;
    public Integer A0f;
    public Integer A0g;
    public Integer A0h;
    public Integer A0i;
    public Integer A0j;
    public Integer A0k;
    public Integer A0l;
    public Integer A0m;
    public Long A0n;
    public Long A0o;
    public String A0p = null;
    public String A0q;
    public String A0r;
    public String A0s;
    public String A0t;
    public String A0u;
    public String A0v;
    public String A0w;
    public String A0x;
    public String A0y;
    public String A0z;
    public String A10;
    public String A11;
    public String A12;
    public String A13;
    public String A14;
    public String A15;
    public String A16;
    public String A17;
    public String A18;
    public String A19;
    public String A1A;
    public String A1B;
    public String A1C;
    public String A1D;
    public String A1E;
    public String A1F;
    public String A1G;
    public String A1H;
    public String A1I;
    public String A1J;
    public String A1K;
    public String A1L;
    public String A1M;
    public String A1N;
    public String A1O;
    public String A1P;
    public String A1Q;
    public String A1R;
    public ArrayList A1S;
    public ArrayList A1T;
    public ArrayList A1U;
    public HashMap A1V;
    public List A1W;
}
