package p000X;
/* renamed from: X.LLZ */
/* loaded from: classes8.dex */
public enum LLZ {
    UNSET_OR_UNRECOGNIZED_ENUM_VALUE,
    CONTENT_ELIGIBLE_REELS_CCP,
    CONTENT_ELIGIBLE_REELS_XAR,
    LAUNCHER_ENABLED_REELS_CCP,
    LAUNCHER_ENABLED_REELS_XAR,
    SHARE_SHEET_REELS_ROW_VISIBLE_CCP,
    SHARE_SHEET_REELS_ROW_VISIBLE_XAR,
    USER_AUTO_SETTINGS_REELS_CCP_DISABLED,
    USER_AUTO_SETTINGS_REELS_XAR_DISABLED,
    USER_AUTO_SETTINGS_REELS_XAR_ENABLED,
    USER_HAS_FB_LINKED_ACCOUNT,
    USER_PUBLIC
}
