package com.instagram.model.reels;

import android.os.SystemClock;
import android.util.Pair;
import com.facebook.common.stringformat.StringFormatUtil;
import com.instagram.api.schemas.RingSpec;
import com.instagram.common.typedurl.ImageUrl;
import com.instagram.model.effect.AttributedAREffect;
import com.instagram.model.reels.sponsored.AutoGeneratedCardType;
import com.instagram.model.reels.sponsored.ReelCarouselType;
import com.instagram.model.shopping.Merchant;
import com.instagram.react.modules.base.IgReactQEModule;
import com.instagram.service.session.UserSession;
import com.instagram.user.model.User;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import p000X.A8B;
import p000X.AnonymousClass000;
import p000X.AnonymousClass006;
import p000X.B70;
import p000X.B74;
import p000X.B76;
import p000X.B77;
import p000X.B7A;
import p000X.B7B;
import p000X.B7J;
import p000X.B7O;
import p000X.B7P;
import p000X.BAX;
import p000X.C073900b;
import p000X.C0OR;
import p000X.C0TD;
import p000X.C0ZV;
import p000X.C150618f9;
import p000X.C150628fA;
import p000X.C150638fB;
import p000X.C150658fD;
import p000X.C150668fE;
import p000X.C150678fF;
import p000X.C150688fG;
import p000X.C150698fH;
import p000X.C156558u9;
import p000X.C156618uF;
import p000X.C156948um;
import p000X.C158328x1;
import p000X.C158548xO;
import p000X.C158748xk;
import p000X.C158758xl;
import p000X.C158778xn;
import p000X.C158788xo;
import p000X.C158798xp;
import p000X.C158808xq;
import p000X.C158818xr;
import p000X.C158828xs;
import p000X.C158848xu;
import p000X.C158858xv;
import p000X.C158868xw;
import p000X.C158878xx;
import p000X.C158888xy;
import p000X.C158918y1;
import p000X.C158928y2;
import p000X.C159178yW;
import p000X.C159198yZ;
import p000X.C159348yo;
import p000X.C159418yy;
import p000X.C171939ke;
import p000X.C178669vf;
import p000X.C178789vr;
import p000X.C18350ix;
import p000X.C18451ACn;
import p000X.C18512AEx;
import p000X.C18531AFq;
import p000X.C19385Afy;
import p000X.C19400kp;
import p000X.C19420kr;
import p000X.C19544Aib;
import p000X.C19652AkN;
import p000X.C19716AlQ;
import p000X.C19758Am7;
import p000X.C19763AmC;
import p000X.C20518B6w;
import p000X.C20520B6y;
import p000X.C20521B6z;
import p000X.C20939BQc;
import p000X.C25920wp;
import p000X.C25930wq;
import p000X.C25940wr;
import p000X.C25950ws;
import p000X.C25960wt;
import p000X.C25970wu;
import p000X.C25980wv;
import p000X.C25990ww;
import p000X.C29E;
import p000X.C32675Gu1;
import p000X.C37786JmD;
import p000X.C3XZ;
import p000X.C40702Gy;
import p000X.C5KV;
import p000X.C6N7;
import p000X.C70763jC;
import p000X.C7D3;
import p000X.C7jU;
import p000X.C91524uS;
import p000X.C91534uT;
import p000X.C91544uU;
import p000X.C91554uV;
import p000X.C91564uW;
import p000X.C91574uX;
import p000X.C98y;
import p000X.InterfaceC21924Bnj;
import p000X.InterfaceC21973BoW;
import p000X.InterfaceC39764KqG;
/* loaded from: classes4.dex */
public final class Reel implements InterfaceC21924Bnj {
    public int A00;
    public int A01;
    public int A02;
    public long A03;
    public long A04;
    public long A05;
    public long A06;
    public long A07;
    public C156558u9 A08;
    public C156618uF A09;
    public C7jU A0A;
    public B7J A0B;
    public B7P A0C;
    public B7P A0D;
    public AttributedAREffect A0E;
    public C98y A0F;
    public C20518B6w A0G;
    public C158758xl A0H;
    public HighlightReelTypeStr A0I;
    public B76 A0J;
    public C18451ACn A0K;
    public C158778xn A0L;
    public C158788xo A0M;
    public BAX A0N;
    public C18531AFq A0O;
    public ReelType A0P;
    public C20520B6y A0Q;
    public B74 A0R;
    public C20521B6z A0S;
    public C158328x1 A0T;
    public B70 A0U;
    public InterfaceC21973BoW A0V;
    public C158918y1 A0W;
    public C158928y2 A0X;
    public ReelCarouselType A0Y;
    public C159178yW A0Z;
    public B7A A0a;
    public C159348yo A0b;
    public C19385Afy A0c;
    public Boolean A0d;
    public Float A0e;
    public Integer A0f;
    public Integer A0g;
    public Integer A0h;
    public Integer A0i;
    public Integer A0j;
    public Long A0k;
    public Long A0l;
    public Long A0m;
    public String A0n;
    public String A0o;
    public String A0p;
    public String A0q;
    public String A0r;
    public String A0s;
    public String A0t;
    public String A0u;
    public String A0v;
    public ArrayList A0w;
    public List A0x;
    public List A0y;
    public List A0z;
    public List A10;
    public List A11;
    public List A12;
    public List A13;
    public List A14;
    public List A15;
    public List A16;
    public List A17;
    public Map A18;
    public Set A19;
    public Set A1A;
    public boolean A1B;
    public boolean A1C;
    public boolean A1D;
    public boolean A1E;
    public boolean A1F;
    public boolean A1G;
    public boolean A1H;
    public boolean A1I;
    public boolean A1J;
    public boolean A1K;
    public boolean A1L;
    public boolean A1M;
    public boolean A1N;
    public boolean A1O;
    public boolean A1P;
    public boolean A1Q;
    public boolean A1R;
    public boolean A1S;
    public boolean A1T;
    public boolean A1U;
    public boolean A1V;
    public boolean A1W;
    public boolean A1X;
    public boolean A1Y;
    public RingSpec A1Z;
    public boolean A1a;
    public final Object A1b;
    public final String A1c;
    public volatile boolean A1d;
    public static final C20939BQc A1f = new C20939BQc();
    public static final Integer A1e = 10;

    public Reel(Integer num, List list) {
        String str;
        boolean A1Y = C150618f9.A1Y(this);
        this.A1W = false;
        this.A1B = A1Y;
        this.A1b = new Object();
        this.A18 = C25920wp.A0z();
        this.A1M = A1Y;
        this.A1P = A1Y;
        this.A1G = false;
        this.A14 = null;
        this.A0A = null;
        if (num.intValue() != 0) {
            str = AnonymousClass000.A00(78);
        } else {
            str = "story_interstitial_chaining";
        }
        this.A1c = str;
        this.A0V = null;
        this.A1V = false;
        this.A0i = num;
        this.A1R = A1Y;
        this.A0h = A1e;
        if (num == AnonymousClass006.A00) {
            this.A11 = list;
        }
    }

    @Override // p000X.InterfaceC21924Bnj
    public final boolean BV8() {
        return true;
    }

    @Override // p000X.InterfaceC21924Bnj
    public final boolean BWz() {
        return true;
    }

    public static void A00(Reel reel, Set set) {
        synchronized (reel.A1b) {
            if (!reel.A19.isEmpty()) {
                HashSet A0r = C91574uX.A0r(reel.A19);
                Iterator it = A0r.iterator();
                while (it.hasNext()) {
                    B7P A0G = C150628fA.A0G(it);
                    if (!set.contains(A0G.A35()) || (A0G.A1u() < System.currentTimeMillis() && !reel.A0h())) {
                        it.remove();
                    }
                }
                reel.A1d = true;
                reel.A19 = Collections.unmodifiableSet(A0r);
            }
        }
    }

    public static boolean A01(InterfaceC39764KqG interfaceC39764KqG, Reel reel, UserSession userSession, boolean z) {
        synchronized (reel.A1b) {
            List A0P = reel.A0P(userSession);
            int A02 = reel.A02(userSession);
            while (true) {
                if (A02 >= A0P.size()) {
                    break;
                }
                B7B A0K = C150688fG.A0K(A0P, A02);
                if ((!z && C7D3.A00(userSession).A06(reel, A0K)) || !interfaceC39764KqG.apply(A0K)) {
                    A02++;
                } else if (A0K == null) {
                    break;
                } else {
                    return true;
                }
            }
        }
        return false;
    }

    public final long A03() {
        long j = this.A04;
        if (j == -9223372036854775807L) {
            return this.A05;
        }
        return j;
    }

    public final RingSpec A05(UserSession userSession) {
        boolean z;
        if (this.A1V) {
            z = C150688fG.A1a(this, userSession, 4);
        } else {
            z = this.A1E;
        }
        if (!z && A0n(userSession)) {
            return null;
        }
        return this.A1Z;
    }

    public final C19400kp A06() {
        C158928y2 c158928y2 = this.A0X;
        String str = null;
        if (c158928y2 == null) {
            return null;
        }
        C19400kp A0J = C150678fF.A0J();
        C19420kr c19420kr = C19758Am7.A28;
        List list = c158928y2.A0G;
        if (list != null) {
            str = list.toString();
        }
        A0J.A04(c19420kr, str);
        A0J.A04(C19758Am7.A26, C150698fH.A0c(c158928y2.A02));
        A0J.A04(C19758Am7.A29, c158928y2.A09);
        A0J.A04(C19758Am7.A2A, c158928y2.A07);
        A0J.A04(C19758Am7.A2B, c158928y2.A0E);
        A0J.A04(C19758Am7.A27, c158928y2.A08);
        A0J.A04(C19758Am7.A2C, c158928y2.A0F);
        return A0J;
    }

    public final ImageUrl A07() {
        C158778xn c158778xn = this.A0L;
        if (c158778xn != null && A0f()) {
            return C178669vf.A00(c158778xn.A00);
        }
        InterfaceC21973BoW interfaceC21973BoW = this.A0V;
        if (interfaceC21973BoW == null) {
            return null;
        }
        return interfaceC21973BoW.AaO();
    }

    public final B7B A08(UserSession userSession) {
        B7B A0K;
        synchronized (this.A1b) {
            if (A0s(userSession)) {
                A0K = null;
            } else {
                A0K = C150688fG.A0K(A0P(userSession), A02(userSession));
            }
        }
        return A0K;
    }

    public final User A0A() {
        InterfaceC21973BoW interfaceC21973BoW = this.A0V;
        if (interfaceC21973BoW == null) {
            return null;
        }
        return interfaceC21973BoW.BKI();
    }

    public final C29E A0B() {
        C98y c98y = this.A0F;
        if (c98y != null && A0c()) {
            C29E c29e = c98y.A0E;
            if (c29e == null) {
                c29e = C29E.A07;
            }
            if (c29e != null) {
                return c29e;
            }
        }
        return C29E.A07;
    }

    public final Boolean A0C() {
        int intValue;
        Integer num = this.A0g;
        Boolean A0U = C25930wq.A0U();
        if (num == null || ((intValue = num.intValue()) != 6 && intValue != 7 && intValue != 8)) {
            return A0U;
        }
        return C25930wq.A0V();
    }

    public final String A0E() {
        B7A b7a;
        String str;
        C37786JmD.A07(this.A0g, "Trying to get the netego ID without netego type");
        switch (this.A0g.intValue()) {
            case 0:
                b7a = this.A0a;
                str = "Bakeoff netego should have simple action";
                break;
            case 1:
                C37786JmD.A07(this.A0Q, "Ad4ad netego should have ad4ad object");
                return this.A0Q.A00.A02;
            case 2:
                C37786JmD.A07(this.A0S, "Suggested Users netego should have suggested user object");
                return this.A0S.getId();
            case 3:
                b7a = this.A0a;
                str = "Quality survey netego should have simple action";
                break;
            case 4:
                b7a = this.A0a;
                str = "Story creation upsell netego should have simple action";
                break;
            case 5:
                C37786JmD.A07(this.A0T, "Suggested clips netego should have suggested clips object");
                return this.A0T.getId();
            case 6:
            case 7:
                C37786JmD.A07(this.A0U, "Suggested products netego should have suggested products object");
                return this.A0U.getId();
            case 8:
                C37786JmD.A07(null, "Suggested shops netego should have suggested shops object");
                throw null;
            case 9:
                b7a = this.A0a;
                str = "Ads content growth story netego should have simple action";
                break;
            case 10:
                C37786JmD.A07(this.A0R, "Bloks netego should have Bloks object");
                return this.A0R.A01.A05;
            case 11:
                C37786JmD.A07(this.A0G, "ACR netego should have ACR in story object");
                return this.A0G.getId();
            case IgReactQEModule.CONFIG_KEY_OFFSET /* 12 */:
                C37786JmD.A07(this.A0J, "Trending prompts netego should have prompts in story object");
                return this.A0J.getId();
            default:
                throw C91544uU.A0v("Trying to get the netego ID of a non-netego unit");
        }
        C37786JmD.A07(b7a, str);
        return this.A0a.getId();
    }

    public final String A0G() {
        Integer num = this.A0g;
        C37786JmD.A07(num, "Trying to get the shopping netego tracking token when there is no netego type");
        int intValue = num.intValue();
        if (intValue != 6 && intValue != 7) {
            if (intValue == 8) {
                C37786JmD.A07(null, "Shops For You netego should have suggested shops object");
                throw null;
            }
            throw C91544uU.A0v("Trying to get the shopping netego tracking token of a non-shopping netego unit");
        }
        C37786JmD.A07(this.A0U, "Products For You netego should have suggested products object");
        String str = this.A0U.A00.A0B;
        if (str == null) {
            return "";
        }
        return str;
    }

    public final String A0H() {
        List list;
        List list2;
        int min;
        String str;
        C158828xs c158828xs;
        C158828xs c158828xs2;
        Integer num = this.A0g;
        if (num != null) {
            int intValue = num.intValue();
            if (intValue != 7) {
                if (intValue == 8) {
                    C37786JmD.A07(null, "Visit These Shops Again netego should have suggested shops object");
                    throw null;
                }
            } else {
                C37786JmD.A07(this.A0U, "Continue Shopping netego should have suggested products object");
                List list3 = this.A0U.A00.A0D;
                if (list3 == null || (c158828xs2 = (C158828xs) C25990ww.A0d(list3)) == null || (list = c158828xs2.A05) == null) {
                    list = C0ZV.A00;
                }
                int size = list.size();
                List list4 = this.A0U.A00.A0D;
                if (list4 == null || (c158828xs = (C158828xs) C25990ww.A0d(list4)) == null || (list2 = c158828xs.A01.A0n) == null) {
                    list2 = C0ZV.A00;
                }
                int size2 = list2.size();
                if (size > 0) {
                    size2 = size;
                }
                if (size2 == 3) {
                    min = 2;
                } else {
                    min = Math.min(4, size2);
                }
                StringBuilder A0n = C25960wt.A0n();
                A0n.append(min);
                A0n.append("_up_grid, ");
                if (size > 0) {
                    str = "shoppable_media";
                } else {
                    str = "pdp_images";
                }
                return C25930wq.A0f(str, A0n);
            }
        }
        return null;
    }

    public final String A0J(int i) {
        C158828xs c158828xs;
        C37786JmD.A07(this.A0g, "Trying to get the card modifier label without netego type");
        if (this.A0g.intValue() != 6) {
            return null;
        }
        try {
            C37786JmD.A07(this.A0U, "Suggested products netego should have suggested products object");
            List list = this.A0U.A00.A0D;
            if (list != null && (c158828xs = (C158828xs) list.get(i)) != null) {
                return c158828xs.A03;
            }
            return null;
        } catch (NullPointerException unused) {
            return null;
        }
    }

    public final String A0K(int i) {
        C158828xs c158828xs;
        Integer num = this.A0g;
        if (num == null || num.intValue() != 7) {
            return null;
        }
        B70 b70 = this.A0U;
        b70.getClass();
        List list = b70.A00.A0D;
        if (list == null || (c158828xs = (C158828xs) list.get(i)) == null) {
            return null;
        }
        return c158828xs.A04;
    }

    public final List A0M() {
        List unmodifiableList;
        synchronized (this.A1b) {
            unmodifiableList = Collections.unmodifiableList(this.A0x);
        }
        return unmodifiableList;
    }

    public final List A0N() {
        List emptyList;
        synchronized (this.A1b) {
            ArrayList arrayList = this.A0w;
            if (arrayList != null) {
                emptyList = Collections.unmodifiableList(arrayList);
            } else {
                emptyList = Collections.emptyList();
            }
        }
        return emptyList;
    }

    /* JADX WARN: Code restructure failed: missing block: B:89:0x02dd, code lost:
        if (p000X.C25920wp.A1X(p000X.C25980wv.A0e(p000X.C16530en.A02().A24)) == false) goto L147;
     */
    /* JADX WARN: Removed duplicated region for block: B:107:0x030b A[Catch: all -> 0x043a, TryCatch #0 {, blocks: (B:6:0x0009, B:8:0x000d, B:10:0x0025, B:11:0x0032, B:12:0x0035, B:13:0x0043, B:14:0x0044, B:15:0x004b, B:21:0x00ab, B:154:0x0426, B:155:0x0429, B:16:0x0057, B:17:0x007a, B:18:0x009d, B:19:0x00a2, B:20:0x00a7, B:22:0x00cc, B:23:0x00ef, B:24:0x0112, B:25:0x0135, B:151:0x03f5, B:153:0x03f9, B:26:0x0158, B:28:0x015e, B:30:0x0164, B:32:0x0168, B:33:0x0171, B:35:0x0175, B:37:0x0182, B:38:0x0184, B:44:0x01ad, B:45:0x01c9, B:47:0x01cf, B:49:0x01d3, B:50:0x01d8, B:43:0x0192, B:39:0x018a, B:51:0x01de, B:53:0x01e4, B:54:0x01f4, B:56:0x01f8, B:58:0x0202, B:59:0x0204, B:60:0x020b, B:63:0x0215, B:64:0x0225, B:67:0x022d, B:69:0x023a, B:70:0x0268, B:72:0x026e, B:74:0x027e, B:75:0x0280, B:76:0x028b, B:78:0x0293, B:79:0x0296, B:80:0x02a0, B:81:0x02a5, B:82:0x02ab, B:84:0x02b1, B:86:0x02bc, B:88:0x02ce, B:95:0x02e7, B:113:0x032f, B:115:0x0346, B:117:0x034a, B:103:0x02fb, B:105:0x0303, B:107:0x030b, B:108:0x0316, B:110:0x031a, B:111:0x031d, B:112:0x0327, B:99:0x02ee, B:101:0x02f6, B:118:0x0351, B:120:0x0359, B:122:0x0364, B:123:0x036a, B:125:0x0370, B:126:0x0381, B:127:0x0388, B:129:0x038c, B:131:0x03a2, B:133:0x03aa, B:134:0x03ac, B:143:0x03ca, B:135:0x03b4, B:137:0x03b8, B:138:0x03bd, B:140:0x03c3, B:150:0x03f2, B:145:0x03d0, B:147:0x03dc, B:149:0x03e2, B:156:0x0438), top: B:163:0x0009 }] */
    /* JADX WARN: Removed duplicated region for block: B:110:0x031a A[Catch: all -> 0x043a, TryCatch #0 {, blocks: (B:6:0x0009, B:8:0x000d, B:10:0x0025, B:11:0x0032, B:12:0x0035, B:13:0x0043, B:14:0x0044, B:15:0x004b, B:21:0x00ab, B:154:0x0426, B:155:0x0429, B:16:0x0057, B:17:0x007a, B:18:0x009d, B:19:0x00a2, B:20:0x00a7, B:22:0x00cc, B:23:0x00ef, B:24:0x0112, B:25:0x0135, B:151:0x03f5, B:153:0x03f9, B:26:0x0158, B:28:0x015e, B:30:0x0164, B:32:0x0168, B:33:0x0171, B:35:0x0175, B:37:0x0182, B:38:0x0184, B:44:0x01ad, B:45:0x01c9, B:47:0x01cf, B:49:0x01d3, B:50:0x01d8, B:43:0x0192, B:39:0x018a, B:51:0x01de, B:53:0x01e4, B:54:0x01f4, B:56:0x01f8, B:58:0x0202, B:59:0x0204, B:60:0x020b, B:63:0x0215, B:64:0x0225, B:67:0x022d, B:69:0x023a, B:70:0x0268, B:72:0x026e, B:74:0x027e, B:75:0x0280, B:76:0x028b, B:78:0x0293, B:79:0x0296, B:80:0x02a0, B:81:0x02a5, B:82:0x02ab, B:84:0x02b1, B:86:0x02bc, B:88:0x02ce, B:95:0x02e7, B:113:0x032f, B:115:0x0346, B:117:0x034a, B:103:0x02fb, B:105:0x0303, B:107:0x030b, B:108:0x0316, B:110:0x031a, B:111:0x031d, B:112:0x0327, B:99:0x02ee, B:101:0x02f6, B:118:0x0351, B:120:0x0359, B:122:0x0364, B:123:0x036a, B:125:0x0370, B:126:0x0381, B:127:0x0388, B:129:0x038c, B:131:0x03a2, B:133:0x03aa, B:134:0x03ac, B:143:0x03ca, B:135:0x03b4, B:137:0x03b8, B:138:0x03bd, B:140:0x03c3, B:150:0x03f2, B:145:0x03d0, B:147:0x03dc, B:149:0x03e2, B:156:0x0438), top: B:163:0x0009 }] */
    /* JADX WARN: Removed duplicated region for block: B:112:0x0327 A[Catch: all -> 0x043a, TryCatch #0 {, blocks: (B:6:0x0009, B:8:0x000d, B:10:0x0025, B:11:0x0032, B:12:0x0035, B:13:0x0043, B:14:0x0044, B:15:0x004b, B:21:0x00ab, B:154:0x0426, B:155:0x0429, B:16:0x0057, B:17:0x007a, B:18:0x009d, B:19:0x00a2, B:20:0x00a7, B:22:0x00cc, B:23:0x00ef, B:24:0x0112, B:25:0x0135, B:151:0x03f5, B:153:0x03f9, B:26:0x0158, B:28:0x015e, B:30:0x0164, B:32:0x0168, B:33:0x0171, B:35:0x0175, B:37:0x0182, B:38:0x0184, B:44:0x01ad, B:45:0x01c9, B:47:0x01cf, B:49:0x01d3, B:50:0x01d8, B:43:0x0192, B:39:0x018a, B:51:0x01de, B:53:0x01e4, B:54:0x01f4, B:56:0x01f8, B:58:0x0202, B:59:0x0204, B:60:0x020b, B:63:0x0215, B:64:0x0225, B:67:0x022d, B:69:0x023a, B:70:0x0268, B:72:0x026e, B:74:0x027e, B:75:0x0280, B:76:0x028b, B:78:0x0293, B:79:0x0296, B:80:0x02a0, B:81:0x02a5, B:82:0x02ab, B:84:0x02b1, B:86:0x02bc, B:88:0x02ce, B:95:0x02e7, B:113:0x032f, B:115:0x0346, B:117:0x034a, B:103:0x02fb, B:105:0x0303, B:107:0x030b, B:108:0x0316, B:110:0x031a, B:111:0x031d, B:112:0x0327, B:99:0x02ee, B:101:0x02f6, B:118:0x0351, B:120:0x0359, B:122:0x0364, B:123:0x036a, B:125:0x0370, B:126:0x0381, B:127:0x0388, B:129:0x038c, B:131:0x03a2, B:133:0x03aa, B:134:0x03ac, B:143:0x03ca, B:135:0x03b4, B:137:0x03b8, B:138:0x03bd, B:140:0x03c3, B:150:0x03f2, B:145:0x03d0, B:147:0x03dc, B:149:0x03e2, B:156:0x0438), top: B:163:0x0009 }] */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public final List A0P(UserSession userSession) {
        long A0A;
        Integer num;
        boolean z;
        ArrayList arrayList;
        boolean A1Z;
        B7B b7b;
        Integer num2;
        B7B b7b2;
        List list;
        B7B b7b3;
        List list2;
        B7A b7a;
        String str;
        if (this.A1d) {
            synchronized (this.A1b) {
                if (this.A1d) {
                    ArrayList A0n = C25970wu.A0n(this.A12);
                    ArrayList A0n2 = C25970wu.A0n(this.A10);
                    if (C25930wq.A1Z(this.A0P, ReelType.A0N)) {
                        C37786JmD.A07(this.A0g, "Netego reel should have a netego type");
                        Integer num3 = this.A0g;
                        switch (num3.intValue()) {
                            case 0:
                                C37786JmD.A07(this.A0C, "Netego bake off should have a background media set");
                                b7a = this.A0a;
                                str = "Bakeoff reel should have a simple action";
                                C37786JmD.A07(b7a, str);
                                String str2 = this.A1c;
                                b7b2 = new B7B(this.A0C, null, null, null, null, null, null, null, this.A0a, null, this.A0g, str2);
                                A0n.add(b7b2);
                                break;
                            case 1:
                                if (this.A0C != null) {
                                    C37786JmD.A07(this.A0Q, "Ad4ad reel should have an ad4ad object");
                                    C37786JmD.A07(this.A0g, "NetegoType parameter of ReelItem is declared non-nullable");
                                    User A2c = this.A0C.A2c(userSession);
                                    String str3 = this.A1c;
                                    b7b2 = new B7B(this.A0C, null, null, this.A0Q, null, null, null, null, null, A2c, this.A0g, str3);
                                    A0n.add(b7b2);
                                    break;
                                }
                                break;
                            case 2:
                                C37786JmD.A07(this.A0S, "Suggested Users reel should have a SimpleSuggestedUsers object");
                                b7b2 = new B7B(null, null, null, null, null, this.A0S, null, null, null, null, this.A0g, this.A1c);
                                A0n.add(b7b2);
                                break;
                            case 3:
                                b7a = this.A0a;
                                str = "Quality survey reel should have a simple action";
                                C37786JmD.A07(b7a, str);
                                String str22 = this.A1c;
                                b7b2 = new B7B(this.A0C, null, null, null, null, null, null, null, this.A0a, null, this.A0g, str22);
                                A0n.add(b7b2);
                                break;
                            case 4:
                                b7a = this.A0a;
                                str = "Story creation upsell reel should have a simple action";
                                C37786JmD.A07(b7a, str);
                                String str222 = this.A1c;
                                b7b2 = new B7B(this.A0C, null, null, null, null, null, null, null, this.A0a, null, this.A0g, str222);
                                A0n.add(b7b2);
                                break;
                            case 5:
                                C37786JmD.A07(this.A0T, "Suggested clips should have a SuggestedClips object");
                                b7b2 = new B7B(null, null, null, null, null, null, this.A0T, null, null, null, this.A0g, this.A1c);
                                A0n.add(b7b2);
                                break;
                            case 6:
                            case 7:
                                C37786JmD.A07(this.A0U, "Suggested Products reel should have a SuggestedProducts object");
                                b7b2 = new B7B(null, null, null, null, null, null, null, this.A0U, null, null, this.A0g, this.A1c);
                                A0n.add(b7b2);
                                break;
                            case 8:
                                C37786JmD.A07(null, "Suggested Shops reel should have a SuggestedShops object");
                                throw null;
                            case 9:
                                b7a = this.A0a;
                                str = "Ads content growth story reel should have a simple action";
                                C37786JmD.A07(b7a, str);
                                String str2222 = this.A1c;
                                b7b2 = new B7B(this.A0C, null, null, null, null, null, null, null, this.A0a, null, this.A0g, str2222);
                                A0n.add(b7b2);
                                break;
                            case 10:
                                C37786JmD.A07(this.A0R, "Bloks netego should have a Bloks object");
                                b7b2 = new B7B(null, null, null, null, this.A0R, null, null, null, null, null, this.A0g, this.A1c);
                                A0n.add(b7b2);
                                break;
                            case 11:
                                C37786JmD.A07(this.A0G, "ACR Netego should have a ACRInStory object");
                                b7b2 = new B7B(null, this.A0G, null, null, null, null, null, null, null, null, this.A0g, this.A1c);
                                A0n.add(b7b2);
                                break;
                            case IgReactQEModule.CONFIG_KEY_OFFSET /* 12 */:
                                C37786JmD.A07(this.A0J, "Trending Prompts Netego should have a prompts in story object");
                                b7b2 = new B7B(null, null, this.A0J, null, null, null, null, null, null, null, this.A0g, this.A1c);
                                A0n.add(b7b2);
                                break;
                            default:
                                throw C25950ws.A0k(C073900b.A0L("Unsupported netego type:", C178789vr.A00(num3)));
                        }
                        this.A1d = false;
                        this.A12 = Collections.unmodifiableList(A0n);
                        this.A10 = Collections.unmodifiableList(A0n2);
                    } else if (BYz()) {
                        if (A0q(userSession)) {
                            C158758xl c158758xl = this.A0H;
                            if (c158758xl != null) {
                                b7b2 = new B7B(c158758xl, this.A1c);
                                A0n.add(b7b2);
                            }
                        } else if (this.A0H == null) {
                            boolean A1Z2 = C150688fG.A1Z(C0TD.A05, userSession, 36315782439111469L);
                            if (A1Z2) {
                                list = this.A0x;
                            } else {
                                list = this.A15;
                            }
                            int size = list.size();
                            for (int i = 0; i < size; i++) {
                                if (!A1Z2) {
                                    B7P A0N = C150638fB.A0N(this.A15, i);
                                    A0N.A2c(userSession).getClass();
                                    b7b3 = new B7B(A0N, A0N.A2c(userSession), AnonymousClass006.A01, this.A1c);
                                } else {
                                    B7O b7o = (B7O) this.A0x.get(i);
                                    B7P b7p = b7o.A0D;
                                    b7p.A2c(userSession).getClass();
                                    b7b3 = new B7B(b7p, b7o, b7p.A2c(userSession), this.A1c);
                                }
                                b7b3.A0F = this.A16;
                                if (i == 0 && (list2 = this.A0y) != null) {
                                    list2.contains(AutoGeneratedCardType.CAPTION);
                                }
                                A0n.add(b7b3);
                            }
                        }
                        this.A1d = false;
                        this.A12 = Collections.unmodifiableList(A0n);
                        this.A10 = Collections.unmodifiableList(A0n2);
                    } else {
                        if (A0j()) {
                            String str4 = this.A1c;
                            b7b2 = new B7B((User) null, AnonymousClass006.A0D, str4, str4);
                            b7b2.A0D = this.A0m;
                        } else if (this.A1R) {
                            Integer num4 = this.A0i;
                            num4.getClass();
                            List list3 = null;
                            if (num4 == AnonymousClass006.A00) {
                                list3 = this.A11;
                            }
                            b7b2 = new B7B(num4, list3);
                        } else {
                            ReelType reelType = this.A0P;
                            if (C25930wq.A1Z(reelType, ReelType.A0S)) {
                                B70 b70 = this.A0U;
                                b70.getClass();
                                b7b2 = new B7B(this.A0K, b70, this.A1c);
                            } else {
                                if (C25930wq.A1Z(reelType, ReelType.A0Y)) {
                                    if (C70763jC.A0E(C0TD.A05, userSession, 36327911426369757L)) {
                                        C7jU c7jU = this.A0A;
                                        c7jU.getClass();
                                        c7jU.A00.getClass();
                                        InterfaceC21973BoW interfaceC21973BoW = this.A0V;
                                        interfaceC21973BoW.getClass();
                                        User user = new User(interfaceC21973BoW.getId(), this.A0V.getName());
                                        ArrayList A0n3 = C25970wu.A0n(this.A0A.A00);
                                        for (C5KV c5kv : this.A0A.A00) {
                                            String str5 = c5kv.A01;
                                            if (str5.equals("intro")) {
                                                num2 = AnonymousClass006.A0F;
                                            } else if (str5.equals("supportive_superstar")) {
                                                num2 = AnonymousClass006.A0G;
                                            } else {
                                                C18350ix.A02("ig_superlatives", AnonymousClass006.A0j, "An invalid templateId was provided");
                                            }
                                            A0n3.add(new B7B(c5kv, user, num2, this.A1c, str5));
                                        }
                                        A0n.addAll(A0n3);
                                    }
                                } else {
                                    Iterator it = this.A19.iterator();
                                    while (it.hasNext()) {
                                        B7P A0G = C150628fA.A0G(it);
                                        boolean z2 = false;
                                        boolean A1V = C25940wr.A1V(A0G.A04);
                                        boolean A01 = C19544Aib.A01(A0G, userSession);
                                        if (C25960wt.A1V(A0G.AvD().BVU())) {
                                            z = true;
                                        }
                                        z = false;
                                        if (!A1V && !A01 && !z) {
                                            z2 = true;
                                        }
                                        if (!this.A1W) {
                                            if (z2) {
                                                A1Z = C25930wq.A1Z(this.A0P, ReelType.A0A);
                                                User A0H = B7P.A0H(A0G, userSession);
                                                String str6 = this.A1c;
                                                if (!A1Z) {
                                                    b7b = new B7B(A0G, A0H, AnonymousClass006.A02, str6);
                                                    b7b.A03 = this.A0E;
                                                } else {
                                                    b7b = new B7B(A0G, A0H, AnonymousClass006.A01, str6);
                                                }
                                                if (this.A1L) {
                                                    b7b.A0I = true;
                                                }
                                                b7b.A0H = A0f();
                                                A0n.add(b7b);
                                            } else {
                                                A0n2.add(Long.valueOf(A0G.A1v()));
                                                if (C7D3.A00(userSession).A06.booleanValue() && (arrayList = this.A0w) != null) {
                                                    arrayList.remove(A0G.A0N);
                                                }
                                            }
                                        } else {
                                            if (A0G.A2l() == AnonymousClass006.A0C && A0G.A04 != 2) {
                                                A1Z = C25930wq.A1Z(this.A0P, ReelType.A0A);
                                                User A0H2 = B7P.A0H(A0G, userSession);
                                                String str62 = this.A1c;
                                                if (!A1Z) {
                                                }
                                                if (this.A1L) {
                                                }
                                                b7b.A0H = A0f();
                                                A0n.add(b7b);
                                            }
                                            A0n2.add(Long.valueOf(A0G.A1v()));
                                            if (C7D3.A00(userSession).A06.booleanValue()) {
                                                arrayList.remove(A0G.A0N);
                                            }
                                        }
                                    }
                                    if (!this.A13.isEmpty()) {
                                        InterfaceC21973BoW interfaceC21973BoW2 = this.A0V;
                                        interfaceC21973BoW2.getClass();
                                        User BKI = interfaceC21973BoW2.BKI();
                                        if (BKI != null) {
                                            for (B77 b77 : this.A13) {
                                                A0n.add(new B7B(b77, BKI, this.A1c));
                                            }
                                        } else {
                                            C18350ix.A03("com.instagram.model.reels.Reel", "Reel with pending media should have an owner.");
                                        }
                                    }
                                    if (this.A0F != null) {
                                        if (!C25950ws.A1Z(((A8B) C150638fB.A0b(userSession, A8B.class, 9)).A00, this.A0F.A0Q)) {
                                            String str7 = this.A1c;
                                            C98y c98y = this.A0F;
                                            if (c98y.A0F != null) {
                                                num = AnonymousClass006.A0j;
                                            } else {
                                                num = AnonymousClass006.A0N;
                                            }
                                            A0n.add(new B7B(c98y, num, str7));
                                        }
                                    }
                                    if (!this.A1U) {
                                        Collections.sort(A0n, A1f);
                                    }
                                    if (A0n.isEmpty() && !A0n2.isEmpty()) {
                                        A0A = 0;
                                    } else if (A0n2.contains(Long.valueOf(this.A03)) && !A0n.isEmpty()) {
                                        A0A = ((B7B) A0n.get(A0n.size() - 1)).A0A();
                                    }
                                    this.A03 = A0A;
                                }
                                this.A1d = false;
                                this.A12 = Collections.unmodifiableList(A0n);
                                this.A10 = Collections.unmodifiableList(A0n2);
                            }
                        }
                        A0n.add(b7b2);
                        this.A1d = false;
                        this.A12 = Collections.unmodifiableList(A0n);
                        this.A10 = Collections.unmodifiableList(A0n2);
                    }
                }
            }
        }
        return this.A12;
    }

    public final Set A0Q() {
        Set unmodifiableSet;
        synchronized (this.A1b) {
            unmodifiableSet = Collections.unmodifiableSet(this.A19);
        }
        return unmodifiableSet;
    }

    public final void A0R(B7P b7p, UserSession userSession) {
        synchronized (this.A1b) {
            HashSet A0r = C91574uX.A0r(this.A19);
            A0r.add(b7p);
            long A1v = b7p.A1v();
            if (A1v > this.A03) {
                this.A03 = A1v;
            }
            if (C7D3.A00(userSession).A06.booleanValue()) {
                ArrayList arrayList = this.A0w;
                if (arrayList == null) {
                    arrayList = C25920wp.A0w();
                    this.A0w = arrayList;
                }
                arrayList.add(b7p.A0N);
            }
            this.A1d = true;
            this.A19 = Collections.unmodifiableSet(A0r);
        }
    }

    public final void A0S(C98y c98y) {
        long longValue;
        boolean booleanValue;
        Boolean bool = c98y.A0K;
        if (bool != null && !(booleanValue = bool.booleanValue())) {
            boolean z = true;
            if (!booleanValue) {
                z = false;
            }
            this.A1T = z;
        }
        C98y c98y2 = this.A0F;
        if (c98y2 == null) {
            this.A0F = c98y;
        } else {
            long j = c98y.A04;
            long j2 = c98y2.A04;
            if (j != j2) {
                C18350ix.A03("reel_broadcast_item_publish_error", C073900b.A0U("previous: ", " new: ", j2, j));
            }
            C98y c98y3 = this.A0F;
            C37786JmD.A0D(c98y3.A0Q.equals(c98y.A0Q));
            C37786JmD.A0C(c98y3.A0D.equals(c98y.A0D));
            C37786JmD.A0C(c98y3.A0Y.equals(c98y.A0Y));
            ImageUrl A03 = c98y.A03();
            if (!C3XZ.A02(A03)) {
                c98y3.A07 = A03;
                SystemClock.elapsedRealtime();
            }
            c98y3.A09 = c98y.A09;
            c98y3.A0U = c98y.A0U;
            c98y3.A0S = c98y.A0S;
            c98y3.A0V = c98y.A0V;
            c98y3.A0T = c98y.A0T;
            c98y3.A0c = c98y.A0c;
            c98y3.A0B = c98y.A0B;
            c98y3.A02 = c98y.A02;
            c98y3.A0j = c98y.A0j;
            c98y3.A01 = c98y.A01;
            c98y3.A04 = c98y.A04;
            c98y3.A03 = c98y.A03;
            c98y3.A0K = c98y.A0K;
            c98y3.A0n = c98y.A0n;
            c98y3.A08 = c98y.A08;
            c98y3.A0O = c98y.A0O;
            c98y3.A0P = c98y.A0P;
            c98y3.A0b = c98y.A0b;
            c98y3.A0W = c98y.A0W;
            c98y3.A00 = c98y.A00;
            c98y3.A0d = c98y.A0d;
            c98y3.A0m = c98y.A0m;
            if (!c98y.A0g.isEmpty()) {
                c98y3.A0g = c98y.A0g;
            }
            if (!c98y.A0h.isEmpty()) {
                c98y3.A0h = c98y.A0h;
            }
            Set set = c98y.A0k;
            c98y3.A0k.clear();
            c98y3.A0k.addAll(set);
            List list = c98y.A0i;
            c98y3.A0i.clear();
            c98y3.A0i.addAll(list);
            c98y3.A0N = c98y.A0N;
            c98y3.A0q = c98y.A0q;
            c98y3.A0A = c98y.A0A;
            c98y3.A0C = c98y.A0C;
            c98y3.A0e = c98y.A0e;
            c98y3.A0R = c98y.A0R;
            c98y3.A0X = c98y.A0X;
            C18512AEx c18512AEx = c98y.A0F;
            if (c18512AEx != null) {
                c98y3.A0F = c18512AEx;
            }
            c98y3.A05 = c98y.A05;
            c98y3.A0f = c98y.A0f;
            c98y3.A0L = c98y.A0L;
            c98y3.A0G = c98y.A0G;
            c98y3.A0M = c98y.A0M;
            c98y3.A0I = c98y.A0I;
            c98y3.A0J = c98y.A0J;
        }
        Long l = c98y.A0O;
        if (l == null) {
            longValue = -9223372036854775807L;
        } else {
            longValue = l.longValue();
        }
        if (longValue != -9223372036854775807L) {
            this.A05 = longValue;
        }
        Long l2 = c98y.A0P;
        if (l2 != null) {
            long longValue2 = l2.longValue();
            if (longValue2 != -9223372036854775807L) {
                this.A06 = longValue2;
            }
        }
        this.A03 = c98y.A04;
        this.A0l = Long.valueOf(c98y.A03);
        this.A1H = C25960wt.A1V(c98y.A0H);
    }

    /* JADX WARN: Code restructure failed: missing block: B:135:0x0274, code lost:
        if (r5.intValue() > 0) goto L134;
     */
    /* JADX WARN: Code restructure failed: missing block: B:173:0x03c2, code lost:
        if (r3.contains("story_remix_reply") == false) goto L177;
     */
    /* JADX WARN: Code restructure failed: missing block: B:93:0x019e, code lost:
        r6.add(r5);
     */
    /* JADX WARN: Removed duplicated region for block: B:114:0x021f  */
    /* JADX WARN: Removed duplicated region for block: B:124:0x0233  */
    /* JADX WARN: Removed duplicated region for block: B:127:0x024a  */
    /* JADX WARN: Removed duplicated region for block: B:130:0x0260  */
    /* JADX WARN: Removed duplicated region for block: B:144:0x02a7  */
    /* JADX WARN: Removed duplicated region for block: B:147:0x02b1  */
    /* JADX WARN: Removed duplicated region for block: B:150:0x02f9  */
    /* JADX WARN: Removed duplicated region for block: B:154:0x0318  */
    /* JADX WARN: Removed duplicated region for block: B:155:0x031b  */
    /* JADX WARN: Removed duplicated region for block: B:158:0x0328  */
    /* JADX WARN: Removed duplicated region for block: B:163:0x0370  */
    /* JADX WARN: Removed duplicated region for block: B:166:0x03ac  */
    /* JADX WARN: Removed duplicated region for block: B:169:0x03b2  */
    /* JADX WARN: Removed duplicated region for block: B:172:0x03bb  */
    /* JADX WARN: Removed duplicated region for block: B:177:0x03c9  */
    /* JADX WARN: Removed duplicated region for block: B:36:0x0081  */
    /* JADX WARN: Removed duplicated region for block: B:39:0x008d  */
    /* JADX WARN: Removed duplicated region for block: B:42:0x0098  */
    /* JADX WARN: Removed duplicated region for block: B:45:0x00b8  */
    /* JADX WARN: Removed duplicated region for block: B:48:0x00c6  */
    /* JADX WARN: Removed duplicated region for block: B:53:0x00d3  */
    /* JADX WARN: Removed duplicated region for block: B:63:0x00f3  */
    /* JADX WARN: Removed duplicated region for block: B:66:0x0119  */
    /* JADX WARN: Removed duplicated region for block: B:71:0x0125  */
    /* JADX WARN: Removed duplicated region for block: B:72:0x012b  */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public final void A0T(BAX bax, UserSession userSession) {
        B7A b7a;
        C20520B6y c20520B6y;
        C20521B6z c20521B6z;
        C20518B6w c20518B6w;
        B76 b76;
        C158888xy c158888xy;
        C158818xr c158818xr;
        C159418yy c159418yy;
        C19385Afy c19385Afy;
        Integer num;
        long j;
        Integer num2;
        Integer num3;
        String str;
        List A04;
        List A03;
        ArrayList arrayList;
        boolean z;
        Boolean bool;
        List list;
        Set set;
        boolean z2;
        C158788xo c158788xo;
        C158798xp c158798xp;
        List<Object> list2;
        ArrayList arrayList2;
        List list3;
        C158928y2 c158928y2;
        C158548xO c158548xO;
        Integer num4;
        Integer num5;
        List list4;
        boolean z3;
        B7P A0G;
        long j2;
        this.A0N = bax;
        ReelType reelType = bax.A0E;
        this.A0P = reelType;
        this.A0H = bax.A09;
        List list5 = bax.A1T;
        A0V(userSession, list5);
        this.A1A = C19716AlQ.A05(bax);
        this.A0g = C19716AlQ.A01(bax);
        this.A0C = bax.A05;
        C159198yZ c159198yZ = bax.A0Q;
        if (c159198yZ != null) {
            b7a = new B7A(c159198yZ);
        } else {
            b7a = null;
        }
        this.A0a = b7a;
        C158808xq c158808xq = bax.A0F;
        if (c158808xq != null) {
            c20520B6y = new C20520B6y(c158808xq);
        } else {
            c20520B6y = null;
        }
        this.A0Q = c20520B6y;
        C158878xx c158878xx = bax.A0H;
        if (c158878xx != null) {
            c20521B6z = new C20521B6z(c158878xx);
        } else {
            c20521B6z = null;
        }
        this.A0S = c20521B6z;
        C158328x1 c158328x1 = bax.A0I;
        if (c158328x1 != null) {
            synchronized (this.A1b) {
                this.A1d = true;
                this.A0T = c158328x1;
            }
        }
        C158748xk c158748xk = bax.A08;
        if (c158748xk != null) {
            c20518B6w = new C20518B6w(c158748xk);
        } else {
            c20518B6w = null;
        }
        this.A0G = c20518B6w;
        C156948um c156948um = bax.A02;
        if (c156948um != null) {
            b76 = new B76(c156948um);
        } else {
            b76 = null;
        }
        this.A0J = b76;
        int A0B = C91554uV.A0B(reelType);
        B70 b70 = null;
        if (A0B != 14) {
            if (A0B == 31) {
                c158888xy = bax.A0K;
                if (c158888xy != null) {
                    b70 = new B70(c158888xy);
                }
            }
            this.A0U = b70;
            B74 b74 = null;
            c158818xr = bax.A0G;
            if (c158818xr != null) {
                b74 = new B74(c158818xr);
            }
            this.A0R = b74;
            c159418yy = bax.A0S;
            if (c159418yy == null) {
                c19385Afy = new C19385Afy(c159418yy);
            } else {
                c19385Afy = null;
            }
            this.A0c = c19385Afy;
            this.A0W = bax.A0N;
            this.A1I = C0OR.A0I(bax.A0h, true);
            this.A0k = bax.A14;
            num = bax.A0y;
            if (num == null) {
                j = num.intValue();
            } else {
                j = -9223372036854775807L;
            }
            if (j != -9223372036854775807L) {
                if (num != null) {
                    j2 = num.intValue();
                } else {
                    j2 = -9223372036854775807L;
                }
                this.A05 = j2;
            }
            num2 = bax.A10;
            if (num2 != null) {
                long intValue = num2.intValue();
                if (intValue != -9223372036854775807L) {
                    this.A06 = intValue;
                }
            }
            num3 = bax.A0x;
            if (num3 != null && num3.intValue() != -1) {
                this.A01 = num3.intValue();
            }
            str = bax.A1M;
            if (str == null) {
                str = "";
            }
            this.A0q = str;
            this.A1B = C0OR.A0I(bax.A0Y, true);
            this.A1C = C0OR.A0I(bax.A0Z, true);
            this.A1L = C0OR.A0I(bax.A0m, true);
            A04 = C19716AlQ.A04(bax);
            if (!A04.isEmpty()) {
                if (list5 != null) {
                    synchronized (this.A1b) {
                        this.A1d = true;
                        ArrayList A0w = C25920wp.A0w();
                        Set A0Q = A0Q();
                        if (list5.isEmpty()) {
                            StringBuilder A0n = C25960wt.A0n();
                            A0n.append("Reel ID: ");
                            A0n.append(this.A1c);
                            A0n.append(" Reel type: ");
                            C18350ix.A03("reel_media_merge_empty_media_ids", C25950ws.A0t(this.A0P, A0n));
                        }
                        Iterator it = list5.iterator();
                        while (it.hasNext()) {
                            String A0h = C25930wq.A0h(it);
                            Iterator it2 = A04.iterator();
                            while (true) {
                                if (it2.hasNext()) {
                                    A0G = C150628fA.A0G(it2);
                                    if (A0h.equals(A0G.A35())) {
                                        break;
                                    }
                                } else {
                                    Iterator it3 = A0Q.iterator();
                                    while (it3.hasNext()) {
                                        A0G = C150628fA.A0G(it3);
                                        if (A0h.equals(A0G.A35())) {
                                        }
                                    }
                                    StringBuilder A0n2 = C25960wt.A0n();
                                    A0n2.append("Media ID: ");
                                    A0n2.append(A0h);
                                    A0n2.append(" Reel ID: ");
                                    A0n2.append(this.A1c);
                                    A0n2.append(" Reel type: ");
                                    C18350ix.A03("reel_media_merge_media_not_found", C25950ws.A0t(this.A0P, A0n2));
                                }
                            }
                        }
                        if (A0w.isEmpty()) {
                            StringBuilder A0n3 = C25960wt.A0n();
                            A0n3.append("Reel ID: ");
                            A0n3.append(this.A1c);
                            A0n3.append(" Reel type: ");
                            C18350ix.A03("reel_media_merge_empty_medias", C25950ws.A0t(this.A0P, A0n3));
                        }
                        A0X(A0w);
                    }
                } else {
                    A0X(A04);
                }
                this.A1J = C0OR.A0I(bax.A0i, true);
            }
            A03 = C19716AlQ.A03(bax);
            if (A03 != null) {
                synchronized (this.A1b) {
                    this.A1d = true;
                    this.A0x = Collections.unmodifiableList(A03);
                }
            }
            arrayList = this.A0w;
            if (arrayList != null) {
                A00(this, C91574uX.A0r(arrayList));
            }
            A04.isEmpty();
            z = false;
            this.A0v = C91564uW.A0u(bax.A1A);
            bool = bax.A0o;
            if (bool != null) {
                this.A1T = C25940wr.A1V(bool.booleanValue() ? 1 : 0);
            }
            Integer num6 = bax.A0z;
            long A05 = C25970wu.A05(num6);
            list = bax.A1V;
            C18531AFq c18531AFq = null;
            if (list == null) {
                set = C91574uX.A0r(list);
            } else {
                set = null;
            }
            A0W(userSession, set, A05);
            if (this.A0P == ReelType.A0K && num6 != null) {
                z2 = true;
            }
            z2 = false;
            this.A1N = z2;
            if (z2 && C25970wu.A05(num6) != C150628fA.A05(bax.A18)) {
                z = true;
            }
            this.A1O = z;
            this.A03 = C150628fA.A05(bax.A18);
            this.A0V = C19716AlQ.A00(bax, userSession);
            this.A02 = C25970wu.A05(bax.A0w);
            c158788xo = bax.A0C;
            if (c158788xo != null) {
                this.A0M = c158788xo;
            }
            this.A0D = bax.A06;
            c158798xp = bax.A0D;
            if (c158798xp != null) {
                c18531AFq = new C18531AFq(c158798xp);
            }
            this.A0O = c18531AFq;
            this.A1D = C0OR.A0I(bax.A0b, true);
            this.A1E = C0OR.A0I(bax.A0d, true);
            this.A1a = C0OR.A0I(bax.A0e, true);
            C0OR.A0I(bax.A0c, true);
            this.A0L = bax.A0B;
            this.A0u = bax.A1O;
            this.A0l = bax.A16;
            this.A0f = bax.A0u;
            this.A0r = bax.A1H;
            this.A0Y = bax.A0O;
            this.A00 = C25970wu.A05(bax.A0t);
            list2 = bax.A1W;
            if (list2 == null) {
                arrayList2 = C25920wp.A0x(list2);
                for (Object obj : list2) {
                    arrayList2.add(Double.valueOf(C25970wu.A00(obj)));
                }
            } else {
                arrayList2 = null;
            }
            this.A16 = arrayList2;
            this.A17 = bax.A1X;
            list3 = bax.A1P;
            this.A0y = list3;
            if (list3 != null) {
                AutoGeneratedCardType autoGeneratedCardType = AutoGeneratedCardType.GENERIC_CARD;
                if (list3.contains(autoGeneratedCardType)) {
                    c158928y2 = C150638fB.A0N(C19716AlQ.A04(bax), this.A0y.indexOf(autoGeneratedCardType)).A0f.A1R;
                    this.A0X = c158928y2;
                    this.A18 = C19763AmC.A0K(bax.A1Q);
                    this.A1F = C0OR.A0I(bax.A0a, true);
                    this.A1H = C0OR.A0I(bax.A0g, true);
                    this.A0t = C91564uW.A0u(bax.A19);
                    this.A1Z = bax.A03;
                    this.A0b = bax.A0R;
                    c158548xO = bax.A07;
                    if (c158548xO != null) {
                        this.A0B = new B7J(c158548xO);
                    }
                    this.A1K = C0OR.A0I(bax.A0k, true);
                    C0OR.A0I(bax.A0n, true);
                    this.A0I = bax.A0A;
                    this.A0d = bax.A0f;
                    this.A1Y = C0OR.A0I(bax.A0p, true);
                    this.A0p = bax.A1E;
                    this.A0o = bax.A1C;
                    this.A0s = bax.A1J;
                    this.A0n = bax.A1B;
                    this.A0Z = bax.A0P;
                    num4 = bax.A11;
                    if (num4 != null) {
                        this.A0h = num4;
                    }
                    num5 = bax.A12;
                    if (num5 != null) {
                        this.A0j = num5;
                    }
                    list4 = bax.A1R;
                    this.A0z = list4;
                    boolean z4 = true;
                    if (list4 != null) {
                        z3 = true;
                    }
                    z3 = false;
                    this.A1M = z3;
                    this.A1P = (list4 == null && list4.contains("story_selfie_reply")) ? false : false;
                    this.A14 = bax.A1U;
                    this.A09 = bax.A01;
                    this.A08 = bax.A00;
                    this.A0A = bax.A04;
                }
            }
            c158928y2 = null;
            this.A0X = c158928y2;
            this.A18 = C19763AmC.A0K(bax.A1Q);
            this.A1F = C0OR.A0I(bax.A0a, true);
            this.A1H = C0OR.A0I(bax.A0g, true);
            this.A0t = C91564uW.A0u(bax.A19);
            this.A1Z = bax.A03;
            this.A0b = bax.A0R;
            c158548xO = bax.A07;
            if (c158548xO != null) {
            }
            this.A1K = C0OR.A0I(bax.A0k, true);
            C0OR.A0I(bax.A0n, true);
            this.A0I = bax.A0A;
            this.A0d = bax.A0f;
            this.A1Y = C0OR.A0I(bax.A0p, true);
            this.A0p = bax.A1E;
            this.A0o = bax.A1C;
            this.A0s = bax.A1J;
            this.A0n = bax.A1B;
            this.A0Z = bax.A0P;
            num4 = bax.A11;
            if (num4 != null) {
            }
            num5 = bax.A12;
            if (num5 != null) {
            }
            list4 = bax.A1R;
            this.A0z = list4;
            boolean z42 = true;
            if (list4 != null) {
            }
            z3 = false;
            this.A1M = z3;
            this.A1P = (list4 == null && list4.contains("story_selfie_reply")) ? false : false;
            this.A14 = bax.A1U;
            this.A09 = bax.A01;
            this.A08 = bax.A00;
            this.A0A = bax.A04;
        }
        Integer A01 = C19716AlQ.A01(bax);
        if (A01 != null) {
            int intValue2 = A01.intValue();
            if (intValue2 != 6) {
                if (intValue2 == 7) {
                    c158888xy = bax.A0J;
                }
            } else {
                c158888xy = bax.A0L;
            }
            if (c158888xy != null) {
            }
        }
        this.A0U = b70;
        B74 b742 = null;
        c158818xr = bax.A0G;
        if (c158818xr != null) {
        }
        this.A0R = b742;
        c159418yy = bax.A0S;
        if (c159418yy == null) {
        }
        this.A0c = c19385Afy;
        this.A0W = bax.A0N;
        this.A1I = C0OR.A0I(bax.A0h, true);
        this.A0k = bax.A14;
        num = bax.A0y;
        if (num == null) {
        }
        if (j != -9223372036854775807L) {
        }
        num2 = bax.A10;
        if (num2 != null) {
        }
        num3 = bax.A0x;
        if (num3 != null) {
            this.A01 = num3.intValue();
        }
        str = bax.A1M;
        if (str == null) {
        }
        this.A0q = str;
        this.A1B = C0OR.A0I(bax.A0Y, true);
        this.A1C = C0OR.A0I(bax.A0Z, true);
        this.A1L = C0OR.A0I(bax.A0m, true);
        A04 = C19716AlQ.A04(bax);
        if (!A04.isEmpty()) {
        }
        A03 = C19716AlQ.A03(bax);
        if (A03 != null) {
        }
        arrayList = this.A0w;
        if (arrayList != null) {
        }
        A04.isEmpty();
        z = false;
        this.A0v = C91564uW.A0u(bax.A1A);
        bool = bax.A0o;
        if (bool != null) {
        }
        Integer num62 = bax.A0z;
        long A052 = C25970wu.A05(num62);
        list = bax.A1V;
        C18531AFq c18531AFq2 = null;
        if (list == null) {
        }
        A0W(userSession, set, A052);
        if (this.A0P == ReelType.A0K) {
            z2 = true;
        }
        z2 = false;
        this.A1N = z2;
        if (z2) {
            z = true;
        }
        this.A1O = z;
        this.A03 = C150628fA.A05(bax.A18);
        this.A0V = C19716AlQ.A00(bax, userSession);
        this.A02 = C25970wu.A05(bax.A0w);
        c158788xo = bax.A0C;
        if (c158788xo != null) {
        }
        this.A0D = bax.A06;
        c158798xp = bax.A0D;
        if (c158798xp != null) {
        }
        this.A0O = c18531AFq2;
        this.A1D = C0OR.A0I(bax.A0b, true);
        this.A1E = C0OR.A0I(bax.A0d, true);
        this.A1a = C0OR.A0I(bax.A0e, true);
        C0OR.A0I(bax.A0c, true);
        this.A0L = bax.A0B;
        this.A0u = bax.A1O;
        this.A0l = bax.A16;
        this.A0f = bax.A0u;
        this.A0r = bax.A1H;
        this.A0Y = bax.A0O;
        this.A00 = C25970wu.A05(bax.A0t);
        list2 = bax.A1W;
        if (list2 == null) {
        }
        this.A16 = arrayList2;
        this.A17 = bax.A1X;
        list3 = bax.A1P;
        this.A0y = list3;
        if (list3 != null) {
        }
        c158928y2 = null;
        this.A0X = c158928y2;
        this.A18 = C19763AmC.A0K(bax.A1Q);
        this.A1F = C0OR.A0I(bax.A0a, true);
        this.A1H = C0OR.A0I(bax.A0g, true);
        this.A0t = C91564uW.A0u(bax.A19);
        this.A1Z = bax.A03;
        this.A0b = bax.A0R;
        c158548xO = bax.A07;
        if (c158548xO != null) {
        }
        this.A1K = C0OR.A0I(bax.A0k, true);
        C0OR.A0I(bax.A0n, true);
        this.A0I = bax.A0A;
        this.A0d = bax.A0f;
        this.A1Y = C0OR.A0I(bax.A0p, true);
        this.A0p = bax.A1E;
        this.A0o = bax.A1C;
        this.A0s = bax.A1J;
        this.A0n = bax.A1B;
        this.A0Z = bax.A0P;
        num4 = bax.A11;
        if (num4 != null) {
        }
        num5 = bax.A12;
        if (num5 != null) {
        }
        list4 = bax.A1R;
        this.A0z = list4;
        boolean z422 = true;
        if (list4 != null) {
        }
        z3 = false;
        this.A1M = z3;
        this.A1P = (list4 == null && list4.contains("story_selfie_reply")) ? false : false;
        this.A14 = bax.A1U;
        this.A09 = bax.A01;
        this.A08 = bax.A00;
        this.A0A = bax.A04;
    }

    public final void A0X(List list) {
        synchronized (this.A1b) {
            this.A1d = true;
            if (BYz()) {
                this.A15 = Collections.unmodifiableList(list);
            } else {
                this.A19 = Collections.unmodifiableSet(C91574uX.A0r(list));
            }
        }
    }

    public final boolean A0Y() {
        for (B77 b77 : this.A13) {
            if (!b77.A00.A0v()) {
                return true;
            }
        }
        return false;
    }

    public final boolean A0Z() {
        String str = this.A1c;
        if (str != null && str.equals(AnonymousClass000.A00(258))) {
            return true;
        }
        return false;
    }

    public final boolean A0a() {
        ReelType reelType = this.A0P;
        if (reelType != ReelType.A05 && reelType != ReelType.A07) {
            return false;
        }
        return true;
    }

    public final boolean A0b() {
        C98y c98y = this.A0F;
        if (c98y != null && c98y.A0F != null) {
            return true;
        }
        return false;
    }

    public final boolean A0c() {
        C98y c98y = this.A0F;
        if (c98y != null && c98y.A0F == null) {
            return true;
        }
        return false;
    }

    public final boolean A0d() {
        if (this.A1V && this.A0P == ReelType.A0a) {
            return true;
        }
        return false;
    }

    public final boolean A0e() {
        Long l = this.A0l;
        if (l == null) {
            return false;
        }
        if (l.longValue() + (C171939ke.A00 / 1000) > C25980wv.A08()) {
            return false;
        }
        return true;
    }

    public final boolean A0h() {
        return C25930wq.A1Z(this.A0P, ReelType.A0M);
    }

    public final boolean A0i() {
        ReelType reelType = this.A0P;
        if (reelType != ReelType.A0K && reelType != ReelType.A0T) {
            return false;
        }
        return true;
    }

    public final boolean A0j() {
        if (this.A1R && this.A0i == AnonymousClass006.A01) {
            return true;
        }
        return false;
    }

    public final boolean A0k() {
        ReelType reelType = this.A0P;
        if (reelType != ReelType.A0W && reelType != ReelType.A0F && reelType != ReelType.A0C && reelType != ReelType.A0V) {
            return false;
        }
        return true;
    }

    /* JADX WARN: Code restructure failed: missing block: B:5:0x000e, code lost:
        if (r4.A1V != false) goto L16;
     */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public final boolean A0l() {
        boolean z;
        ReelType reelType = this.A0P;
        if (C25930wq.A1Z(reelType, ReelType.A0a)) {
            z = true;
        }
        z = false;
        if (this.A1c != null) {
            if (z || reelType == ReelType.A0K || A0a()) {
                return true;
            }
            return false;
        }
        return false;
    }

    public final boolean A0m(B7P b7p) {
        if (!this.A19.contains(b7p) && !this.A15.contains(b7p)) {
            return false;
        }
        return true;
    }

    public final boolean A0n(UserSession userSession) {
        if (this.A1V) {
            return C150688fG.A1a(this, userSession, 3);
        }
        return this.A1D;
    }

    public final boolean A0p(UserSession userSession) {
        if (this.A1V) {
            return C150688fG.A1a(this, userSession, 6);
        }
        return this.A1a;
    }

    public final boolean A0q(UserSession userSession) {
        boolean booleanValue = C70763jC.A05(C0TD.A05, userSession, 36324973668934479L).booleanValue();
        if (this.A0H != null && booleanValue) {
            return true;
        }
        return false;
    }

    public final boolean A0r(UserSession userSession) {
        if (!this.A10.isEmpty() && A0s(userSession)) {
            return true;
        }
        return false;
    }

    public final boolean A0u(UserSession userSession) {
        ReelCarouselType reelCarouselType = ReelCarouselType.OPT_IN;
        ReelCarouselType reelCarouselType2 = this.A0Y;
        if ((reelCarouselType.equals(reelCarouselType2) || ReelCarouselType.DPA.equals(reelCarouselType2)) && C150658fD.A05(this, userSession) > 1) {
            return true;
        }
        return false;
    }

    public final boolean A0v(UserSession userSession) {
        long A03 = C70763jC.A03(C0TD.A05, userSession, 36596389832100107L);
        if (A03 >= 0) {
            long j = this.A07;
            if (j > 0 && C25990ww.A02(j) < A03) {
                return true;
            }
            return false;
        }
        return this.A1Q;
    }

    public final boolean A0w(UserSession userSession) {
        if (C70763jC.A0E(C0TD.A05, userSession, 36327911426369757L) && this.A0P == ReelType.A0Y) {
            return true;
        }
        return false;
    }

    @Override // p000X.InterfaceC21924Bnj
    public final String BDU(UserSession userSession) {
        List list = this.A12;
        if (!list.isEmpty() && C150688fG.A0K(list, 0).BW9()) {
            return C19763AmC.A0C(B7B.A01(C150688fG.A0K(list, 0)), userSession);
        }
        if (list.isEmpty() || !C150688fG.A0K(list, 0).A1I(userSession) || C150688fG.A0K(list, 0).mBrandResearchSurvey == null) {
            return null;
        }
        return C150688fG.A0K(list, 0).mBrandResearchSurvey.A08;
    }

    @Override // p000X.InterfaceC21924Bnj
    public final boolean BYz() {
        return C25930wq.A1Z(this.A0P, ReelType.A03);
    }

    public final boolean equals(Object obj) {
        if ((obj instanceof Reel) && C40702Gy.A00(((Reel) obj).A1c, this.A1c)) {
            return true;
        }
        return false;
    }

    public final int hashCode() {
        return C91534uT.A0D(this.A1c);
    }

    public final String toString() {
        String str;
        StringBuilder A0m = C25940wr.A0m("{id: ");
        A0m.append(this.A1c);
        A0m.append(" owner: ");
        InterfaceC21973BoW interfaceC21973BoW = this.A0V;
        if (interfaceC21973BoW != null) {
            str = interfaceC21973BoW.toString();
        } else {
            str = "null";
        }
        A0m.append(str);
        A0m.append(" reel type: ");
        A0m.append(this.A0P);
        return C25930wq.A0f("}", A0m);
    }

    public final int A02(UserSession userSession) {
        if (!A0t(userSession) && !A0c() && ((!A0f() || this.A1N) && !A0a() && !A0Z() && !BYz())) {
            C7D3 A00 = C7D3.A00(userSession);
            boolean booleanValue = A00.A05.booleanValue();
            List A0P = A0P(userSession);
            if (booleanValue) {
                int A0F = C91524uS.A0F(A0P);
                int i = A0F;
                while (true) {
                    if (i >= 0) {
                        if (A00.A06(this, C150688fG.A0K(A0P, i))) {
                            break;
                        }
                        i--;
                    } else {
                        i = -1;
                        break;
                    }
                }
                if (i == A0F) {
                    return 0;
                }
                return i + 1;
            }
            for (int i2 = 0; i2 < A0P.size(); i2++) {
                if (!A00.A06(this, C150688fG.A0K(A0P, i2))) {
                    return i2;
                }
            }
        }
        return 0;
    }

    public final long A04() {
        if (!C150678fF.A1T(this)) {
            return 0L;
        }
        Integer num = this.A0g;
        num.getClass();
        int intValue = num.intValue();
        if (intValue != 6 && intValue != 7) {
            if (intValue == 8) {
                C37786JmD.A07(null, "Shops For You netego should have suggested shops object");
                throw null;
            }
            throw C91544uU.A0v("Trying to get the shopping netego item count of a non-shopping netego unit");
        }
        C37786JmD.A07(this.A0U, "Products For You netego should have suggested products object");
        List list = this.A0U.A00.A0D;
        if (list == null) {
            list = C0ZV.A00;
        }
        return list.size();
    }

    public final B7B A09(UserSession userSession, int i) {
        return C150688fG.A0K(A0P(userSession), i);
    }

    public final String A0D() {
        boolean z = true;
        if (A0Z()) {
            z = false;
        }
        if (!z) {
            return null;
        }
        String str = this.A0v;
        if (str != null) {
            return str;
        }
        if (C19652AkN.A04(getId())) {
            return getId();
        }
        C18350ix.A03("Ad$ Revenue Impacted: FIX IMMEDIATELY!", StringFormatUtil.formatStrLocaleSafe("Non Numeric Reel ID found in Ads Injection. ReelID: %s \r\nThis affects (reduces) ads revenue.\r\nRefer https://fb.facebook.com/groups/214085649094210/permalink/250107518825356/ and roll a fix ASAP.\r\nExperiments that cause non numeric IDs in tray inventory cannot ship until this is fixed.", getId()));
        return null;
    }

    public final String A0F() {
        C158868xw c158868xw;
        C158858xv c158858xv;
        if (!C150678fF.A1T(this)) {
            return null;
        }
        Integer num = this.A0g;
        num.getClass();
        int intValue = num.intValue();
        if (intValue != 6 && intValue != 7) {
            if (intValue == 8) {
                return null;
            }
            throw C91544uU.A0v("Trying to get the shopping netego incentive id of a non-shopping netego unit");
        }
        C37786JmD.A07(this.A0U, "Products For You netego should have suggested products object");
        C158848xu c158848xu = this.A0U.A00.A03;
        if (c158848xu == null || (c158868xw = c158848xu.A00) == null || (c158858xv = c158868xw.A00) == null) {
            return null;
        }
        return c158858xv.A00.A07;
    }

    public final String A0I() {
        if (A0c()) {
            C98y c98y = this.A0F;
            c98y.getClass();
            if (!Collections.unmodifiableSet(c98y.A0k).isEmpty()) {
                return "live_with";
            }
        }
        if (A0c()) {
            return "live";
        }
        if (A0i()) {
            return "highlight";
        }
        if (A0k()) {
            return "suggested_highlight";
        }
        if (A0g()) {
            return "live_question_and_answer";
        }
        if (!C150668fE.A1U(this) && !A0j()) {
            if (A0h()) {
                return "memory_reel";
            }
            return "story";
        }
        return "rollcall_v2";
    }

    public final String A0L(int i) {
        C158828xs c158828xs;
        Merchant merchant;
        if (C150678fF.A1T(this)) {
            Integer num = this.A0g;
            num.getClass();
            int intValue = num.intValue();
            if (intValue != 6 && intValue != 7) {
                if (intValue == 8) {
                    C37786JmD.A07(null, "Shops For You netego should have suggested shops object");
                    throw null;
                }
                throw C91544uU.A0v("Trying to get the merchant id of a non-shopping netego unit");
            }
            C37786JmD.A07(this.A0U, "Products For You netego should have suggested products object");
            List list = this.A0U.A00.A0D;
            String str = (list == null || (c158828xs = (C158828xs) list.get(i)) == null || (merchant = c158828xs.A01.A0C) == null || (str = merchant.A06) == null) ? null : null;
            str.getClass();
            return str;
        }
        throw C91544uU.A0v("Trying to get the shopping netego tracking token of a non-shopping netego unit");
    }

    /* JADX WARN: Multi-variable type inference failed */
    /* JADX WARN: Type inference failed for: r2v1, types: [X.0ZV] */
    /* JADX WARN: Type inference failed for: r2v2, types: [java.util.List] */
    /* JADX WARN: Type inference failed for: r2v4, types: [java.util.AbstractCollection, java.util.ArrayList] */
    public final List A0O(int i) {
        ?? r2;
        Long l;
        if (!C150678fF.A1T(this)) {
            return null;
        }
        Integer num = this.A0g;
        num.getClass();
        int intValue = num.intValue();
        if (intValue != 6 && intValue != 7) {
            if (intValue == 8) {
                return null;
            }
            throw C91544uU.A0v("Trying to get the shopping netego product ids of a non-shopping netego unit");
        }
        C37786JmD.A07(this.A0U, "Products For You netego should have suggested products object");
        List<C158828xs> list = this.A0U.A00.A0D;
        if (list != null) {
            r2 = C25920wp.A0x(list);
            for (C158828xs c158828xs : list) {
                String str = c158828xs.A01.A0j;
                if (str != null) {
                    l = C25920wp.A0e(str);
                } else {
                    l = null;
                }
                r2.add(l);
            }
        } else {
            r2 = C0ZV.A00;
        }
        return r2.subList(i, i + 1);
    }

    public final void A0U(UserSession userSession) {
        C6N7.A00(userSession).A05(new C32675Gu1(this));
    }

    public final void A0V(UserSession userSession, List list) {
        HashSet hashSet;
        ArrayList arrayList = null;
        if (C7D3.A00(userSession).A04.booleanValue()) {
            HashSet A0r = C91574uX.A0r(A0N());
            if (list != null) {
                hashSet = C91574uX.A0r(list);
            } else {
                hashSet = null;
            }
            if (hashSet != null && !hashSet.isEmpty()) {
                A0r = C91574uX.A0r(A0r);
                A0r.removeAll(hashSet);
            }
            if (!A0r.isEmpty()) {
                C7D3.A00(userSession).A03(new Pair(C25980wv.A0c(), A0r), this, userSession);
            }
        }
        if (list != null) {
            arrayList = C25950ws.A0w(list);
        }
        this.A0w = arrayList;
    }

    public final void A0W(UserSession userSession, Set set, long j) {
        if (!A0c() && !BYz() && !C25930wq.A1Z(this.A0P, ReelType.A0N) && !A0a() && !A0Z()) {
            C7D3.A00(userSession).A03(new Pair(Long.valueOf(j), set), this, userSession);
        }
    }

    public final boolean A0f() {
        if (!A0i() && !A0k()) {
            return false;
        }
        return true;
    }

    public final boolean A0g() {
        if (A0c()) {
            C98y c98y = this.A0F;
            c98y.getClass();
            if (c98y.A0N != null) {
                return true;
            }
        }
        return false;
    }

    public final boolean A0o(UserSession userSession) {
        String str;
        List<B7B> A0P = A0P(userSession);
        if (!A0a() || (A0P.isEmpty() && this.A1A.size() <= 0)) {
            long j = -1;
            if (!this.A10.isEmpty()) {
                j = C25950ws.A0E(Collections.max(this.A10));
            }
            if (!A0P.isEmpty()) {
                if (this.A0P == ReelType.A0a && C7D3.A00(userSession).A02.booleanValue()) {
                    List A0N = A0N();
                    ArrayList A0w = C25920wp.A0w();
                    for (B7B b7b : A0P) {
                        B7P b7p = b7b.A0M;
                        if (b7p != null) {
                            str = b7p.A0N;
                        } else {
                            str = b7b.A0U;
                        }
                        A0w.add(str);
                    }
                    if (!A0w.containsAll(A0N)) {
                        return false;
                    }
                }
                j = Math.max(C150688fG.A0K(A0P, C91544uU.A0M(A0P, 1)).A0A(), j);
            }
            if (j < this.A03) {
                return false;
            }
        }
        return true;
    }

    public final boolean A0s(UserSession userSession) {
        if (A0P(userSession).isEmpty() && !(!this.A1A.isEmpty())) {
            return true;
        }
        return false;
    }

    public final boolean A0t(UserSession userSession) {
        long max;
        List<InterfaceC21924Bnj> unmodifiableList;
        if (A0c()) {
            return false;
        }
        if (this.A1L) {
            if (C7D3.A00(userSession).A05(this)) {
                return true;
            }
            return false;
        } else if (A0Z()) {
            return false;
        } else {
            List A0P = A0P(userSession);
            if (A0P.isEmpty()) {
                max = this.A03;
            } else {
                max = Math.max(C150688fG.A0K(A0P, C91524uS.A0F(A0P)).A0A(), this.A03);
            }
            HashSet A0r = C91574uX.A0r(A0N());
            synchronized (this) {
                unmodifiableList = Collections.unmodifiableList(this.A13);
            }
            for (InterfaceC21924Bnj interfaceC21924Bnj : unmodifiableList) {
                A0r.add(interfaceC21924Bnj.getId());
            }
            C7D3 A00 = C7D3.A00(userSession);
            Long valueOf = Long.valueOf(max);
            if (A0r.isEmpty()) {
                A0r = null;
            }
            return A00.A04(new Pair(valueOf, A0r), this);
        }
    }

    @Override // p000X.InterfaceC21924Bnj
    public final String getId() {
        if (A0Z()) {
            C18350ix.A03("reel", "Add to story reel cannot be referenced directly by ID");
        }
        return this.A1c;
    }

    public Reel(InterfaceC21973BoW interfaceC21973BoW, String str, boolean z) {
        boolean A1Y = C150618f9.A1Y(this);
        this.A1W = false;
        this.A1B = A1Y;
        this.A1b = new Object();
        this.A18 = C25920wp.A0z();
        this.A1M = A1Y;
        this.A1P = A1Y;
        this.A1G = false;
        this.A14 = null;
        this.A0A = null;
        if (z && (interfaceC21973BoW == null || interfaceC21973BoW.BJJ() != AnonymousClass006.A01)) {
            A1Y = false;
        }
        C37786JmD.A0D(A1Y);
        this.A1c = str;
        this.A0V = interfaceC21973BoW;
        this.A1V = z;
        this.A1R = false;
    }

    public Reel(ReelType reelType, InterfaceC21973BoW interfaceC21973BoW, String str, boolean z) {
        this(interfaceC21973BoW, str, z);
        this.A1R = false;
        this.A0P = reelType;
    }
}
