.class public Lcom/facebook/redex/IDxMCallbackShape23S1200000_7_I2;
.super Ljava/lang/Object;
.source ""

# interfaces
.implements Lcom/facebook/msys/mca/MailboxCallback;


# instance fields
.field public A00:Ljava/lang/Object;

.field public A01:Ljava/lang/Object;

.field public A02:Ljava/lang/String;

.field public final A03:I


# direct methods
.method public constructor <init>(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;I)V
    .locals 0

    .line 0
    iput p4, p0, Lcom/facebook/redex/IDxMCallbackShape23S1200000_7_I2;->A03:I

    .line 1
    .line 2
    iput-object p1, p0, Lcom/facebook/redex/IDxMCallbackShape23S1200000_7_I2;->A00:Ljava/lang/Object;

    .line 3
    .line 4
    iput-object p2, p0, Lcom/facebook/redex/IDxMCallbackShape23S1200000_7_I2;->A01:Ljava/lang/Object;

    .line 5
    .line 6
    iput-object p3, p0, Lcom/facebook/redex/IDxMCallbackShape23S1200000_7_I2;->A02:Ljava/lang/String;

    .line 7
    .line 8
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 9
    .line 10
    .line 11
    return-void
    .line 12
    .line 13
    .line 14
    .line 15
    .line 16
    .line 17
    .line 18
    .line 19
    .line 20
    .line 21
    .line 22
    .line 23
.end method


# virtual methods
.method public final bridge synthetic onCompletion(Ljava/lang/Object;)V
    .locals 10

    .line 0
    move-object v5, p1

    .line 1
    iget v0, p0, Lcom/facebook/redex/IDxMCallbackShape23S1200000_7_I2;->A03:I

    .line 2
    .line 3
    packed-switch v0, :pswitch_data_0

    .line 4
    .line 5
    .line 6
    check-cast v5, Lcom/facebook/msys/mca/SlimMailbox;

    .line 7
    .line 8
    monitor-enter v5

    .line 9
    :try_start_0
    iget-object v4, v5, Lcom/facebook/msys/mca/SlimMailbox;->mNotificationCenterCallbackManager:LX/Lnj;

    .line 10
    .line 11
    if-nez v4, :cond_0

    .line 12
    .line 13
    invoke-virtual {v5}, Lcom/facebook/msys/mca/SlimMailbox;->getNotificationCenter()Lcom/facebook/msys/mci/NotificationCenter;

    .line 14
    .line 15
    .line 16
    move-result-object v0

    .line 17
    new-instance v4, LX/Lnj;

    .line 18
    .line 19
    invoke-direct {v4, v0}, LX/Lnj;-><init>(Lcom/facebook/msys/mci/NotificationCenter;)V

    .line 20
    .line 21
    .line 22
    iput-object v4, v5, Lcom/facebook/msys/mca/SlimMailbox;->mNotificationCenterCallbackManager:LX/Lnj;
    :try_end_0
    .catchall {:try_start_0 .. :try_end_0} :catchall_0

    .line 23
    .line 24
    :cond_0
    monitor-exit v5

    .line 25
    iget-object v3, p0, Lcom/facebook/redex/IDxMCallbackShape23S1200000_7_I2;->A02:Ljava/lang/String;

    .line 26
    .line 27
    iget-object v2, p0, Lcom/facebook/redex/IDxMCallbackShape23S1200000_7_I2;->A01:Ljava/lang/Object;

    .line 28
    .line 29
    check-cast v2, Lcom/facebook/msys/util/NotificationScope;

    .line 30
    .line 31
    iget-object v0, v4, LX/Lnj;->A02:Ljava/util/Map;

    .line 32
    .line 33
    invoke-interface {v0, v2}, Ljava/util/Map;->remove(Ljava/lang/Object;)Ljava/lang/Object;

    .line 34
    .line 35
    .line 36
    iget-object v1, v4, LX/Lnj;->A01:Lcom/facebook/msys/mci/NotificationCenter;

    .line 37
    .line 38
    iget-object v0, v4, LX/Lnj;->A00:Lcom/facebook/msys/mci/NotificationCenter$NotificationCallback;

    .line 39
    .line 40
    invoke-virtual {v1, v0, v3, v2}, Lcom/facebook/msys/mci/NotificationCenter;->removeObserver(Lcom/facebook/msys/mci/NotificationCenter$NotificationCallback;Ljava/lang/String;LX/HjH;)V

    .line 41
    .line 42
    .line 43
    return-void

    .line 44
    :catchall_0
    move-exception v0

    .line 45
    monitor-exit v5

    .line 46
    throw v0

    .line 47
    :pswitch_0
    check-cast v5, Lcom/facebook/msys/mca/Mailbox;

    .line 48
    .line 49
    sget-object v1, LX/LBv;->A00:LX/GHs;

    .line 50
    .line 51
    const/16 v0, 0xb

    .line 52
    .line 53
    invoke-static {v1, v0}, LX/Kyw;->A0r(LX/GHs;I)Ljava/lang/String;

    .line 54
    .line 55
    .line 56
    move-result-object v3

    .line 57
    invoke-virtual {v5}, Lcom/facebook/msys/mca/Mailbox;->getNotificationCenterCallbackManager()LX/Lnj;

    .line 58
    .line 59
    .line 60
    move-result-object v1

    .line 61
    const/4 v0, 0x6

    .line 62
    invoke-static {v1, p0, v3, v0}, LX/Lnj;->A00(LX/Lnj;Ljava/lang/Object;Ljava/lang/String;I)Lcom/facebook/msys/util/NotificationScope;

    .line 63
    .line 64
    .line 65
    move-result-object v2

    .line 66
    iget-object v0, p0, Lcom/facebook/redex/IDxMCallbackShape23S1200000_7_I2;->A01:Ljava/lang/Object;

    .line 67
    .line 68
    invoke-static {v2, v0, v3}, LX/Kyw;->A1I(Lcom/facebook/msys/util/NotificationScope;Ljava/lang/Object;Ljava/lang/String;)V

    .line 69
    .line 70
    .line 71
    iget-object v1, p0, Lcom/facebook/redex/IDxMCallbackShape23S1200000_7_I2;->A02:Ljava/lang/String;

    .line 72
    .line 73
    const/16 v0, 0xa

    .line 74
    .line 75
    invoke-static {v0, v5, v1, v2}, Lcom/facebook/encryptedbackups/mca/MailboxEncryptedBackupsJNI;->dispatchVOOO(ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V

    .line 76
    .line 77
    .line 78
    return-void

    .line 79
    :pswitch_1
    check-cast v5, Lcom/facebook/msys/mca/Mailbox;

    .line 80
    .line 81
    sget-object v1, LX/LBv;->A00:LX/GHs;

    .line 82
    .line 83
    const/16 v0, 0x1c

    .line 84
    .line 85
    invoke-static {v1, v0}, LX/Kyw;->A0r(LX/GHs;I)Ljava/lang/String;

    .line 86
    .line 87
    .line 88
    move-result-object v3

    .line 89
    invoke-virtual {v5}, Lcom/facebook/msys/mca/Mailbox;->getNotificationCenterCallbackManager()LX/Lnj;

    .line 90
    .line 91
    .line 92
    move-result-object v1

    .line 93
    const/4 v0, 0x7

    .line 94
    invoke-static {v1, p0, v3, v0}, LX/Lnj;->A00(LX/Lnj;Ljava/lang/Object;Ljava/lang/String;I)Lcom/facebook/msys/util/NotificationScope;

    .line 95
    .line 96
    .line 97
    move-result-object v2

    .line 98
    iget-object v0, p0, Lcom/facebook/redex/IDxMCallbackShape23S1200000_7_I2;->A01:Ljava/lang/Object;

    .line 99
    .line 100
    invoke-static {v2, v0, v3}, LX/Kyw;->A1I(Lcom/facebook/msys/util/NotificationScope;Ljava/lang/Object;Ljava/lang/String;)V

    .line 101
    .line 102
    .line 103
    iget-object v1, p0, Lcom/facebook/redex/IDxMCallbackShape23S1200000_7_I2;->A02:Ljava/lang/String;

    .line 104
    .line 105
    const/16 v0, 0xb

    .line 106
    .line 107
    invoke-static {v0, v5, v2, v1}, Lcom/facebook/encryptedbackups/mca/MailboxEncryptedBackupsJNI;->dispatchVOOO(ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V

    .line 108
    .line 109
    .line 110
    return-void

    .line 111
    :pswitch_2
    check-cast v5, Lcom/facebook/msys/mca/Mailbox;

    .line 112
    .line 113
    sget-object v1, LX/LBw;->A00:LX/GHs;

    .line 114
    .line 115
    const/4 v0, 0x3

    .line 116
    invoke-static {v1, v0}, LX/Kyw;->A0r(LX/GHs;I)Ljava/lang/String;

    .line 117
    .line 118
    .line 119
    move-result-object v2

    .line 120
    invoke-virtual {v5}, Lcom/facebook/msys/mca/Mailbox;->getNotificationCenterCallbackManager()LX/Lnj;

    .line 121
    .line 122
    .line 123
    move-result-object v1

    .line 124
    const/16 v0, 0xe

    .line 125
    .line 126
    invoke-static {v1, p0, v2, v0}, LX/Lnj;->A00(LX/Lnj;Ljava/lang/Object;Ljava/lang/String;I)Lcom/facebook/msys/util/NotificationScope;

    .line 127
    .line 128
    .line 129
    move-result-object v9

    .line 130
    iget-object v0, p0, Lcom/facebook/redex/IDxMCallbackShape23S1200000_7_I2;->A01:Ljava/lang/Object;

    .line 131
    .line 132
    invoke-static {v9, v0, v2}, LX/Kyw;->A1I(Lcom/facebook/msys/util/NotificationScope;Ljava/lang/Object;Ljava/lang/String;)V

    .line 133
    .line 134
    .line 135
    const-string v6, "android_tincan:enable_prekey_predistribution:tincan_retry_limit:reset_thread_after_thread_creation:disable_ephemeral_msg:enable_replies:disable_contact_debugging:enable_replies_in_tincan:disable_msys_tincan_push_based_notifications:enable_reactions_in_tincan:is_secure_message_over_wa_enabled:is_secure_message_over_wa_cat_sync_enabled:secure_message_over_wa_background_connection_duration_seconds:wamsys_disable_connection_when_network_disconnected:secure_message_over_wa_fg_service_duration_seconds:notify_frequent_contact_count:enable_device_change_notify:is_media_load_concurrency_fix_enabled:is_secure_message_over_wa_async_injection_enabled:is_advanced_crypto_transport_login_result_async:disable_cat_sync_delay|qe_fb_app_lightweight_messaging:enable_fetch_subscription_key_from_message_thread:enable_header_video_call:enable_header_voice_call:lwm_profile_search_message_button_enabled:enable_nt_progressive_diode:lwm_fetch_history_minutes:enable_seen_state_ios:lwm_profile_segment_a_eligible:lwm_profile_segment_b_eligible:lwm_fetch_history_minutes_alt:lwm_profile_search_message_button_enabled_android_alt:lwm_profile_segment_a_eligible_alt:lwm_profile_segment_b_eligible_alt:lwm_profile_search_message_button_enabled_alt:enable_mentions:lwm_pages_message_button_segment_a_enabled:lwm_pages_message_button_segment_b_enabled:lwm_reactor_message_button_segment_a_enabled:lwm_reactor_message_button_segment_b_enabled:lwm_profile_friend_request_message_button_segment_a_enabled:lwm_profile_friend_request_message_button_segment_b_enabled:lwm_stories_viewer_sheet_message_button_segment_a_enabled:lwm_stories_viewer_sheet_message_button_segment_b_enabled:lwm_page_followers_segment_a_enabled:lwm_page_followers_segment_b_enabled:lwm_profile_search_segment_a_enabled:lwm_profile_search_segment_b_enabled:enable_core_null_state_android:enable_core_instant_reply_monitor:show_rtc_on_bottom_sheet:enable_full_screen_menu_actions:enable_message_reply_android:enable_member_list_screen:enable_replies_rendering_ios:lwm_open_full_screen_thread_view_with_back_to_inbox_behavior:lwm_open_full_screen_thread_view_with_back_to_inbox_behavior_alt:srib_android_msys:enable_profile_menu_option_message:lwm_page_followers_segment_a_enabled_sandbox:lwm_page_followers_segment_b_enabled_sandbox:lwm_pages_message_button_segment_a_enabled_sandbox:lwm_pages_message_button_segment_b_enabled_sandbox:lwm_profile_friend_request_message_button_segment_a_enabled_sandbox:lwm_profile_friend_request_message_button_segment_b_enabled_sandbox:lwm_profile_search_segment_a_enabled_sandbox:lwm_profile_search_segment_b_enabled_sandbox:lwm_reactor_message_button_segment_a_enabled_sandbox:lwm_reactor_message_button_segment_b_enabled_sandbox:lwm_stories_viewer_sheet_message_button_segment_a_enabled_sandbox:lwm_stories_viewer_sheet_message_button_segment_b_enabled_sandbox:enable_core_navbar_back_button_unread_count:inbox_thread_view_android_msys:thread_actions_android_msys:thread_view_android_message_send_lightweight_api:enable_toolbar_remove_message:enable_toolbar_reply_to_message:enable_gif_overlay_attribution:enable_message_reply_menu_action:enable_double_tap_to_like_android:enable_gesture_intercept_component:enable_mib_notif_collapse_android:enable_stories_event_logger:enable_message_actions_bottom_bar:enable_message_nux_android:enable_press_n_hold_to_react_nux_android:enable_double_tap_to_like_nux_android:enable_message_removal_android:lwm_page_followers_segment_a_us_like_enabled:lwm_pages_message_button_segment_a_us_like_enabled:lwm_profile_friend_request_message_button_segment_a_us_like_enabled:lwm_profile_search_segment_a_us_like_enabled:lwm_profile_segment_a_us_like_eligible:lwm_reactor_message_button_segment_a_us_like_enabled:lwm_stories_viewer_sheet_message_button_segment_a_us_like_enabled:enable_message_nux_ios:enable_toolbar_copy_message:enable_toolbar_save_message:enable_gif_render_as_mp4_gql_ios:enable_gif_render_as_mp4_msys_ios:enable_stories_lightweight_messaging_api:thread_actions_android_msys_inbox:enable_audio_rendering:enable_sticker_composer_tray:enable_message_reply_hoisting:enable_request_scroll_to_message:enable_message_copy_android:enable_save_image_android:enable_message_thread_scroll_to_bottom:enable_thread_view_new_message_merger:enable_expressions_composer_grouping:enable_audio_message_sending_msys:msys_debug_reporter_killswitch:enable_double_tap_to_like_nux_ios:enable_press_n_hold_to_react_nux_ios:enable_messaging_app_switch_secure_context_plugin:mib_fb4a_enable_mentions:enable_message_reply_bottom_bar:enable_message_request_with_cta_ios:enable_fb4a_send_audio_message:enable_armadillo_inbox_threadview:enable_armadillo_device_registration:thread_view_android_message_send_lightweight_api_inbox:thread_view_android_message_send_lightweight_api_all:enable_mib_armadillo_notification:enable_armadillo_msys_dark_test:msys_enable_custom_offline_id_generator:enable_srib_armadillo_viewer_sheet:enable_srib_armadillo_viewer_sheet_thread_creation:enable_srib_armadillo_message_actions:msys_fb4a_test_bootstrap_on_start:msys_message_send_path:msys_enable_multi_mailbox:msys_enable_reporting_app_state:msys_skip_http_tasks_disconnected_enabled:msys_skip_http_tasks_disconnected_only_in_background:msys_should_register_network_event_during_init:disable_armadillo_connection_when_network_disconnected:armadillo_background_connection_duration_in_seconds:msys_skip_crash_db_open_errors:thread_view_android_message_send_lightweight_api_inbox_alt:enable_custom_reactions_bottomsheet:enable_armadillo_android_vaulting:android_cask_relax_policy:enable_delete_thread_android:enable_armadillo_msys_full_contact_sync_android:current_armadillo_msys_full_contact_sync_experiment_date_android:enable_fb4a_send_audio_message_msys:enable_poll_rendering:enable_photo_picker_camera_roll_view_provider:msys_verify_contact_row_exists_killswitch:enable_custom_reaction_bar:msys_enable_bootstrap_for_background_sessions:msys_set_background_executor_for_msys_scheduler:msys_exposure_point_srib:msys_enable_run_bootstrap_job_last:enable_android_gi_stories:enable_android_msys_stories_archive:msys_set_thread_priority:msys_thread_priority:enable_android_vaulting_ui:enable_send_video_message:enable_android_msys_initialize_logout_debug:enable_mib_fb4a_dual_send_text:enable_mailbox_sdk:enable_android_e2ee_stories_archive:enable_poll_creation:msys_make_cleanup_call_blocking:msys_enable_multi_mailbox_tracking:enable_android_msys_stop_initialize_if_logged_out:is_app_state_fix_enabled:msys_check_login_before_init:msys_ignore_mailbox_call_after_logout:dual_send_clean_up_date_android:clean_db_after_dual_send_test_android:msys_delay_init_from_login:msys_skip_mqtt_operation_for_wrong_account:msys_enable_multi_mailbox_inbox:msys_enable_custom_offline_id_generator_inbox:msys_fb4a_foreground_dark_sync_inbox:enable_android_msys_stop_initialize_if_logged_out_inbox:enable_icebreaker_integrity_ui_update:enable_idle_executor_for_foreground_init:msys_delay_init_from_login_delay_in_seconds:is_serial_mqtt_publish_enabled:enable_separate_directory_for_media:enable_app_mute_status_update_for_armadillo_push_dedup:lazy_mailbox_version:msys_mailbox_activation_mode:ensure_mailbox_cleanup:enable_multi_mailbox_checker:msys_in_memory_db_restore:msys_init_kick_mqtt:msys_persist_db_on_logout_ios:skip_exposure_logging_for_msys_db_deleting:msys_exposure_point_inbox:msys_reconnect_kick_mqtt_enabled:msys_reconnect_kick_mqtt_interval_seconds:show_delete_message_history_option:enable_armadillo_device_registration_for_dual_send:msys_kick_mqtt_for_sync_failure:msys_persistent_db_restore:enabled_tap_to_dismiss_keyboard:enable_srib_armadillo_viewer_sheet_content_share_id_manager:enable_mib_fb4a_dual_send_xapp:mib_dual_send_text_sampling_rate:enable_message_forward_android:armadillo_reply_receive_enabled:armadillo_reaction_receive_enabled:armadillo_reaction_receive_supported:enable_ephemeral_settings:enable_e2ee_metadata_sync:msys_fb4a_bootstrap_on_push:armadillo_feed_share_receive_enabled:armadillo_feed_share_receive_supported:armadillo_story_share_receive_enabled:armadillo_story_share_receive_supported:enable_multiple_image_ux:msys_cleanup_call_blocking_time_sec:enable_e2ee_send_message:enable_feed_armadillo_message_actions:force_push_notification_to_graphql:enable_android_message_forward_limit:enable_stax_reaction_pile:require_non_messenger_device_for_threads_features:enable_stax_reaction_pile_animation:enable_tam_mailbox_sdk:enable_thread_view_hot_likes_android:enable_msys_push_thread_view_ios:restrict_unsends_on_message_reqs:enable_message_list_animation:show_force_e2ee_group_thread_creation_toggle:enable_reactions_frag_above_message_bubble:pass_through_mqtt_connected_event:enable_reactions_threadview_jump_fix:e2ee_group_participant_limit_size:enable_e2ee_group_participant_limit:armadillo_story_reply_receive_enabled:armadillo_story_reply_receive_supported:enable_e2ee_non_addressable_user_handling:enable_reactions_long_press_animations:enable_ios_msys_product_type:enable_android_msys_product_type:msys_set_background_executor_for_msys_scheduler_hp:enable_message_forward_button_android:enable_key_change_alert_entrypoint:enable_mib_armadillo_notification_deletion_for_unsent_messages:enable_mib_armadillo_notification_deletion_when_open_thread_view:disable_mib_armadillo_notification_for_open_thread_view:use_message_box_id_for_profile_intent:enable_nicknames_thread_settings_row:idk_rotation_version:should_perform_key_rotation:enable_load_gifs_as_preview_image:enable_load_gifs_as_preview_image_e2ee:disable_fb4a_notif_reactions_when_sync_path_enabled:enable_nicknames_thread_settings_row_for_open_seg_a:enable_nicknames_thread_settings_row_for_open_seg_b:enable_theme_thread_settings_row_seg_a:enable_theme_thread_settings_row_seg_b:disable_vault_fds_text_span|ls_waterfall_sampling:should_log_waterfall|ls_rich_media:enable_client_dedup:hash_secret_salt:use_background_upload_api:use_networker_priority_queue:networker_max_requests_in_parallel:is_prefetch_unread_thread_image_previews:is_prefetch_unread_thread_videos:max_num_of_media_prefetch_per_thread:inception_enabled:use_file_path_upload:image_retry_count:video_retry_count:max_backoff_time_interval_ms:use_streaming_upload:max_message_attachments:insert_prepare_task:video_retry_count_sdk:image_retry_count_sdk:global_share_extension_queue:audio_retry_count_sdk:audio_retry_count:use_file_path_upload_sdk:send_by_server_for_images:bypass_jpeg_server_transcoding:video_pass_through_mp4:send_by_server_for_videos:limit_max_int32_video_size|messenger_mci_misinfo_prevenetion_mc:mci_enable_forward_limit_5_messages:mwb_remove_forward_limit_on_fb_messenger_share:should_show_highly_forwarded_indicator:highly_forwarded_threshold:should_compute_forward_score:enable_forwarding_limit_ux_improvement:enable_disabled_send_button_tap_when_forward_limited:should_parse_inform_treatment_params:should_show_inform_treatment:enable_inform_treatment_for_armadillo:is_breadth_dynamic_forward_limit_enabled:breadth_dynamic_forward_limit_schema:should_always_use_dynamic_limit:forwarding_limit_ux_improvement_type:breadth_forward_limit_schema:should_use_forward_limit_from_schema:should_compute_tam_forward_score:breadth_minimum_forward_limit_schema:should_show_armadillo_highly_forwarded_indicator:should_show_forward_friction_for_message_with_inform_treatment|ios_lightspeed_data_trace_config:sync_group_contact_enabled:sync_group_experiment_enabled:sync_group_mailbox_enabled:sync_group_settings_enabled:sync_group_stories_enabled:message_send_trace_sample_rate:sync_group_securemailbox_enabled:securemessage_send_trace_sample_rate:append_trace_id_to_topic:sync_client_mode_enabled:task_label_255_send_trace_sample_rate:task_client_mode_enabled:rich_media_download_sample_rate:rich_media_upload_sample_rate:task_label_46_request_id_sample_rate:task_label_10005_request_id_sample_rate:task_label_4_send_trace_sample_rate:task_label_20001_send_trace_sample_rate:task_label_145_send_trace_sample_rate:task_label_145_request_id_sample_rate:task_label_228_send_trace_sample_rate:task_label_228_request_id_sample_rate:task_label_209_send_trace_sample_rate:task_label_209_request_id_sample_rate:task_client_mode_tincan_act_enabled:tam_task_client_mode_enabled:task_label_4_request_id_sample_rate:enable_open_message_media_send:enable_open_message_media_download:media_download_listener_sample_rate:rich_media_send_mci_trace_enabled:rich_media_send_mci_sample_rate:open_message_recipient_trace_sample_rate:open_message_recipient_request_id_sample_rate:recipient_trace_continuation_sample_rate:orca_mailbox_sync_mci_trace_enabled:mcd_trace_open_text_send_enabled:task_label_207_request_id_sample_rate:sync_group_mailbox_enabled_new:orca_mailbox_sync_mci_trace_enabled_new:sync_group_mailbox_enabled_custom_method:sync_group_community_chat_enabled:init_sync_trace_sample_rate:activate_send_mcdtrace_in_sproc|msys_sync_config:background_sync_optimization_enabled:skip_sync_when_no_network:skip_task_when_no_network:skip_sync_when_no_mqtt:process_dasm_when_idle:enable_hybrid_perf_logger:process_dasm_with_low_priority:skip_sync_when_no_network_all_states:skip_sync_dgw_use_dgw_state:enable_mcdsync_multiaccount:delete_sqlite_file_for_corruption:skip_sync_when_no_mqtt_all_states:use_in_memory_sync_group_allowlist:msys_resume_sync_batch:fail_hard_auth_fbid_mismatch:enable_context_propagation:enable_task_stats:use_normal_priority_for_app_state:trigger_optimistic_db_update_first:enable_critical_statement_cache:enable_synchronous_critical_commit_callback:enable_optimize_database:disable_app_state_persistence|ls_mobileconfig_secure_message_over_wa:enable_connection:enable_pushkit_notification:enable_act_group:enable_nse_notification:enable_act_one_to_one:notify_frequent_contact_count:enable_device_change_notify:enable_act_incoming_group_rendering:enable_rich_notification:enable_presence_send:thread_migration_batch_size:ios_background_connection_duration_seconds:use_internal_armadillo_thread_indicator:enable_typing_indicator_one_on_one:enable_typing_indicator_send_group:act_employee_dogfood:enable_armadillo_debugging_logs:bootstrap_participating_groups_fetch_size:log_armadillo_usage:enable_thread_unread_action_sync:enable_thread_read_action_sync:enable_thread_delete_action_sync:enable_thread_archive_action_sync:enable_ab_props:enable_dual_send_with_open_msg:enable_e2ee_metadata_sync:enable_thread_details_group_info_fetch:enable_devices_fetch_after_participating_groups_fetch:enable_secret_convo_rebrand:use_v2_device_fetch:enable_notification_actions:use_mns_socket:enable_syncd:enable_prekey_fetch_in_group_notifications:dual_send_media_rate_limit:enable_media_dual_send:enable_dual_send_xapp:enable_notification_setting_reaction:enable_icdc_data_processing:enable_icdc_alert:reply_receive_enabled:send_audio_sampling_rate:send_image_sampling_rate:send_video_sampling_rate:send_text_sampling_rate:enable_cross_app_notification_deduplication:enable_sender_key_pre_distribution:device_fetch_batch_size:idk_rotation_version:should_perform_key_rotation:should_logout_after_key_rotation:icdc_failure_cooldown_interval_in_minutes:icdc_alert_trigger_failure_count:enable_group_dual_send_with_open_msg:enable_basic_reactions_validation:enable_delete_for_me:enable_icdc_registration:enable_v2_device_fetch_send_path:group_size_threshold_for_sender_key_pre_distribution:enable_connection_sharing:ignore_cat_expiration_after_fresh_network_fetch:enable_smart_group_sender_key_rotation:switch_to_family_device_id_as_android_registration_id:enable_offline_deferred_receipts:peer_device_change_admin_message_optimization:did_fetch_config_values:enable_registration_task_retry:enable_e2ee_metadata_thread_snapshotting:enable_pull_mode:enable_device_name_fix_android:send_retry_receipt_after_persistence:enable_dr_pre_acking:enable_self_threads:enable_receipt_pre_acking:enable_nse_singleton_mailbox:enable_delete_thread_message_range_sync:peer_device_added_admin_message_view_logins:hide_device_change_admin_message_in_snippet:disable_nse_extra_db_connections:enable_device_change_admin_message_toggle_optimization:enable_media_downloadable_preview:enable_key_backup_to_secure_storage_android:enable_key_backup_to_secure_storage_ios:enable_peer_device_change_admin_messages_by_default:enable_pending_message_recovery:move_peer_device_change_admin_messages_to_setting:enable_remove_delay_on_reconnection:enable_global_identity_version_validation:enable_media_bank_migration:peer_device_security_alerts_query_counts_limit:peer_device_security_alerts_query_days_limit:enable_offline_message_deferral:offline_message_threshold_for_deferral:enable_all_members_add_mode:enable_media_scrutiny:enable_occam_read_receipts:enable_media_background_upload:enable_mentions_receive_handling:fail_message_send_older_than_in_days:enable_media_background_download:enable_key_backup_to_lockbox_android:enable_key_backup_to_lockbox_ios:enable_media_download_retry_in_wcmms:enable_media_upload_retry_in_wcmms:enable_whatsapp_periodic_tasks:device_fetch_cooldown_hours:enable_wameta_disconnect_immediately:crypto_auth_token_refresh_interval_sec:disable_media_jpeg_preview:armadillo_connection_retry_limit:enable_uart_restore_flow:critical_priority_for_armadillo_media_send:enable_message_send_v2_qpl:enable_forced_pending_message_delete:enable_media_message_send_v2_qpl:mem_process_prewarm_connection_block:enable_media_connection_prewarming:enable_image_4k_ios:video_resolution_max_size:enable_cross_app_notification_dedup_read_app_selector_from_msys:video_resolution_max_size_android:enable_occam_delivery_receipts:use_decoding_context_for_transcoding:use_diskio_context_for_cat_fetcher_queue:use_critical_priority_for_task_handling:enable_media_download_qpl:enable_cross_app_notification_dedup_app_preference:critical_priority_for_armadillo_receive:use_possibly_synchronous_execution_for_task_handling:server_ack_timeout_in_seconds:enable_copy_file_during_content_token_creation:use_image_transcoder_v2_android:enable_cross_app_notif_dedup_counter_app_install_checker:enable_cross_app_notif_dedup_last_connection_checker:skip_mns_dns_resolver_creation:upload_progress_increment:enable_media_resume_upload:disable_location_in_security_alerts:enable_database_connection_execute_possibly_sync:enable_in_place_full_attachment_download:enable_batched_decryption:enable_task_handler_job_disambiguation:support_bump_message_receive:enable_eager_secure_enclave_backup_android:skip_image_preview_for_small_files:enable_v2_act_media_out_handler:enable_reinstall_logging_android:support_edit_message_receive:enable_connection_certificate_chain_validation:futureproof_recovery_override:enable_eager_secure_enclave_backup_ios:enable_media_pre_download:ios_everyone_command_receive_enabled:ios_everyone_command_receiving_protobuf_supported:android_everyone_command_receive_enabled:android_everyone_command_receiving_protobuf_supported:idk_lockbox_beagle_sample_rate:bump_e2ee_metadata_thread_from_tam:create_user_agent_with_android_id:enable_prefetched_readstores_during_connection:enable_eb_validation_on_full_download_fallback:skip_image_preview_for_small_files_v2:android_enable_media_file_upload:support_poll_messages_receive|android_messenger_search_h1_2021:message_search_scrim_screen:should_maybe_hide_unscored_groups_omnipicker:should_rank_non_contact_as_group:is_armadillo_enabled:is_private_search_enabled:should_include_non_contacts_in_tincan_search:should_enable_adding_users_to_existing_armadillo_threads:should_log_send_dwell_for_armadillo_tincan_in_universal:is_create_group_from_armadillo_one_to_one_enabled:is_search_in_conversation_for_armadillo_one_to_one_enabled:is_create_group_from_ig_one_to_one_enabled:is_add_member_for_xac_group_enabled:num_of_users_deduplicate_suggestion_from_inbox_in_ns:is_e2e_encrypted_thread_new_subtitle_enabled:is_unnamed_encrypted_group_creation_enabled_in_omnipicker:is_search_rapid_feedback_survey_enabled:is_universal_search_keypress_blending_enabled:universal_search_keypress_blending_query_lower_bound:universal_search_keypress_blending_query_upper_bound:should_use_armadillo_search_surface_type:should_enable_mnet_retry_mechanism:enable_fuzzy_match:mnet_retry_interval_hour:enable_act_non_contact_group_creation:enable_clickstream_token_sync:sync_clickstream_interval_hr:is_search_in_conversation_for_armadillo_group_enabled:clickstream_min_query_length|msg_ios_armadillo_search:include_client_group_threads:include_client_contacts:is_enabled_for_omnipicker:is_enabled_for_universal_search:is_enabled_for_bcf:is_enabled_for_tam_mailbox_omnipicker_null_state:is_enabled_match_tincan_for_query_search:is_enabled_omnipicker_encrypted_switch_ui:include_client_1to1_threads:is_enabled_for_share_extension:omnipicker_name_step_option:should_log_armadillo_recipient_real_fbids:should_use_armadillo_surface_type_to_issue_search_query:is_enabled_non_contact_group_creation:is_enabled_toggle_e2ee_button_when_contacts_selected:is_enabled_omnipicker_addressible_badge:is_enabled_bcf_m3_features:is_enabled_bcf_m3_share_extension:enable_stick_armadillo_results_to_open_results:is_enabled_bcf_m3_fb_share:m3_null_state_cutover_enabled:enable_search_null_state_stick_armadillo_to_open:enable_armadillo_search_m3:enable_show_self_e2ee_thread:min_fb_version_for_bcf_m3_fb_share:fb_version_key_for_bcf_m3_fb_share:m3_remove_cutover_e2ee_attribution:enable_armadillo_group_tlc:enable_omnipicker_encryption_toggle_tlc_user:bcf_group_tlc_enabled:omnipicker_default_e2ee_group_creation:bcf_default_e2ee_group_creation:is_xma_forward_enabled:is_m3_fb_feed_forward_enabled:is_m3_external_link_forward_enabled:enable_null_state_recent_search:enable_fix_for_remove_server_armadillo_filter|msys_tam_trace_config:enable_tam_armadillo_message_send:enable_tam_armadillo_media_send:enable_tam_armadillo_media_receive:enable_tam_message_send_trace:enable_tam_armadillo_media_download:enable_tam_message_receive_trace:enable_act_media_sharing_trace|msys_tam_contact_sync:enable_tam_contact_sync|msg_message_expiration:is_enabled:sender_threshold_for_short_duration_msg_in_sec:receiver_threshold_for_short_duration_msg_in_sec:expiration_lengths:is_expiration_change_synchronized:screenshot_enabled:one_on_one_thread_expiration_lengths:group_thread_show_composer_timer:one_on_one_thread_show_composer_timer:group_thread_expiration_lengths:thread_show_composer_banner:is_cta_shown_in_admin_message:is_current_settings_shown_in_thread_details:swipe_up_to_change_ephemerality:swipe_up_default_expiration_time:screenshot_notif_logging_enabled:ephemeral_message_periodic_scan:periodic_scan_in_thread_view_enabled:should_disable_threadview_banner:should_disable_threadview_nux:enable_screenshot_block_view:enable_read_receipt_backfill:ephemerality_type|ls_echo:act_auto_echo_enabled:message_scroll_after_enabled:initial_restore_enabled:message_restore_enabled:message_scroll_before_enabled:encryption_at_rest_enabled:mcc_enable_echo_identity_related:act_echo_mci_trace_sample_rate:mcc_enable_echo_everything_else:mcc_enable_echo_non_identity_related:enable_media_bank_share_across_apps:media_bank_backfill_file_size_data:enable_automated_media_truncation:enable_media_bank_share_across_apps_android:media_truncation_threshold_in_mb|enable_connectivity_status_client_table:enabled:banner_display_delay:banner_display_enabled:advanced_banner_content_enabled|msys_db_trace_config:enable_echo_trace:dasm_sample_rate:enable_dasm_trace|armadillo_null_state:use_persisted_null_state|messenger_ranking_feature_wallet_mc:enable_fw_ranking_for_search_open_thread:enable_fw_ranking_for_search_armadillo_thread:enable_fw_ranking_for_an_open_thread:active_now_model_name:active_now_asset_name:active_now_prediction_batch_size:active_now_model_version:read_features_without_inference:use_target_decay_table:run_ranking_task_in_background_only:enable_impression_batch_write:early_termination_point:use_mldw:mldw_version:enable_direct_run:feature_ids_for_active_now:use_ppml_ranking_for_an:init_ppml_after_inbox_renders:log_training_data_for_an:pytorch_library_load_delay:combine_server_an_score_for_ppml_ranking:ppml_active_now_value_model_config:enable_an_ppml_score_logging:enable_an_ppml_displayed_ratio_logging:enable_an_ppml_candidates_logging:active_now_ranking_interval_ms:enable_mldw_disk_repack:mldw_disk_cap:mldw_active_now_impression_event_id:ppa_fw_exposure_event_id:enable_ppa_fw:ppa_fw_exposure_feature_id:ppa_fw_ppa_datestamp_completed_event_id:ppa_fw_metric_ids:ppa_fw_last_completed_datestamp_feature_id:ppa_fw_max_delay_days:ppa_db_version:mldw_event_logging_execution_context:enable_mldw_event_logging_execution_low_priority:mldw_event_logging_execution_delay_ms:use_java_api_mldw_event_logging:ppml_init_delay_ms:use_java_ranking_task_scheduler:enable_ranking_task_schedule_exponential_backoff:ppa_fw_exposure_name:init_after_first_drawn_no_timeout:use_separate_inbox_load_completed_handler:feature_group_id:feature_group_version:use_mldw_server:require_charging_for_prediction:enable_ppa_run_in_init:enable_ppa_run_in_schedule:enable_event_intent_detection:mantle_config_an_ranking:enable_run_mantle_sync:init_mldw_on_msys:mldw_feature_registry_delay_ms:enable_fw_papaya_logging:enable_bcf_mldw_logging:enable_ppml_for_an:enable_ppml:use_mantle_generalization|msys_device_registration_config:enable_device_registration_trace:enable_armadillo_connection_trace|armadillo_security_alerts:force_enable_alerts|act_threadview:are_reactions_enabled:are_mentions_enabled:are_seen_receipts_enabled:are_replies_enabled:is_feed_xma_enabled:is_story_xma_enabled:is_emoji_customization_enabled:is_save_media_enabled:is_armadillo_forwarding_enabled:is_verified_badge_enabled:is_video_editing_enabled:is_unsend_message_enabled:is_delete_message_enabled:is_reply_render_enabled:is_hotlike_sticker_render_enabled:should_show_video_player_ui_changes:is_custom_reaction_enabled:are_story_replies_enabled:are_reactions_supported:are_reactions_received_enabled:deprecate_always_resolving_to_open_thread:prefer_navigation_to_e2ee_thread:is_group_profile_image_customization_enabled:is_xma_render_enabled:max_thread_name_length:is_theme_customization_enabled:is_xma_forwarding_enabled:is_sticker_forwarding_enabled:is_gradient_theme_enabled:is_fb_feed_share_supported:is_fb_feed_share_enabled:is_fb_story_share_enabled:is_fb_story_share_supported:is_reaction_thread_update_enabled:is_external_link_share_enabled:is_flat_link_share_enabled:is_rich_preview_for_external_link_enabled:is_rich_preview_share_enabled:force_navigation_to_e2ee_thread:is_story_share_render_callback_enable:is_message_list_reload_optimize_enabled:should_composer_plugins_init_lazy:are_reaction_animations_enabled:is_pinned_messages_enabled:should_prevent_emoji_keyboard_preload:is_avatar_sticker_enabled:is_nickname_customization_enabled:are_thread_themes_enabled:is_open_gif_keyboard_on_message_click_enabled:is_fb_story_reply_enabled:is_fb_story_reply_supported:is_external_link_share_supported:are_armadillo_bubbles_supported:is_hotlike_sticker_sizing_enabled:is_zoomable_photo_enabled:move_attribution_lock_icon:is_reaction_keyboard_fix_enabled:is_group_member_add_mode_plugin_enabled:android_custom_reaction_enabled:is_emoji_admin_message_enabled:is_nickname_admin_message_enabled:is_group_profile_image_admin_message_enabled:is_theme_customization_enabled_ios:is_theme_admin_message_enabled:is_profile_share_async_enabled:should_show_group_member_add_mode_thread_details_entrypoint:is_additional_custom_reaction_logging_enabled:is_delete_thread_details_enabled:is_word_effects_enabled:is_story_ring_enabled_android:is_emoji_logging_enabled:is_full_screen_media_forwarding_enabled:ios_media_render_logging_enabled:is_sticker_tray_expandable:is_kaizen_mv_w1_enabled:is_gif_tab_expandable:is_armadillo_location_sharing_enabled:is_custom_reaction_search_enabled:is_kaizen_large_emoji_enabled:is_admin_message_collapsible_enabled:composer_default_tab:is_quick_reaction_full_set_enabled:is_armadillo_location_sharing_supported:should_show_default_user_profile_picture:is_word_effects_admin_message_enabled:is_bump_message_enabled:is_doc_send_enabled:is_deidentified_sticker_search_enabled:ios_enable_reactions_nux_for_e2ee:is_doc_render_enabled:is_avatar_mimicry_enabled:is_sticker_pack_detail_enabled_ios:word_effects_range_optimization_enabled:is_quick_reaction_emoji_search_enabled:is_star_tab_enabled:is_bump_message_render_enabled:is_armadillo_p2p_payment_enabled:is_word_effects_enabled_android:is_armadillo_p2p_payment_supported:is_new_tam_sort_key_timestamp_enabled:is_xma_forward_enabled_e2ee:is_fb_feed_forward_enabled:is_external_link_forward_enabled:is_fb_event_share_from_messenger_enabled:is_poll_enabled:is_nickname_copy_enabled:is_m4a_e2ee_show_bump_in_action_drawer_menu_enabled:is_swipe_to_bump_message_enabled:is_doc_send_testing_enabled:migrate_to_read_time_capabilities:is_silent_command_enabled:word_effects_range_optimization_fallback_enabled:word_effects_prefer_emojis_in_blob:is_m4a_e2ee_bump_message_ender_enabled:is_send_effects_enabled_android:is_external_link_share_refactor_enabled:should_use_cm_send_status:is_armadillo_location_sharing_v2_enabled:is_armadillo_location_sharing_v2_supported:is_updated_ig_post_external_link_share_enabled:is_m4a_stax_bump_message_logging_enabled:is_all_doc_type_send_testing_enabled:is_long_press_sticker_render_preview_enabled:is_use_generic_renderer_for_posts_enabled:is_send_effects_in_star_tab_enabled_android:is_additional_armadillo_pre_logging_enabled:is_use_generic_renderer_for_story_share_enabled|msg_v2_send_sproc_config:v2_enabled|android_messenger_search_h2_2021:omnipicker_nullstate_suggestions_limit:should_downrank_gxac_ineligible_users:log_for_omnipicker_private_search:enable_universal_search_ns_context_line:fuzzy_match_score_multiplier:fuzzy_match_bias:fuzzy_match_edit_ratio_multiplier:enable_search_unified_logging:should_log_transport_type_for_epd_users:clickstream_multiplier:clickstream_bias:use_blended_view_min_query_length:deprecate_non_blended_ranking_view:recent_section_to_top_suggested_limit:enable_new_error_states:fuzzy_match_last_token_prefix_max_length:is_exact_name_boosting_enabled:enable_groups_with_all_selected_users:limit_local_groups_containing_selected_users_num:enable_private_search_unified_logging:search_in_chat_open_msys_thread_view_enabled:uprank_prefix_matched_items:birthday_boost_limit:enable_new_error_states_logging|armadillo_push_notification:start_fg_service_for_all:use_act_api_notification_flow:handle_notification_with_workmanager:enable_push_config_registration_msys_task:handle_notification_with_workmanager_aync:enable_e2e_logging_message_level:enable_e2e_logging_notification_level:disable_work_manager:enable_e2e_notification_level_log_regardless_of_atid:mcc_error_to_qpl_logging:killswitch_for_analytics_for_extension|ls_mci_trace_session_based_config:ls_mci_trace_open_text_send_sample_rate:ls_mci_trace_open_text_send_traceid_rate:ls_mci_trace_open_rich_media_send_sampling_rate:ls_mci_trace_open_rich_media_send_traceid_rate:ls_mci_trace_armadillo_rich_media_send_sampling_rate:ls_mci_trace_armadillo_rich_media_send_traceid_rate:ls_mci_trace_armadillo_text_send_sampling_rate:ls_mci_trace_armadillo_text_send_traceid_rate:ls_mci_trace_tam_message_send_traceid_rate:ls_mci_trace_tam_message_send_sampling_rate:orca_mailbox_sync_trace_flush_lock:ls_mci_trace_open_rich_media_download_sampling_rate:ls_mci_trace_open_rich_media_download_traceid_rate:ls_mci_trace_community_messaging_channel_join_sample_rate:ls_mci_trace_community_messaging_channel_join_trace_id_rate:ls_mci_trace_armadillo_rich_media_download_sampling_rate:ls_mci_trace_armadillo_rich_media_camera_roll_backup_sampling_rate:ls_mci_trace_community_messaging_rich_media_sample_rate:ls_mci_trace_community_messaging_text_trace_id_rate:ls_mci_trace_community_messaging_text_sample_rate:ls_mci_trace_community_messaging_rich_media_trace_id_rate:ls_mci_trace_open_text_receive_msg_traceid_rate:ls_mci_trace_orca_mailbox_legacy_sync_traceid_rate:ls_mci_trace_orca_mailbox_legacy_init_sync_traceid_rate:ls_mci_trace_armadillo_rich_media_camera_roll_backup_traceid_rate:ls_mci_trace_armadillo_rich_media_download_traceid_rate:should_use_async_dr_for_push:ls_mci_trace_armadillo_registration_sampling_rate:ls_mci_trace_armadillo_registration_traceid_rate:ls_mci_trace_chatd_sample_rate:ls_mci_trace_chatd_trace_id_rate:ls_mci_trace_e2ee_mailbox_sync:ls_mci_trace_armadillo_data_loss_sampling_rate:ls_mci_trace_armadillo_data_loss_traceid_rate:ls_mci_trace_mqtt_connect_sampling_rate:ls_mci_trace_armadillo_receive_sampling_rate:ls_mci_trace_armadillo_receive_traceid_rate:ls_mci_trace_armadillo_connection:ls_mci_trace_type_all_sample_rate:ls_mci_trace_message_reactions_traceid_rate:ls_mci_trace_message_reactions_sampling_rate:ls_mci_trace_message_actions_sampling_rate:ls_mci_trace_message_actions_traceid_rate:ls_mci_trace_lss_traceid_rate:ls_mci_trace_lss_sampling_rate:enable_logging_thread_id:msys_db_health_sampling_rate:ls_mci_trace_armadillo_media_sharing_sampling_rate:ls_mci_trace_armadillo_media_sharing_traceid_rate:ls_mci_trace_open_text_local_send_speed_sampling_rate:ls_mci_trace_open_text_local_send_speed_tracing_rate:ls_mci_trace_armadillo_local_send_speed_tracing_rate:ls_mci_trace_id_non_null_enforcement:ls_mci_trace_thread_action_sampling_rate:ls_mci_trace_thread_action_traceid_rate|msys_db_truncation:enable_thread_truncation:enable_message_truncation:enable_contact_truncation:num_messages_to_keep:num_threads_to_keep:num_contacts_to_keep:enable_armadillo_thread_truncation:total_thread_truncation_execution_interval_in_days:enable_armadillo_message_truncation:enable_thread_contact_truncation:enable_dangling_contact_truncation:should_truncate_armadillo_thread:work_enable_thread_truncation:work_enable_message_truncation:work_enable_contact_truncation:work_num_threads_to_keep:work_num_messages_to_keep:work_num_contacts_to_keep|armadillo_cutover:is_enabled:is_enabled_migration_task_on_thread_navigation:is_enabled_read_only_open_thread:is_enabled_e2ee_metadata_mailbox_sync:hide_armadillo_null_state:cutover_enable_navigation_redirection:enable_people_entrypoint:enable_presence_indicator_entrypoint:is_cutover_trigger_enabled:is_enabled_group_cutover_in_active_now:enable_contact_list_entrypoint:enable_profile_action_sheet_entrypoint:enable_bcf_null_state_entrypoint:enable_act_cascade_delete_to_open:enable_rewrite_navigation_destination_entrypoint:enable_receipt_pre_acking:enable_message_copy_echo_integration:enable_cascading_message_deletion_unsend:enable_fb_profile_entrypoint:enable_mi_cascade_delete_to_armadillo:enable_cutover_read_timestamp_migration:is_enabled_more_unread_messages:force_disable_cutover:is_enabled_read_only_message_disclosure:enable_act_cascade_thread_delete_to_open:enable_e2ee_notice_v2:cutover_engagement_educational_interstitial_threadview_first_entry_variant_id:cutover_engagement_educational_interstitial_admin_message_cta_variant_id:enable_default_e2ee_threads_one_to_one:enable_thread_details_attribution:enable_thread_title_attribution:hide_bcf_cutover_attribution:enable_navigation_api_async:is_enabled_read_only_message_disclosure_open_thread:enable_cutover_delete_thread_dialog:is_exposed_user:enable_forward_on_cutover_copied_messages:enable_reaction_on_cutover_copied_messages:enable_cutover_message_actions_logging:enable_chat_head_thread_title_attribution:enable_bubbles_thread_title_attribution:enable_chat_head_reopen_navigation_redirection:enable_open_message_pagination:enable_cutover_one_to_one_open_thread_folder_fixer:enable_cutover_unread_count_carry_over:enable_chat_head_instrumentation_coverage:enable_chat_head_engagement_events_logging:enable_thread_details_education_nux|armadillo_franking:send_path:receive_path:ack_path:report_path:should_drop_invalid_payload:should_drop_on_missing_tags|labyrinth:is_epoch_rotation_enabled:shadow_test_enable_backup_init:shadow_test_enable_upload_flow:is_media_backup_enabled:is_media_gif_backup_enabled:is_media_sticker_backup_enabled:is_media_image_backup_enabled:is_media_video_backup_enabled:is_media_audio_backup_enabled:is_encryption_versioning_sync_enabled:enabled:is_ope_sortkey:enable_media_access_control:is_shadow_test_enabled:shadow_test_enable_ios_plugin:shadow_test_enable_backup_restore:shadow_test_enable_android_plugin:is_shadow_test_enabled_msgr_android:shadow_test_enable_backup_init_msgr_android:shadow_test_enable_backup_restore_msgr_android:is_media_xma_backup_enabled:is_retroactive_backups_enabled:is_backup_init_flow_enabled:is_add_device_flow_enabled:is_initialize_restore_flow_enabled:is_paged_restore_enabled:is_fetch_backup_ids_flow_enabled:is_thread_delete_enabled:media_backup_restore_min_age_secs:is_custom_task_executor_enabled:is_mci_trace_enabled:is_point_query_restore_flow_enabled:is_backup_upload_flow_enabled:is_surrounding_message_restore_enabled:is_post_server_task_cleanup_enabled:is_intermittent_backup_failure_enabled:is_media_multiple_attachments_backup_enabled:is_media_whatsapp_storage_fallback_disabled:is_tam_reset_enabled_in_prepare_message_ranges_for_restore:tam_task_delay:mci_trace_sampling_rate_restore_flow:backup_restore_use_http_sync:backup_upload_use_http_sync:is_media_backup_retry_enabled:ls_mci_trace_eb_backup_upload_trace_id_rate:ls_mci_trace_eb_backup_upload_sampling_rate:is_client_routing_occam_enabled:is_internal_dogfooding_canary_version_enabled:ls_mci_trace_eb_media_backup_timeout:ls_mci_trace_eb_media_backup_trace_id_rate:ls_mci_trace_eb_media_backup_sampling_rate:ls_mci_trace_eb_message_integrity_checker_sampling_rate:ls_mci_trace_eb_message_integrity_checker_trace_id_rate:ls_mci_trace_eb_backup_upload_timeout:ls_mci_trace_eb_message_integrity_checker_timeout:ls_mci_trace_eb_media_restore_sampling_rate:ls_mci_trace_eb_media_restore_trace_id_rate:ls_mci_trace_eb_media_restore_timeout:backup_upload_ids:backup_upload_tokens:ls_mci_trace_eb_backup_restore_sampling_rate:ls_mci_trace_eb_backup_restore_trace_id_rate:ls_mci_trace_eb_backup_restore_timeout:upload_task_delay_ms:should_upload_raw_tokens_with_restore_request:should_upload_raw_ids_with_restore_request:restore_fetch_local_threads:restore_fetch_messages_per_thread:media_backup_upload_send_ids:enable_encrypted_backups_upload_from_mem:eb_upload_new_task:enable_protobuf_double_write:eb_serialize_echo_inline:enable_eb_init_backup_v2:is_range_restore_v2_enabled:ls_mci_trace_eb_opt_out_of_backup_sampling_rate:ls_mci_trace_eb_retroactive_backup_entrypoint_traceid_rate:ls_mci_trace_eb_retroactive_backup_taskhandle_sampling_rate:ls_mci_trace_eb_finish_add_peer_device_sampling_rate:ls_mci_trace_eb_add_device_traceid_rate:ls_mci_trace_eb_generate_recovery_code_sampling_rate:ls_mci_trace_eb_generate_recovery_code_traceid_rate:ls_mci_trace_eb_finish_add_peer_device_traceid_rate:ls_mci_trace_eb_add_device_sampling_rate:ls_mci_trace_eb_retroactive_backup_taskhandle_traceid_rate:ls_mci_trace_eb_opt_out_of_backup_traceid_rate:ls_mci_trace_eb_retroactive_backup_entrypoint_sampling_rate:ls_mci_trace_eb_fetch_backups_metadata_traceid_rate:ls_mci_trace_eb_fetch_backup_status_traceid_rate:ls_mci_trace_eb_delete_backups_sampling_rate:ls_mci_trace_eb_remove_virtual_device_sampling_rate:ls_mci_trace_eb_delete_backups_traceid_rate:ls_mci_trace_eb_remove_virtual_device_traceid_rate:ls_mci_trace_eb_fetch_backup_status_sampling_rate:ls_mci_trace_eb_fetch_backups_metadata_sampling_rate:is_meb_restore_disabled_for_shim_optimistic_thread_insertion:is_point_query_restore_v2_enabled:disable_act_triggered_message_restore:is_fetch_backups_high_priority_queue_enabled:enable_message_persistence_store_layer:should_send_fetch_backups_task_over_http|msys_api_instrumentation:onetraceid_callback_sampling_rate:default_msdk_api_sampling_rate:default_msdk_thread_action_api_sampling_rate:default_msdk_message_action_api_sampling_rate:default_msdk_message_send_api_sampling_rate:default_msdk_read_api_sampling_rate:enable_mailbox_health_beagle_logs:mailbox_health_beagle_logs_default_sampling_rate|msys_db_query:cache_statement_count|msgr_armadillo_pre:num_of_prefetched_thread:msys_thread_lru_cache_size:is_pause_threadlist_observer_in_threadview_enabled:check_data_loss:enable_is_cutover_thread_logging:num_of_link_messages:delay_activate_thread_session_enabled:flytrap_android_report_recent_server_thread_id:high_prio_contact_list_query_enabled:attachment_resolve_token_timeout_ms:sticker_flicker_fix_enabled:media_error_categorization_logging:redesigned_seen_head_decorator_enabled:ignore_duplicate_anchor_request:enable_ignore_inactive_threads:thread_source_use_important_priority|mwb_reporting_review_armadillo_h122:should_tlc_include_imported_messages|msgr_armadillo_dual_send_extension:enable_act_coexist:enable_dual_send_infra_test:enable_dual_send_one_on_one:enable_group_dual_send:force_clear_e2ee_db:should_include_extensive_shadow_thread_filter:enable_ui_shadow_message_leak_detection:enable_dst_periodic_db_scan:leave_group_deferred_time:disable_leave_all_shadow_groups:enable_echo_shadow_thread_restore:enable_is_hidden_check:enable_message_retry:disable_one_on_one_dst_send:disable_gdst_send:enable_delayed_echo_shadow_thread_restore|msys_commit_hook_debouncer_v2:debounce_interval_ms:should_exempt_messaging_tables|mu_configs:all_text_mu_config:all_mu_configs_map_json:mu_config_email_only:mu_config_email_phone:mu_config_email_phone_integrity:linked_ranges_mu_tag:offensive_mu_tag:mu_config_sent_msg:mu_config_taggers_integrity:mu_config_taggers_holiday_v:sticker_intent_mu_tag:mu_config_received_msg:holiday_mu_tag:mu_config_taggers_holiday_sp:mu_config_taggers:received_text_mu_config:sent_text_mu_config:enable_mu:map_config_taggers:enabled_countries:map_config_received_msg:enable_mu_run_on_shared_background:msys_table_mode:map_config_smart_reply:enable_mu_async:enable_mu_on_data_load:mu_soft_error_report_ratio:use_direct_call:map_config_dummy_echo:enable_mu_stax:enabled_countries_stax:sync_direct_call_mu:use_simplejni:map_config_smart_compose:use_simplejni_stax:init_map_coronet:enable_mu_noncluster:enable_mu_stax_noncluster:enabled_countries_noncluster|messenger_search_ranking_feature_wallet_mc:enable_fw_ranking_for_nullstate_open_thread:feature_ids_for_nullstate:nullstate_model_version:nullstate_asset_name:nullstate_model_name:enable_fw_ranking_for_search_armadillo_thread:enable_fw_ranking_for_search_open_thread:nullstate_ranking_interval_ms|concurrent_attachment_operations:should_use_per_message_queue:enable_per_media_type_queue:enable_parent_tasks_for_attachments|msys_task_system_v2:use_process_tasks_v2:use_critical_task_dispatch_priority:msys_task_processing_logging|msys_sync_system_v2:enable_sync_system_v2|android_messenger_search_h2_2022:enable_ui_section_rank_index_unified_logging:enable_view_stories_on_universal_search:enable_view_stories_static_upranking:enable_view_stories_multiplier_upranking:view_stories_static_uprank_position:view_stories_static_uprank_limit:view_stories_multiplier:enable_msys_server_search:enable_view_stories_on_universal_search_logging:enable_profile_entry_points_on_universal_search:enable_friend_updates_on_universal_search:enable_profile_entry_points_on_universal_search_logging:enable_profile_entry_points_qp:deprecate_v2_query_for_local_group_search:remove_redundant_restricted_filter:enable_msys_universal_recent_search:enable_cm_universal_search_green_dot:disable_cache_search_item_data_source:disable_phone_contacts:disable_local_all_non_contact_users_data_source:disable_local_all_pages_data_source:android_search_results_limit:android_search_contact_fetch_limit:android_search_threads_fetch_limit:android_search_secure_threads_limit:enable_friend_updates_profile_entrypoint:enable_remove_hidden_contacts_from_null_state:enable_remove_hidden_contacts_from_query_state:enable_universal_search_hide_contact_menu_option:enable_universal_search_hide_contact_menu_option_null_state_only:enable_search_with_high_priority:enable_fuzzy_match_msys:enable_clickstream_token_sync_msys:match_thread_participant_name:enable_qpl_search_latency_logging:enable_qpl_search_latency_query_for_employee|msys_traffic_control:enable_traffic_task_dispatcher:enable_traffic_mailbox:should_check:should_respect:token_cost:task_delay:enable_alert_logging:enable_log_throttling:enable_db_commits_monitoring:enable_mailbox_api_execution_monitoring:mailbox_api_operation_cost:enable_dasm_execution_monitoring|ios_messenger_thread_perf_h2_2022:defer_after_1st_ml_rendered:defer_after_animation:should_defer_banner_content_update:should_defer_composer_top_sheet:should_defer_intent_provider:should_defer_thread_supplementary_view:should_defer_thread_view_context_publish:should_debup_thread_view_context_publish_call:should_mpl_check_tv_data:should_back_trace_touch_down:should_log_platform_foa_data:enable_platform_arm_scroll_perf_logging:enable_platform_open_scroll_perf_logging:should_log_armadillo_cutover_data:create_token_from_image_path:create_token_from_video_path:arm_tv_fetch_participant_parallel:wait_all_tv_queries_completed_on_main:wait_all_tv_queries_completed_duration:should_referch_participant_on_main:om_tv_fetch_participant_parallel:transcode_image_in_msys:warm_start_thread_view_enabled:act_warm_start_thread_view_enabled:arm_thread_view_data_prefetch:thread_view_data_prefetch_wait_sync_complete:optimize_open_is_asset_gif:optimize_armadillo_is_asset_gif:media_upload_progress_increment:avoid_duplicate_ml_vm_update:tltv_sync_monitor_enabled:insert_cached_preview_for_image:navigation_animation_perf_log_enabled:insert_cached_preview_for_video:new_thread_for_tam_media_decoding:tttt_use_new_order_by|msys_validate_foreign_keys_from_sync_receiver:validate_foreign_keys|tam_client_mobileconfig:enable_error_logging:enable_periodic_inbox_validation_tasks:enable_reaction_read_status_cross_device_sync|android_messenger_dolphin_backtest_mc:enabled|messenger_e2ee_dataclass_devx:enable_xma_dataclass:enable_readonly_metadata_dataclass|android_messenger_video_transcode_mc:fallback_to_original_file|platform_trace_session_based_config:armadillo_text_send_sampling_rate:open_text_send_sample_rate:health_report_sampling_rate:bootstrap_sampling_rate:message_send_sampling_rate:armadillo_lss_sampling_rate:open_send_invalid_thread_fbid:lightspeed_task_sampling_rate:labyrinth_platformtrace_sampling_rate:act_offline_sync_sampling_rate:rich_media_send_sampling_rate:health_report_enable_unsampled:act_message_receive_sampling_rate:labyrinth_mailbox_beagle_trace|msys_internal_congestion:critical_tasks_should_execute_async:disallow_noncritical_possiblysync:enable_per_task_queue_reprocessing:noncritical_tasks_should_execute_async:should_throttle_commit_notifications:should_wrap_mciexecute_jobs_in_savepoint:suppress_tracing_column_commit_tracking:suppress_tracing_table_commit_tracking:should_wrap_mciexecute_jobs_in_transaction:use_new_scheduling:respect_new_job_priority_for_enqueue:use_synchronous_mode_normal:respect_current_job_priority_for_enqueue:enable_async_task_dispatching:enable_congestion_detection:enable_sync_request_did_complete:should_use_boxed_alloc_in_dasm|msys_commit_hook_scheduling:use_new_scheduling|msgr_android_armadillo_fts:plugin_enabled:index_batch_count:progressive_indexing_enabled:expose_fts_logging_flag:progressive_indexing_for_client_messages_enabled:index_batch_count_for_client_messages|occam_dm_setting_migration:is_act_setting_handling_disabled:is_mi_setting_handling_enabled:is_setting_change_server_ack_disabled:is_setting_restore_from_echo_disabled:is_thread_level_sync_response_disabled:is_act_setting_sync_logging_enabled:is_initial_sync_admin_message_enabled|mwb_msgr_archive_update:is_enabled_android:is_enabled_ios:force_show_nux:is_enabled_xplat|msgr_e2ee_thread_gallery_fetch_from_network:page_size:max_network_fetch:message_to_load_per_fetch:max_num_of_media_to_fetch:max_num_of_media_to_fetch_first_page:max_network_fetch_first_page:enabled:merge_with_open_enabled|messenger_armadillo_silent_command:ios_enable_silent_command_send:android_enable_silent_command_send:android_silent_command_protobuf_enabled:android_silent_command_protobuf_supported:ios_silent_command_protobuf_enabled:ios_silent_command_protobuf_supported:allow_slash_trigger_for_silent_android|mwb_hc_forward_rate_limit:enabled:forward_rate_limit:time_window_seconds:enforcement_type:write_on_ui_enabled:is_csam_rate_limit_enabled:csam_send_path_enabled:csam_time_window_seconds:csam_rate_limit:listen_on_ui_enabled|msgr_db_query_optimizations:enable_orca_threadlist_unread_count_optimization:enable_orca_non_participant_sender_list_optimization:enable_orca_participant_list_optimization:ls_stories_expiration_checker_interval_sec:enable_orca_reactions_summary_optimization:enable_cutover_fetch_duplicate_open_thread_optimization:enable_thread_theme_variant_optimization:enable_orca_temp_message_list_optimization:enable_orca_message_list_optimization:enable_orca_threadlist_unread_count_optimization_v2|mci_telemetry_session_based_config:mci_telemetry_sampling_rate:sproc_id_attribution_enabled|tam_optimizations:tam_enable_in_memory_content_token_mapping|msgr_xma_receiver_fetch:is_receiver_fetch_enabled:is_receiver_fetch_supported|"

    .line 136
    .line 137
    const-string v7, "b4088b9f9bad365edaa15362ec8f25e40ce62642448569fa5d19e1ae29c6dba4"

    .line 138
    .line 139
    iget-object v8, p0, Lcom/facebook/redex/IDxMCallbackShape23S1200000_7_I2;->A02:Ljava/lang/String;

    .line 140
    .line 141
    const/4 v4, 0x0

    .line 142
    invoke-static/range {v4 .. v9}, Lcom/facebook/experiment/mca/MailboxExperimentJNI;->dispatchVOOOOO(ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V

    .line 143
    .line 144
    .line 145
    return-void

    .line 146
    :pswitch_data_0
    .packed-switch 0x0
        :pswitch_0
        :pswitch_1
        :pswitch_2
    .end packed-switch
    .line 147
    .line 148
    .line 149
    .line 150
.end method
