package com.facebook.video.heroplayer.ipc;

import android.os.Parcel;
import android.os.Parcelable;
import p000X.C25930wq;
import p000X.C25940wr;
import p000X.C25950ws;
import p000X.C25960wt;
import p000X.C28354Emp;
import p000X.C34901Hvb;
import p000X.C91514uR;
import p000X.C91554uV;
import p000X.EnumC36016IqS;
import p000X.EnumC36032Iqq;
import p000X.KKE;
/* loaded from: classes7.dex */
public class HttpTransferStartEvent extends KKE implements Parcelable {
    public static final Parcelable.Creator CREATOR = C91554uV.A0Z(30);
    public final int A00;
    public final int A01;
    public final int A02;
    public final int A03;
    public final int A04;
    public final int A05;
    public final int A06;
    public final int A07;
    public final int A08;
    public final int A09;
    public final int A0A;
    public final int A0B;
    public final int A0C;
    public final long A0D;
    public final long A0E;
    public final long A0F;
    public final long A0G;
    public final long A0H;
    public final long A0I;
    public final long A0J;
    public final long A0K;
    public final long A0L;
    public final long A0M;
    public final long A0N;
    public final long A0O;
    public final long A0P;
    public final long A0Q;
    public final long A0R;
    public final long A0S;
    public final long A0T;
    public final long A0U;
    public final EnumC36016IqS A0V;
    public final Long A0W;
    public final Long A0X;
    public final String A0Y;
    public final String A0Z;
    public final String A0a;
    public final String A0b;
    public final String A0c;
    public final String A0d;
    public final String A0e;
    public final String A0f;
    public final String A0g;
    public final String A0h;
    public final String A0i;
    public final String A0j;
    public final String A0k;
    public final String A0l;
    public final String A0m;
    public final String A0n;
    public final String A0o;
    public final String A0p;
    public final String A0q;
    public final String A0r;
    public final String A0s;
    public final String A0t;
    public final String A0u;
    public final boolean A0v;
    public final boolean A0w;
    public final boolean A0x;
    public final boolean A0y;
    public final boolean A0z;
    public final boolean A10;
    public final boolean A11;
    public final boolean A12;
    public final boolean A13;
    public final boolean A14;
    public final boolean A15;
    public final boolean A16;
    public final boolean A17;
    public final boolean A18;

    @Override // android.os.Parcelable
    public final int describeContents() {
        return 0;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        parcel.writeLong(this.A0S);
        parcel.writeString(this.A0t);
        parcel.writeLong(this.A0L);
        parcel.writeString(this.A0r);
        parcel.writeString(this.A0e);
        parcel.writeByte(this.A14 ? (byte) 1 : (byte) 0);
        parcel.writeString(this.A0n);
        parcel.writeLong(this.A0M);
        parcel.writeLong(this.A0T);
        parcel.writeInt(this.A0C);
        parcel.writeValue(this.A0V);
        parcel.writeByte(this.A0z ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A10 ? (byte) 1 : (byte) 0);
        parcel.writeString(this.A0k);
        parcel.writeString(this.A0l);
        parcel.writeLong(this.A0R);
        parcel.writeLong(this.A0N);
        parcel.writeInt(this.A0B);
        parcel.writeLong(this.A0O);
        parcel.writeInt(this.A0A);
        parcel.writeString(this.A0c);
        parcel.writeString(this.A0o);
        parcel.writeString(this.A0a);
        parcel.writeInt(this.A07);
        parcel.writeLong(this.A0D);
        parcel.writeByte(this.A11 ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.A00);
        parcel.writeLong(this.A0P);
        parcel.writeLong(this.A0Q);
        parcel.writeByte(this.A16 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A17 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A18 ? (byte) 1 : (byte) 0);
        parcel.writeString(this.A0s);
        parcel.writeLong(this.A0U);
        parcel.writeString(this.A0p);
        parcel.writeString(this.A0q);
        parcel.writeString(this.A0Y);
        parcel.writeLong(this.A0H);
        parcel.writeLong(this.A0I);
        parcel.writeLong(this.A0J);
        parcel.writeInt(this.A01);
        parcel.writeLong(this.A0G);
        parcel.writeByte(this.A0x ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0y ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A15 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0v ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A12 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0w ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A13 ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.A03);
        parcel.writeInt(this.A09);
        parcel.writeLong(this.A0K);
        parcel.writeString(this.A0d);
        parcel.writeString(this.A0j);
        parcel.writeString(this.A0Z);
        parcel.writeLong(this.A0E);
        parcel.writeString(this.A0b);
        parcel.writeInt(this.A05);
        parcel.writeLong(this.A0F);
        parcel.writeInt(this.A02);
        parcel.writeInt(this.A06);
        parcel.writeString(this.A0g);
        parcel.writeString(this.A0h);
        parcel.writeString(this.A0f);
        parcel.writeString(this.A0i);
        parcel.writeString(this.A0m);
        parcel.writeInt(this.A08);
        parcel.writeString(this.A0u);
        parcel.writeInt(this.A04);
        parcel.writeSerializable(this.A0W);
        parcel.writeSerializable(this.A0X);
    }

    public final String toString() {
        StringBuilder A0n = C25960wt.A0n();
        KKE.A02("timeMs=", A0n, this.A0S);
        C28354Emp.A1L(", videoId=", this.A0t, A0n);
        KKE.A02(", playerId=", A0n, this.A0L);
        C28354Emp.A1L(", url=", this.A0r, A0n);
        C28354Emp.A1L(", exception=", this.A0e, A0n);
        C34901Hvb.A1T(", isPrefetch=", A0n, this.A14);
        C28354Emp.A1L(", prefetchSource=", this.A0n, A0n);
        KKE.A02(", queueDuration=", A0n, this.A0M);
        KKE.A02(", startDuration=", A0n, this.A0T);
        C34901Hvb.A1S(", seqNum=", A0n, this.A0C);
        C28354Emp.A1L(", cacheType=", this.A0V.A01, A0n);
        C34901Hvb.A1T(", isFirstPlay=", A0n, this.A0z);
        C28354Emp.A1L(", playOrigin=", this.A0k, A0n);
        KKE.A02(", startingByteOffset=", A0n, this.A0R);
        KKE.A02(", requestedLength=", A0n, this.A0N);
        C34901Hvb.A1S(", streamType=", A0n, this.A0B);
        KKE.A02(", segmentStart=", A0n, this.A0O);
        C34901Hvb.A1S(", segmentDuration=", A0n, this.A0A);
        C28354Emp.A1L(", dataSourceFactory=", this.A0c, A0n);
        C28354Emp.A1L(", qualityLabel=", this.A0o, A0n);
        C28354Emp.A1L(", connQual=", this.A0a, A0n);
        C34901Hvb.A1S(", networkPriority=", A0n, this.A07);
        C34901Hvb.A1S(", bufferedDurationMs=", A0n, this.A00);
        KKE.A02(", startVideoBandwidth=", A0n, this.A0P);
        KKE.A02(", startVideoTTFB=", A0n, this.A0Q);
        C28354Emp.A1L(", videoBandwidthEstimateStr=", this.A0s, A0n);
        KKE.A02(", upstreamTTFB=", A0n, this.A0U);
        C28354Emp.A1L(", tigonSessionId=", this.A0p, A0n);
        C28354Emp.A1L(", tigonTransactionId=", this.A0q, A0n);
        C28354Emp.A1L(", appNetSesssionId=", this.A0Y, A0n);
        KKE.A02(", manifestFirstSegmentStartTs=", A0n, this.A0H);
        KKE.A02(", manifestLastSegmentEndTs=", A0n, this.A0I);
        KKE.A02(", manifestNumSegments=", A0n, this.A0J);
        C34901Hvb.A1S(", bufferedDurationMsAtDataSpecCreation=", A0n, this.A01);
        KKE.A02(", dataSpecCreationTimeMs=", A0n, this.A0G);
        C28354Emp.A1L(", playSubOrigin=", this.A0l, A0n);
        C34901Hvb.A1T(", isFBMS=", A0n, this.A0x);
        C34901Hvb.A1T(", isFbPredictiveDASH=", A0n, this.A0y);
        C34901Hvb.A1T(", isSkipAheadChunk=", A0n, this.A15);
        C34901Hvb.A1T(", inRewoundState=", A0n, this.A0v);
        C34901Hvb.A1T(", isManifestDynamic=", A0n, this.A12);
        C34901Hvb.A1T(", isChunkedTransfer=", A0n, this.A0w);
        C34901Hvb.A1T(", isPredictedURL=", A0n, this.A13);
        C34901Hvb.A1S(", expectedPredictedNumber=", A0n, this.A03);
        C34901Hvb.A1S(", predictedNumberMapping=", A0n, this.A09);
        KKE.A02(", numSegmentsToEndOfManifest= ", A0n, this.A0K);
        C28354Emp.A1L(", edgeHit= ", this.A0d, A0n);
        C28354Emp.A1L(", originHit= ", this.A0j, A0n);
        C28354Emp.A1L(", codec= ", this.A0Z, A0n);
        KKE.A02(", cdnResponseTime= ", A0n, this.A0E);
        C28354Emp.A1L(", contentType= ", this.A0b, A0n);
        C34901Hvb.A1S(", latestSegmentId= ", A0n, this.A05);
        KKE.A02(", confidenceBasedBitrateEstimate=", A0n, this.A0F);
        C34901Hvb.A1S(", confidencePctForBitrateEstimate=", A0n, this.A02);
        C34901Hvb.A1S(", minimumLoadPositionMs=", A0n, this.A06);
        C28354Emp.A1L(", oneReqWave=", this.A0g, A0n);
        C28354Emp.A1L(", oneResWave=", this.A0h, A0n);
        C28354Emp.A1L(", oneObserved=", this.A0f, A0n);
        C28354Emp.A1L(", oneVariant=", this.A0i, A0n);
        C28354Emp.A1L(", playerType=", this.A0m, A0n);
        C34901Hvb.A1S(", positionInUnit=", A0n, this.A08);
        C28354Emp.A1L(", vpSessionId=", this.A0u, A0n);
        C34901Hvb.A1S(", firstChunkSize=", A0n, this.A04);
        A0n.append(C25950ws.A0t(this.A0W, C25940wr.A0m(", clientWallClockOffsetMs=")));
        return C25930wq.A0f(C25950ws.A0t(this.A0X, C25940wr.A0m(", contentLength=")), A0n);
    }

    public HttpTransferStartEvent(EnumC36016IqS enumC36016IqS, Long l, Long l2, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, String str15, String str16, String str17, String str18, String str19, String str20, String str21, String str22, String str23, int i, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10, int i11, int i12, int i13, long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14) {
        super(EnumC36032Iqq.A0D);
        this.A0S = j;
        this.A0t = str;
        this.A0L = j2;
        this.A0r = str2;
        this.A0e = str3;
        this.A14 = z;
        this.A0n = str4;
        this.A0M = j3;
        this.A0T = j4;
        this.A0C = i;
        this.A0V = enumC36016IqS;
        this.A0z = z2;
        this.A10 = z3;
        this.A0k = str5;
        this.A0l = str13;
        this.A0R = j5;
        this.A0N = j6;
        this.A0B = i2;
        this.A0O = j7;
        this.A0A = i3;
        this.A0c = str6;
        this.A0o = str7;
        this.A0a = str8;
        this.A07 = i4;
        this.A0D = j8;
        this.A11 = z4;
        this.A00 = i5;
        this.A0P = j9;
        this.A0Q = j10;
        this.A16 = z5;
        this.A17 = z6;
        this.A18 = z7;
        this.A0s = str9;
        this.A0U = j11;
        this.A0p = str10;
        this.A0q = str11;
        this.A0Y = str12;
        this.A0H = j12;
        this.A0I = j13;
        this.A0J = j14;
        this.A01 = i6;
        this.A0G = j15;
        this.A0x = z8;
        this.A0y = z9;
        this.A15 = z10;
        this.A0v = z11;
        this.A12 = z12;
        this.A0w = z13;
        this.A13 = z14;
        this.A03 = i8;
        this.A09 = i7;
        this.A0K = j16;
        this.A0d = str14;
        this.A0j = str15;
        this.A0Z = str16;
        this.A0E = j17;
        this.A0b = str17;
        this.A05 = i9;
        this.A0F = j18;
        this.A02 = i10;
        this.A06 = i11;
        this.A0g = str18;
        this.A0h = str19;
        this.A0f = str20;
        this.A0i = str21;
        this.A0m = str22;
        this.A08 = i12;
        this.A0u = str23;
        this.A04 = i13;
        this.A0W = l;
        this.A0X = l2;
    }

    public HttpTransferStartEvent(Parcel parcel) {
        super(EnumC36032Iqq.A0D);
        this.A0S = parcel.readLong();
        this.A0t = parcel.readString();
        this.A0L = parcel.readLong();
        this.A0r = parcel.readString();
        this.A0e = parcel.readString();
        this.A14 = C25930wq.A1W(parcel.readByte(), 1);
        this.A0n = parcel.readString();
        this.A0M = parcel.readLong();
        this.A0T = parcel.readLong();
        this.A0C = parcel.readInt();
        EnumC36016IqS enumC36016IqS = (EnumC36016IqS) C91514uR.A0b(parcel, EnumC36016IqS.class);
        this.A0V = enumC36016IqS == null ? EnumC36016IqS.NOT_APPLY : enumC36016IqS;
        this.A0z = C25930wq.A1W(parcel.readByte(), 1);
        this.A10 = C25930wq.A1W(parcel.readByte(), 1);
        this.A0k = parcel.readString();
        this.A0l = parcel.readString();
        this.A0R = parcel.readLong();
        this.A0N = parcel.readLong();
        this.A0B = parcel.readInt();
        this.A0O = parcel.readLong();
        this.A0A = parcel.readInt();
        this.A0c = parcel.readString();
        this.A0o = parcel.readString();
        this.A0a = parcel.readString();
        this.A07 = parcel.readInt();
        this.A0D = parcel.readLong();
        this.A11 = C25930wq.A1W(parcel.readByte(), 1);
        this.A00 = parcel.readInt();
        this.A0P = parcel.readLong();
        this.A0Q = parcel.readLong();
        this.A16 = C25930wq.A1W(parcel.readByte(), 1);
        this.A17 = C25930wq.A1W(parcel.readByte(), 1);
        this.A18 = C25930wq.A1W(parcel.readByte(), 1);
        this.A0s = parcel.readString();
        this.A0U = parcel.readLong();
        this.A0p = parcel.readString();
        this.A0q = parcel.readString();
        this.A0Y = parcel.readString();
        this.A0H = parcel.readLong();
        this.A0I = parcel.readLong();
        this.A0J = parcel.readLong();
        this.A01 = parcel.readInt();
        this.A0G = parcel.readLong();
        this.A0x = C25930wq.A1W(parcel.readByte(), 1);
        this.A0y = C25930wq.A1W(parcel.readByte(), 1);
        this.A15 = C25930wq.A1W(parcel.readByte(), 1);
        this.A0v = C25930wq.A1W(parcel.readByte(), 1);
        this.A12 = C25930wq.A1W(parcel.readByte(), 1);
        this.A0w = C25930wq.A1W(parcel.readByte(), 1);
        this.A13 = parcel.readByte() == 1;
        this.A03 = parcel.readInt();
        this.A09 = parcel.readInt();
        this.A0K = parcel.readLong();
        this.A0d = parcel.readString();
        this.A0j = parcel.readString();
        this.A0Z = parcel.readString();
        this.A0E = parcel.readLong();
        this.A0b = parcel.readString();
        this.A05 = parcel.readInt();
        this.A0F = parcel.readLong();
        this.A02 = parcel.readInt();
        this.A06 = parcel.readInt();
        this.A0g = parcel.readString();
        this.A0h = parcel.readString();
        this.A0f = parcel.readString();
        this.A0i = parcel.readString();
        this.A0m = parcel.readString();
        this.A08 = parcel.readInt();
        this.A0u = parcel.readString();
        this.A04 = parcel.readInt();
        this.A0W = (Long) parcel.readSerializable();
        this.A0X = (Long) parcel.readSerializable();
    }
}
